In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_115123/1985460196.py:25: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats(fig_format)

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 42

CHAINS = 4
DRAWS = 500
N_RESERVOIRS = 6
N_PRODUCERS = 20

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=45e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=60e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2_000_000,
    producer_abandonment_cost_USD=500_000,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 17:34:14.361 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 17:34:14.365 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 17:34:14.369 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 17:34:14.373 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 17:34:14.376 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 17:34:14.380 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 17:34:14.386 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 17:34:14.386 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 17:34:14.586 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 17:34:14.587 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 17:34:14.587 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 17:34:14.587 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 17:34:14.588 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 17:34:14.588 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 17:34:14.588 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 17:34:14.588 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 17:34:14.589 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 17:34:14.589 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 17:34:14.589 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 17:34:14.589 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 17:34:14.589 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 17:34:14.589 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 17:34:14.589 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 17:34:14.589 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 17:34:14.590 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 17:34:14.590 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 17:34:14.590 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 17:34:14.590 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 17:34:14.590 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 17:34:14.603 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 17:34:14.612 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 17:34:14.875 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 17:34:14.875 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 17:34:14.876 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (20 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 116.19it/s]

Chain 0:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 63.66it/s]

Chain 0:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 54.70it/s]

Chain 0:  11%|███████████▍                                                                                           | 40/360 [00:00<00:06, 49.65it/s]

Chain 0:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 47.08it/s]

Chain 0:  14%|██████████████▌                                                                                        | 51/360 [00:00<00:06, 44.28it/s]

Chain 0:  16%|████████████████                                                                                       | 56/360 [00:01<00:07, 42.66it/s]

Chain 0:  17%|█████████████████▍                                                                                     | 61/360 [00:01<00:07, 42.16it/s]

Chain 0:  18%|██████████████████▉                                                                                    | 66/360 [00:01<00:07, 41.49it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  20%|████████████████████▎                                                                                  | 71/360 [00:01<00:06, 41.61it/s]

Chain 1:   3%|███▍                                                                                                  | 12/360 [00:00<00:02, 119.88it/s]

Chain 0:  21%|█████████████████████▋                                                                                 | 76/360 [00:01<00:06, 42.29it/s]

Chain 0:  22%|███████████████████████▏                                                                               | 81/360 [00:01<00:06, 42.42it/s]

Chain 1:   7%|██████▊                                                                                                | 24/360 [00:00<00:05, 58.59it/s]

Chain 0:  24%|████████████████████████▌                                                                              | 86/360 [00:01<00:06, 42.55it/s]

Chain 0:  25%|██████████████████████████                                                                             | 91/360 [00:01<00:06, 42.55it/s]

Chain 1:   9%|█████████▏                                                                                             | 32/360 [00:00<00:06, 50.95it/s]

Chain 0:  27%|███████████████████████████▍                                                                           | 96/360 [00:02<00:06, 41.43it/s]

Chain 1:  11%|██████████▊                                                                                            | 38/360 [00:00<00:07, 45.79it/s]

Chain 0:  28%|████████████████████████████▌                                                                         | 101/360 [00:02<00:06, 39.93it/s]

Chain 1:  12%|████████████▌                                                                                          | 44/360 [00:00<00:07, 42.44it/s]

Chain 0:  29%|██████████████████████████████                                                                        | 106/360 [00:02<00:06, 40.80it/s]

Chain 1:  14%|██████████████                                                                                         | 49/360 [00:01<00:07, 40.75it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:02<00:06, 41.14it/s]

Chain 0:  32%|████████████████████████████████▊                                                                     | 116/360 [00:02<00:05, 41.86it/s]

Chain 1:  15%|███████████████▍                                                                                       | 54/360 [00:01<00:07, 39.90it/s]

Chain 0:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:02<00:05, 42.23it/s]

Chain 1:  16%|████████████████▉                                                                                      | 59/360 [00:01<00:07, 39.06it/s]

Chain 0:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:02<00:05, 41.46it/s]

Chain 1:  18%|██████████████████                                                                                     | 63/360 [00:01<00:07, 38.37it/s]

Chain 0:  36%|█████████████████████████████████████                                                                 | 131/360 [00:02<00:05, 42.07it/s]

Chain 1:  19%|███████████████████▏                                                                                   | 67/360 [00:01<00:07, 37.65it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:03<00:05, 42.73it/s]

Chain 1:  20%|████████████████████▎                                                                                  | 71/360 [00:01<00:07, 36.75it/s]

Chain 2:   3%|███▍                                                                                                  | 12/360 [00:00<00:03, 101.99it/s]

Chain 0:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:03<00:05, 43.76it/s]

Chain 1:  21%|█████████████████████▍                                                                                 | 75/360 [00:01<00:08, 35.42it/s]

Chain 0:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:03<00:04, 45.41it/s]

Chain 1:  22%|██████████████████████▌                                                                                | 79/360 [00:01<00:07, 36.10it/s]

Chain 0:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:03<00:04, 46.14it/s]

Chain 1:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:07, 36.60it/s]

Chain 2:   6%|██████▌                                                                                                | 23/360 [00:00<00:06, 49.99it/s]

Chain 0:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:03<00:04, 47.10it/s]

Chain 1:  24%|████████████████████████▉                                                                              | 87/360 [00:02<00:07, 37.07it/s]

Chain 0:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:03<00:04, 48.59it/s]

Chain 1:  25%|██████████████████████████                                                                             | 91/360 [00:02<00:07, 37.22it/s]

Chain 2:   8%|████████▌                                                                                              | 30/360 [00:00<00:07, 42.04it/s]

Chain 0:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:03<00:03, 48.70it/s]

Chain 1:  26%|███████████████████████████▏                                                                           | 95/360 [00:02<00:07, 36.54it/s]

Chain 2:  10%|██████████                                                                                             | 35/360 [00:00<00:08, 39.55it/s]

Chain 0:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:03<00:04, 45.20it/s]

Chain 1:  28%|████████████████████████████▎                                                                          | 99/360 [00:02<00:07, 36.53it/s]

Chain 0:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:03<00:03, 47.57it/s]

Chain 1:  29%|█████████████████████████████▏                                                                        | 103/360 [00:02<00:07, 36.38it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:00<00:08, 36.12it/s]

Chain 0:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:04<00:03, 48.76it/s]

Chain 1:  30%|██████████████████████████████▎                                                                       | 107/360 [00:02<00:07, 35.88it/s]

Chain 2:  12%|████████████▌                                                                                          | 44/360 [00:01<00:09, 35.01it/s]

Chain 0:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:04<00:03, 50.64it/s]

Chain 1:  31%|███████████████████████████████▍                                                                      | 111/360 [00:02<00:06, 36.62it/s]

Chain 2:  13%|█████████████▋                                                                                         | 48/360 [00:01<00:08, 34.67it/s]

Chain 0:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:04<00:03, 52.79it/s]

Chain 1:  32%|████████████████████████████████▌                                                                     | 115/360 [00:02<00:06, 37.43it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:01<00:08, 34.42it/s]

Chain 1:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:02<00:06, 37.65it/s]

Chain 0:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:04<00:03, 51.97it/s]

Chain 2:  16%|████████████████                                                                                       | 56/360 [00:01<00:09, 31.86it/s]

Chain 0:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:04<00:02, 53.02it/s]

Chain 1:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:03<00:06, 35.73it/s]

Chain 0:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:04<00:02, 52.23it/s]

Chain 1:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:03<00:06, 35.27it/s]

Chain 2:  17%|█████████████████▏                                                                                     | 60/360 [00:01<00:09, 30.26it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:04<00:02, 56.43it/s]

Chain 1:  36%|█████████████████████████████████████                                                                 | 131/360 [00:03<00:06, 34.90it/s]

Chain 2:  18%|██████████████████▎                                                                                    | 64/360 [00:01<00:09, 30.80it/s]

Chain 0:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:04<00:02, 56.23it/s]

Chain 1:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:03<00:06, 35.64it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:  19%|███████████████████▍                                                                                   | 68/360 [00:01<00:09, 30.45it/s]

Chain 0:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:04<00:02, 59.43it/s]

Chain 1:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:03<00:06, 36.44it/s]

Chain 3:   3%|███▍                                                                                                  | 12/360 [00:00<00:03, 101.28it/s]

Chain 0:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:05<00:01, 63.58it/s]

Chain 1:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:03<00:05, 37.36it/s]

Chain 2:  20%|████████████████████▌                                                                                  | 72/360 [00:02<00:10, 28.28it/s]

Chain 0:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:05<00:01, 65.29it/s]

Chain 1:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:03<00:05, 39.06it/s]

Chain 2:  21%|█████████████████████▋                                                                                 | 76/360 [00:02<00:09, 29.83it/s]

Chain 0:  72%|█████████████████████████████████████████████████████████████████████████                             | 258/360 [00:05<00:01, 70.35it/s]

Chain 1:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:03<00:05, 40.95it/s]

Chain 2:  22%|██████████████████████▉                                                                                | 80/360 [00:02<00:09, 30.97it/s]

Chain 3:   6%|██████▌                                                                                                | 23/360 [00:00<00:07, 47.43it/s]

Chain 0:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:05<00:01, 73.99it/s]

Chain 1:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:03<00:04, 41.88it/s]

Chain 2:  23%|████████████████████████                                                                               | 84/360 [00:02<00:08, 31.99it/s]

Chain 0:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:05<00:01, 80.63it/s]

Chain 1:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:04<00:04, 43.33it/s]

Chain 2:  24%|█████████████████████████▏                                                                             | 88/360 [00:02<00:08, 32.37it/s]

Chain 3:   8%|████████▌                                                                                              | 30/360 [00:00<00:08, 39.70it/s]

Chain 0:  80%|█████████████████████████████████████████████████████████████████████████████████▌                    | 288/360 [00:05<00:00, 87.66it/s]

Chain 1:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:04<00:04, 43.97it/s]

Chain 2:  26%|██████████████████████████▎                                                                            | 92/360 [00:02<00:08, 32.73it/s]

Chain 0:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:05<00:00, 87.62it/s]

Chain 1:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:04<00:04, 44.08it/s]

Chain 3:  10%|██████████                                                                                             | 35/360 [00:00<00:09, 34.86it/s]

Chain 0:  85%|██████████████████████████████████████████████████████████████████████████████████████▉               | 307/360 [00:05<00:00, 90.12it/s]

Chain 2:  27%|███████████████████████████▍                                                                           | 96/360 [00:02<00:08, 32.60it/s]

Chain 1:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:04<00:04, 42.34it/s]

Chain 0:  88%|██████████████████████████████████████████████████████████████████████████████████████████            | 318/360 [00:05<00:00, 93.59it/s]

Chain 3:  11%|███████████▏                                                                                           | 39/360 [00:01<00:09, 32.59it/s]

Chain 2:  28%|████████████████████████████▎                                                                         | 100/360 [00:02<00:08, 31.76it/s]

Chain 0:  93%|█████████████████████████████████████████████████████████████████████████████████████████████▋       | 334/360 [00:05<00:00, 111.10it/s]

Chain 1:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:04<00:04, 40.43it/s]

Chain 3:  12%|████████████▎                                                                                          | 43/360 [00:01<00:10, 31.36it/s]

Chain 2:  29%|█████████████████████████████▍                                                                        | 104/360 [00:03<00:08, 30.26it/s]

Chain 0:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████▉   | 349/360 [00:06<00:00, 121.98it/s]

Chain 1:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:04<00:04, 41.85it/s]

Chain 3:  13%|█████████████▍                                                                                         | 47/360 [00:01<00:10, 29.89it/s]

Chain 2:  30%|██████████████████████████████▌                                                                       | 108/360 [00:03<00:08, 29.88it/s]

Chain 1:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:04<00:03, 42.66it/s]

Chain 1:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:04<00:03, 41.74it/s]

Chain 2:  31%|███████████████████████████████▋                                                                      | 112/360 [00:03<00:08, 28.99it/s]

Chain 3:  14%|██████████████▌                                                                                        | 51/360 [00:01<00:10, 28.25it/s]

Chain 2:  32%|████████████████████████████████▌                                                                     | 115/360 [00:03<00:08, 29.20it/s]

Chain 1:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:05<00:03, 42.11it/s]

Chain 3:  15%|███████████████▍                                                                                       | 54/360 [00:01<00:11, 27.12it/s]

Chain 2:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:03<00:07, 30.13it/s]

Chain 1:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:05<00:03, 44.91it/s]

Chain 3:  16%|████████████████▎                                                                                      | 57/360 [00:01<00:11, 26.66it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:05<00:03, 45.38it/s]

Chain 2:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:03<00:07, 30.75it/s]

Chain 3:  17%|█████████████████▏                                                                                     | 60/360 [00:01<00:11, 26.76it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:05<00:02, 48.34it/s]

Chain 2:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:03<00:07, 31.64it/s]

Chain 3:  18%|██████████████████                                                                                     | 63/360 [00:01<00:10, 27.37it/s]

Chain 1:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:05<00:02, 51.08it/s]

Chain 2:  36%|█████████████████████████████████████                                                                 | 131/360 [00:03<00:07, 31.77it/s]

Chain 3:  18%|██████████████████▉                                                                                    | 66/360 [00:02<00:11, 26.35it/s]

Chain 1:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:05<00:02, 54.35it/s]

Chain 3:  19%|███████████████████▋                                                                                   | 69/360 [00:02<00:10, 27.01it/s]

Chain 2:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:04<00:07, 32.12it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:05<00:02, 53.72it/s]

Chain 3:  20%|████████████████████▌                                                                                  | 72/360 [00:02<00:10, 27.65it/s]

Chain 2:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:04<00:06, 33.34it/s]

Chain 1:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:05<00:02, 56.52it/s]

Chain 3:  21%|█████████████████████▍                                                                                 | 75/360 [00:02<00:10, 28.03it/s]

Chain 2:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:04<00:06, 33.64it/s]

Chain 1:  70%|███████████████████████████████████████████████████████████████████████▋                              | 253/360 [00:05<00:01, 58.37it/s]

Chain 3:  22%|██████████████████████▎                                                                                | 78/360 [00:02<00:10, 26.77it/s]

Chain 2:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:04<00:06, 34.73it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:06<00:01, 63.33it/s]

Chain 2:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:04<00:05, 35.76it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:02<00:09, 28.07it/s]

Chain 1:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:06<00:01, 66.91it/s]

Chain 2:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:04<00:05, 38.01it/s]

Chain 3:  24%|████████████████████████▌                                                                              | 86/360 [00:02<00:09, 29.53it/s]

Chain 1:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:06<00:01, 72.73it/s]

Chain 2:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:04<00:05, 39.21it/s]

Chain 3:  25%|█████████████████████████▊                                                                             | 90/360 [00:02<00:08, 30.32it/s]

Chain 1:  80%|█████████████████████████████████████████████████████████████████████████████████▌                    | 288/360 [00:06<00:00, 78.63it/s]

Chain 2:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:04<00:05, 38.29it/s]

Chain 1:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:06<00:00, 83.53it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:03<00:08, 30.30it/s]

Chain 2:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:04<00:04, 40.05it/s]

Chain 1:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:06<00:00, 89.71it/s]

Chain 3:  27%|████████████████████████████                                                                           | 98/360 [00:03<00:08, 30.19it/s]

Chain 2:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:05<00:04, 40.82it/s]

Chain 1:  89%|██████████████████████████████████████████████████████████████████████████████████████████▍           | 319/360 [00:06<00:00, 92.60it/s]

Chain 3:  28%|████████████████████████████▉                                                                         | 102/360 [00:03<00:08, 29.76it/s]

Chain 1:  92%|█████████████████████████████████████████████████████████████████████████████████████████████▍       | 333/360 [00:06<00:00, 104.34it/s]

Chain 2:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:05<00:04, 41.60it/s]

Chain 3:  29%|█████████████████████████████▊                                                                        | 105/360 [00:03<00:08, 28.37it/s]

Chain 1:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████▏  | 350/360 [00:06<00:00, 122.51it/s]

Chain 2:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:05<00:03, 44.63it/s]

Chain 3:  30%|██████████████████████████████▌                                                                       | 108/360 [00:03<00:08, 28.46it/s]

Chain 2:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:05<00:03, 46.57it/s]

Chain 3:  31%|███████████████████████████████▍                                                                      | 111/360 [00:03<00:08, 28.75it/s]

Chain 2:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:05<00:03, 44.89it/s]

Chain 3:  32%|████████████████████████████████▌                                                                     | 115/360 [00:03<00:07, 30.75it/s]

Chain 2:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:05<00:03, 45.32it/s]

Chain 3:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:03<00:07, 31.50it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:05<00:03, 45.54it/s]

Chain 3:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:03<00:07, 32.51it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:05<00:02, 49.38it/s]

Chain 3:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:04<00:06, 34.08it/s]

Chain 2:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:05<00:02, 53.67it/s]

Chain 3:  36%|█████████████████████████████████████                                                                 | 131/360 [00:04<00:06, 34.51it/s]

Chain 2:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:06<00:02, 52.79it/s]

Chain 3:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:04<00:06, 34.80it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:06<00:02, 54.57it/s]

Chain 3:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:04<00:06, 36.61it/s]

Chain 2:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:06<00:02, 58.07it/s]

Chain 3:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:04<00:05, 37.39it/s]

Chain 2:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:06<00:01, 61.98it/s]

Chain 3:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:04<00:05, 38.65it/s]

Chain 2:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:06<00:01, 66.65it/s]

Chain 3:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:04<00:05, 38.91it/s]

Chain 2:  73%|██████████████████████████████████████████████████████████████████████████▌                           | 263/360 [00:06<00:01, 68.57it/s]

Chain 3:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:04<00:05, 39.07it/s]

Chain 2:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:06<00:01, 69.87it/s]

Chain 3:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:04<00:04, 39.63it/s]

Chain 2:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:06<00:01, 69.09it/s]

Chain 2:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:06<00:00, 74.53it/s]

Chain 3:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:05<00:04, 40.48it/s]

Chain 2:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:07<00:00, 80.89it/s]

Chain 3:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:05<00:04, 42.45it/s]

Chain 2:  86%|███████████████████████████████████████████████████████████████████████████████████████▎              | 308/360 [00:07<00:00, 88.78it/s]

Chain 3:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:05<00:04, 43.22it/s]

Chain 2:  89%|██████████████████████████████████████████████████████████████████████████████████████████▎          | 322/360 [00:07<00:00, 102.44it/s]

Chain 3:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:05<00:04, 43.61it/s]

Chain 2:  93%|█████████████████████████████████████████████████████████████████████████████████████████████▋       | 334/360 [00:07<00:00, 107.48it/s]

Chain 3:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:05<00:03, 44.21it/s]

Chain 2:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████  | 353/360 [00:07<00:00, 130.16it/s]

Chain 3:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:05<00:03, 45.26it/s]

Chain 3:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:05<00:03, 47.62it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:05<00:02, 52.35it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:05<00:02, 56.29it/s]

Chain 3:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:06<00:02, 59.50it/s]

Chain 3:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:06<00:02, 62.45it/s]

Chain 3:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:06<00:01, 67.34it/s]

Chain 3:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:06<00:01, 73.31it/s]

Chain 3:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:06<00:01, 77.07it/s]

Chain 3:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:06<00:01, 82.09it/s]

Chain 3:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:06<00:00, 90.68it/s]

Chain 3:  80%|████████████████████████████████████████████████████████████████████████████████▊                    | 288/360 [00:06<00:00, 104.14it/s]

Chain 3:  84%|█████████████████████████████████████████████████████████████████████████████████████▎               | 304/360 [00:06<00:00, 119.78it/s]

Chain 3:  89%|█████████████████████████████████████████████████████████████████████████████████████████▍           | 319/360 [00:06<00:00, 126.55it/s]

Chain 3:  96%|████████████████████████████████████████████████████████████████████████████████████████████████▌    | 344/360 [00:07<00:00, 162.34it/s]

2026-05-28 17:34:30.442 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 17:34:30.595 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 17:34:32.899 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 17:34:33.265 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 17:34:33.266 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 17:34:33.270 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 17:34:33.579 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 17:34:33.595 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 17:34:33.768 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 17:34:34.007 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 17:34:34.280 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 17:34:34.366 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 17:34:34.367 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,33.3,68.7,128.2,215.2,302.8
GIIP (mscf),Total Volumes,1.0,13.8,28.4,55.5,99.3,147.4
Condensate (stb),Total Volumes,1.0,0.3,0.9,1.9,3.8,7.0
Solution Gas (mscf),Total Volumes,1.0,56.4,116.5,235.4,420.8,649.2

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)  P99   P90   P50   P10    P1
Total Oil EUR         1.0  7.2  15.2  29.9  51.7  74.6

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.56  1.1  2.9  7.4  17.7  36.6
Zone 2           0.89  1.2  2.8  7.0  16.9  32.0
Zone 3           0.57  1.1  2.6  5.6  11.7  19.2
Zone 4           0.77  1.1  2.4  6.1  14.1  30.1
Zone 5           0.87  0.5  1.4  4.5  12.0  28.8
Zone 6           0.61  0.5  1.9  5.4  13.6  26.8

In [14]:
reporter.tabler.npv_table()

     P(Commercial)    P99    P90    P50     P10      P1
NPV           0.81 -502.0 -157.0  376.0  1025.0  1540.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)    P99    P90    P50    P10      P1
EMV           0.81 -417.0 -136.0  297.0  826.0  1245.0

In [16]:
from resgo.plotting.tables import npv_USD
import numpy as np
import pandas as pd

npv = npv_USD(
    simpack,
    nominal=True,
    discounted=True,
    success_only=False,
)
npv_usd = npv.to_numpy().ravel()
npv_df = pd.DataFrame({"npv_usd_mm": npv_usd / 1e6})

histogram = (
    alt.Chart(npv_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "npv_usd_mm:Q",
            bin=alt.Bin(maxbins=60),
            title="Nominal discounted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", title="Simulation count"),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated NPV Distribution",
    )
)

break_even = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(histogram, break_even)
fig.show()

alt.LayerChart(...)

In [17]:
def loss_adjusted_npv_USD(
    npv_usd,
    bankruptcy_threshold_usd=500e6,
    floor_usd=-10e9,
):
    npv_usd = np.asarray(npv_usd)
    threshold = bankruptcy_threshold_usd

    with np.errstate(divide="ignore", invalid="ignore"):
        adjusted = np.where(
            npv_usd >= 0,
            npv_usd,
            (threshold * npv_usd) / (threshold + npv_usd),
        )

    adjusted = np.where(npv_usd <= -threshold, floor_usd, adjusted)
    return np.maximum(adjusted, floor_usd)

x_usd = np.linspace(-499.9e6, 1.5e9, 1_000)
loss_function_df = pd.DataFrame(
    {
        "npv_usd_mm": x_usd / 1e6,
        "loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(x_usd) / 1e6,
    }
)

loss_function = (
    alt.Chart(loss_function_df)
    .mark_line(color="#FACC15", strokeWidth=3)
    .encode(
        x=alt.X("npv_usd_mm:Q", title="Nominal discounted NPV ($USD MM)"),
        y=alt.Y(
            "loss_adjusted_npv_usd_mm:Q",
            title="Loss-adjusted NPV ($USD MM)",
        ),
        tooltip=[
            alt.Tooltip("npv_usd_mm:Q", title="NPV ($MM)", format=",.0f"),
            alt.Tooltip(
                "loss_adjusted_npv_usd_mm:Q",
                title="Loss-adjusted NPV ($MM)",
                format=",.0f",
            ),
        ],
    )
    .properties(
        width=650,
        height=250,
        title="Company Loss Function",
    )
)

bankruptcy_threshold = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [-500]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

loss_floor = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [-10_000]}))
    .mark_rule(color="red", strokeDash=[2, 4], strokeWidth=1)
    .encode(y="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_function, bankruptcy_threshold, loss_floor)
fig.show()

alt.LayerChart(...)

In [18]:
loss_df = pd.DataFrame(
    {"loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(npv_usd) / 1e6}
)

loss_histogram = (
    alt.Chart(loss_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "loss_adjusted_npv_usd_mm:Q",
            bin=alt.Bin(maxbins=60),
            title="Loss-adjusted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", title="Simulation count"),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated Loss-Adjusted NPV Distribution",
    )
)

break_even_loss = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_histogram, break_even_loss)
fig.show()

alt.LayerChart(...)