In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_624379/1985460196.py:25: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats(fig_format)

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 42

CHAINS = 10
DRAWS = 500
N_RESERVOIRS = 10
N_PRODUCERS = 25

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=60_000,
    gas_development=False,
    producer_capex_USD=80e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=350e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2e6,
    producer_abandonment_cost_USD=0.5e6,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 21:59:57.431 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 21:59:57.435 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 21:59:57.439 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 21:59:57.444 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 21:59:57.448 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 21:59:57.452 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 21:59:57.457 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 7 reservoir volumetric simulation complete.

2026-05-28 21:59:57.461 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 8 reservoir volumetric simulation complete.

2026-05-28 21:59:57.466 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 9 reservoir volumetric simulation complete.

2026-05-28 21:59:57.470 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 10 reservoir volumetric simulation complete.

2026-05-28 21:59:57.475 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 21:59:57.476 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 21:59:58.295 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 21:59:58.296 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 21:59:58.297 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 21:59:58.297 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 21:59:58.297 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 21:59:58.297 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 21:59:58.297 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 21:59:58.298 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 21:59:58.298 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 21:59:58.298 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 21:59:58.298 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 21:59:58.298 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 21:59:58.298 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 21:59:58.298 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 21 start_idx = 245

2026-05-28 21:59:58.299 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 22 start_idx = 257

2026-05-28 21:59:58.300 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 23 start_idx = 269

2026-05-28 21:59:58.300 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 24 start_idx = 280

2026-05-28 21:59:58.300 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 25 start_idx = 292

2026-05-28 21:59:58.340 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 21:59:58.355 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 21:59:58.986 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 21:59:58.987 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 21:59:58.987 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (25 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 83.11it/s]

Chain 0:   6%|█████▋                                                                                                 | 20/360 [00:00<00:09, 34.47it/s]

Chain 0:   7%|███████▏                                                                                               | 25/360 [00:00<00:11, 29.64it/s]

Chain 0:   8%|████████▎                                                                                              | 29/360 [00:00<00:12, 27.45it/s]

Chain 0:   9%|█████████▍                                                                                             | 33/360 [00:01<00:12, 25.76it/s]

Chain 0:  10%|██████████▎                                                                                            | 36/360 [00:01<00:12, 25.00it/s]

Chain 0:  11%|███████████▏                                                                                           | 39/360 [00:01<00:13, 24.54it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:01<00:13, 24.39it/s]

Chain 0:  12%|████████████▉                                                                                          | 45/360 [00:01<00:12, 24.37it/s]

Chain 0:  13%|█████████████▋                                                                                         | 48/360 [00:01<00:12, 24.17it/s]

Chain 0:  14%|██████████████▌                                                                                        | 51/360 [00:01<00:12, 23.96it/s]

Chain 0:  15%|███████████████▍                                                                                       | 54/360 [00:01<00:12, 23.93it/s]

Chain 0:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:12, 24.00it/s]

Chain 0:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:12, 23.32it/s]

Chain 0:  18%|██████████████████                                                                                     | 63/360 [00:02<00:12, 23.03it/s]

Chain 0:  18%|██████████████████▉                                                                                    | 66/360 [00:02<00:13, 22.54it/s]

Chain 0:  19%|███████████████████▋                                                                                   | 69/360 [00:02<00:12, 22.48it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  20%|████████████████████▌                                                                                  | 72/360 [00:02<00:12, 22.53it/s]

Chain 1:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 76.79it/s]

Chain 0:  21%|█████████████████████▍                                                                                 | 75/360 [00:02<00:12, 22.87it/s]

Chain 0:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:12, 22.91it/s]

Chain 0:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:12, 23.03it/s]

Chain 1:   5%|█████▍                                                                                                 | 19/360 [00:00<00:10, 33.15it/s]

Chain 0:  23%|████████████████████████                                                                               | 84/360 [00:03<00:11, 23.02it/s]

Chain 0:  24%|████████████████████████▉                                                                              | 87/360 [00:03<00:11, 22.76it/s]

Chain 1:   7%|██████▊                                                                                                | 24/360 [00:00<00:11, 28.33it/s]

Chain 0:  25%|█████████████████████████▊                                                                             | 90/360 [00:03<00:11, 22.89it/s]

Chain 1:   8%|████████                                                                                               | 28/360 [00:00<00:12, 26.48it/s]

Chain 0:  26%|██████████████████████████▌                                                                            | 93/360 [00:03<00:11, 23.26it/s]

Chain 1:   9%|████████▊                                                                                              | 31/360 [00:01<00:13, 24.88it/s]

Chain 0:  27%|███████████████████████████▍                                                                           | 96/360 [00:03<00:10, 24.07it/s]

Chain 1:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 24.00it/s]

Chain 0:  28%|████████████████████████████▎                                                                          | 99/360 [00:03<00:10, 24.18it/s]

Chain 0:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:10, 24.69it/s]

Chain 1:  10%|██████████▌                                                                                            | 37/360 [00:01<00:13, 23.41it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:10, 24.99it/s]

Chain 1:  11%|███████████▍                                                                                           | 40/360 [00:01<00:13, 23.19it/s]

Chain 0:  30%|██████████████████████████████▌                                                                       | 108/360 [00:04<00:10, 25.10it/s]

Chain 1:  12%|████████████▎                                                                                          | 43/360 [00:01<00:13, 23.11it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:04<00:09, 25.34it/s]

Chain 1:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:13, 23.16it/s]

Chain 0:  32%|████████████████████████████████▎                                                                     | 114/360 [00:04<00:09, 25.58it/s]

Chain 1:  14%|██████████████                                                                                         | 49/360 [00:01<00:13, 23.23it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:04<00:09, 25.68it/s]

Chain 1:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:13, 23.22it/s]

Chain 0:  33%|██████████████████████████████████                                                                    | 120/360 [00:04<00:09, 25.99it/s]

Chain 1:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 23.26it/s]

Chain 0:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:04<00:09, 26.24it/s]

Chain 1:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:13, 22.99it/s]

Chain 0:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:04<00:08, 26.43it/s]

Chain 0:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:05<00:08, 26.47it/s]

Chain 1:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:13, 22.85it/s]

Chain 0:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:05<00:08, 26.48it/s]

Chain 1:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:13, 22.63it/s]

Chain 0:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:05<00:08, 26.51it/s]

Chain 1:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:13, 22.45it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  38%|███████████████████████████████████████                                                               | 138/360 [00:05<00:08, 26.50it/s]

Chain 1:  19%|████████████████████                                                                                   | 70/360 [00:02<00:13, 22.29it/s]

Chain 0:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:05<00:08, 26.69it/s]

Chain 2:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 75.50it/s]

Chain 0:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:05<00:07, 27.05it/s]

Chain 1:  20%|████████████████████▉                                                                                  | 73/360 [00:02<00:12, 22.18it/s]

Chain 0:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:05<00:07, 27.42it/s]

Chain 1:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:12, 22.43it/s]

Chain 0:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:05<00:07, 27.58it/s]

Chain 1:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:12, 22.28it/s]

Chain 2:   5%|█████▍                                                                                                 | 19/360 [00:00<00:10, 32.57it/s]

Chain 0:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:05<00:07, 27.37it/s]

Chain 1:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:12, 22.44it/s]

Chain 0:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:06<00:07, 27.89it/s]

Chain 0:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:06<00:07, 28.43it/s]

Chain 1:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:12, 22.47it/s]

Chain 2:   7%|██████▊                                                                                                | 24/360 [00:00<00:12, 27.91it/s]

Chain 0:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:06<00:06, 28.65it/s]

Chain 1:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:12, 22.49it/s]

Chain 2:   8%|████████                                                                                               | 28/360 [00:00<00:12, 26.11it/s]

Chain 0:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:06<00:06, 29.27it/s]

Chain 1:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:11, 22.48it/s]

Chain 2:   9%|████████▊                                                                                              | 31/360 [00:01<00:13, 24.65it/s]

Chain 0:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:06<00:06, 29.90it/s]

Chain 1:  26%|██████████████████████████▉                                                                            | 94/360 [00:03<00:11, 23.22it/s]

Chain 0:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:06<00:06, 30.79it/s]

Chain 2:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 23.27it/s]

Chain 1:  27%|███████████████████████████▊                                                                           | 97/360 [00:03<00:10, 23.99it/s]

Chain 0:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:06<00:05, 31.17it/s]

Chain 1:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:10, 24.68it/s]

Chain 2:  10%|██████████▌                                                                                            | 37/360 [00:01<00:14, 22.84it/s]

Chain 0:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:06<00:05, 32.00it/s]

Chain 1:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:10, 25.00it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:01<00:14, 22.61it/s]

Chain 0:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:07<00:05, 32.59it/s]

Chain 1:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:10, 24.90it/s]

Chain 2:  12%|████████████▎                                                                                          | 43/360 [00:01<00:14, 22.26it/s]

Chain 0:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:07<00:05, 33.28it/s]

Chain 1:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:10, 24.89it/s]

Chain 2:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:14, 22.22it/s]

Chain 0:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:07<00:04, 34.12it/s]

Chain 1:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:09, 25.02it/s]

Chain 2:  14%|██████████████                                                                                         | 49/360 [00:01<00:13, 22.28it/s]

Chain 0:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:07<00:04, 34.71it/s]

Chain 1:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:09, 25.16it/s]

Chain 0:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:07<00:04, 35.43it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:13, 22.38it/s]

Chain 1:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:04<00:09, 25.27it/s]

Chain 0:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:07<00:04, 35.98it/s]

Chain 2:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 22.31it/s]

Chain 1:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:04<00:09, 25.44it/s]

Chain 0:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:07<00:04, 36.37it/s]

Chain 1:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:09, 25.32it/s]

Chain 2:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:13, 21.90it/s]

Chain 0:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:07<00:03, 36.99it/s]

Chain 1:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:09, 25.22it/s]

Chain 0:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:07<00:03, 37.59it/s]

Chain 2:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:13, 21.73it/s]

Chain 0:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:07<00:03, 38.14it/s]

Chain 1:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 25.05it/s]

Chain 2:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:13, 21.56it/s]

Chain 0:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:08<00:03, 38.25it/s]

Chain 1:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:09, 25.11it/s]

Chain 2:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:14, 20.91it/s]

Chain 0:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:08<00:03, 37.57it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:09, 24.76it/s]

Chain 0:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:08<00:03, 39.40it/s]

Chain 3:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 98.27it/s]

Chain 2:  19%|████████████████████                                                                                   | 70/360 [00:02<00:13, 20.90it/s]

Chain 1:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:05<00:08, 25.19it/s]

Chain 0:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:08<00:02, 40.58it/s]

Chain 1:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:05<00:08, 24.98it/s]

Chain 2:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:13, 20.87it/s]

Chain 0:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:08<00:02, 42.54it/s]

Chain 1:  40%|█████████████████████████████████████████                                                             | 145/360 [00:05<00:08, 25.59it/s]

Chain 2:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:13, 20.98it/s]

Chain 0:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:08<00:02, 44.01it/s]

Chain 1:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:05<00:08, 25.83it/s]

Chain 0:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:08<00:02, 45.51it/s]

Chain 2:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.99it/s]

Chain 1:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:07, 26.19it/s]

Chain 3:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 29.40it/s]

Chain 0:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:08<00:02, 47.48it/s]

Chain 2:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 21.07it/s]

Chain 1:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 26.34it/s]

Chain 0:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:08<00:01, 49.06it/s]

Chain 1:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 26.32it/s]

Chain 2:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.67it/s]

Chain 0:  76%|█████████████████████████████████████████████████████████████████████████████▎                        | 273/360 [00:09<00:01, 51.20it/s]

Chain 1:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:07, 27.02it/s]

Chain 3:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 25.51it/s]

Chain 0:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:09<00:01, 54.57it/s]

Chain 2:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:13, 20.78it/s]

Chain 1:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:06<00:07, 27.18it/s]

Chain 0:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:09<00:01, 57.20it/s]

Chain 3:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.96it/s]

Chain 1:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:06<00:06, 27.81it/s]

Chain 2:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:12, 20.77it/s]

Chain 0:  82%|███████████████████████████████████████████████████████████████████████████████████▌                  | 295/360 [00:09<00:01, 62.67it/s]

Chain 1:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:06<00:07, 25.07it/s]

Chain 0:  84%|█████████████████████████████████████████████████████████████████████████████████████▊                | 303/360 [00:09<00:00, 66.53it/s]

Chain 2:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:13, 19.63it/s]

Chain 3:   9%|█████████▋                                                                                             | 34/360 [00:01<00:15, 21.13it/s]

Chain 1:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:06<00:07, 26.33it/s]

Chain 0:  87%|████████████████████████████████████████████████████████████████████████████████████████▍             | 312/360 [00:09<00:00, 72.29it/s]

Chain 2:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 20.93it/s]

Chain 0:  89%|███████████████████████████████████████████████████████████████████████████████████████████▏          | 322/360 [00:09<00:00, 79.74it/s]

Chain 1:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:07<00:06, 27.89it/s]

Chain 3:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 20.94it/s]

Chain 2:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 21.92it/s]

Chain 0:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▉       | 335/360 [00:09<00:00, 92.45it/s]

Chain 1:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:06, 28.93it/s]

Chain 3:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.83it/s]

Chain 2:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:11, 22.45it/s]

Chain 0:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████▊  | 352/360 [00:09<00:00, 113.46it/s]

Chain 1:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:05, 29.42it/s]

Chain 2:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 22.56it/s]

Chain 3:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 20.90it/s]

Chain 1:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:07<00:05, 30.13it/s]

Chain 2:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:11, 22.81it/s]

Chain 3:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:14, 21.02it/s]

Chain 1:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:07<00:05, 30.74it/s]

Chain 2:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:10, 23.03it/s]

Chain 3:  14%|██████████████                                                                                         | 49/360 [00:02<00:14, 20.97it/s]

Chain 1:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:07<00:05, 31.46it/s]

Chain 2:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:10, 23.18it/s]

Chain 3:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:14, 20.96it/s]

Chain 1:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:07<00:04, 32.12it/s]

Chain 2:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:10, 23.36it/s]

Chain 1:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:07<00:04, 32.53it/s]

Chain 3:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:14, 20.85it/s]

Chain 2:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 23.24it/s]

Chain 1:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:07<00:04, 33.13it/s]

Chain 3:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:14, 20.29it/s]

Chain 2:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 23.40it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:08<00:04, 33.45it/s]

Chain 3:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:14, 20.06it/s]

Chain 2:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:09, 23.43it/s]

Chain 1:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:08<00:04, 33.99it/s]

Chain 2:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 23.51it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:08<00:04, 34.72it/s]

Chain 3:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:14, 19.94it/s]

Chain 2:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:09, 24.17it/s]

Chain 1:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:08<00:03, 36.58it/s]

Chain 3:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:14, 20.11it/s]

Chain 4:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:08<00:03, 37.00it/s]

Chain 2:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:09, 24.31it/s]

Chain 3:  19%|████████████████████                                                                                   | 70/360 [00:03<00:14, 20.17it/s]

Chain 4:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 96.51it/s]

Chain 2:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:05<00:08, 24.86it/s]

Chain 1:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:08<00:03, 38.61it/s]

Chain 3:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 20.42it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:08<00:03, 40.13it/s]

Chain 2:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 24.64it/s]

Chain 1:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:08<00:02, 41.69it/s]

Chain 2:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 25.33it/s]

Chain 3:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:13, 20.85it/s]

Chain 1:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:09<00:02, 43.00it/s]

Chain 2:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 25.47it/s]

Chain 3:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.84it/s]

Chain 1:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:09<00:02, 44.65it/s]

Chain 2:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:08, 25.96it/s]

Chain 4:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 29.60it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 21.03it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:09<00:02, 46.91it/s]

Chain 2:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 26.60it/s]

Chain 1:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:09<00:01, 48.33it/s]

Chain 3:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.86it/s]

Chain 2:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 26.54it/s]

Chain 1:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:09<00:01, 50.59it/s]

Chain 4:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 25.50it/s]

Chain 2:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:07, 27.13it/s]

Chain 3:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:13, 20.85it/s]

Chain 1:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:09<00:01, 52.79it/s]

Chain 2:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:06<00:07, 27.52it/s]

Chain 1:  79%|████████████████████████████████████████████████████████████████████████████████▍                     | 284/360 [00:09<00:01, 54.66it/s]

Chain 3:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:13, 20.29it/s]

Chain 4:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.89it/s]

Chain 2:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 27.69it/s]

Chain 1:  81%|██████████████████████████████████████████████████████████████████████████████████▋                   | 292/360 [00:09<00:01, 59.60it/s]

Chain 2:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:07, 25.13it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:14, 18.60it/s]

Chain 1:  83%|████████████████████████████████████████████████████████████████████████████████████▋                 | 299/360 [00:09<00:00, 62.06it/s]

Chain 2:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:07, 26.06it/s]

Chain 4:   9%|█████████▋                                                                                             | 34/360 [00:01<00:15, 20.41it/s]

Chain 3:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:13, 20.03it/s]

Chain 1:  85%|██████████████████████████████████████████████████████████████████████████████████████▉               | 307/360 [00:09<00:00, 65.42it/s]

Chain 2:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 26.80it/s]

Chain 1:  88%|█████████████████████████████████████████████████████████████████████████████████████████▎            | 315/360 [00:10<00:00, 69.52it/s]

Chain 4:  10%|██████████▌                                                                                            | 37/360 [00:01<00:16, 20.09it/s]

Chain 3:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:12, 20.49it/s]

Chain 2:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:06, 27.26it/s]

Chain 1:  90%|███████████████████████████████████████████████████████████████████████████████████████████▊          | 324/360 [00:10<00:00, 75.24it/s]

Chain 3:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:12, 21.29it/s]

Chain 4:  11%|███████████▍                                                                                           | 40/360 [00:01<00:16, 19.99it/s]

Chain 2:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:06, 26.83it/s]

Chain 1:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▉       | 335/360 [00:10<00:00, 85.07it/s]

Chain 2:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:06, 27.46it/s]

Chain 3:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 21.43it/s]

Chain 1:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████▌   | 348/360 [00:10<00:00, 97.75it/s]

Chain 4:  12%|████████████▎                                                                                          | 43/360 [00:01<00:16, 19.73it/s]

Chain 2:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:07<00:06, 27.82it/s]

Chain 3:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:12, 20.70it/s]

Chain 2:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:07<00:06, 27.13it/s]

Chain 4:  13%|█████████████▏                                                                                         | 46/360 [00:02<00:16, 18.95it/s]

Chain 3:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:11, 21.17it/s]

Chain 4:  13%|█████████████▋                                                                                         | 48/360 [00:02<00:16, 18.79it/s]

Chain 2:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:07<00:05, 28.56it/s]

Chain 4:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:16, 18.80it/s]

Chain 3:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:11, 21.68it/s]

Chain 2:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:08<00:05, 29.88it/s]

Chain 4:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:16, 18.97it/s]

Chain 3:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:10, 22.02it/s]

Chain 2:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:08<00:05, 30.92it/s]

Chain 4:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:16, 19.12it/s]

Chain 3:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 22.39it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:08<00:04, 31.54it/s]

Chain 4:  16%|████████████████                                                                                       | 56/360 [00:02<00:15, 19.18it/s]

Chain 3:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 22.82it/s]

Chain 2:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:08<00:04, 31.93it/s]

Chain 4:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:15, 19.19it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:08<00:04, 32.99it/s]

Chain 4:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:15, 19.17it/s]

Chain 3:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:10, 22.90it/s]

Chain 2:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:08<00:04, 34.06it/s]

Chain 4:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:15, 19.29it/s]

Chain 3:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 23.16it/s]

Chain 4:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 18.51it/s]

Chain 2:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:08<00:04, 33.60it/s]

Chain 5:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 3:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:09, 23.43it/s]

Chain 2:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:08<00:03, 34.41it/s]

Chain 5:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 96.80it/s]

Chain 4:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:15, 19.40it/s]

Chain 3:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:09, 23.79it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:09<00:03, 36.46it/s]

Chain 3:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:09, 24.11it/s]

Chain 4:  19%|████████████████████                                                                                   | 70/360 [00:03<00:14, 19.80it/s]

Chain 2:  66%|██████████████████████████████████████████████████████████████████▊                                   | 236/360 [00:09<00:03, 38.37it/s]

Chain 3:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 24.25it/s]

Chain 4:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 20.35it/s]

Chain 2:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:09<00:02, 40.08it/s]

Chain 3:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 24.61it/s]

Chain 4:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:13, 20.29it/s]

Chain 2:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:09<00:02, 41.21it/s]

Chain 3:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 25.16it/s]

Chain 5:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 28.82it/s]

Chain 2:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:09<00:02, 42.63it/s]

Chain 4:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.65it/s]

Chain 3:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:08, 25.62it/s]

Chain 2:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:09<00:02, 43.54it/s]

Chain 3:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 26.04it/s]

Chain 4:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 20.62it/s]

Chain 2:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:09<00:02, 45.83it/s]

Chain 5:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 25.16it/s]

Chain 3:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 26.43it/s]

Chain 4:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.68it/s]

Chain 2:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:09<00:01, 48.23it/s]

Chain 3:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:07, 26.92it/s]

Chain 2:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:09<00:01, 50.31it/s]

Chain 4:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:13, 20.66it/s]

Chain 5:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.63it/s]

Chain 3:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:07, 27.22it/s]

Chain 2:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:10<00:01, 51.36it/s]

Chain 3:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 27.38it/s]

Chain 4:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:13, 20.29it/s]

Chain 2:  79%|█████████████████████████████████████████████████████████████████████████████████                     | 286/360 [00:10<00:01, 52.92it/s]

Chain 5:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 22.21it/s]

Chain 3:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 27.45it/s]

Chain 4:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:12, 20.51it/s]

Chain 2:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:10<00:01, 55.41it/s]

Chain 3:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:07, 26.75it/s]

Chain 5:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 21.26it/s]

Chain 2:  83%|█████████████████████████████████████████████████████████████████████████████████████                 | 300/360 [00:10<00:01, 58.24it/s]

Chain 4:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 20.97it/s]

Chain 3:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 26.83it/s]

Chain 2:  86%|███████████████████████████████████████████████████████████████████████████████████████▎              | 308/360 [00:10<00:00, 62.88it/s]

Chain 5:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.56it/s]

Chain 4:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:12, 21.60it/s]

Chain 3:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:06, 27.46it/s]

Chain 2:  88%|█████████████████████████████████████████████████████████████████████████████████████████▊            | 317/360 [00:10<00:00, 68.40it/s]

Chain 3:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:06, 27.99it/s]

Chain 5:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 19.82it/s]

Chain 4:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:12, 21.37it/s]

Chain 2:  91%|████████████████████████████████████████████████████████████████████████████████████████████▎         | 326/360 [00:10<00:00, 73.34it/s]

Chain 3:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:06, 28.53it/s]

Chain 4:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 21.44it/s]

Chain 2:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▍      | 337/360 [00:10<00:00, 83.41it/s]

Chain 5:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:16, 19.60it/s]

Chain 3:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:08<00:06, 28.83it/s]

Chain 2:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████▊  | 352/360 [00:10<00:00, 101.27it/s]

Chain 4:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:11, 21.76it/s]

Chain 3:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:08<00:05, 29.57it/s]

Chain 5:  14%|██████████████                                                                                         | 49/360 [00:02<00:16, 19.38it/s]

Chain 3:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:08<00:05, 29.65it/s]

Chain 4:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:11, 21.93it/s]

Chain 5:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:16, 19.15it/s]

Chain 3:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:08<00:05, 30.20it/s]

Chain 5:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:16, 19.08it/s]

Chain 4:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:11, 21.93it/s]

Chain 5:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:15, 19.14it/s]

Chain 3:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:08<00:05, 31.03it/s]

Chain 4:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:10, 22.23it/s]

Chain 5:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 19.00it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:08<00:04, 31.57it/s]

Chain 4:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 22.50it/s]

Chain 5:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:16, 18.58it/s]

Chain 3:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:08<00:04, 32.26it/s]

Chain 4:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 22.50it/s]

Chain 5:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:16, 18.42it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:08<00:04, 33.11it/s]

Chain 5:  18%|██████████████████                                                                                     | 63/360 [00:02<00:16, 18.38it/s]

Chain 4:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:10, 22.07it/s]

Chain 3:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:08<00:04, 34.33it/s]

Chain 5:  18%|██████████████████▌                                                                                    | 65/360 [00:03<00:16, 17.70it/s]

Chain 4:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:06<00:10, 22.04it/s]

Chain 3:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:09<00:04, 34.20it/s]

Chain 6:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 5:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:16, 17.69it/s]

Chain 3:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:09<00:03, 34.54it/s]

Chain 4:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:10, 22.32it/s]

Chain 6:   3%|██▊                                                                                                    | 10/360 [00:00<00:04, 85.26it/s]

Chain 5:  19%|███████████████████▋                                                                                   | 69/360 [00:03<00:16, 17.98it/s]

Chain 3:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:09<00:03, 35.93it/s]

Chain 4:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:09, 23.03it/s]

Chain 3:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:09<00:03, 38.17it/s]

Chain 5:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:15, 19.04it/s]

Chain 4:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:09, 23.59it/s]

Chain 5:  21%|█████████████████████▏                                                                                 | 74/360 [00:03<00:14, 19.28it/s]

Chain 3:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:09<00:03, 39.98it/s]

Chain 4:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:09, 23.97it/s]

Chain 3:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:09<00:02, 41.53it/s]

Chain 5:  21%|██████████████████████                                                                                 | 77/360 [00:03<00:14, 19.77it/s]

Chain 4:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 24.54it/s]

Chain 6:   5%|█████▍                                                                                                 | 19/360 [00:00<00:11, 30.00it/s]

Chain 3:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:09<00:02, 43.02it/s]

Chain 4:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 25.13it/s]

Chain 5:  22%|██████████████████████▉                                                                                | 80/360 [00:03<00:13, 20.36it/s]

Chain 3:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:09<00:02, 44.21it/s]

Chain 4:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:08, 25.38it/s]

Chain 6:   7%|██████▊                                                                                                | 24/360 [00:00<00:13, 25.79it/s]

Chain 5:  23%|███████████████████████▋                                                                               | 83/360 [00:03<00:13, 20.50it/s]

Chain 3:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:09<00:02, 45.80it/s]

Chain 4:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:07<00:08, 25.65it/s]

Chain 3:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:10<00:02, 45.65it/s]

Chain 5:  24%|████████████████████████▌                                                                              | 86/360 [00:04<00:13, 20.39it/s]

Chain 4:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:07<00:07, 25.73it/s]

Chain 6:   8%|████████                                                                                               | 28/360 [00:01<00:13, 23.75it/s]

Chain 3:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:10<00:01, 48.71it/s]

Chain 4:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:07, 26.32it/s]

Chain 5:  25%|█████████████████████████▍                                                                             | 89/360 [00:04<00:13, 20.28it/s]

Chain 3:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:10<00:01, 50.86it/s]

Chain 6:   9%|████████▊                                                                                              | 31/360 [00:01<00:14, 22.16it/s]

Chain 4:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:07, 25.75it/s]

Chain 3:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:10<00:01, 50.83it/s]

Chain 5:  26%|██████████████████████████▎                                                                            | 92/360 [00:04<00:13, 19.99it/s]

Chain 6:   9%|█████████▋                                                                                             | 34/360 [00:01<00:15, 21.21it/s]

Chain 4:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 25.82it/s]

Chain 3:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:10<00:01, 54.52it/s]

Chain 5:  26%|███████████████████████████▏                                                                           | 95/360 [00:04<00:12, 20.91it/s]

Chain 4:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:07, 26.36it/s]

Chain 3:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:10<00:01, 59.77it/s]

Chain 6:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 20.22it/s]

Chain 5:  27%|████████████████████████████                                                                           | 98/360 [00:04<00:12, 21.61it/s]

Chain 4:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:07, 26.73it/s]

Chain 3:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:10<00:00, 62.55it/s]

Chain 5:  28%|████████████████████████████▌                                                                         | 101/360 [00:04<00:11, 22.08it/s]

Chain 6:  11%|███████████▍                                                                                           | 40/360 [00:01<00:16, 19.97it/s]

Chain 4:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 27.05it/s]

Chain 3:  87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 314/360 [00:10<00:00, 68.87it/s]

Chain 4:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:06, 27.04it/s]

Chain 5:  29%|█████████████████████████████▍                                                                        | 104/360 [00:04<00:11, 22.01it/s]

Chain 3:  90%|███████████████████████████████████████████████████████████████████████████████████████████▊          | 324/360 [00:10<00:00, 76.20it/s]

Chain 6:  12%|████████████▎                                                                                          | 43/360 [00:01<00:16, 19.72it/s]

Chain 4:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:08<00:06, 27.27it/s]

Chain 3:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▉       | 335/360 [00:11<00:00, 83.70it/s]

Chain 5:  30%|██████████████████████████████▎                                                                       | 107/360 [00:05<00:11, 22.17it/s]

Chain 6:  13%|█████████████▏                                                                                         | 46/360 [00:02<00:16, 19.27it/s]

Chain 3:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████▉   | 349/360 [00:11<00:00, 98.42it/s]

Chain 4:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:08<00:06, 28.43it/s]

Chain 5:  31%|███████████████████████████████▏                                                                      | 110/360 [00:05<00:11, 21.72it/s]

Chain 4:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:08<00:06, 28.61it/s]

Chain 6:  14%|██████████████                                                                                         | 49/360 [00:02<00:15, 19.58it/s]

Chain 5:  31%|████████████████████████████████                                                                      | 113/360 [00:05<00:11, 21.46it/s]

Chain 6:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:15, 19.66it/s]

Chain 4:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:08<00:05, 29.23it/s]

Chain 6:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:15, 19.50it/s]

Chain 5:  32%|████████████████████████████████▊                                                                     | 116/360 [00:05<00:11, 21.29it/s]

Chain 4:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:08<00:05, 29.86it/s]

Chain 6:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:15, 19.46it/s]

Chain 5:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:05<00:11, 21.78it/s]

Chain 4:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:08<00:05, 30.24it/s]

Chain 6:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 18.99it/s]

Chain 5:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:05<00:10, 22.09it/s]

Chain 4:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:08<00:05, 30.79it/s]

Chain 6:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:16, 18.61it/s]

Chain 5:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:05<00:10, 22.45it/s]

Chain 4:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:08<00:04, 31.57it/s]

Chain 6:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:16, 18.65it/s]

Chain 5:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:05<00:10, 22.83it/s]

Chain 4:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:09<00:04, 31.59it/s]

Chain 6:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 19.22it/s]

Chain 5:  36%|█████████████████████████████████████                                                                 | 131/360 [00:06<00:09, 23.04it/s]

Chain 4:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:09<00:04, 32.54it/s]

Chain 6:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:15, 18.96it/s]

Chain 7:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 4:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:09<00:04, 32.73it/s]

Chain 5:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:06<00:09, 22.94it/s]

Chain 6:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:15, 18.90it/s]

Chain 7:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 87.97it/s]

Chain 4:  62%|███████████████████████████████████████████████████████████████▍                                      | 224/360 [00:09<00:04, 33.78it/s]

Chain 6:  19%|████████████████████                                                                                   | 70/360 [00:03<00:15, 18.73it/s]

Chain 5:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:06<00:09, 22.93it/s]

Chain 4:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:09<00:03, 35.94it/s]

Chain 5:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:06<00:09, 23.20it/s]

Chain 6:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 19.33it/s]

Chain 4:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:09<00:03, 37.32it/s]

Chain 5:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:06<00:09, 23.75it/s]

Chain 6:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:14, 20.14it/s]

Chain 4:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:09<00:03, 39.37it/s]

Chain 5:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:06<00:08, 24.60it/s]

Chain 7:   5%|█████▍                                                                                                 | 19/360 [00:00<00:11, 29.14it/s]

Chain 6:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.82it/s]

Chain 4:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:09<00:02, 41.22it/s]

Chain 5:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:06<00:08, 25.03it/s]

Chain 4:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:09<00:02, 42.51it/s]

Chain 6:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 20.59it/s]

Chain 5:  42%|███████████████████████████████████████████                                                           | 152/360 [00:06<00:08, 24.38it/s]

Chain 7:   7%|██████▊                                                                                                | 24/360 [00:00<00:13, 25.40it/s]

Chain 4:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:10<00:02, 44.40it/s]

Chain 6:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 19.84it/s]

Chain 5:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:07<00:08, 25.19it/s]

Chain 4:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:10<00:02, 45.28it/s]

Chain 6:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:14, 19.37it/s]

Chain 7:   8%|████████                                                                                               | 28/360 [00:01<00:13, 23.76it/s]

Chain 5:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:07<00:07, 25.61it/s]

Chain 4:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:10<00:02, 47.38it/s]

Chain 6:  25%|█████████████████████████▍                                                                             | 89/360 [00:04<00:14, 19.23it/s]

Chain 5:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:07<00:07, 26.06it/s]

Chain 4:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:10<00:01, 49.35it/s]

Chain 7:   9%|████████▊                                                                                              | 31/360 [00:01<00:14, 22.67it/s]

Chain 6:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:14, 19.04it/s]

Chain 5:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:07<00:07, 26.31it/s]

Chain 4:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:10<00:01, 50.80it/s]

Chain 7:   9%|█████████▋                                                                                             | 34/360 [00:01<00:15, 21.58it/s]

Chain 5:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:07<00:07, 27.04it/s]

Chain 6:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:13, 19.91it/s]

Chain 4:  79%|████████████████████████████████████████████████████████████████████████████████▍                     | 284/360 [00:10<00:01, 54.44it/s]

Chain 5:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:07<00:06, 27.77it/s]

Chain 7:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 21.03it/s]

Chain 6:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 21.03it/s]

Chain 4:  81%|██████████████████████████████████████████████████████████████████████████████████▍                   | 291/360 [00:10<00:01, 57.75it/s]

Chain 5:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:07<00:06, 28.12it/s]

Chain 6:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 21.69it/s]

Chain 4:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:10<00:01, 61.05it/s]

Chain 7:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.87it/s]

Chain 5:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:07<00:06, 28.37it/s]

Chain 4:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:10<00:00, 55.76it/s]

Chain 6:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:12, 21.03it/s]

Chain 5:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:06, 28.34it/s]

Chain 7:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 20.05it/s]

Chain 4:  87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 314/360 [00:11<00:00, 63.01it/s]

Chain 6:  29%|██████████████████████████████                                                                        | 106/360 [00:05<00:12, 21.16it/s]

Chain 5:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:08<00:06, 29.15it/s]

Chain 7:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:15, 20.32it/s]

Chain 4:  90%|███████████████████████████████████████████████████████████████████████████████████████████▌          | 323/360 [00:11<00:00, 68.67it/s]

Chain 5:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:08<00:05, 29.28it/s]

Chain 6:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:11, 21.14it/s]

Chain 4:  92%|██████████████████████████████████████████████████████████████████████████████████████████████▎       | 333/360 [00:11<00:00, 77.09it/s]

Chain 7:  14%|██████████████                                                                                         | 49/360 [00:02<00:15, 20.32it/s]

Chain 5:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:08<00:05, 28.89it/s]

Chain 4:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████▎   | 347/360 [00:11<00:00, 93.95it/s]

Chain 6:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:11, 21.73it/s]

Chain 7:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:15, 20.28it/s]

Chain 5:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:08<00:05, 28.66it/s]

Chain 6:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:11, 21.83it/s]

Chain 5:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:08<00:05, 29.97it/s]

Chain 7:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:15, 20.02it/s]

Chain 6:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:11, 21.93it/s]

Chain 5:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:08<00:05, 30.76it/s]

Chain 7:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:15, 20.09it/s]

Chain 6:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 22.52it/s]

Chain 5:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:08<00:05, 30.96it/s]

Chain 7:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:15, 19.68it/s]

Chain 6:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 22.70it/s]

Chain 5:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:08<00:04, 30.64it/s]

Chain 7:  18%|██████████████████                                                                                     | 63/360 [00:02<00:15, 19.61it/s]

Chain 6:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:10, 23.00it/s]

Chain 5:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:09<00:04, 31.87it/s]

Chain 7:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:15, 19.43it/s]

Chain 6:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:06<00:10, 22.82it/s]

Chain 5:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:09<00:04, 31.99it/s]

Chain 7:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:15, 18.90it/s]

Chain 5:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:09<00:04, 33.32it/s]

Chain 6:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:09, 23.01it/s]

Chain 7:  19%|███████████████████▋                                                                                   | 69/360 [00:03<00:15, 19.10it/s]

Chain 5:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:09<00:03, 33.99it/s]

Chain 7:  20%|████████████████████▎                                                                                  | 71/360 [00:03<00:15, 19.15it/s]

Chain 6:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:09, 23.17it/s]

Chain 5:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:09<00:03, 35.07it/s]

Chain 7:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 19.35it/s]

Chain 6:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:09, 23.71it/s]

Chain 7:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:14, 19.40it/s]

Chain 5:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:09<00:03, 36.49it/s]

Chain 8:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 6:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:09, 23.85it/s]

Chain 5:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:09<00:03, 38.41it/s]

Chain 8:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 98.37it/s]

Chain 7:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:14, 20.11it/s]

Chain 6:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 24.66it/s]

Chain 5:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:09<00:02, 39.86it/s]

Chain 6:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 25.13it/s]

Chain 7:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:13, 20.13it/s]

Chain 5:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:09<00:02, 41.44it/s]

Chain 6:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:08, 25.23it/s]

Chain 7:  23%|████████████████████████                                                                               | 84/360 [00:03<00:13, 20.22it/s]

Chain 5:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:10<00:02, 43.27it/s]

Chain 6:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:07<00:08, 25.23it/s]

Chain 5:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:10<00:02, 44.58it/s]

Chain 7:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:13, 20.07it/s]

Chain 6:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:07<00:07, 25.69it/s]

Chain 8:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 28.57it/s]

Chain 5:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:10<00:02, 46.70it/s]

Chain 6:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:07, 26.60it/s]

Chain 7:  25%|█████████████████████████▊                                                                             | 90/360 [00:04<00:13, 20.19it/s]

Chain 5:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:10<00:01, 49.19it/s]

Chain 6:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:07, 26.71it/s]

Chain 7:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:13, 20.48it/s]

Chain 5:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:10<00:01, 51.58it/s]

Chain 6:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 27.29it/s]

Chain 8:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 24.85it/s]

Chain 5:  79%|████████████████████████████████████████████████████████████████████████████████▍                     | 284/360 [00:10<00:01, 55.03it/s]

Chain 7:  27%|███████████████████████████▍                                                                           | 96/360 [00:04<00:12, 21.47it/s]

Chain 6:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 28.02it/s]

Chain 5:  81%|██████████████████████████████████████████████████████████████████████████████████▍                   | 291/360 [00:10<00:01, 58.25it/s]

Chain 7:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:11, 22.11it/s]

Chain 6:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:06, 28.33it/s]

Chain 8:   8%|████████▌                                                                                              | 30/360 [00:01<00:14, 23.50it/s]

Chain 5:  83%|████████████████████████████████████████████████████████████████████████████████████▋                 | 299/360 [00:10<00:00, 62.38it/s]

Chain 7:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:11, 22.57it/s]

Chain 6:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 27.63it/s]

Chain 5:  85%|██████████████████████████████████████████████████████████████████████████████████████▋               | 306/360 [00:10<00:00, 63.84it/s]

Chain 6:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:06, 27.84it/s]

Chain 8:   9%|█████████▋                                                                                             | 34/360 [00:01<00:15, 21.36it/s]

Chain 7:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:11, 21.88it/s]

Chain 5:  88%|█████████████████████████████████████████████████████████████████████████████████████████▎            | 315/360 [00:11<00:00, 69.11it/s]

Chain 6:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:06, 27.95it/s]

Chain 5:  90%|███████████████████████████████████████████████████████████████████████████████████████████▊          | 324/360 [00:11<00:00, 74.69it/s]

Chain 7:  30%|██████████████████████████████▌                                                                       | 108/360 [00:04<00:11, 21.54it/s]

Chain 8:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 20.48it/s]

Chain 6:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:08<00:06, 28.79it/s]

Chain 5:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▉       | 335/360 [00:11<00:00, 83.89it/s]

Chain 7:  31%|███████████████████████████████▍                                                                      | 111/360 [00:05<00:11, 21.63it/s]

Chain 8:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.07it/s]

Chain 6:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:08<00:05, 29.29it/s]

Chain 5:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████▉   | 349/360 [00:11<00:00, 99.17it/s]

Chain 7:  32%|████████████████████████████████▎                                                                     | 114/360 [00:05<00:11, 21.94it/s]

Chain 6:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:08<00:05, 29.79it/s]

Chain 8:  12%|████████████▎                                                                                          | 43/360 [00:01<00:16, 19.78it/s]

Chain 7:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:11, 22.04it/s]

Chain 6:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:08<00:05, 30.30it/s]

Chain 8:  13%|█████████████▏                                                                                         | 46/360 [00:02<00:15, 19.66it/s]

Chain 7:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:10, 22.57it/s]

Chain 6:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:08<00:05, 31.39it/s]

Chain 8:  14%|██████████████                                                                                         | 49/360 [00:02<00:15, 19.67it/s]

Chain 7:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:10, 22.68it/s]

Chain 6:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:08<00:04, 31.92it/s]

Chain 7:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:05<00:10, 23.35it/s]

Chain 8:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:15, 19.72it/s]

Chain 6:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:08<00:04, 31.71it/s]

Chain 7:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:05<00:10, 22.93it/s]

Chain 6:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:08<00:04, 32.45it/s]

Chain 8:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:15, 19.62it/s]

Chain 6:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:09<00:04, 33.35it/s]

Chain 7:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:06<00:09, 23.26it/s]

Chain 8:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 19.43it/s]

Chain 6:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:09<00:04, 33.96it/s]

Chain 8:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:15, 19.29it/s]

Chain 7:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:06<00:09, 23.58it/s]

Chain 6:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:09<00:03, 35.02it/s]

Chain 8:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:15, 19.38it/s]

Chain 7:  38%|███████████████████████████████████████                                                               | 138/360 [00:06<00:09, 24.14it/s]

Chain 8:  18%|██████████████████                                                                                     | 63/360 [00:02<00:15, 19.02it/s]

Chain 6:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:09<00:03, 36.81it/s]

Chain 7:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:06<00:08, 24.58it/s]

Chain 8:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:15, 19.14it/s]

Chain 6:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:09<00:03, 38.08it/s]

Chain 7:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:06<00:08, 24.97it/s]

Chain 9:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 8:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:15, 18.86it/s]

Chain 6:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:09<00:03, 39.20it/s]

Chain 7:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:06<00:08, 25.11it/s]

Chain 9:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 98.89it/s]

Chain 8:  19%|████████████████████                                                                                   | 70/360 [00:03<00:14, 19.51it/s]

Chain 6:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:09<00:02, 40.62it/s]

Chain 7:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:06<00:08, 25.80it/s]

Chain 6:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:09<00:02, 41.40it/s]

Chain 7:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:06<00:07, 26.14it/s]

Chain 8:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 20.13it/s]

Chain 6:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:10<00:02, 43.27it/s]

Chain 7:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:06<00:07, 26.72it/s]

Chain 8:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:14, 20.10it/s]

Chain 6:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:10<00:02, 43.57it/s]

Chain 7:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:07<00:07, 26.59it/s]

Chain 8:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.40it/s]

Chain 6:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:10<00:02, 45.27it/s]

Chain 7:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:07<00:07, 26.84it/s]

Chain 9:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 28.57it/s]

Chain 6:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:10<00:01, 47.59it/s]

Chain 7:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:07<00:07, 27.10it/s]

Chain 8:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 20.52it/s]

Chain 6:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:10<00:01, 49.82it/s]

Chain 7:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:07<00:06, 27.69it/s]

Chain 8:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.32it/s]

Chain 6:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:10<00:01, 52.43it/s]

Chain 7:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:07<00:06, 28.19it/s]

Chain 9:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 24.48it/s]

Chain 6:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:10<00:01, 56.81it/s]

Chain 8:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:13, 20.05it/s]

Chain 7:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 28.87it/s]

Chain 6:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:10<00:01, 61.43it/s]

Chain 9:   8%|████████▌                                                                                              | 30/360 [00:01<00:14, 23.25it/s]

Chain 7:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:06, 28.78it/s]

Chain 8:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:13, 20.13it/s]

Chain 6:  85%|██████████████████████████████████████████████████████████████████████████████████████▋               | 306/360 [00:10<00:00, 64.96it/s]

Chain 7:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:06, 28.87it/s]

Chain 8:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:13, 20.43it/s]

Chain 9:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 22.11it/s]

Chain 6:  87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 314/360 [00:10<00:00, 68.41it/s]

Chain 7:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:07<00:05, 29.41it/s]

Chain 6:  90%|███████████████████████████████████████████████████████████████████████████████████████████▌          | 323/360 [00:11<00:00, 74.43it/s]

Chain 8:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:13, 20.18it/s]

Chain 7:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:08<00:06, 28.06it/s]

Chain 9:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 21.03it/s]

Chain 6:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▉       | 335/360 [00:11<00:00, 86.33it/s]

Chain 8:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:12, 21.13it/s]

Chain 7:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:08<00:05, 29.70it/s]

Chain 6:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████▊  | 352/360 [00:11<00:00, 109.14it/s]

Chain 9:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.94it/s]

Chain 8:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:11, 21.99it/s]

Chain 7:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:08<00:05, 30.61it/s]

Chain 9:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 20.97it/s]

Chain 7:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:08<00:05, 31.56it/s]

Chain 8:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 21.75it/s]

Chain 9:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:14, 20.95it/s]

Chain 7:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:08<00:04, 32.59it/s]

Chain 8:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:11, 21.95it/s]

Chain 9:  14%|██████████████                                                                                         | 49/360 [00:02<00:14, 20.80it/s]

Chain 7:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:08<00:04, 33.62it/s]

Chain 8:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:10, 22.61it/s]

Chain 7:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:08<00:04, 34.14it/s]

Chain 9:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:14, 20.83it/s]

Chain 8:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:10, 23.02it/s]

Chain 7:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:08<00:04, 34.23it/s]

Chain 9:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:14, 20.74it/s]

Chain 8:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:10, 22.76it/s]

Chain 7:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:09<00:03, 35.14it/s]

Chain 8:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 22.67it/s]

Chain 9:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:14, 20.28it/s]

Chain 7:  62%|███████████████████████████████████████████████████████████████▍                                      | 224/360 [00:09<00:03, 35.90it/s]

Chain 8:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 23.05it/s]

Chain 7:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:09<00:03, 37.38it/s]

Chain 9:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:14, 20.29it/s]

Chain 8:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:09, 23.35it/s]

Chain 7:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:09<00:03, 38.73it/s]

Chain 9:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:14, 20.32it/s]

Chain 7:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:09<00:02, 40.65it/s]

Chain 8:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 23.89it/s]

Chain 9:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:14, 20.77it/s]

Chain 7:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:09<00:02, 42.59it/s]

Chain 8:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:09, 24.74it/s]

Chain 7:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:09<00:02, 43.63it/s]

Chain 9:  19%|████████████████████                                                                                   | 70/360 [00:03<00:13, 20.89it/s]

Chain 8:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:08, 25.27it/s]

Chain 7:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:09<00:02, 46.35it/s]

Chain 8:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:08, 25.98it/s]

Chain 9:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:13, 20.79it/s]

Chain 7:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:09<00:02, 48.30it/s]

Chain 8:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 26.21it/s]

Chain 9:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:13, 20.52it/s]

Chain 7:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:10<00:01, 50.12it/s]

Chain 8:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 26.24it/s]

Chain 9:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 21.01it/s]

Chain 7:  76%|█████████████████████████████████████████████████████████████████████████████▎                        | 273/360 [00:10<00:01, 51.77it/s]

Chain 8:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:07, 26.73it/s]

Chain 7:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:10<00:01, 54.79it/s]

Chain 8:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:07, 26.75it/s]

Chain 9:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 21.04it/s]

Chain 7:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:10<00:01, 58.23it/s]

Chain 8:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 27.16it/s]

Chain 9:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:12, 21.23it/s]

Chain 8:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 27.91it/s]

Chain 7:  82%|███████████████████████████████████████████████████████████████████████████████████▌                  | 295/360 [00:10<00:01, 62.42it/s]

Chain 9:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:12, 21.10it/s]

Chain 7:  84%|██████████████████████████████████████████████████████████████████████████████████████▏               | 304/360 [00:10<00:00, 68.50it/s]

Chain 8:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:07<00:06, 28.67it/s]

Chain 7:  87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 314/360 [00:10<00:00, 76.36it/s]

Chain 8:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:07<00:06, 28.89it/s]

Chain 9:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:12, 20.90it/s]

Chain 7:  91%|████████████████████████████████████████████████████████████████████████████████████████████▎         | 326/360 [00:10<00:00, 86.87it/s]

Chain 8:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:07<00:06, 29.17it/s]

Chain 9:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:12, 20.90it/s]

Chain 7:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▍     | 340/360 [00:10<00:00, 100.39it/s]

Chain 8:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:07<00:06, 29.20it/s]

Chain 9:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 21.30it/s]

Chain 8:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:07<00:06, 30.14it/s]

Chain 9:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 21.80it/s]

Chain 8:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:05, 30.60it/s]

Chain 9:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:11, 22.55it/s]

Chain 8:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:07<00:05, 31.31it/s]

Chain 9:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:10, 23.13it/s]

Chain 8:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:07<00:05, 32.14it/s]

Chain 9:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:10, 23.79it/s]

Chain 8:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:08<00:05, 32.73it/s]

Chain 9:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:10, 24.26it/s]

Chain 8:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:08<00:04, 33.64it/s]

Chain 9:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:10, 24.35it/s]

Chain 8:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:08<00:04, 34.44it/s]

Chain 9:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:09, 24.47it/s]

Chain 8:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:08<00:04, 34.36it/s]

Chain 9:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:09, 24.73it/s]

Chain 8:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:08<00:04, 35.19it/s]

Chain 8:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:08<00:04, 36.46it/s]

Chain 9:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:09, 25.16it/s]

Chain 8:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:08<00:03, 37.81it/s]

Chain 9:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:09, 25.33it/s]

Chain 9:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 25.24it/s]

Chain 8:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:08<00:03, 38.66it/s]

Chain 9:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:08, 25.64it/s]

Chain 8:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:08<00:03, 39.47it/s]

Chain 9:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:08, 26.07it/s]

Chain 8:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:09<00:03, 40.86it/s]

Chain 9:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:08, 26.41it/s]

Chain 8:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:09<00:02, 41.93it/s]

Chain 9:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 26.81it/s]

Chain 8:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:09<00:02, 43.39it/s]

Chain 9:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:07, 27.32it/s]

Chain 8:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:09<00:02, 44.42it/s]

Chain 9:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:07, 27.69it/s]

Chain 8:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:09<00:02, 45.58it/s]

Chain 9:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:07, 27.80it/s]

Chain 8:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:09<00:02, 47.87it/s]

Chain 9:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 26.90it/s]

Chain 8:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:09<00:02, 47.14it/s]

Chain 9:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 27.52it/s]

Chain 8:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:09<00:01, 50.54it/s]

Chain 8:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:09<00:01, 54.01it/s]

Chain 9:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:06<00:06, 28.68it/s]

Chain 8:  78%|███████████████████████████████████████████████████████████████████████████████▌                      | 281/360 [00:10<00:01, 56.15it/s]

Chain 9:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:06<00:06, 29.49it/s]

Chain 8:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:10<00:01, 61.15it/s]

Chain 9:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 30.38it/s]

Chain 8:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:10<00:00, 65.40it/s]

Chain 9:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:07<00:06, 30.88it/s]

Chain 8:  85%|██████████████████████████████████████████████████████████████████████████████████████▋               | 306/360 [00:10<00:00, 70.63it/s]

Chain 9:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:07<00:05, 30.65it/s]

Chain 8:  88%|█████████████████████████████████████████████████████████████████████████████████████████▌            | 316/360 [00:10<00:00, 78.19it/s]

Chain 9:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:05, 31.15it/s]

Chain 8:  91%|█████████████████████████████████████████████████████████████████████████████████████████████▏        | 329/360 [00:10<00:00, 91.24it/s]

Chain 8:  96%|████████████████████████████████████████████████████████████████████████████████████████████████▌    | 344/360 [00:10<00:00, 107.85it/s]

Chain 9:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:07<00:05, 31.90it/s]

Chain 9:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:07<00:05, 32.27it/s]

Chain 9:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:07<00:05, 32.94it/s]

Chain 9:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:07<00:04, 34.14it/s]

Chain 9:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:08<00:04, 34.96it/s]

Chain 9:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:08<00:04, 36.02it/s]

Chain 9:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:08<00:04, 36.43it/s]

Chain 9:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:08<00:03, 36.93it/s]

Chain 9:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:08<00:03, 38.94it/s]

Chain 9:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:08<00:03, 40.40it/s]

Chain 9:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:08<00:03, 41.93it/s]

Chain 9:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:08<00:02, 42.89it/s]

Chain 9:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:08<00:02, 43.96it/s]

Chain 9:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:09<00:02, 46.31it/s]

Chain 9:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:09<00:02, 48.49it/s]

Chain 9:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:09<00:02, 50.62it/s]

Chain 9:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:09<00:01, 52.56it/s]

Chain 9:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:09<00:01, 55.21it/s]

Chain 9:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:09<00:01, 58.42it/s]

Chain 9:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:09<00:01, 61.62it/s]

Chain 9:  81%|██████████████████████████████████████████████████████████████████████████████████▍                   | 291/360 [00:09<00:01, 65.21it/s]

Chain 9:  83%|█████████████████████████████████████████████████████████████████████████████████████                 | 300/360 [00:09<00:00, 70.40it/s]

Chain 9:  86%|███████████████████████████████████████████████████████████████████████████████████████▊              | 310/360 [00:09<00:00, 77.96it/s]

Chain 9:  89%|███████████████████████████████████████████████████████████████████████████████████████████▏          | 322/360 [00:10<00:00, 88.63it/s]

Chain 9:  94%|██████████████████████████████████████████████████████████████████████████████████████████████▊      | 338/360 [00:10<00:00, 108.31it/s]

2026-05-28 22:00:43.513 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 22:00:44.108 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 22:00:50.345 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 22:00:51.089 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 22:00:51.090 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 22:00:51.097 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 22:00:52.311 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 22:00:52.357 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 22:00:53.017 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 22:00:54.084 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 22:00:55.199 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 22:00:55.415 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 22:00:55.415 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,105.2,171.7,285.4,454.9,633.7
GIIP (mscf),Total Volumes,1.0,40.6,71.0,124.8,207.8,331.3
Condensate (stb),Total Volumes,1.0,1.2,2.3,4.4,7.9,13.6
Solution Gas (mscf),Total Volumes,1.0,183.2,298.2,527.3,883.7,1364.6

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50    P10     P1
Total Oil EUR         1.0  23.7  38.8  65.8  107.1  150.8

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.65  0.6  2.4  9.3  29.4  71.8
Zone 2           0.97  1.0  2.9  7.7  18.5  37.3
Zone 3           0.71  1.1  2.8  6.6  14.7  29.1
Zone 4           0.51  1.1  2.7  6.6  14.4  27.1
Zone 5           0.83  0.6  2.0  6.7  18.4  40.7
Zone 6           0.73  0.8  2.4  7.3  18.8  41.6
Zone 7           0.85  0.9  3.0  9.5  26.3  58.1
Zone 8           0.46  0.5  2.2  7.4  21.6  54.9
Zone 9           0.73  1.1  3.0  7.7  18.7  41.9
Zone 10          0.48  0.4  1.8  6.6  20.0  52.3

In [14]:
reporter.tabler.npv_table()

     P(Commercial)    P99    P90     P50     P10      P1
NPV           0.97 -182.0  324.0  1077.0  1924.0  2538.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)    P99    P90     P50     P10      P1
EMV           0.97 -179.0  313.0  1045.0  1869.0  2466.0

In [16]:
from resgo.plotting.tables import npv_USD
import numpy as np
import pandas as pd

npv = npv_USD(
    simpack,
    nominal=True,
    discounted=True,
    success_only=False,
)
npv_usd = npv.to_numpy().ravel()
npv_df = pd.DataFrame({"npv_usd_mm": npv_usd / 1e6})

histogram = (
    alt.Chart(npv_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Nominal discounted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Project NPV Distribution",
    )
)

break_even = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(histogram, break_even)
fig.show()

alt.LayerChart(...)

In [17]:
BANKRUPTCY_THRESHOLD_USD = 300e6
LOSS_FLOOR_USD = -5e9

def loss_adjusted_npv_USD(
    npv_usd,
    bankruptcy_threshold_usd=BANKRUPTCY_THRESHOLD_USD,
    floor_usd=LOSS_FLOOR_USD,
):
    npv_usd = np.asarray(npv_usd)
    threshold = bankruptcy_threshold_usd

    with np.errstate(divide="ignore", invalid="ignore"):
        adjusted = np.where(
            npv_usd >= 0,
            npv_usd,
            (threshold * npv_usd) / (threshold + npv_usd),
        )

    adjusted = np.where(npv_usd <= -threshold, floor_usd, adjusted)
    return np.maximum(adjusted, floor_usd)

x_usd = np.linspace(-0.9999 * BANKRUPTCY_THRESHOLD_USD, 1.5e9, 1_000)
loss_function_df = pd.DataFrame(
    {
        "npv_usd_mm": x_usd / 1e6,
        "loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(x_usd) / 1e6,
    }
)
loss_function_plot_df = loss_function_df[
    loss_function_df["loss_adjusted_npv_usd_mm"] > LOSS_FLOOR_USD / 1e6
]

loss_function = (
    alt.Chart(loss_function_plot_df)
    .mark_line(color="#FACC15", strokeWidth=3)
    .encode(
        x=alt.X("npv_usd_mm:Q", title="Nominal discounted NPV ($USD MM)"),
        y=alt.Y(
            "loss_adjusted_npv_usd_mm:Q",
            title="Loss-adjusted NPV ($USD MM)",
        ),
        tooltip=[
            alt.Tooltip("npv_usd_mm:Q", title="NPV ($MM)", format=",.0f"),
            alt.Tooltip(
                "loss_adjusted_npv_usd_mm:Q",
                title="Loss-adjusted NPV ($MM)",
                format=",.0f",
            ),
        ],
    )
    .properties(
        width=650,
        height=250,
        title="Company Loss Function",
    )
)

bankruptcy_threshold = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [-BANKRUPTCY_THRESHOLD_USD / 1e6]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(loss_function, bankruptcy_threshold)
fig.show()

alt.LayerChart(...)

In [18]:
loss_df = pd.DataFrame(
    {"loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(npv_usd) / 1e6}
)

loss_histogram = (
    alt.Chart(loss_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "loss_adjusted_npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Loss-adjusted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated Loss-Adjusted NPV Distribution",
    )
)

break_even_loss = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_histogram, break_even_loss)
fig.show()

alt.LayerChart(...)