In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

/tmp/ipykernel_389850/1985460196.py:25: DeprecationWarning:

`set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 42

CHAINS = 6
DRAWS = 1000
N_RESERVOIRS = 10
N_PRODUCERS = 25

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=100e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=250e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2e6,
    producer_abandonment_cost_USD=0.5e6,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 20:12:50.790 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 20:12:50.795 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 20:12:50.800 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 20:12:50.805 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 20:12:50.809 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 20:12:50.814 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 20:12:50.818 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 7 reservoir volumetric simulation complete.

2026-05-28 20:12:50.822 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 8 reservoir volumetric simulation complete.

2026-05-28 20:12:50.827 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 9 reservoir volumetric simulation complete.

2026-05-28 20:12:50.831 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 10 reservoir volumetric simulation complete.

2026-05-28 20:12:50.837 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 20:12:50.838 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 20:12:51.854 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 20:12:51.854 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 20:12:51.854 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 20:12:51.855 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 20:12:51.855 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 20:12:51.855 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 20:12:51.855 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 20:12:51.855 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 20:12:51.855 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 20:12:51.855 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 20:12:51.856 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 20:12:51.856 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 20:12:51.856 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 20:12:51.856 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 20:12:51.857 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 20:12:51.857 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 20:12:51.857 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 20:12:51.857 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 20:12:51.857 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 20:12:51.857 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 20:12:51.857 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 20:12:51.857 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 21 start_idx = 245

2026-05-28 20:12:51.858 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 22 start_idx = 257

2026-05-28 20:12:51.858 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 23 start_idx = 269

2026-05-28 20:12:51.858 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 24 start_idx = 280

2026-05-28 20:12:51.858 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 25 start_idx = 292

2026-05-28 20:12:51.906 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 20:12:51.922 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 20:12:52.748 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 20:12:52.749 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 20:12:52.749 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (25 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   3%|██▊                                                                                                    | 10/360 [00:00<00:05, 58.36it/s]

Chain 0:   4%|████▌                                                                                                  | 16/360 [00:00<00:16, 20.69it/s]

Chain 0:   6%|█████▋                                                                                                 | 20/360 [00:01<00:20, 16.79it/s]

Chain 0:   6%|██████▌                                                                                                | 23/360 [00:01<00:22, 15.23it/s]

Chain 0:   7%|███████▏                                                                                               | 25/360 [00:01<00:23, 14.47it/s]

Chain 0:   8%|███████▋                                                                                               | 27/360 [00:01<00:24, 13.87it/s]

Chain 0:   8%|████████▎                                                                                              | 29/360 [00:01<00:25, 13.17it/s]

Chain 0:   9%|████████▊                                                                                              | 31/360 [00:01<00:26, 12.44it/s]

Chain 0:   9%|█████████▍                                                                                             | 33/360 [00:02<00:26, 12.16it/s]

Chain 0:  10%|██████████                                                                                             | 35/360 [00:02<00:26, 12.12it/s]

Chain 0:  10%|██████████▌                                                                                            | 37/360 [00:02<00:26, 12.11it/s]

Chain 0:  11%|███████████▏                                                                                           | 39/360 [00:02<00:26, 12.22it/s]

Chain 0:  11%|███████████▋                                                                                           | 41/360 [00:02<00:25, 12.33it/s]

Chain 0:  12%|████████████▎                                                                                          | 43/360 [00:02<00:25, 12.36it/s]

Chain 0:  12%|████████████▉                                                                                          | 45/360 [00:03<00:25, 12.30it/s]

Chain 0:  13%|█████████████▍                                                                                         | 47/360 [00:03<00:25, 12.36it/s]

Chain 0:  14%|██████████████                                                                                         | 49/360 [00:03<00:24, 12.45it/s]

Chain 0:  14%|██████████████▌                                                                                        | 51/360 [00:03<00:24, 12.48it/s]

Chain 0:  15%|███████████████▏                                                                                       | 53/360 [00:03<00:24, 12.54it/s]

Chain 0:  15%|███████████████▋                                                                                       | 55/360 [00:03<00:24, 12.47it/s]

Chain 0:  16%|████████████████▎                                                                                      | 57/360 [00:04<00:24, 12.12it/s]

Chain 0:  16%|████████████████▉                                                                                      | 59/360 [00:04<00:25, 11.83it/s]

Chain 0:  17%|█████████████████▍                                                                                     | 61/360 [00:04<00:25, 11.80it/s]

Chain 0:  18%|██████████████████                                                                                     | 63/360 [00:04<00:24, 11.92it/s]

Chain 0:  18%|██████████████████▌                                                                                    | 65/360 [00:04<00:24, 12.09it/s]

Chain 0:  19%|███████████████████▏                                                                                   | 67/360 [00:04<00:24, 12.16it/s]

Chain 0:  19%|███████████████████▋                                                                                   | 69/360 [00:05<00:23, 12.27it/s]

Chain 0:  20%|████████████████████▎                                                                                  | 71/360 [00:05<00:23, 12.30it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  20%|████████████████████▉                                                                                  | 73/360 [00:05<00:23, 12.17it/s]

Chain 1:   3%|██▊                                                                                                    | 10/360 [00:00<00:06, 55.95it/s]

Chain 0:  21%|█████████████████████▍                                                                                 | 75/360 [00:05<00:23, 12.24it/s]

Chain 0:  21%|██████████████████████                                                                                 | 77/360 [00:05<00:23, 12.17it/s]

Chain 0:  22%|██████████████████████▌                                                                                | 79/360 [00:05<00:23, 12.20it/s]

Chain 1:   4%|████▌                                                                                                  | 16/360 [00:00<00:17, 19.70it/s]

Chain 0:  22%|███████████████████████▏                                                                               | 81/360 [00:06<00:22, 12.25it/s]

Chain 0:  23%|███████████████████████▋                                                                               | 83/360 [00:06<00:22, 12.14it/s]

Chain 1:   5%|█████▍                                                                                                 | 19/360 [00:00<00:20, 16.47it/s]

Chain 0:  24%|████████████████████████▎                                                                              | 85/360 [00:06<00:22, 12.12it/s]

Chain 0:  24%|████████████████████████▉                                                                              | 87/360 [00:06<00:23, 11.71it/s]

Chain 1:   6%|██████▎                                                                                                | 22/360 [00:01<00:22, 14.82it/s]

Chain 0:  25%|█████████████████████████▍                                                                             | 89/360 [00:06<00:23, 11.65it/s]

Chain 1:   7%|██████▊                                                                                                | 24/360 [00:01<00:24, 13.97it/s]

Chain 0:  25%|██████████████████████████                                                                             | 91/360 [00:06<00:22, 11.72it/s]

Chain 1:   7%|███████▍                                                                                               | 26/360 [00:01<00:25, 13.34it/s]

Chain 0:  26%|██████████████████████████▌                                                                            | 93/360 [00:07<00:22, 11.74it/s]

Chain 1:   8%|████████                                                                                               | 28/360 [00:01<00:25, 12.89it/s]

Chain 0:  26%|███████████████████████████▏                                                                           | 95/360 [00:07<00:22, 11.79it/s]

Chain 1:   8%|████████▌                                                                                              | 30/360 [00:01<00:27, 12.13it/s]

Chain 0:  27%|███████████████████████████▊                                                                           | 97/360 [00:07<00:22, 11.68it/s]

Chain 1:   9%|█████████▏                                                                                             | 32/360 [00:02<00:28, 11.67it/s]

Chain 0:  28%|████████████████████████████▎                                                                          | 99/360 [00:07<00:22, 11.76it/s]

Chain 1:   9%|█████████▋                                                                                             | 34/360 [00:02<00:28, 11.56it/s]

Chain 0:  28%|████████████████████████████▌                                                                         | 101/360 [00:07<00:21, 11.83it/s]

Chain 1:  10%|██████████▎                                                                                            | 36/360 [00:02<00:27, 11.58it/s]

Chain 0:  29%|█████████████████████████████▏                                                                        | 103/360 [00:07<00:21, 11.85it/s]

Chain 1:  11%|██████████▊                                                                                            | 38/360 [00:02<00:27, 11.58it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:08<00:21, 11.74it/s]

Chain 1:  11%|███████████▍                                                                                           | 40/360 [00:02<00:27, 11.62it/s]

Chain 0:  30%|██████████████████████████████▎                                                                       | 107/360 [00:08<00:21, 11.60it/s]

Chain 1:  12%|████████████                                                                                           | 42/360 [00:03<00:27, 11.70it/s]

Chain 0:  30%|██████████████████████████████▉                                                                       | 109/360 [00:08<00:21, 11.69it/s]

Chain 1:  12%|████████████▌                                                                                          | 44/360 [00:03<00:26, 11.77it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:08<00:21, 11.76it/s]

Chain 1:  13%|█████████████▏                                                                                         | 46/360 [00:03<00:26, 11.84it/s]

Chain 0:  31%|████████████████████████████████                                                                      | 113/360 [00:08<00:20, 11.78it/s]

Chain 1:  13%|█████████████▋                                                                                         | 48/360 [00:03<00:26, 11.88it/s]

Chain 0:  32%|████████████████████████████████▌                                                                     | 115/360 [00:08<00:21, 11.56it/s]

Chain 1:  14%|██████████████▎                                                                                        | 50/360 [00:03<00:25, 11.94it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:09<00:21, 11.45it/s]

Chain 1:  14%|██████████████▉                                                                                        | 52/360 [00:03<00:25, 11.96it/s]

Chain 0:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:09<00:20, 11.57it/s]

Chain 1:  15%|███████████████▍                                                                                       | 54/360 [00:04<00:25, 12.01it/s]

Chain 0:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:09<00:20, 11.69it/s]

Chain 1:  16%|████████████████                                                                                       | 56/360 [00:04<00:25, 12.08it/s]

Chain 0:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:09<00:20, 11.84it/s]

Chain 1:  16%|████████████████▌                                                                                      | 58/360 [00:04<00:25, 11.63it/s]

Chain 0:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:09<00:19, 11.95it/s]

Chain 1:  17%|█████████████████▏                                                                                     | 60/360 [00:04<00:26, 11.48it/s]

Chain 0:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:09<00:19, 11.96it/s]

Chain 1:  17%|█████████████████▋                                                                                     | 62/360 [00:04<00:25, 11.50it/s]

Chain 0:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:10<00:19, 11.83it/s]

Chain 1:  18%|██████████████████▎                                                                                    | 64/360 [00:04<00:25, 11.59it/s]

Chain 0:  36%|█████████████████████████████████████                                                                 | 131/360 [00:10<00:19, 11.85it/s]

Chain 1:  18%|██████████████████▉                                                                                    | 66/360 [00:05<00:25, 11.71it/s]

Chain 0:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:10<00:18, 11.96it/s]

Chain 1:  19%|███████████████████▍                                                                                   | 68/360 [00:05<00:24, 11.83it/s]

Chain 0:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:10<00:18, 11.98it/s]

Chain 1:  19%|████████████████████                                                                                   | 70/360 [00:05<00:24, 11.63it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:10<00:18, 11.87it/s]

Chain 1:  20%|████████████████████▌                                                                                  | 72/360 [00:05<00:24, 11.56it/s]

Chain 2:   3%|██▊                                                                                                    | 10/360 [00:00<00:06, 52.94it/s]

Chain 0:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:11<00:18, 11.92it/s]

Chain 1:  21%|█████████████████████▏                                                                                 | 74/360 [00:05<00:24, 11.49it/s]

Chain 0:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:11<00:18, 11.78it/s]

Chain 1:  21%|█████████████████████▋                                                                                 | 76/360 [00:05<00:24, 11.38it/s]

Chain 0:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:11<00:18, 11.70it/s]

Chain 1:  22%|██████████████████████▎                                                                                | 78/360 [00:06<00:24, 11.51it/s]

Chain 0:  40%|█████████████████████████████████████████                                                             | 145/360 [00:11<00:18, 11.73it/s]

Chain 2:   4%|████▌                                                                                                  | 16/360 [00:00<00:18, 18.76it/s]

Chain 1:  22%|██████████████████████▉                                                                                | 80/360 [00:06<00:24, 11.57it/s]

Chain 0:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:11<00:17, 11.87it/s]

Chain 1:  23%|███████████████████████▍                                                                               | 82/360 [00:06<00:24, 11.53it/s]

Chain 2:   5%|█████▍                                                                                                 | 19/360 [00:01<00:21, 15.73it/s]

Chain 0:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:11<00:17, 12.07it/s]

Chain 1:  23%|████████████████████████                                                                               | 84/360 [00:06<00:24, 11.47it/s]

Chain 0:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:12<00:17, 12.20it/s]

Chain 2:   6%|██████▎                                                                                                | 22/360 [00:01<00:24, 13.87it/s]

Chain 1:  24%|████████████████████████▌                                                                              | 86/360 [00:06<00:24, 11.21it/s]

Chain 0:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:12<00:17, 12.06it/s]

Chain 2:   7%|██████▊                                                                                                | 24/360 [00:01<00:25, 13.11it/s]

Chain 0:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:12<00:16, 12.22it/s]

Chain 1:  24%|█████████████████████████▏                                                                             | 88/360 [00:06<00:24, 10.97it/s]

Chain 0:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:12<00:16, 12.58it/s]

Chain 2:   7%|███████▍                                                                                               | 26/360 [00:01<00:26, 12.53it/s]

Chain 1:  25%|█████████████████████████▊                                                                             | 90/360 [00:07<00:24, 11.06it/s]

Chain 0:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:12<00:15, 12.78it/s]

Chain 2:   8%|████████                                                                                               | 28/360 [00:01<00:27, 12.17it/s]

Chain 1:  26%|██████████████████████████▎                                                                            | 92/360 [00:07<00:24, 11.13it/s]

Chain 0:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:12<00:15, 12.55it/s]

Chain 2:   8%|████████▌                                                                                              | 30/360 [00:02<00:29, 11.36it/s]

Chain 1:  26%|██████████████████████████▉                                                                            | 94/360 [00:07<00:25, 10.62it/s]

Chain 0:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:12<00:15, 12.76it/s]

Chain 2:   9%|█████████▏                                                                                             | 32/360 [00:02<00:29, 11.10it/s]

Chain 1:  27%|███████████████████████████▍                                                                           | 96/360 [00:07<00:24, 10.76it/s]

Chain 0:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:13<00:15, 12.91it/s]

Chain 0:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:13<00:14, 13.07it/s]

Chain 2:   9%|█████████▋                                                                                             | 34/360 [00:02<00:29, 10.94it/s]

Chain 1:  27%|████████████████████████████                                                                           | 98/360 [00:07<00:24, 10.67it/s]

Chain 0:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:13<00:14, 13.35it/s]

Chain 2:  10%|██████████▎                                                                                            | 36/360 [00:02<00:29, 11.00it/s]

Chain 1:  28%|████████████████████████████▎                                                                         | 100/360 [00:08<00:24, 10.71it/s]

Chain 0:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:13<00:14, 13.30it/s]

Chain 2:  11%|██████████▊                                                                                            | 38/360 [00:02<00:29, 11.06it/s]

Chain 1:  28%|████████████████████████████▉                                                                         | 102/360 [00:08<00:23, 10.90it/s]

Chain 0:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:13<00:13, 13.47it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:02<00:28, 11.12it/s]

Chain 1:  29%|█████████████████████████████▍                                                                        | 104/360 [00:08<00:23, 11.02it/s]

Chain 0:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:13<00:13, 13.59it/s]

Chain 2:  12%|████████████                                                                                           | 42/360 [00:03<00:28, 11.08it/s]

Chain 0:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:13<00:13, 13.47it/s]

Chain 1:  29%|██████████████████████████████                                                                        | 106/360 [00:08<00:23, 10.91it/s]

Chain 0:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:14<00:13, 13.53it/s]

Chain 2:  12%|████████████▌                                                                                          | 44/360 [00:03<00:28, 11.00it/s]

Chain 1:  30%|██████████████████████████████▌                                                                       | 108/360 [00:08<00:22, 11.04it/s]

Chain 0:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:14<00:12, 13.91it/s]

Chain 2:  13%|█████████████▏                                                                                         | 46/360 [00:03<00:28, 11.08it/s]

Chain 1:  31%|███████████████████████████████▏                                                                      | 110/360 [00:09<00:22, 11.18it/s]

Chain 0:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:14<00:12, 14.31it/s]

Chain 2:  13%|█████████████▋                                                                                         | 48/360 [00:03<00:27, 11.20it/s]

Chain 0:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:14<00:11, 14.66it/s]

Chain 1:  31%|███████████████████████████████▋                                                                      | 112/360 [00:09<00:22, 11.24it/s]

Chain 0:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:14<00:11, 14.86it/s]

Chain 2:  14%|██████████████▎                                                                                        | 50/360 [00:03<00:27, 11.31it/s]

Chain 1:  32%|████████████████████████████████▎                                                                     | 114/360 [00:09<00:21, 11.22it/s]

Chain 0:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:14<00:11, 15.15it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:04<00:27, 11.38it/s]

Chain 0:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:14<00:11, 15.35it/s]

Chain 1:  32%|████████████████████████████████▊                                                                     | 116/360 [00:09<00:22, 10.73it/s]

Chain 0:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:15<00:10, 15.36it/s]

Chain 2:  15%|███████████████▍                                                                                       | 54/360 [00:04<00:26, 11.43it/s]

Chain 1:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:09<00:22, 10.75it/s]

Chain 0:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:15<00:10, 15.55it/s]

Chain 2:  16%|████████████████                                                                                       | 56/360 [00:04<00:26, 11.53it/s]

Chain 1:  33%|██████████████████████████████████                                                                    | 120/360 [00:09<00:21, 10.92it/s]

Chain 0:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:15<00:10, 15.80it/s]

Chain 2:  16%|████████████████▌                                                                                      | 58/360 [00:04<00:27, 11.16it/s]

Chain 0:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:15<00:10, 15.82it/s]

Chain 1:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:10<00:21, 10.95it/s]

Chain 0:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:15<00:10, 15.50it/s]

Chain 2:  17%|█████████████████▏                                                                                     | 60/360 [00:04<00:27, 10.83it/s]

Chain 1:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:10<00:21, 10.92it/s]

Chain 0:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:15<00:10, 15.49it/s]

Chain 2:  17%|█████████████████▋                                                                                     | 62/360 [00:04<00:27, 10.72it/s]

Chain 0:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:15<00:09, 15.53it/s]

Chain 1:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:10<00:21, 10.85it/s]

Chain 0:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:15<00:09, 15.78it/s]

Chain 2:  18%|██████████████████▎                                                                                    | 64/360 [00:05<00:27, 10.66it/s]

Chain 1:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:10<00:21, 10.81it/s]

Chain 0:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:16<00:09, 15.89it/s]

Chain 2:  18%|██████████████████▉                                                                                    | 66/360 [00:05<00:27, 10.69it/s]

Chain 0:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:16<00:09, 15.99it/s]

Chain 1:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:10<00:21, 10.75it/s]

Chain 0:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:16<00:08, 16.41it/s]

Chain 2:  19%|███████████████████▍                                                                                   | 68/360 [00:05<00:27, 10.67it/s]

Chain 1:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:11<00:21, 10.77it/s]

Chain 0:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:16<00:08, 16.18it/s]

Chain 0:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:16<00:08, 16.03it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:  19%|████████████████████                                                                                   | 70/360 [00:05<00:27, 10.47it/s]

Chain 1:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:11<00:21, 10.75it/s]

Chain 3:   2%|██▌                                                                                                     | 9/360 [00:00<00:04, 85.19it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:16<00:08, 16.09it/s]

Chain 2:  20%|████████████████████▌                                                                                  | 72/360 [00:05<00:27, 10.50it/s]

Chain 1:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:11<00:20, 10.78it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:16<00:08, 16.21it/s]

Chain 0:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:16<00:08, 16.00it/s]

Chain 2:  21%|█████████████████████▏                                                                                 | 74/360 [00:06<00:27, 10.29it/s]

Chain 1:  38%|███████████████████████████████████████                                                               | 138/360 [00:11<00:20, 10.62it/s]

Chain 0:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:17<00:08, 15.93it/s]

Chain 2:  21%|█████████████████████▋                                                                                 | 76/360 [00:06<00:27, 10.21it/s]

Chain 1:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:11<00:20, 10.59it/s]

Chain 0:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:17<00:08, 15.58it/s]

Chain 0:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:17<00:07, 16.64it/s]

Chain 1:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:11<00:20, 10.71it/s]

Chain 2:  22%|██████████████████████▎                                                                                | 78/360 [00:06<00:27, 10.24it/s]

Chain 0:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:17<00:07, 17.46it/s]

Chain 0:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:17<00:07, 17.83it/s]

Chain 1:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:12<00:20, 10.49it/s]

Chain 2:  22%|██████████████████████▉                                                                                | 80/360 [00:06<00:27, 10.06it/s]

Chain 0:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:17<00:07, 17.81it/s]

Chain 3:   5%|█████▏                                                                                                 | 18/360 [00:01<00:23, 14.76it/s]

Chain 0:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:17<00:06, 18.28it/s]

Chain 1:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:12<00:20, 10.51it/s]

Chain 2:  23%|███████████████████████▍                                                                               | 82/360 [00:06<00:27, 10.10it/s]

Chain 0:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:17<00:06, 19.22it/s]

Chain 1:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:12<00:19, 10.68it/s]

Chain 2:  23%|████████████████████████                                                                               | 84/360 [00:07<00:27, 10.11it/s]

Chain 0:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:17<00:05, 19.85it/s]

Chain 1:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:12<00:19, 10.90it/s]

Chain 0:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:18<00:05, 19.59it/s]

Chain 3:   6%|██████▌                                                                                                | 23/360 [00:01<00:26, 12.67it/s]

Chain 2:  24%|████████████████████████▌                                                                              | 86/360 [00:07<00:27,  9.96it/s]

Chain 0:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:18<00:05, 19.55it/s]

Chain 1:  42%|███████████████████████████████████████████                                                           | 152/360 [00:12<00:19, 10.92it/s]

Chain 2:  24%|████████████████████████▉                                                                              | 87/360 [00:07<00:27,  9.81it/s]

Chain 0:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:18<00:05, 19.60it/s]

Chain 2:  24%|█████████████████████████▏                                                                             | 88/360 [00:07<00:28,  9.49it/s]

Chain 0:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:18<00:05, 19.22it/s]

Chain 3:   7%|███████▍                                                                                               | 26/360 [00:01<00:28, 11.76it/s]

Chain 1:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:13<00:19, 10.67it/s]

Chain 0:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:18<00:05, 20.39it/s]

Chain 2:  25%|█████████████████████████▊                                                                             | 90/360 [00:07<00:27,  9.88it/s]

Chain 1:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:13<00:18, 10.96it/s]

Chain 3:   8%|████████                                                                                               | 28/360 [00:02<00:29, 11.37it/s]

Chain 0:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:18<00:04, 21.44it/s]

Chain 2:  26%|██████████████████████████▎                                                                            | 92/360 [00:07<00:26, 10.02it/s]

Chain 0:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:18<00:04, 22.06it/s]

Chain 1:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:13<00:17, 11.24it/s]

Chain 3:   8%|████████▌                                                                                              | 30/360 [00:02<00:30, 10.80it/s]

Chain 0:  73%|██████████████████████████████████████████████████████████████████████████▌                           | 263/360 [00:18<00:04, 22.89it/s]

Chain 2:  26%|██████████████████████████▉                                                                            | 94/360 [00:08<00:26, 10.15it/s]

Chain 1:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:13<00:17, 11.50it/s]

Chain 0:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:19<00:03, 24.18it/s]

Chain 3:   9%|█████████▏                                                                                             | 32/360 [00:02<00:30, 10.63it/s]

Chain 1:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:13<00:16, 11.90it/s]

Chain 0:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:19<00:03, 24.95it/s]

Chain 2:  27%|███████████████████████████▍                                                                           | 96/360 [00:08<00:25, 10.28it/s]

Chain 0:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:19<00:03, 25.31it/s]

Chain 3:   9%|█████████▋                                                                                             | 34/360 [00:02<00:31, 10.39it/s]

Chain 1:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:13<00:16, 11.76it/s]

Chain 2:  27%|████████████████████████████                                                                           | 98/360 [00:08<00:25, 10.38it/s]

Chain 0:  76%|█████████████████████████████████████████████████████████████████████████████▉                        | 275/360 [00:19<00:03, 25.77it/s]

Chain 1:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:14<00:16, 11.78it/s]

Chain 0:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:19<00:03, 25.83it/s]

Chain 3:  10%|██████████▎                                                                                            | 36/360 [00:02<00:31, 10.21it/s]

Chain 2:  28%|████████████████████████████▎                                                                         | 100/360 [00:08<00:25, 10.37it/s]

Chain 0:  78%|███████████████████████████████████████████████████████████████████████████████▌                      | 281/360 [00:19<00:03, 26.02it/s]

Chain 1:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:14<00:16, 11.96it/s]

Chain 3:  11%|██████████▊                                                                                            | 38/360 [00:03<00:31, 10.19it/s]

Chain 2:  28%|████████████████████████████▉                                                                         | 102/360 [00:08<00:24, 10.38it/s]

Chain 0:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:19<00:02, 27.45it/s]

Chain 1:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:14<00:15, 12.04it/s]

Chain 0:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:19<00:02, 28.64it/s]

Chain 3:  11%|███████████▍                                                                                           | 40/360 [00:03<00:31, 10.22it/s]

Chain 2:  29%|█████████████████████████████▍                                                                        | 104/360 [00:09<00:24, 10.44it/s]

Chain 1:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:14<00:15, 12.06it/s]

Chain 0:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:19<00:02, 29.24it/s]

Chain 3:  12%|████████████                                                                                           | 42/360 [00:03<00:31, 10.25it/s]

Chain 0:  82%|███████████████████████████████████████████████████████████████████████████████████▊                  | 296/360 [00:20<00:02, 29.26it/s]

Chain 2:  29%|██████████████████████████████                                                                        | 106/360 [00:09<00:24, 10.43it/s]

Chain 1:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:14<00:15, 12.28it/s]

Chain 0:  83%|█████████████████████████████████████████████████████████████████████████████████████                 | 300/360 [00:20<00:01, 31.28it/s]

Chain 1:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:14<00:14, 12.55it/s]

Chain 3:  12%|████████████▌                                                                                          | 44/360 [00:03<00:30, 10.25it/s]

Chain 2:  30%|██████████████████████████████▌                                                                       | 108/360 [00:09<00:23, 10.50it/s]

Chain 0:  84%|██████████████████████████████████████████████████████████████████████████████████████▏               | 304/360 [00:20<00:01, 33.13it/s]

Chain 0:  86%|███████████████████████████████████████████████████████████████████████████████████████▎              | 308/360 [00:20<00:01, 34.89it/s]

Chain 1:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:15<00:14, 12.82it/s]

Chain 3:  13%|█████████████▏                                                                                         | 46/360 [00:03<00:30, 10.30it/s]

Chain 2:  31%|███████████████████████████████▏                                                                      | 110/360 [00:09<00:23, 10.64it/s]

Chain 0:  87%|████████████████████████████████████████████████████████████████████████████████████████▋             | 313/360 [00:20<00:01, 36.95it/s]

Chain 1:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:15<00:13, 13.17it/s]

Chain 0:  88%|██████████████████████████████████████████████████████████████████████████████████████████            | 318/360 [00:20<00:01, 39.27it/s]

Chain 3:  13%|█████████████▋                                                                                         | 48/360 [00:04<00:29, 10.40it/s]

Chain 2:  31%|███████████████████████████████▋                                                                      | 112/360 [00:09<00:23, 10.49it/s]

Chain 1:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:15<00:13, 13.26it/s]

Chain 0:  90%|███████████████████████████████████████████████████████████████████████████████████████████▌          | 323/360 [00:20<00:00, 41.87it/s]

Chain 1:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:15<00:13, 13.45it/s]

Chain 3:  14%|██████████████▎                                                                                        | 50/360 [00:04<00:29, 10.48it/s]

Chain 0:  91%|█████████████████████████████████████████████████████████████████████████████████████████████▏        | 329/360 [00:20<00:00, 45.16it/s]

Chain 2:  32%|████████████████████████████████▎                                                                     | 114/360 [00:10<00:23, 10.40it/s]

Chain 0:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▉       | 335/360 [00:20<00:00, 48.93it/s]

Chain 1:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:15<00:12, 13.68it/s]

Chain 3:  14%|██████████████▉                                                                                        | 52/360 [00:04<00:29, 10.39it/s]

Chain 2:  32%|████████████████████████████████▊                                                                     | 116/360 [00:10<00:23, 10.30it/s]

Chain 0:  95%|████████████████████████████████████████████████████████████████████████████████████████████████▉     | 342/360 [00:21<00:00, 54.12it/s]

Chain 1:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:15<00:12, 13.46it/s]

Chain 0:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████▍  | 351/360 [00:21<00:00, 62.84it/s]

Chain 3:  15%|███████████████▍                                                                                       | 54/360 [00:04<00:29, 10.46it/s]

Chain 2:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:10<00:24, 10.07it/s]

Chain 1:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:15<00:12, 13.77it/s]

Chain 1:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:16<00:11, 14.07it/s]

Chain 3:  16%|████████████████                                                                                       | 56/360 [00:04<00:29, 10.35it/s]

Chain 2:  33%|██████████████████████████████████                                                                    | 120/360 [00:10<00:23, 10.25it/s]

Chain 1:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:16<00:11, 14.14it/s]

Chain 3:  16%|████████████████▌                                                                                      | 58/360 [00:05<00:30, 10.02it/s]

Chain 2:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:10<00:22, 10.36it/s]

Chain 1:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:16<00:11, 14.18it/s]

Chain 1:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:16<00:11, 14.23it/s]

Chain 2:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:11<00:22, 10.33it/s]

Chain 3:  17%|█████████████████▏                                                                                     | 60/360 [00:05<00:30,  9.80it/s]

Chain 1:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:16<00:11, 13.98it/s]

Chain 2:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:11<00:22, 10.38it/s]

Chain 3:  17%|█████████████████▋                                                                                     | 62/360 [00:05<00:30,  9.81it/s]

Chain 1:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:16<00:11, 13.86it/s]

Chain 3:  18%|██████████████████                                                                                     | 63/360 [00:05<00:30,  9.82it/s]

Chain 2:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:11<00:22, 10.18it/s]

Chain 3:  18%|██████████████████▎                                                                                    | 64/360 [00:05<00:30,  9.82it/s]

Chain 1:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:16<00:11, 14.00it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:17<00:10, 14.19it/s]

Chain 2:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:11<00:22, 10.19it/s]

Chain 3:  18%|██████████████████▉                                                                                    | 66/360 [00:05<00:29,  9.99it/s]

Chain 1:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:17<00:10, 14.45it/s]

Chain 2:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:11<00:22, 10.27it/s]

Chain 3:  19%|███████████████████▍                                                                                   | 68/360 [00:06<00:29, 10.02it/s]

Chain 1:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:17<00:10, 14.44it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:17<00:10, 14.09it/s]

Chain 2:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:12<00:22,  9.97it/s]

Chain 3:  19%|████████████████████                                                                                   | 70/360 [00:06<00:29,  9.71it/s]

Chain 4:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:12<00:22,  9.93it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:17<00:10, 14.10it/s]

Chain 3:  20%|████████████████████▎                                                                                  | 71/360 [00:06<00:29,  9.72it/s]

Chain 4:   2%|██▌                                                                                                     | 9/360 [00:00<00:04, 76.64it/s]

Chain 2:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:12<00:22,  9.94it/s]

Chain 3:  20%|████████████████████▌                                                                                  | 72/360 [00:06<00:29,  9.71it/s]

Chain 1:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:17<00:10, 14.33it/s]

Chain 1:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:17<00:09, 14.50it/s]

Chain 2:  38%|███████████████████████████████████████                                                               | 138/360 [00:12<00:22, 10.04it/s]

Chain 3:  21%|█████████████████████▏                                                                                 | 74/360 [00:06<00:28,  9.86it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:18<00:09, 14.36it/s]

Chain 3:  21%|█████████████████████▍                                                                                 | 75/360 [00:06<00:29,  9.56it/s]

Chain 2:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:12<00:22,  9.75it/s]

Chain 3:  21%|█████████████████████▋                                                                                 | 76/360 [00:06<00:31,  9.03it/s]

Chain 1:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:18<00:10, 13.69it/s]

Chain 2:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:12<00:22,  9.54it/s]

Chain 1:  62%|███████████████████████████████████████████████████████████████▍                                      | 224/360 [00:18<00:09, 14.67it/s]

Chain 3:  22%|██████████████████████▎                                                                                | 78/360 [00:07<00:29,  9.66it/s]

Chain 2:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:12<00:21,  9.94it/s]

Chain 1:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:18<00:08, 14.97it/s]

Chain 1:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:18<00:08, 16.15it/s]

Chain 3:  22%|██████████████████████▉                                                                                | 80/360 [00:07<00:27, 10.10it/s]

Chain 4:   5%|████▊                                                                                                  | 17/360 [00:00<00:22, 14.94it/s]

Chain 2:  40%|█████████████████████████████████████████                                                             | 145/360 [00:13<00:21, 10.15it/s]

Chain 1:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:18<00:07, 16.50it/s]

Chain 3:  22%|███████████████████████▏                                                                               | 81/360 [00:07<00:27,  9.97it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:07<00:28,  9.88it/s]

Chain 1:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:18<00:07, 16.89it/s]

Chain 2:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:13<00:20, 10.18it/s]

Chain 1:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:18<00:07, 17.72it/s]

Chain 3:  23%|████████████████████████                                                                               | 84/360 [00:07<00:26, 10.24it/s]

Chain 2:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:13<00:19, 10.58it/s]

Chain 4:   6%|██████                                                                                                 | 21/360 [00:01<00:26, 12.68it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:18<00:06, 18.76it/s]

Chain 3:  24%|████████████████████████▌                                                                              | 86/360 [00:07<00:26, 10.44it/s]

Chain 2:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:13<00:19, 10.90it/s]

Chain 1:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:19<00:06, 19.52it/s]

Chain 1:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:19<00:05, 20.11it/s]

Chain 4:   7%|██████▊                                                                                                | 24/360 [00:01<00:28, 11.95it/s]

Chain 2:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:13<00:18, 11.06it/s]

Chain 3:  24%|█████████████████████████▏                                                                             | 88/360 [00:08<00:26, 10.32it/s]

Chain 1:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:19<00:05, 20.67it/s]

Chain 2:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:14<00:18, 11.21it/s]

Chain 4:   7%|███████▍                                                                                               | 26/360 [00:01<00:28, 11.55it/s]

Chain 3:  25%|█████████████████████████▊                                                                             | 90/360 [00:08<00:25, 10.56it/s]

Chain 1:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:19<00:05, 21.21it/s]

Chain 2:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:14<00:17, 11.49it/s]

Chain 3:  26%|██████████████████████████▎                                                                            | 92/360 [00:08<00:25, 10.62it/s]

Chain 4:   8%|████████                                                                                               | 28/360 [00:02<00:29, 11.26it/s]

Chain 1:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:19<00:05, 21.07it/s]

Chain 2:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:14<00:17, 11.70it/s]

Chain 1:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:19<00:04, 21.60it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:08<00:25, 10.46it/s]

Chain 4:   8%|████████▌                                                                                              | 30/360 [00:02<00:30, 10.70it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████                             | 258/360 [00:19<00:04, 22.03it/s]

Chain 2:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:14<00:17, 11.70it/s]

Chain 3:  27%|███████████████████████████▍                                                                           | 96/360 [00:08<00:24, 10.71it/s]

Chain 4:   9%|█████████▏                                                                                             | 32/360 [00:02<00:31, 10.51it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:20<00:05, 18.17it/s]

Chain 2:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:14<00:19, 10.21it/s]

Chain 3:  27%|████████████████████████████                                                                           | 98/360 [00:09<00:25, 10.24it/s]

Chain 1:  73%|██████████████████████████████████████████████████████████████████████████▊                           | 264/360 [00:20<00:05, 18.96it/s]

Chain 4:   9%|█████████▋                                                                                             | 34/360 [00:02<00:32,  9.96it/s]

Chain 2:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:14<00:18, 10.54it/s]

Chain 1:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:20<00:04, 19.91it/s]

Chain 3:  28%|████████████████████████████▎                                                                         | 100/360 [00:09<00:25, 10.20it/s]

Chain 4:  10%|██████████▎                                                                                            | 36/360 [00:02<00:33,  9.80it/s]

Chain 2:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:15<00:17, 10.85it/s]

Chain 1:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:20<00:04, 20.74it/s]

Chain 3:  28%|████████████████████████████▉                                                                         | 102/360 [00:09<00:25, 10.12it/s]

Chain 1:  76%|█████████████████████████████████████████████████████████████████████████████▎                        | 273/360 [00:20<00:03, 22.27it/s]

Chain 2:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:15<00:16, 11.34it/s]

Chain 4:  11%|██████████▊                                                                                            | 38/360 [00:03<00:32,  9.87it/s]

Chain 1:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:20<00:03, 23.54it/s]

Chain 3:  29%|█████████████████████████████▍                                                                        | 104/360 [00:09<00:25, 10.14it/s]

Chain 2:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:15<00:16, 11.43it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████                       | 279/360 [00:20<00:03, 23.72it/s]

Chain 4:  11%|███████████▍                                                                                           | 40/360 [00:03<00:32,  9.95it/s]

Chain 3:  29%|██████████████████████████████                                                                        | 106/360 [00:09<00:24, 10.33it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████▉                      | 282/360 [00:21<00:03, 24.05it/s]

Chain 2:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:15<00:15, 11.83it/s]

Chain 4:  12%|████████████                                                                                           | 42/360 [00:03<00:31, 10.01it/s]

Chain 1:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:21<00:03, 24.94it/s]

Chain 2:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:15<00:15, 12.12it/s]

Chain 3:  30%|██████████████████████████████▌                                                                       | 108/360 [00:10<00:24, 10.33it/s]

Chain 1:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:21<00:02, 26.77it/s]

Chain 4:  12%|████████████▌                                                                                          | 44/360 [00:03<00:31,  9.95it/s]

Chain 2:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:15<00:15, 12.15it/s]

Chain 1:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:21<00:02, 28.70it/s]

Chain 3:  31%|███████████████████████████████▏                                                                      | 110/360 [00:10<00:24, 10.10it/s]

Chain 2:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:16<00:14, 12.39it/s]

Chain 1:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:21<00:02, 29.51it/s]

Chain 4:  13%|█████████████▏                                                                                         | 46/360 [00:03<00:31,  9.95it/s]

Chain 3:  31%|███████████████████████████████▋                                                                      | 112/360 [00:10<00:24, 10.03it/s]

Chain 1:  84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 301/360 [00:21<00:01, 30.96it/s]

Chain 2:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:16<00:14, 12.58it/s]

Chain 4:  13%|█████████████▋                                                                                         | 48/360 [00:04<00:31,  9.98it/s]

Chain 1:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:21<00:01, 32.34it/s]

Chain 2:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:16<00:14, 12.62it/s]

Chain 3:  32%|████████████████████████████████▎                                                                     | 114/360 [00:10<00:24,  9.99it/s]

Chain 1:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:21<00:01, 33.19it/s]

Chain 4:  14%|██████████████▎                                                                                        | 50/360 [00:04<00:31,  9.85it/s]

Chain 3:  32%|████████████████████████████████▌                                                                     | 115/360 [00:10<00:24,  9.90it/s]

Chain 1:  87%|████████████████████████████████████████████████████████████████████████████████████████▋             | 313/360 [00:21<00:01, 34.75it/s]

Chain 2:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:16<00:13, 12.70it/s]

Chain 4:  14%|██████████████▌                                                                                        | 51/360 [00:04<00:31,  9.83it/s]

Chain 3:  32%|████████████████████████████████▊                                                                     | 116/360 [00:10<00:24,  9.90it/s]

Chain 1:  88%|█████████████████████████████████████████████████████████████████████████████████████████▊            | 317/360 [00:22<00:01, 36.14it/s]

Chain 2:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:16<00:13, 12.67it/s]

Chain 4:  14%|██████████████▉                                                                                        | 52/360 [00:04<00:32,  9.61it/s]

Chain 3:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:10<00:25,  9.67it/s]

Chain 1:  89%|███████████████████████████████████████████████████████████████████████████████████████████▏          | 322/360 [00:22<00:00, 38.96it/s]

Chain 4:  15%|███████████████▏                                                                                       | 53/360 [00:04<00:31,  9.68it/s]

Chain 1:  91%|████████████████████████████████████████████████████████████████████████████████████████████▋         | 327/360 [00:22<00:00, 41.16it/s]

Chain 2:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:16<00:13, 12.64it/s]

Chain 3:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:11<00:24,  9.72it/s]

Chain 4:  15%|███████████████▍                                                                                       | 54/360 [00:04<00:33,  9.25it/s]

Chain 1:  92%|██████████████████████████████████████████████████████████████████████████████████████████████        | 332/360 [00:22<00:00, 43.12it/s]

Chain 2:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:17<00:14, 11.97it/s]

Chain 1:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▊      | 338/360 [00:22<00:00, 47.05it/s]

Chain 3:  33%|██████████████████████████████████                                                                    | 120/360 [00:11<00:26,  8.90it/s]

Chain 4:  15%|███████████████▋                                                                                       | 55/360 [00:04<00:36,  8.36it/s]

Chain 1:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████▍    | 344/360 [00:22<00:00, 50.73it/s]

Chain 4:  16%|████████████████                                                                                       | 56/360 [00:05<00:35,  8.59it/s]

Chain 2:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:17<00:13, 12.29it/s]

Chain 3:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:11<00:25,  9.27it/s]

Chain 1:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████▍  | 351/360 [00:22<00:00, 54.92it/s]

Chain 4:  16%|████████████████▎                                                                                      | 57/360 [00:05<00:35,  8.56it/s]

Chain 2:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:17<00:13, 12.19it/s]

Chain 3:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:11<00:25,  9.38it/s]

Chain 1: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋| 359/360 [00:22<00:00, 61.54it/s]

Chain 4:  16%|████████████████▌                                                                                      | 58/360 [00:05<00:36,  8.39it/s]

Chain 3:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:11<00:25,  9.28it/s]

Chain 2:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:17<00:13, 12.42it/s]

Chain 4:  16%|████████████████▉                                                                                      | 59/360 [00:05<00:35,  8.38it/s]

Chain 3:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:11<00:25,  9.34it/s]

Chain 2:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:17<00:12, 12.51it/s]

Chain 4:  17%|█████████████████▏                                                                                     | 60/360 [00:05<00:36,  8.13it/s]

Chain 3:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:11<00:26,  8.94it/s]

Chain 4:  17%|█████████████████▍                                                                                     | 61/360 [00:05<00:36,  8.29it/s]

Chain 3:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:12<00:26,  8.85it/s]

Chain 2:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:17<00:13, 12.10it/s]

Chain 4:  17%|█████████████████▋                                                                                     | 62/360 [00:05<00:34,  8.54it/s]

Chain 3:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:12<00:25,  9.03it/s]

Chain 2:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:18<00:12, 12.43it/s]

Chain 4:  18%|██████████████████                                                                                     | 63/360 [00:05<00:34,  8.72it/s]

Chain 3:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:12<00:24,  9.29it/s]

Chain 4:  18%|██████████████████▎                                                                                    | 64/360 [00:06<00:33,  8.94it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:18<00:11, 12.92it/s]

Chain 3:  36%|█████████████████████████████████████                                                                 | 131/360 [00:12<00:23,  9.76it/s]

Chain 4:  18%|██████████████████▌                                                                                    | 65/360 [00:06<00:32,  9.07it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:18<00:11, 13.17it/s]

Chain 3:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:12<00:23,  9.61it/s]

Chain 4:  18%|██████████████████▉                                                                                    | 66/360 [00:06<00:33,  8.87it/s]

Chain 3:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:12<00:24,  9.40it/s]

Chain 2:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:18<00:11, 12.95it/s]

Chain 4:  19%|███████████████████▏                                                                                   | 67/360 [00:06<00:34,  8.54it/s]

Chain 5:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 3:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:12<00:24,  9.30it/s]

Chain 4:  19%|███████████████████▍                                                                                   | 68/360 [00:06<00:33,  8.70it/s]

Chain 2:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:18<00:11, 12.60it/s]

Chain 3:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:12<00:24,  9.35it/s]

Chain 5:   2%|██▌                                                                                                     | 9/360 [00:00<00:04, 74.40it/s]

Chain 4:  19%|███████████████████▋                                                                                   | 69/360 [00:06<00:33,  8.72it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:18<00:11, 12.69it/s]

Chain 3:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:13<00:24,  9.18it/s]

Chain 4:  19%|████████████████████                                                                                   | 70/360 [00:06<00:33,  8.55it/s]

Chain 3:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:13<00:24,  9.06it/s]

Chain 2:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:18<00:11, 12.55it/s]

Chain 4:  20%|████████████████████▎                                                                                  | 71/360 [00:06<00:34,  8.34it/s]

Chain 3:  38%|███████████████████████████████████████                                                               | 138/360 [00:13<00:25,  8.73it/s]

Chain 4:  20%|████████████████████▌                                                                                  | 72/360 [00:06<00:35,  8.11it/s]

Chain 2:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:19<00:11, 12.58it/s]

Chain 3:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:13<00:24,  8.89it/s]

Chain 4:  20%|████████████████████▉                                                                                  | 73/360 [00:07<00:34,  8.41it/s]

Chain 3:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:13<00:24,  9.00it/s]

Chain 2:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:19<00:10, 13.19it/s]

Chain 4:  21%|█████████████████████▏                                                                                 | 74/360 [00:07<00:33,  8.65it/s]

Chain 2:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:19<00:10, 13.79it/s]

Chain 4:  21%|█████████████████████▍                                                                                 | 75/360 [00:07<00:31,  9.00it/s]

Chain 3:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:13<00:22,  9.59it/s]

Chain 2:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:19<00:09, 14.26it/s]

Chain 4:  21%|█████████████████████▋                                                                                 | 76/360 [00:07<00:31,  9.10it/s]

Chain 3:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:13<00:22,  9.66it/s]

Chain 2:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:19<00:09, 14.99it/s]

Chain 4:  21%|██████████████████████                                                                                 | 77/360 [00:07<00:30,  9.35it/s]

Chain 5:   5%|████▊                                                                                                  | 17/360 [00:01<00:24, 13.79it/s]

Chain 3:  40%|█████████████████████████████████████████                                                             | 145/360 [00:13<00:21,  9.90it/s]

Chain 2:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:19<00:08, 15.24it/s]

Chain 4:  22%|██████████████████████▌                                                                                | 79/360 [00:07<00:28,  9.81it/s]

Chain 3:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:14<00:21,  9.87it/s]

Chain 2:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:19<00:08, 16.19it/s]

Chain 4:  22%|██████████████████████▉                                                                                | 80/360 [00:07<00:28,  9.70it/s]

Chain 3:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:14<00:21,  9.83it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:19<00:07, 16.72it/s]

Chain 5:   6%|██████                                                                                                 | 21/360 [00:01<00:27, 12.14it/s]

Chain 4:  23%|███████████████████████▍                                                                               | 82/360 [00:07<00:27, 10.12it/s]

Chain 2:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:20<00:06, 18.01it/s]

Chain 3:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:14<00:20, 10.49it/s]

Chain 4:  23%|███████████████████████▋                                                                               | 83/360 [00:08<00:27,  9.96it/s]

Chain 2:  66%|██████████████████████████████████████████████████████████████████▊                                   | 236/360 [00:20<00:06, 18.22it/s]

Chain 3:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:14<00:19, 10.88it/s]

Chain 4:  23%|████████████████████████                                                                               | 84/360 [00:08<00:27,  9.89it/s]

Chain 2:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:20<00:06, 19.21it/s]

Chain 5:   7%|██████▊                                                                                                | 24/360 [00:01<00:29, 11.58it/s]

Chain 3:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:14<00:18, 11.22it/s]

Chain 2:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:20<00:06, 19.33it/s]

Chain 4:  24%|████████████████████████▌                                                                              | 86/360 [00:08<00:27,  9.86it/s]

Chain 5:   7%|███████▍                                                                                               | 26/360 [00:02<00:29, 11.17it/s]

Chain 2:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:20<00:05, 20.25it/s]

Chain 3:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:14<00:17, 11.58it/s]

Chain 4:  24%|████████████████████████▉                                                                              | 87/360 [00:08<00:28,  9.72it/s]

Chain 2:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:20<00:05, 21.03it/s]

Chain 5:   8%|████████                                                                                               | 28/360 [00:02<00:30, 11.05it/s]

Chain 3:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:15<00:17, 11.59it/s]

Chain 4:  25%|█████████████████████████▍                                                                             | 89/360 [00:08<00:26, 10.10it/s]

Chain 2:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:20<00:05, 21.45it/s]

Chain 5:   8%|████████▌                                                                                              | 30/360 [00:02<00:30, 10.74it/s]

Chain 3:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:15<00:18, 11.11it/s]

Chain 2:  70%|███████████████████████████████████████████████████████████████████████▋                              | 253/360 [00:20<00:04, 22.04it/s]

Chain 4:  25%|██████████████████████████                                                                             | 91/360 [00:08<00:26, 10.35it/s]

Chain 2:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:21<00:04, 22.60it/s]

Chain 3:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:15<00:17, 11.43it/s]

Chain 5:   9%|█████████▏                                                                                             | 32/360 [00:02<00:31, 10.39it/s]

Chain 4:  26%|██████████████████████████▌                                                                            | 93/360 [00:09<00:26, 10.21it/s]

Chain 2:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:21<00:04, 23.05it/s]

Chain 3:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:15<00:16, 11.72it/s]

Chain 2:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:21<00:04, 23.78it/s]

Chain 5:   9%|█████████▋                                                                                             | 34/360 [00:02<00:31, 10.33it/s]

Chain 4:  26%|███████████████████████████▏                                                                           | 95/360 [00:09<00:25, 10.29it/s]

Chain 3:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:15<00:16, 12.02it/s]

Chain 2:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:21<00:04, 23.62it/s]

Chain 5:  10%|██████████▎                                                                                            | 36/360 [00:03<00:31, 10.25it/s]

Chain 4:  27%|███████████████████████████▊                                                                           | 97/360 [00:09<00:25, 10.27it/s]

Chain 2:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:21<00:03, 24.40it/s]

Chain 3:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:15<00:15, 12.25it/s]

Chain 2:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:21<00:03, 24.86it/s]

Chain 4:  28%|████████████████████████████▎                                                                          | 99/360 [00:09<00:24, 10.49it/s]

Chain 3:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:16<00:15, 12.45it/s]

Chain 5:  11%|██████████▊                                                                                            | 38/360 [00:03<00:32, 10.04it/s]

Chain 2:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:21<00:03, 25.87it/s]

Chain 3:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:16<00:15, 12.58it/s]

Chain 2:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:21<00:03, 26.29it/s]

Chain 4:  28%|████████████████████████████▌                                                                         | 101/360 [00:09<00:24, 10.62it/s]

Chain 5:  11%|███████████▍                                                                                           | 40/360 [00:03<00:31, 10.06it/s]

Chain 2:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:22<00:03, 26.60it/s]

Chain 3:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:16<00:14, 12.64it/s]

Chain 4:  29%|█████████████████████████████▏                                                                        | 103/360 [00:10<00:23, 10.82it/s]

Chain 2:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:22<00:02, 26.76it/s]

Chain 5:  12%|████████████                                                                                           | 42/360 [00:03<00:31, 10.23it/s]

Chain 3:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:16<00:14, 12.68it/s]

Chain 2:  79%|█████████████████████████████████████████████████████████████████████████████████                     | 286/360 [00:22<00:02, 27.66it/s]

Chain 4:  29%|█████████████████████████████▊                                                                        | 105/360 [00:10<00:23, 10.81it/s]

Chain 5:  12%|████████████▌                                                                                          | 44/360 [00:03<00:30, 10.32it/s]

Chain 2:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:22<00:02, 27.46it/s]

Chain 3:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:16<00:14, 12.92it/s]

Chain 2:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:22<00:02, 29.27it/s]

Chain 4:  30%|██████████████████████████████▎                                                                       | 107/360 [00:10<00:23, 10.80it/s]

Chain 3:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:16<00:14, 12.87it/s]

Chain 5:  13%|█████████████▏                                                                                         | 46/360 [00:03<00:30, 10.19it/s]

Chain 2:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:22<00:02, 30.38it/s]

Chain 4:  30%|██████████████████████████████▉                                                                       | 109/360 [00:10<00:23, 10.75it/s]

Chain 3:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:16<00:13, 13.11it/s]

Chain 2:  84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 301/360 [00:22<00:01, 32.25it/s]

Chain 5:  13%|█████████████▋                                                                                         | 48/360 [00:04<00:30, 10.29it/s]

Chain 2:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:22<00:01, 32.78it/s]

Chain 3:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:17<00:13, 12.78it/s]

Chain 4:  31%|███████████████████████████████▍                                                                      | 111/360 [00:10<00:24, 10.14it/s]

Chain 2:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:22<00:01, 33.48it/s]

Chain 5:  14%|██████████████▎                                                                                        | 50/360 [00:04<00:30, 10.03it/s]

Chain 3:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:17<00:13, 12.88it/s]

Chain 2:  87%|████████████████████████████████████████████████████████████████████████████████████████▋             | 313/360 [00:23<00:01, 35.16it/s]

Chain 4:  31%|████████████████████████████████                                                                      | 113/360 [00:10<00:24, 10.12it/s]

Chain 5:  14%|██████████████▉                                                                                        | 52/360 [00:04<00:31,  9.81it/s]

Chain 2:  88%|██████████████████████████████████████████████████████████████████████████████████████████            | 318/360 [00:23<00:01, 36.70it/s]

Chain 3:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:17<00:13, 12.75it/s]

Chain 2:  89%|███████████████████████████████████████████████████████████████████████████████████████████▏          | 322/360 [00:23<00:01, 36.53it/s]

Chain 5:  15%|███████████████▏                                                                                       | 53/360 [00:04<00:31,  9.60it/s]

Chain 4:  32%|████████████████████████████████▌                                                                     | 115/360 [00:11<00:25,  9.62it/s]

Chain 3:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:17<00:13, 12.31it/s]

Chain 2:  91%|████████████████████████████████████████████████████████████████████████████████████████████▋         | 327/360 [00:23<00:00, 39.74it/s]

Chain 4:  32%|████████████████████████████████▊                                                                     | 116/360 [00:11<00:25,  9.61it/s]

Chain 5:  15%|███████████████▋                                                                                       | 55/360 [00:04<00:31,  9.81it/s]

Chain 2:  92%|██████████████████████████████████████████████████████████████████████████████████████████████        | 332/360 [00:23<00:00, 42.47it/s]

Chain 3:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:17<00:13, 12.77it/s]

Chain 4:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:11<00:25,  9.58it/s]

Chain 2:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▊      | 338/360 [00:23<00:00, 46.22it/s]

Chain 3:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:17<00:12, 12.90it/s]

Chain 4:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:11<00:25,  9.62it/s]

Chain 5:  16%|████████████████▎                                                                                      | 57/360 [00:05<00:30,  9.85it/s]

Chain 2:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████▊    | 345/360 [00:23<00:00, 51.85it/s]

Chain 3:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:18<00:12, 13.17it/s]

Chain 5:  16%|████████████████▌                                                                                      | 58/360 [00:05<00:30,  9.77it/s]

Chain 2:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████  | 353/360 [00:23<00:00, 59.51it/s]

Chain 4:  33%|██████████████████████████████████                                                                    | 120/360 [00:11<00:24,  9.90it/s]

Chain 5:  16%|████████████████▉                                                                                      | 59/360 [00:05<00:30,  9.75it/s]

Chain 3:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:18<00:12, 13.42it/s]

Chain 5:  17%|█████████████████▏                                                                                     | 60/360 [00:05<00:30,  9.73it/s]

Chain 4:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:11<00:23, 10.10it/s]

Chain 3:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:18<00:11, 13.72it/s]

Chain 5:  17%|█████████████████▋                                                                                     | 62/360 [00:05<00:29, 10.07it/s]

Chain 3:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:18<00:11, 13.88it/s]

Chain 4:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:12<00:22, 10.46it/s]

Chain 3:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:18<00:10, 14.35it/s]

Chain 5:  18%|██████████████████▎                                                                                    | 64/360 [00:05<00:28, 10.48it/s]

Chain 4:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:12<00:21, 10.77it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:18<00:10, 14.81it/s]

Chain 5:  18%|██████████████████▉                                                                                    | 66/360 [00:05<00:27, 10.79it/s]

Chain 4:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:12<00:21, 10.88it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:18<00:10, 15.29it/s]

Chain 3:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:18<00:09, 15.56it/s]

Chain 5:  19%|███████████████████▍                                                                                   | 68/360 [00:06<00:26, 10.97it/s]

Chain 4:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:12<00:20, 10.97it/s]

Chain 3:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:19<00:09, 15.82it/s]

Chain 5:  19%|████████████████████                                                                                   | 70/360 [00:06<00:26, 11.07it/s]

Chain 4:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:12<00:20, 11.14it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:19<00:09, 16.13it/s]

Chain 3:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:19<00:08, 16.51it/s]

Chain 5:  20%|████████████████████▌                                                                                  | 72/360 [00:06<00:25, 11.13it/s]

Chain 4:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:12<00:20, 11.28it/s]

Chain 3:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:19<00:08, 16.69it/s]

Chain 5:  21%|█████████████████████▏                                                                                 | 74/360 [00:06<00:25, 11.23it/s]

Chain 4:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:13<00:19, 11.31it/s]

Chain 3:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:19<00:08, 16.83it/s]

Chain 3:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:19<00:08, 17.18it/s]

Chain 5:  21%|█████████████████████▋                                                                                 | 76/360 [00:06<00:25, 11.26it/s]

Chain 4:  38%|███████████████████████████████████████                                                               | 138/360 [00:13<00:19, 11.46it/s]

Chain 3:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:19<00:07, 17.21it/s]

Chain 5:  22%|██████████████████████▎                                                                                | 78/360 [00:07<00:24, 11.35it/s]

Chain 4:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:13<00:19, 11.48it/s]

Chain 3:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:19<00:07, 17.51it/s]

Chain 3:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:19<00:07, 17.53it/s]

Chain 5:  22%|██████████████████████▉                                                                                | 80/360 [00:07<00:24, 11.47it/s]

Chain 4:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:13<00:18, 11.63it/s]

Chain 3:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:20<00:06, 18.83it/s]

Chain 5:  23%|███████████████████████▍                                                                               | 82/360 [00:07<00:23, 11.67it/s]

Chain 4:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:13<00:18, 11.63it/s]

Chain 3:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:20<00:06, 19.82it/s]

Chain 5:  23%|████████████████████████                                                                               | 84/360 [00:07<00:23, 11.77it/s]

Chain 4:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:13<00:18, 11.74it/s]

Chain 3:  66%|██████████████████████████████████████████████████████████████████▊                                   | 236/360 [00:20<00:06, 20.57it/s]

Chain 5:  24%|████████████████████████▌                                                                              | 86/360 [00:07<00:23, 11.73it/s]

Chain 4:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:14<00:17, 11.98it/s]

Chain 3:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:20<00:05, 21.25it/s]

Chain 3:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:20<00:05, 21.82it/s]

Chain 4:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:14<00:17, 12.19it/s]

Chain 5:  24%|█████████████████████████▏                                                                             | 88/360 [00:07<00:23, 11.58it/s]

Chain 3:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:20<00:05, 22.30it/s]

Chain 4:  42%|███████████████████████████████████████████                                                           | 152/360 [00:14<00:17, 12.09it/s]

Chain 5:  25%|█████████████████████████▊                                                                             | 90/360 [00:08<00:23, 11.54it/s]

Chain 3:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:20<00:04, 22.46it/s]

Chain 4:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:14<00:16, 12.34it/s]

Chain 5:  26%|██████████████████████████▎                                                                            | 92/360 [00:08<00:23, 11.56it/s]

Chain 3:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:21<00:04, 22.65it/s]

Chain 4:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:14<00:16, 12.56it/s]

Chain 3:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:21<00:04, 23.33it/s]

Chain 5:  26%|██████████████████████████▉                                                                            | 94/360 [00:08<00:22, 11.57it/s]

Chain 3:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:21<00:04, 24.14it/s]

Chain 4:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:14<00:15, 12.81it/s]

Chain 5:  27%|███████████████████████████▍                                                                           | 96/360 [00:08<00:22, 11.64it/s]

Chain 3:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:21<00:04, 24.83it/s]

Chain 4:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:15<00:15, 12.61it/s]

Chain 3:  73%|██████████████████████████████████████████████████████████████████████████▌                           | 263/360 [00:21<00:03, 25.65it/s]

Chain 5:  27%|████████████████████████████                                                                           | 98/360 [00:08<00:22, 11.58it/s]

Chain 3:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:21<00:03, 26.20it/s]

Chain 4:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:15<00:15, 12.84it/s]

Chain 5:  28%|████████████████████████████▎                                                                         | 100/360 [00:08<00:22, 11.68it/s]

Chain 3:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:21<00:03, 27.06it/s]

Chain 4:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:15<00:15, 13.03it/s]

Chain 3:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:21<00:03, 27.32it/s]

Chain 5:  28%|████████████████████████████▉                                                                         | 102/360 [00:09<00:22, 11.70it/s]

Chain 4:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:15<00:14, 13.31it/s]

Chain 3:  76%|█████████████████████████████████████████████████████████████████████████████▉                        | 275/360 [00:21<00:03, 27.70it/s]

Chain 3:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:22<00:02, 28.30it/s]

Chain 4:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:15<00:14, 13.45it/s]

Chain 5:  29%|█████████████████████████████▍                                                                        | 104/360 [00:09<00:22, 11.51it/s]

Chain 3:  78%|███████████████████████████████████████████████████████████████████████████████▌                      | 281/360 [00:22<00:02, 28.61it/s]

Chain 4:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:15<00:14, 13.26it/s]

Chain 3:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:22<00:02, 29.53it/s]

Chain 5:  29%|██████████████████████████████                                                                        | 106/360 [00:09<00:23, 11.00it/s]

Chain 4:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:15<00:14, 13.30it/s]

Chain 3:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:22<00:02, 30.58it/s]

Chain 5:  30%|██████████████████████████████▌                                                                       | 108/360 [00:09<00:22, 11.15it/s]

Chain 3:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:22<00:02, 32.17it/s]

Chain 4:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:16<00:13, 13.43it/s]

Chain 3:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:22<00:01, 33.55it/s]

Chain 5:  31%|███████████████████████████████▏                                                                      | 110/360 [00:09<00:22, 11.25it/s]

Chain 4:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:16<00:13, 13.50it/s]

Chain 3:  84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 301/360 [00:22<00:01, 35.04it/s]

Chain 5:  31%|███████████████████████████████▋                                                                      | 112/360 [00:09<00:21, 11.31it/s]

Chain 4:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:16<00:13, 13.57it/s]

Chain 3:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:22<00:01, 36.24it/s]

Chain 3:  86%|███████████████████████████████████████████████████████████████████████████████████████▊              | 310/360 [00:22<00:01, 37.88it/s]

Chain 4:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:16<00:13, 13.70it/s]

Chain 5:  32%|████████████████████████████████▎                                                                     | 114/360 [00:10<00:21, 11.25it/s]

Chain 3:  88%|█████████████████████████████████████████████████████████████████████████████████████████▎            | 315/360 [00:23<00:01, 40.08it/s]

Chain 4:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:16<00:12, 13.93it/s]

Chain 3:  89%|██████████████████████████████████████████████████████████████████████████████████████████▋           | 320/360 [00:23<00:00, 42.39it/s]

Chain 5:  32%|████████████████████████████████▊                                                                     | 116/360 [00:10<00:21, 11.10it/s]

Chain 4:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:16<00:12, 14.07it/s]

Chain 3:  91%|████████████████████████████████████████████████████████████████████████████████████████████▎         | 326/360 [00:23<00:00, 45.79it/s]

Chain 5:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:10<00:21, 11.12it/s]

Chain 4:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:16<00:12, 14.24it/s]

Chain 3:  92%|██████████████████████████████████████████████████████████████████████████████████████████████        | 332/360 [00:23<00:00, 49.33it/s]

Chain 3:  94%|████████████████████████████████████████████████████████████████████████████████████████████████      | 339/360 [00:23<00:00, 54.81it/s]

Chain 4:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:17<00:12, 14.33it/s]

Chain 5:  33%|██████████████████████████████████                                                                    | 120/360 [00:10<00:21, 11.16it/s]

Chain 3:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████▎   | 347/360 [00:23<00:00, 61.20it/s]

Chain 4:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:17<00:11, 14.50it/s]

Chain 3:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍| 358/360 [00:23<00:00, 74.04it/s]

Chain 5:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:10<00:21, 11.27it/s]

Chain 4:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:17<00:11, 14.81it/s]

Chain 5:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:11<00:20, 11.56it/s]

Chain 4:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:17<00:11, 15.08it/s]

Chain 4:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:17<00:10, 15.52it/s]

Chain 5:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:11<00:19, 11.84it/s]

Chain 4:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:17<00:10, 15.91it/s]

Chain 5:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:11<00:19, 12.00it/s]

Chain 4:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:17<00:10, 15.83it/s]

Chain 5:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:11<00:19, 12.09it/s]

Chain 4:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:18<00:09, 15.91it/s]

Chain 4:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:18<00:09, 16.24it/s]

Chain 5:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:11<00:18, 12.21it/s]

Chain 4:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:18<00:09, 16.59it/s]

Chain 5:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:11<00:18, 12.25it/s]

Chain 4:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:18<00:08, 16.92it/s]

Chain 5:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:12<00:18, 12.27it/s]

Chain 4:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:18<00:08, 17.02it/s]

Chain 4:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:18<00:08, 17.19it/s]

Chain 5:  38%|███████████████████████████████████████                                                               | 138/360 [00:12<00:17, 12.36it/s]

Chain 4:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:18<00:08, 17.50it/s]

Chain 5:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:12<00:17, 12.40it/s]

Chain 4:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:18<00:08, 17.85it/s]

Chain 4:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:18<00:07, 18.02it/s]

Chain 5:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:12<00:17, 12.48it/s]

Chain 4:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:19<00:07, 18.25it/s]

Chain 5:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:12<00:17, 12.29it/s]

Chain 4:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:19<00:07, 18.45it/s]

Chain 4:  62%|███████████████████████████████████████████████████████████████▍                                      | 224/360 [00:19<00:07, 18.80it/s]

Chain 5:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:12<00:17, 12.32it/s]

Chain 4:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:19<00:07, 18.55it/s]

Chain 5:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:12<00:16, 12.56it/s]

Chain 4:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:19<00:06, 19.89it/s]

Chain 5:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:13<00:16, 12.68it/s]

Chain 4:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:19<00:06, 20.64it/s]

Chain 5:  42%|███████████████████████████████████████████                                                           | 152/360 [00:13<00:16, 12.69it/s]

Chain 4:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:19<00:05, 21.30it/s]

Chain 4:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:19<00:05, 22.10it/s]

Chain 5:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:13<00:16, 12.86it/s]

Chain 4:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:19<00:05, 22.78it/s]

Chain 5:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:13<00:15, 13.10it/s]

Chain 4:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:20<00:04, 23.43it/s]

Chain 5:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:13<00:15, 13.13it/s]

Chain 4:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:20<00:04, 23.91it/s]

Chain 5:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:13<00:15, 13.15it/s]

Chain 4:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:20<00:04, 23.63it/s]

Chain 5:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:14<00:14, 13.35it/s]

Chain 4:  70%|███████████████████████████████████████████████████████████████████████▋                              | 253/360 [00:20<00:04, 23.57it/s]

Chain 4:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:20<00:04, 24.45it/s]

Chain 5:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:14<00:14, 13.38it/s]

Chain 4:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:20<00:04, 24.62it/s]

Chain 5:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:14<00:14, 13.43it/s]

Chain 4:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:20<00:03, 25.36it/s]

Chain 5:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:14<00:14, 13.35it/s]

Chain 4:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:20<00:03, 26.03it/s]

Chain 4:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:21<00:03, 26.88it/s]

Chain 5:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:14<00:14, 13.32it/s]

Chain 4:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:21<00:03, 27.19it/s]

Chain 5:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:14<00:14, 12.89it/s]

Chain 4:  76%|█████████████████████████████████████████████████████████████████████████████▉                        | 275/360 [00:21<00:02, 28.78it/s]

Chain 4:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:21<00:02, 28.62it/s]

Chain 5:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:14<00:14, 13.03it/s]

Chain 4:  78%|███████████████████████████████████████████████████████████████████████████████▉                      | 282/360 [00:21<00:02, 29.68it/s]

Chain 5:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:15<00:13, 13.39it/s]

Chain 4:  79%|█████████████████████████████████████████████████████████████████████████████████                     | 286/360 [00:21<00:02, 31.02it/s]

Chain 5:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:15<00:13, 13.77it/s]

Chain 4:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:21<00:02, 32.43it/s]

Chain 5:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:15<00:12, 14.07it/s]

Chain 4:  82%|███████████████████████████████████████████████████████████████████████████████████▎                  | 294/360 [00:21<00:01, 33.94it/s]

Chain 5:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:15<00:12, 14.46it/s]

Chain 4:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:21<00:01, 35.55it/s]

Chain 4:  84%|█████████████████████████████████████████████████████████████████████████████████████▊                | 303/360 [00:22<00:01, 37.62it/s]

Chain 5:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:15<00:11, 14.77it/s]

Chain 4:  86%|███████████████████████████████████████████████████████████████████████████████████████▎              | 308/360 [00:22<00:01, 39.16it/s]

Chain 5:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:15<00:11, 15.10it/s]

Chain 4:  87%|████████████████████████████████████████████████████████████████████████████████████████▋             | 313/360 [00:22<00:01, 41.70it/s]

Chain 5:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:15<00:11, 15.31it/s]

Chain 4:  89%|██████████████████████████████████████████████████████████████████████████████████████████▍           | 319/360 [00:22<00:00, 44.71it/s]

Chain 5:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:15<00:10, 15.53it/s]

Chain 4:  90%|████████████████████████████████████████████████████████████████████████████████████████████          | 325/360 [00:22<00:00, 48.71it/s]

Chain 5:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:16<00:10, 15.61it/s]

Chain 4:  92%|██████████████████████████████████████████████████████████████████████████████████████████████        | 332/360 [00:22<00:00, 53.70it/s]

Chain 5:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:16<00:10, 15.89it/s]

Chain 4:  94%|████████████████████████████████████████████████████████████████████████████████████████████████▎     | 340/360 [00:22<00:00, 60.19it/s]

Chain 5:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:16<00:10, 16.24it/s]

Chain 4:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████▏  | 350/360 [00:22<00:00, 70.98it/s]

Chain 5:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:16<00:09, 16.54it/s]

Chain 5:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:16<00:09, 16.47it/s]

Chain 5:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:16<00:09, 16.43it/s]

Chain 5:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:16<00:09, 16.76it/s]

Chain 5:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:16<00:08, 17.20it/s]

Chain 5:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:17<00:08, 17.57it/s]

Chain 5:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:17<00:08, 17.84it/s]

Chain 5:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:17<00:08, 18.16it/s]

Chain 5:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:17<00:07, 18.45it/s]

Chain 5:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:17<00:07, 18.83it/s]

Chain 5:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:17<00:07, 19.04it/s]

Chain 5:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:17<00:07, 19.54it/s]

Chain 5:  62%|███████████████████████████████████████████████████████████████▍                                      | 224/360 [00:17<00:06, 19.87it/s]

Chain 5:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:17<00:06, 19.62it/s]

Chain 5:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:18<00:06, 20.66it/s]

Chain 5:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:18<00:05, 21.70it/s]

Chain 5:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:18<00:05, 22.31it/s]

Chain 5:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:18<00:05, 23.08it/s]

Chain 5:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:18<00:05, 23.78it/s]

Chain 5:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:18<00:04, 24.31it/s]

Chain 5:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:18<00:04, 24.84it/s]

Chain 5:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:18<00:04, 24.65it/s]

Chain 5:  70%|███████████████████████████████████████████████████████████████████████▋                              | 253/360 [00:19<00:04, 25.16it/s]

Chain 5:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:19<00:04, 25.70it/s]

Chain 5:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:19<00:03, 26.57it/s]

Chain 5:  73%|██████████████████████████████████████████████████████████████████████████▌                           | 263/360 [00:19<00:03, 27.83it/s]

Chain 5:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:19<00:03, 28.14it/s]

Chain 5:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:19<00:03, 29.37it/s]

Chain 5:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:19<00:02, 30.64it/s]

Chain 5:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:19<00:02, 31.01it/s]

Chain 5:  78%|███████████████████████████████████████████████████████████████████████████████▉                      | 282/360 [00:19<00:02, 31.81it/s]

Chain 5:  79%|█████████████████████████████████████████████████████████████████████████████████                     | 286/360 [00:20<00:02, 33.32it/s]

Chain 5:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:20<00:02, 34.73it/s]

Chain 5:  82%|███████████████████████████████████████████████████████████████████████████████████▎                  | 294/360 [00:20<00:01, 35.99it/s]

Chain 5:  83%|████████████████████████████████████████████████████████████████████████████████████▋                 | 299/360 [00:20<00:01, 38.11it/s]

Chain 5:  84%|██████████████████████████████████████████████████████████████████████████████████████▏               | 304/360 [00:20<00:01, 40.17it/s]

Chain 5:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:20<00:01, 41.48it/s]

Chain 5:  88%|█████████████████████████████████████████████████████████████████████████████████████████▎            | 315/360 [00:20<00:01, 44.76it/s]

Chain 5:  89%|██████████████████████████████████████████████████████████████████████████████████████████▉           | 321/360 [00:20<00:00, 48.45it/s]

Chain 5:  91%|████████████████████████████████████████████████████████████████████████████████████████████▉         | 328/360 [00:20<00:00, 53.53it/s]

Chain 5:  93%|███████████████████████████████████████████████████████████████████████████████████████████████▏      | 336/360 [00:21<00:00, 59.89it/s]

Chain 5:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████▊    | 345/360 [00:21<00:00, 67.75it/s]

Chain 5: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋| 359/360 [00:21<00:00, 86.98it/s]

2026-05-28 20:13:55.866 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 20:13:56.601 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 20:14:04.346 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 20:14:04.785 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 20:14:04.785 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 20:14:04.796 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 20:14:06.235 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 20:14:06.286 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 20:14:07.065 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 20:14:08.348 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 20:14:09.698 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 20:14:09.954 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 20:14:09.955 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,115.1,176.4,271.9,395.6,559.0
GIIP (mscf),Total Volumes,1.0,46.4,73.2,119.1,184.4,262.0
Condensate (stb),Total Volumes,1.0,1.4,2.3,4.2,7.2,11.6
Solution Gas (mscf),Total Volumes,1.0,191.9,311.0,504.1,786.5,1175.4

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50   P10     P1
Total Oil EUR         1.0  25.6  39.7  62.0  92.8  131.7

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.94  1.3  3.4  9.2  22.7  44.6
Zone 2           0.87  0.9  2.4  6.1  14.1  27.4
Zone 3           0.76  1.1  2.7  6.4  13.9  24.0
Zone 4           0.61  1.0  2.7  8.1  21.4  46.9
Zone 5           0.96  1.6  3.6  9.0  20.3  42.9
Zone 6           0.45  1.1  2.6  6.4  14.0  25.3
Zone 7           0.62  0.9  2.5  7.1  18.4  38.2
Zone 8           0.42  0.6  2.2  6.9  20.5  46.4
Zone 9           0.62  1.0  2.5  5.7  13.0  23.1
Zone 10          0.93  1.1  2.7  6.3  13.9  25.9

In [14]:
reporter.tabler.npv_table()

     P(Commercial)    P99    P90    P50    P10      P1
NPV           0.61 -992.0 -498.0  133.0  784.0  1358.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)    P99    P90   P50    P10     P1
EMV           0.61 -647.0 -344.0  43.0  442.0  794.0

In [16]:
from resgo.plotting.tables import npv_USD
import numpy as np
import pandas as pd

npv = npv_USD(
    simpack,
    nominal=True,
    discounted=True,
    success_only=False,
)
npv_usd = npv.to_numpy().ravel()
npv_df = pd.DataFrame({"npv_usd_mm": npv_usd / 1e6})

histogram = (
    alt.Chart(npv_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Nominal discounted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Project NPV Distribution",
    )
)

break_even = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(histogram, break_even)
fig.show()

alt.LayerChart(...)

In [17]:
BANKRUPTCY_THRESHOLD_USD = 300e6
LOSS_FLOOR_USD = -5e9

def loss_adjusted_npv_USD(
    npv_usd,
    bankruptcy_threshold_usd=BANKRUPTCY_THRESHOLD_USD,
    floor_usd=LOSS_FLOOR_USD,
):
    npv_usd = np.asarray(npv_usd)
    threshold = bankruptcy_threshold_usd

    with np.errstate(divide="ignore", invalid="ignore"):
        adjusted = np.where(
            npv_usd >= 0,
            npv_usd,
            (threshold * npv_usd) / (threshold + npv_usd),
        )

    adjusted = np.where(npv_usd <= -threshold, floor_usd, adjusted)
    return np.maximum(adjusted, floor_usd)

x_usd = np.linspace(-0.9999 * BANKRUPTCY_THRESHOLD_USD, 1.5e9, 1_000)
loss_function_df = pd.DataFrame(
    {
        "npv_usd_mm": x_usd / 1e6,
        "loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(x_usd) / 1e6,
    }
)

loss_function = (
    alt.Chart(loss_function_df)
    .mark_line(color="#FACC15", strokeWidth=3)
    .encode(
        x=alt.X("npv_usd_mm:Q", title="Nominal discounted NPV ($USD MM)"),
        y=alt.Y(
            "loss_adjusted_npv_usd_mm:Q",
            title="Loss-adjusted NPV ($USD MM)",
        ),
        tooltip=[
            alt.Tooltip("npv_usd_mm:Q", title="NPV ($MM)", format=",.0f"),
            alt.Tooltip(
                "loss_adjusted_npv_usd_mm:Q",
                title="Loss-adjusted NPV ($MM)",
                format=",.0f",
            ),
        ],
    )
    .properties(
        width=650,
        height=250,
        title="Company Loss Function",
    )
)

bankruptcy_threshold = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [-BANKRUPTCY_THRESHOLD_USD / 1e6]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

loss_floor = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [LOSS_FLOOR_USD / 1e6]}))
    .mark_rule(color="red", strokeDash=[2, 4], strokeWidth=1)
    .encode(y="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_function, bankruptcy_threshold, loss_floor)
fig.show()

alt.LayerChart(...)

In [18]:
loss_df = pd.DataFrame(
    {"loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(npv_usd) / 1e6}
)

loss_histogram = (
    alt.Chart(loss_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "loss_adjusted_npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Loss-adjusted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated Loss-Adjusted NPV Distribution",
    )
)

break_even_loss = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_histogram, break_even_loss)
fig.show()

alt.LayerChart(...)