In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

/tmp/ipykernel_512213/1985460196.py:25: DeprecationWarning:

`set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 42

CHAINS = 10
DRAWS = 500
N_RESERVOIRS = 10
N_PRODUCERS = 25

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=60_000,
    gas_development=False,
    producer_capex_USD=80e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=250e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2e6,
    producer_abandonment_cost_USD=0.5e6,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 21:01:44.920 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 21:01:44.925 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 21:01:44.930 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 21:01:44.934 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 21:01:44.939 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 21:01:44.944 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 21:01:44.949 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 7 reservoir volumetric simulation complete.

2026-05-28 21:01:44.953 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 8 reservoir volumetric simulation complete.

2026-05-28 21:01:44.958 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 9 reservoir volumetric simulation complete.

2026-05-28 21:01:44.962 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 10 reservoir volumetric simulation complete.

2026-05-28 21:01:44.967 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 21:01:44.968 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 21:01:45.807 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 21:01:45.808 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 21:01:45.808 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 21:01:45.809 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 21:01:45.810 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 21:01:45.810 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 21:01:45.810 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 21:01:45.810 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 21:01:45.810 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 21:01:45.810 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 21:01:45.810 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 21:01:45.810 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 21:01:45.811 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 21:01:45.811 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 21 start_idx = 245

2026-05-28 21:01:45.811 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 22 start_idx = 257

2026-05-28 21:01:45.811 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 23 start_idx = 269

2026-05-28 21:01:45.811 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 24 start_idx = 280

2026-05-28 21:01:45.811 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 25 start_idx = 292

2026-05-28 21:01:45.851 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 21:01:45.866 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 21:01:46.512 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 21:01:46.512 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 21:01:46.513 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (25 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 81.74it/s]

Chain 0:   6%|█████▋                                                                                                 | 20/360 [00:00<00:09, 34.41it/s]

Chain 0:   7%|███████▏                                                                                               | 25/360 [00:00<00:11, 29.96it/s]

Chain 0:   8%|████████▎                                                                                              | 29/360 [00:00<00:11, 27.69it/s]

Chain 0:   9%|█████████▍                                                                                             | 33/360 [00:01<00:12, 25.85it/s]

Chain 0:  10%|██████████▎                                                                                            | 36/360 [00:01<00:12, 25.10it/s]

Chain 0:  11%|███████████▏                                                                                           | 39/360 [00:01<00:13, 24.59it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:01<00:13, 24.42it/s]

Chain 0:  12%|████████████▉                                                                                          | 45/360 [00:01<00:12, 24.38it/s]

Chain 0:  13%|█████████████▋                                                                                         | 48/360 [00:01<00:12, 24.31it/s]

Chain 0:  14%|██████████████▌                                                                                        | 51/360 [00:01<00:13, 23.58it/s]

Chain 0:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:13, 23.29it/s]

Chain 0:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:13, 22.74it/s]

Chain 0:  26%|██████████████████████████▌                                                                            | 93/360 [00:03<00:12, 21.19it/s]

Chain 0:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:13, 22.26it/s]

Chain 0:  18%|██████████████████                                                                                     | 63/360 [00:02<00:13, 22.55it/s]

Chain 0:  18%|██████████████████▉                                                                                    | 66/360 [00:02<00:12, 22.77it/s]

Chain 0:  19%|███████████████████▋                                                                                   | 69/360 [00:02<00:12, 22.89it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  20%|████████████████████▌                                                                                  | 72/360 [00:02<00:12, 23.03it/s]

Chain 1:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 78.48it/s]

Chain 0:  21%|█████████████████████▍                                                                                 | 75/360 [00:02<00:12, 23.05it/s]

Chain 0:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:12, 22.90it/s]

Chain 1:   5%|█████▍                                                                                                 | 19/360 [00:00<00:10, 33.12it/s]

Chain 0:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:12, 21.80it/s]

Chain 0:  23%|████████████████████████                                                                               | 84/360 [00:03<00:12, 21.88it/s]

Chain 1:   7%|██████▊                                                                                                | 24/360 [00:00<00:11, 28.57it/s]

Chain 0:  24%|████████████████████████▉                                                                              | 87/360 [00:03<00:12, 21.30it/s]

Chain 1:   8%|████████                                                                                               | 28/360 [00:00<00:12, 26.69it/s]

Chain 0:  25%|█████████████████████████▊                                                                             | 90/360 [00:03<00:12, 21.13it/s]

Chain 1:   9%|████████▊                                                                                              | 31/360 [00:01<00:13, 25.13it/s]

Chain 1:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 24.22it/s]

Chain 0:  27%|███████████████████████████▍                                                                           | 96/360 [00:03<00:12, 21.64it/s]

Chain 1:  10%|██████████▌                                                                                            | 37/360 [00:01<00:13, 23.14it/s]

Chain 0:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:11, 22.32it/s]

Chain 1:  11%|███████████▍                                                                                           | 40/360 [00:01<00:14, 22.81it/s]

Chain 0:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:11, 22.93it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:10, 23.24it/s]

Chain 1:  12%|████████████▎                                                                                          | 43/360 [00:01<00:14, 22.62it/s]

Chain 0:  30%|██████████████████████████████▌                                                                       | 108/360 [00:04<00:10, 23.98it/s]

Chain 1:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:13, 22.60it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:04<00:10, 24.58it/s]

Chain 1:  14%|██████████████                                                                                         | 49/360 [00:01<00:14, 22.09it/s]

Chain 0:  32%|████████████████████████████████▎                                                                     | 114/360 [00:04<00:09, 25.00it/s]

Chain 1:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:14, 21.76it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:04<00:09, 25.35it/s]

Chain 1:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 21.99it/s]

Chain 0:  33%|██████████████████████████████████                                                                    | 120/360 [00:04<00:09, 24.67it/s]

Chain 0:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:06<00:06, 29.65it/s]

Chain 1:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:13, 21.80it/s]

Chain 0:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:09, 24.64it/s]

Chain 0:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:05<00:09, 25.12it/s]

Chain 1:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:13, 21.57it/s]

Chain 0:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:05<00:09, 25.56it/s]

Chain 1:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:13, 21.28it/s]

Chain 0:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:05<00:08, 25.55it/s]

Chain 1:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:13, 21.22it/s]

Chain 0:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:05<00:08, 25.97it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  38%|███████████████████████████████████████                                                               | 138/360 [00:05<00:08, 26.08it/s]

Chain 1:  19%|████████████████████                                                                                   | 70/360 [00:02<00:13, 20.78it/s]

Chain 2:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 77.38it/s]

Chain 0:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:05<00:08, 26.63it/s]

Chain 1:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:13, 20.66it/s]

Chain 0:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:05<00:07, 27.07it/s]

Chain 1:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:13, 20.67it/s]

Chain 0:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:05<00:07, 27.27it/s]

Chain 0:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:06<00:07, 26.71it/s]

Chain 1:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.42it/s]

Chain 2:   5%|█████▍                                                                                                 | 19/360 [00:00<00:10, 32.58it/s]

Chain 0:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:06<00:07, 26.62it/s]

Chain 1:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 20.32it/s]

Chain 0:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:06<00:07, 27.20it/s]

Chain 2:   7%|██████▊                                                                                                | 24/360 [00:00<00:12, 27.87it/s]

Chain 1:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.28it/s]

Chain 0:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:07, 28.24it/s]

Chain 2:   8%|████████                                                                                               | 28/360 [00:00<00:12, 25.95it/s]

Chain 1:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:13, 20.28it/s]

Chain 0:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:06<00:06, 28.85it/s]

Chain 2:   9%|████████▊                                                                                              | 31/360 [00:01<00:13, 24.50it/s]

Chain 1:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:13, 20.12it/s]

Chain 2:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 23.71it/s]

Chain 0:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:06<00:06, 30.00it/s]

Chain 1:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:12, 20.49it/s]

Chain 2:  10%|██████████▌                                                                                            | 37/360 [00:01<00:14, 22.97it/s]

Chain 0:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:06<00:05, 30.84it/s]

Chain 1:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 21.24it/s]

Chain 0:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:05, 31.13it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:01<00:14, 22.74it/s]

Chain 1:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 21.87it/s]

Chain 0:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:05, 31.61it/s]

Chain 1:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:11, 22.52it/s]

Chain 2:  12%|████████████▎                                                                                          | 43/360 [00:01<00:13, 22.67it/s]

Chain 0:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:07<00:05, 32.47it/s]

Chain 1:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 22.92it/s]

Chain 2:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:13, 22.66it/s]

Chain 0:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:07<00:05, 33.30it/s]

Chain 1:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:10, 23.32it/s]

Chain 2:  14%|██████████████                                                                                         | 49/360 [00:01<00:13, 22.46it/s]

Chain 0:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:07<00:04, 34.10it/s]

Chain 1:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:10, 23.81it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:13, 22.12it/s]

Chain 0:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:07<00:04, 34.78it/s]

Chain 1:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:10, 24.26it/s]

Chain 0:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:07<00:04, 35.54it/s]

Chain 2:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 22.04it/s]

Chain 1:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:09, 24.48it/s]

Chain 0:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:07<00:04, 35.50it/s]

Chain 2:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:13, 21.67it/s]

Chain 1:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:09, 24.04it/s]

Chain 0:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:07<00:04, 35.34it/s]

Chain 2:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:14, 21.12it/s]

Chain 1:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:09, 24.18it/s]

Chain 0:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:08<00:03, 36.24it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:08<00:03, 37.14it/s]

Chain 1:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:09, 24.44it/s]

Chain 2:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:14, 20.56it/s]

Chain 0:  62%|███████████████████████████████████████████████████████████████▍                                      | 224/360 [00:08<00:03, 37.55it/s]

Chain 1:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 24.60it/s]

Chain 2:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:14, 20.43it/s]

Chain 0:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:08<00:03, 38.58it/s]

Chain 1:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:09, 24.81it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:  19%|████████████████████                                                                                   | 70/360 [00:02<00:14, 19.95it/s]

Chain 0:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:08<00:03, 39.43it/s]

Chain 1:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:09, 24.88it/s]

Chain 3:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 92.35it/s]

Chain 2:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:14, 19.86it/s]

Chain 0:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:08<00:02, 40.43it/s]

Chain 1:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:05<00:08, 25.18it/s]

Chain 2:  21%|█████████████████████▏                                                                                 | 74/360 [00:03<00:14, 19.83it/s]

Chain 0:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:08<00:02, 41.77it/s]

Chain 1:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 25.42it/s]

Chain 2:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:14, 19.84it/s]

Chain 0:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:08<00:02, 42.77it/s]

Chain 1:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 25.86it/s]

Chain 2:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:14, 19.65it/s]

Chain 0:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:08<00:02, 43.95it/s]

Chain 1:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 26.02it/s]

Chain 2:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:14, 19.90it/s]

Chain 0:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:09<00:02, 45.47it/s]

Chain 3:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 29.50it/s]

Chain 1:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:07, 26.31it/s]

Chain 2:  23%|███████████████████████▋                                                                               | 83/360 [00:03<00:13, 19.90it/s]

Chain 0:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:09<00:02, 47.22it/s]

Chain 1:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 26.14it/s]

Chain 2:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 19.79it/s]

Chain 0:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:09<00:01, 49.37it/s]

Chain 1:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 26.70it/s]

Chain 3:   7%|███████▏                                                                                               | 25/360 [00:00<00:13, 25.65it/s]

Chain 2:  24%|████████████████████████▉                                                                              | 87/360 [00:03<00:13, 19.74it/s]

Chain 0:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:09<00:01, 51.98it/s]

Chain 1:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:07, 27.16it/s]

Chain 2:  25%|█████████████████████████▍                                                                             | 89/360 [00:03<00:13, 19.44it/s]

Chain 0:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:09<00:01, 53.87it/s]

Chain 3:   8%|████████▎                                                                                              | 29/360 [00:01<00:13, 23.82it/s]

Chain 1:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:06<00:07, 27.42it/s]

Chain 2:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:13, 19.38it/s]

Chain 0:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:09<00:01, 56.92it/s]

Chain 1:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:06<00:06, 28.08it/s]

Chain 3:   9%|█████████▏                                                                                             | 32/360 [00:01<00:14, 22.73it/s]

Chain 2:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:15, 17.66it/s]

Chain 0:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:09<00:01, 58.77it/s]

Chain 1:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 28.51it/s]

Chain 0:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:09<00:00, 64.61it/s]

Chain 3:  10%|██████████                                                                                             | 35/360 [00:01<00:14, 21.93it/s]

Chain 2:  27%|███████████████████████████▍                                                                           | 96/360 [00:04<00:13, 19.25it/s]

Chain 1:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:07<00:06, 29.50it/s]

Chain 0:  87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 314/360 [00:09<00:00, 71.13it/s]

Chain 2:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:12, 20.34it/s]

Chain 1:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:07<00:06, 29.83it/s]

Chain 3:  11%|██████████▊                                                                                            | 38/360 [00:01<00:15, 21.06it/s]

Chain 0:  90%|███████████████████████████████████████████████████████████████████████████████████████████▊          | 324/360 [00:09<00:00, 79.01it/s]

Chain 2:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:12, 21.34it/s]

Chain 1:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:05, 30.30it/s]

Chain 0:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▍      | 337/360 [00:10<00:00, 92.49it/s]

Chain 3:  11%|███████████▋                                                                                           | 41/360 [00:01<00:15, 20.71it/s]

Chain 2:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:11, 21.94it/s]

Chain 0:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████▌ | 355/360 [00:10<00:00, 117.35it/s]

Chain 1:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:07<00:05, 30.81it/s]

Chain 3:  12%|████████████▌                                                                                          | 44/360 [00:01<00:15, 20.67it/s]

Chain 2:  30%|██████████████████████████████▌                                                                       | 108/360 [00:04<00:11, 22.41it/s]

Chain 1:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:07<00:05, 31.60it/s]

Chain 3:  13%|█████████████▍                                                                                         | 47/360 [00:01<00:15, 20.30it/s]

Chain 2:  31%|███████████████████████████████▍                                                                      | 111/360 [00:04<00:11, 22.63it/s]

Chain 1:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:07<00:05, 31.93it/s]

Chain 3:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:15, 20.29it/s]

Chain 1:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:07<00:05, 32.56it/s]

Chain 2:  32%|████████████████████████████████▎                                                                     | 114/360 [00:05<00:10, 22.66it/s]

Chain 1:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:07<00:04, 33.24it/s]

Chain 3:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:14, 20.52it/s]

Chain 2:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:10, 22.48it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:08<00:04, 33.72it/s]

Chain 2:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:10, 22.39it/s]

Chain 3:  16%|████████████████                                                                                       | 56/360 [00:02<00:15, 20.25it/s]

Chain 1:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:08<00:04, 33.84it/s]

Chain 2:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:10, 22.23it/s]

Chain 3:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:15, 20.02it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:08<00:04, 33.80it/s]

Chain 2:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:05<00:10, 21.58it/s]

Chain 1:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:08<00:04, 33.48it/s]

Chain 3:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:15, 19.14it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:08<00:04, 34.16it/s]

Chain 2:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:05<00:10, 21.98it/s]

Chain 3:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 19.24it/s]

Chain 1:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:08<00:03, 34.60it/s]

Chain 2:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:05<00:10, 22.40it/s]

Chain 3:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:14, 19.93it/s]

Chain 4:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:08<00:03, 35.80it/s]

Chain 2:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:06<00:09, 23.20it/s]

Chain 4:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 97.02it/s]

Chain 3:  19%|████████████████████                                                                                   | 70/360 [00:03<00:14, 20.19it/s]

Chain 1:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:08<00:03, 37.65it/s]

Chain 2:  38%|███████████████████████████████████████                                                               | 138/360 [00:06<00:09, 23.82it/s]

Chain 3:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 20.10it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:09<00:03, 39.09it/s]

Chain 2:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:06<00:08, 24.48it/s]

Chain 1:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:09<00:02, 40.93it/s]

Chain 2:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:06<00:08, 25.26it/s]

Chain 3:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:13, 20.32it/s]

Chain 1:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:09<00:02, 42.07it/s]

Chain 2:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:06<00:08, 25.69it/s]

Chain 3:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.30it/s]

Chain 1:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:09<00:02, 43.86it/s]

Chain 4:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 29.73it/s]

Chain 2:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:06<00:08, 26.06it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:09<00:02, 45.46it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 20.29it/s]

Chain 2:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:06<00:07, 26.01it/s]

Chain 1:  73%|██████████████████████████████████████████████████████████████████████████▊                           | 264/360 [00:09<00:02, 46.51it/s]

Chain 2:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:06<00:07, 26.39it/s]

Chain 3:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.00it/s]

Chain 4:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 25.50it/s]

Chain 1:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:09<00:01, 48.97it/s]

Chain 2:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:06<00:07, 27.07it/s]

Chain 1:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:09<00:01, 51.37it/s]

Chain 3:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:13, 19.93it/s]

Chain 2:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:07<00:07, 27.47it/s]

Chain 4:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.98it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████▉                      | 282/360 [00:09<00:01, 53.53it/s]

Chain 3:  25%|█████████████████████████▊                                                                             | 90/360 [00:04<00:13, 19.77it/s]

Chain 2:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:07<00:06, 28.16it/s]

Chain 1:  80%|█████████████████████████████████████████████████████████████████████████████████▌                    | 288/360 [00:10<00:01, 47.61it/s]

Chain 2:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:07<00:06, 27.54it/s]

Chain 3:  26%|██████████████████████████▎                                                                            | 92/360 [00:04<00:15, 16.79it/s]

Chain 4:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 22.67it/s]

Chain 1:  82%|███████████████████████████████████████████████████████████████████████████████████▌                  | 295/360 [00:10<00:01, 52.05it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:15, 17.42it/s]

Chain 2:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:07<00:07, 26.64it/s]

Chain 4:  10%|██████████▌                                                                                            | 37/360 [00:01<00:14, 21.68it/s]

Chain 1:  84%|█████████████████████████████████████████████████████████████████████████████████████▌                | 302/360 [00:10<00:01, 56.79it/s]

Chain 2:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:07<00:06, 27.53it/s]

Chain 3:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:14, 18.63it/s]

Chain 1:  86%|███████████████████████████████████████████████████████████████████████████████████████▊              | 310/360 [00:10<00:00, 62.23it/s]

Chain 2:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:07<00:06, 26.98it/s]

Chain 4:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 21.06it/s]

Chain 3:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:13, 19.21it/s]

Chain 1:  88%|██████████████████████████████████████████████████████████████████████████████████████████            | 318/360 [00:10<00:00, 66.07it/s]

Chain 2:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:07, 25.68it/s]

Chain 1:  91%|████████████████████████████████████████████████████████████████████████████████████████████▋         | 327/360 [00:10<00:00, 72.30it/s]

Chain 3:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:13, 18.52it/s]

Chain 4:  12%|████████████▎                                                                                          | 43/360 [00:01<00:16, 19.24it/s]

Chain 2:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:07<00:06, 26.15it/s]

Chain 1:  94%|████████████████████████████████████████████████████████████████████████████████████████████████▎     | 340/360 [00:10<00:00, 87.59it/s]

Chain 3:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:12, 19.70it/s]

Chain 2:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:07<00:06, 26.94it/s]

Chain 4:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:16, 18.85it/s]

Chain 1: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████▋| 359/360 [00:10<00:00, 116.78it/s]

Chain 3:  30%|██████████████████████████████▌                                                                       | 108/360 [00:05<00:12, 20.42it/s]

Chain 2:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:08<00:05, 28.45it/s]

Chain 4:  14%|██████████████                                                                                         | 49/360 [00:02<00:16, 19.15it/s]

Chain 3:  31%|███████████████████████████████▍                                                                      | 111/360 [00:05<00:12, 20.72it/s]

Chain 2:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:08<00:05, 29.68it/s]

Chain 4:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:16, 19.18it/s]

Chain 2:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:08<00:05, 30.57it/s]

Chain 3:  32%|████████████████████████████████▎                                                                     | 114/360 [00:05<00:11, 21.04it/s]

Chain 4:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:16, 18.83it/s]

Chain 2:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:08<00:05, 31.39it/s]

Chain 3:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:11, 21.51it/s]

Chain 4:  16%|████████████████                                                                                       | 56/360 [00:02<00:15, 19.24it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:08<00:04, 32.00it/s]

Chain 4:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:15, 18.93it/s]

Chain 3:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:11, 21.71it/s]

Chain 2:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:08<00:04, 32.37it/s]

Chain 4:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:15, 19.02it/s]

Chain 3:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:10, 21.74it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:08<00:04, 33.24it/s]

Chain 4:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:15, 18.95it/s]

Chain 3:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:05<00:10, 22.16it/s]

Chain 2:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:08<00:04, 33.53it/s]

Chain 4:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 18.86it/s]

Chain 3:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:06<00:10, 21.99it/s]

Chain 4:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:15, 18.49it/s]

Chain 2:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:08<00:04, 32.95it/s]

Chain 5:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 3:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:06<00:10, 22.67it/s]

Chain 4:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:15, 18.75it/s]

Chain 2:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:09<00:03, 34.30it/s]

Chain 5:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 94.83it/s]

Chain 4:  19%|████████████████████                                                                                   | 70/360 [00:03<00:15, 18.92it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:09<00:03, 35.20it/s]

Chain 3:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:06<00:09, 23.09it/s]

Chain 4:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:15, 18.85it/s]

Chain 2:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:09<00:03, 37.25it/s]

Chain 3:  38%|███████████████████████████████████████                                                               | 138/360 [00:06<00:09, 23.96it/s]

Chain 3:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:06<00:09, 24.33it/s]

Chain 2:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:09<00:03, 38.61it/s]

Chain 4:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:14, 19.19it/s]

Chain 3:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:06<00:08, 24.83it/s]

Chain 2:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:09<00:02, 40.19it/s]

Chain 4:  21%|██████████████████████                                                                                 | 77/360 [00:03<00:14, 19.10it/s]

Chain 5:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 28.99it/s]

Chain 2:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:09<00:02, 41.78it/s]

Chain 3:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:06<00:08, 25.61it/s]

Chain 4:  22%|██████████████████████▉                                                                                | 80/360 [00:03<00:14, 19.53it/s]

Chain 2:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:09<00:02, 43.28it/s]

Chain 3:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:06<00:08, 25.60it/s]

Chain 4:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:14, 19.48it/s]

Chain 2:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:09<00:02, 45.00it/s]

Chain 3:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:06<00:08, 25.83it/s]

Chain 4:  23%|████████████████████████                                                                               | 84/360 [00:03<00:14, 19.52it/s]

Chain 5:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 24.94it/s]

Chain 2:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:09<00:01, 47.23it/s]

Chain 3:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:07<00:07, 26.37it/s]

Chain 4:  24%|████████████████████████▌                                                                              | 86/360 [00:04<00:14, 19.50it/s]

Chain 2:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:10<00:01, 48.96it/s]

Chain 3:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:07<00:07, 26.79it/s]

Chain 4:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:14, 19.33it/s]

Chain 5:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.60it/s]

Chain 2:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:10<00:01, 51.79it/s]

Chain 3:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:07<00:08, 23.99it/s]

Chain 4:  25%|█████████████████████████▊                                                                             | 90/360 [00:04<00:16, 16.86it/s]

Chain 2:  79%|████████████████████████████████████████████████████████████████████████████████▍                     | 284/360 [00:10<00:01, 51.42it/s]

Chain 5:   9%|█████████▍                                                                                             | 33/360 [00:01<00:15, 21.42it/s]

Chain 4:  26%|██████████████████████████▎                                                                            | 92/360 [00:04<00:15, 17.25it/s]

Chain 3:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:07<00:08, 24.02it/s]

Chain 2:  81%|██████████████████████████████████████████████████████████████████████████████████▍                   | 291/360 [00:10<00:01, 54.44it/s]

Chain 4:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:15, 17.57it/s]

Chain 5:  10%|██████████▎                                                                                            | 36/360 [00:01<00:15, 20.28it/s]

Chain 3:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:07<00:07, 24.72it/s]

Chain 2:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:10<00:01, 56.98it/s]

Chain 3:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:07<00:07, 24.96it/s]

Chain 4:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:14, 18.68it/s]

Chain 2:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:10<00:00, 59.10it/s]

Chain 5:  11%|███████████▏                                                                                           | 39/360 [00:01<00:16, 19.11it/s]

Chain 3:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:07<00:07, 25.22it/s]

Chain 2:  87%|████████████████████████████████████████████████████████████████████████████████████████▍             | 312/360 [00:10<00:00, 60.95it/s]

Chain 4:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:14, 17.67it/s]

Chain 5:  12%|████████████                                                                                           | 42/360 [00:01<00:16, 18.99it/s]

Chain 3:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:07<00:07, 25.30it/s]

Chain 2:  89%|██████████████████████████████████████████████████████████████████████████████████████████▉           | 321/360 [00:10<00:00, 68.17it/s]

Chain 4:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:13, 18.72it/s]

Chain 5:  12%|████████████▌                                                                                          | 44/360 [00:01<00:16, 19.10it/s]

Chain 3:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:08<00:06, 26.30it/s]

Chain 2:  92%|█████████████████████████████████████████████████████████████████████████████████████████████▊        | 331/360 [00:10<00:00, 77.19it/s]

Chain 4:  29%|█████████████████████████████▊                                                                        | 105/360 [00:05<00:12, 19.79it/s]

Chain 3:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:08<00:06, 26.95it/s]

Chain 2:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████▊    | 345/360 [00:11<00:00, 95.04it/s]

Chain 5:  13%|█████████████▍                                                                                         | 47/360 [00:02<00:16, 19.39it/s]

Chain 3:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:08<00:06, 27.06it/s]

Chain 4:  30%|██████████████████████████████▌                                                                       | 108/360 [00:05<00:12, 20.05it/s]

Chain 5:  14%|██████████████                                                                                         | 49/360 [00:02<00:16, 19.28it/s]

Chain 5:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:15, 19.34it/s]

Chain 3:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:08<00:06, 28.11it/s]

Chain 4:  31%|███████████████████████████████▍                                                                      | 111/360 [00:05<00:12, 20.14it/s]

Chain 5:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:16, 19.06it/s]

Chain 3:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:08<00:05, 29.20it/s]

Chain 4:  32%|████████████████████████████████▎                                                                     | 114/360 [00:05<00:11, 20.66it/s]

Chain 5:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:16, 18.99it/s]

Chain 3:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:08<00:05, 30.24it/s]

Chain 4:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:11, 21.45it/s]

Chain 5:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 19.09it/s]

Chain 3:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:08<00:05, 31.07it/s]

Chain 5:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:15, 18.90it/s]

Chain 4:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:11, 21.61it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:08<00:04, 31.79it/s]

Chain 5:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:15, 18.88it/s]

Chain 4:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:10, 21.91it/s]

Chain 3:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:09<00:04, 32.19it/s]

Chain 5:  18%|██████████████████                                                                                     | 63/360 [00:02<00:15, 18.89it/s]

Chain 4:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:06<00:10, 22.48it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:09<00:04, 33.25it/s]

Chain 5:  18%|██████████████████▌                                                                                    | 65/360 [00:03<00:15, 18.66it/s]

Chain 4:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:06<00:10, 22.42it/s]

Chain 3:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:09<00:04, 33.19it/s]

Chain 5:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:16, 18.10it/s]

Chain 6:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 4:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:06<00:09, 23.04it/s]

Chain 3:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:09<00:04, 34.16it/s]

Chain 5:  19%|███████████████████▋                                                                                   | 69/360 [00:03<00:16, 17.70it/s]

Chain 6:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 88.48it/s]

Chain 3:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:09<00:03, 35.36it/s]

Chain 4:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:06<00:09, 23.71it/s]

Chain 5:  20%|████████████████████▎                                                                                  | 71/360 [00:03<00:16, 18.06it/s]

Chain 3:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:09<00:03, 37.44it/s]

Chain 4:  38%|███████████████████████████████████████                                                               | 138/360 [00:06<00:09, 24.53it/s]

Chain 5:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:15, 18.56it/s]

Chain 4:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:06<00:08, 25.06it/s]

Chain 3:  66%|██████████████████████████████████████████████████████████████████▊                                   | 236/360 [00:09<00:03, 38.89it/s]

Chain 5:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:15, 18.71it/s]

Chain 5:  21%|██████████████████████                                                                                 | 77/360 [00:03<00:14, 19.06it/s]

Chain 4:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:06<00:08, 25.26it/s]

Chain 3:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:09<00:02, 40.07it/s]

Chain 6:   5%|█████▍                                                                                                 | 19/360 [00:00<00:11, 29.96it/s]

Chain 4:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:06<00:08, 25.91it/s]

Chain 3:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:09<00:02, 41.77it/s]

Chain 5:  22%|██████████████████████▉                                                                                | 80/360 [00:03<00:14, 19.66it/s]

Chain 3:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:10<00:02, 43.01it/s]

Chain 4:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:06<00:08, 26.00it/s]

Chain 5:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:14, 19.61it/s]

Chain 6:   7%|██████▊                                                                                                | 24/360 [00:00<00:13, 25.68it/s]

Chain 3:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:10<00:02, 44.47it/s]

Chain 4:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:07<00:07, 26.12it/s]

Chain 5:  24%|████████████████████████▎                                                                              | 85/360 [00:04<00:13, 19.82it/s]

Chain 3:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:10<00:02, 46.59it/s]

Chain 4:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:07<00:07, 26.49it/s]

Chain 6:   8%|████████                                                                                               | 28/360 [00:01<00:13, 23.99it/s]

Chain 5:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:13, 19.51it/s]

Chain 4:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:07<00:07, 26.93it/s]

Chain 3:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:10<00:01, 47.85it/s]

Chain 5:  25%|█████████████████████████▍                                                                             | 89/360 [00:04<00:14, 19.35it/s]

Chain 6:   9%|████████▊                                                                                              | 31/360 [00:01<00:14, 22.59it/s]

Chain 4:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:07<00:07, 27.01it/s]

Chain 3:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:10<00:01, 49.03it/s]

Chain 5:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:14, 18.08it/s]

Chain 4:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:07<00:07, 27.32it/s]

Chain 3:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:10<00:01, 50.90it/s]

Chain 6:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 21.76it/s]

Chain 5:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:14, 18.14it/s]

Chain 4:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:07<00:06, 28.00it/s]

Chain 3:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:10<00:01, 53.76it/s]

Chain 5:  26%|███████████████████████████▏                                                                           | 95/360 [00:04<00:14, 18.59it/s]

Chain 6:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 21.12it/s]

Chain 4:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:07<00:06, 27.84it/s]

Chain 3:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:10<00:01, 55.22it/s]

Chain 5:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:13, 18.85it/s]

Chain 6:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.68it/s]

Chain 3:  84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 301/360 [00:10<00:00, 60.18it/s]

Chain 4:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 28.57it/s]

Chain 5:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:13, 19.95it/s]

Chain 3:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:11<00:00, 64.54it/s]

Chain 4:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:08<00:06, 27.25it/s]

Chain 6:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 20.16it/s]

Chain 5:  29%|█████████████████████████████▏                                                                        | 103/360 [00:05<00:12, 20.79it/s]

Chain 3:  88%|██████████████████████████████████████████████████████████████████████████████████████████            | 318/360 [00:11<00:00, 70.52it/s]

Chain 4:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:08<00:06, 27.81it/s]

Chain 3:  91%|████████████████████████████████████████████████████████████████████████████████████████████▉         | 328/360 [00:11<00:00, 78.78it/s]

Chain 6:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:15, 19.64it/s]

Chain 4:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:08<00:06, 28.38it/s]

Chain 5:  29%|██████████████████████████████                                                                        | 106/360 [00:05<00:11, 21.33it/s]

Chain 3:  94%|████████████████████████████████████████████████████████████████████████████████████████████████      | 339/360 [00:11<00:00, 87.08it/s]

Chain 6:  13%|█████████████▋                                                                                         | 48/360 [00:02<00:15, 19.65it/s]

Chain 4:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:08<00:06, 28.31it/s]

Chain 5:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:11, 21.69it/s]

Chain 3:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████▍  | 351/360 [00:11<00:00, 96.22it/s]

Chain 4:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:08<00:06, 28.08it/s]

Chain 6:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:16, 18.64it/s]

Chain 5:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:11, 21.82it/s]

Chain 6:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:16, 18.56it/s]

Chain 4:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:08<00:05, 29.13it/s]

Chain 5:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:11, 21.99it/s]

Chain 6:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:16, 18.49it/s]

Chain 4:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:08<00:05, 29.95it/s]

Chain 5:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:10, 22.14it/s]

Chain 6:  16%|████████████████                                                                                       | 56/360 [00:02<00:16, 18.51it/s]

Chain 4:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:08<00:05, 30.50it/s]

Chain 6:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:16, 18.32it/s]

Chain 5:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 21.74it/s]

Chain 4:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:08<00:04, 31.10it/s]

Chain 6:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:16, 18.38it/s]

Chain 5:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 22.09it/s]

Chain 4:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:09<00:04, 31.51it/s]

Chain 6:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:16, 18.27it/s]

Chain 5:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:06<00:10, 22.47it/s]

Chain 4:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:09<00:04, 32.58it/s]

Chain 6:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:16, 18.18it/s]

Chain 4:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:09<00:04, 32.79it/s]

Chain 5:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:06<00:10, 21.85it/s]

Chain 7:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 6:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:17, 16.87it/s]

Chain 4:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:09<00:04, 33.70it/s]

Chain 7:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 90.57it/s]

Chain 5:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:10, 21.30it/s]

Chain 6:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:17, 16.50it/s]

Chain 4:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:09<00:03, 33.88it/s]

Chain 5:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:10, 22.10it/s]

Chain 6:  19%|████████████████████                                                                                   | 70/360 [00:03<00:17, 16.93it/s]

Chain 4:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:09<00:03, 35.11it/s]

Chain 6:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:16, 17.63it/s]

Chain 5:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:09, 23.19it/s]

Chain 4:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:09<00:03, 37.33it/s]

Chain 6:  21%|█████████████████████▏                                                                                 | 74/360 [00:03<00:15, 17.89it/s]

Chain 5:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:09, 22.95it/s]

Chain 4:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:09<00:03, 37.97it/s]

Chain 6:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:16, 17.37it/s]

Chain 5:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:09, 23.47it/s]

Chain 7:   6%|█████▋                                                                                                 | 20/360 [00:00<00:12, 28.11it/s]

Chain 4:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:09<00:02, 40.08it/s]

Chain 6:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:15, 17.67it/s]

Chain 5:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 24.10it/s]

Chain 4:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:10<00:02, 42.01it/s]

Chain 6:  22%|██████████████████████▉                                                                                | 80/360 [00:03<00:15, 17.78it/s]

Chain 4:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:10<00:02, 43.37it/s]

Chain 5:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:07<00:08, 24.67it/s]

Chain 7:   7%|███████▏                                                                                               | 25/360 [00:00<00:13, 25.06it/s]

Chain 6:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:15, 18.37it/s]

Chain 4:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:10<00:02, 44.77it/s]

Chain 5:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:07<00:08, 25.22it/s]

Chain 6:  24%|████████████████████████▎                                                                              | 85/360 [00:04<00:14, 18.73it/s]

Chain 4:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:10<00:02, 46.61it/s]

Chain 7:   8%|████████▎                                                                                              | 29/360 [00:01<00:14, 23.62it/s]

Chain 5:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:07<00:07, 25.82it/s]

Chain 6:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:14, 18.50it/s]

Chain 5:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:07, 26.60it/s]

Chain 4:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:10<00:01, 48.58it/s]

Chain 7:   9%|█████████▏                                                                                             | 32/360 [00:01<00:14, 22.77it/s]

Chain 6:  25%|█████████████████████████▍                                                                             | 89/360 [00:04<00:14, 18.77it/s]

Chain 5:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:07, 27.27it/s]

Chain 4:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:10<00:01, 51.04it/s]

Chain 7:  10%|██████████                                                                                             | 35/360 [00:01<00:14, 22.02it/s]

Chain 6:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:14, 18.85it/s]

Chain 5:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 27.39it/s]

Chain 4:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:10<00:01, 52.64it/s]

Chain 6:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:14, 18.82it/s]

Chain 5:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 27.88it/s]

Chain 4:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:10<00:01, 54.99it/s]

Chain 7:  11%|██████████▊                                                                                            | 38/360 [00:01<00:15, 21.21it/s]

Chain 6:  26%|███████████████████████████▏                                                                           | 95/360 [00:04<00:13, 19.10it/s]

Chain 5:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:06, 27.58it/s]

Chain 4:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:10<00:01, 57.63it/s]

Chain 7:  11%|███████████▋                                                                                           | 41/360 [00:01<00:15, 20.05it/s]

Chain 6:  27%|████████████████████████████                                                                           | 98/360 [00:04<00:12, 20.22it/s]

Chain 5:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 26.66it/s]

Chain 4:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:11<00:00, 62.18it/s]

Chain 5:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:08<00:06, 27.47it/s]

Chain 4:  87%|████████████████████████████████████████████████████████████████████████████████████████▋             | 313/360 [00:11<00:00, 66.53it/s]

Chain 7:  12%|████████████▌                                                                                          | 44/360 [00:01<00:15, 20.11it/s]

Chain 6:  28%|████████████████████████████▌                                                                         | 101/360 [00:04<00:12, 20.95it/s]

Chain 4:  90%|███████████████████████████████████████████████████████████████████████████████████████████▌          | 323/360 [00:11<00:00, 74.15it/s]

Chain 5:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:08<00:06, 28.77it/s]

Chain 6:  29%|█████████████████████████████▍                                                                        | 104/360 [00:05<00:12, 21.20it/s]

Chain 7:  13%|█████████████▍                                                                                         | 47/360 [00:02<00:15, 19.78it/s]

Chain 4:  92%|██████████████████████████████████████████████████████████████████████████████████████████████▎       | 333/360 [00:11<00:00, 79.49it/s]

Chain 5:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:08<00:06, 28.97it/s]

Chain 6:  30%|██████████████████████████████▎                                                                       | 107/360 [00:05<00:11, 21.73it/s]

Chain 4:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████▌   | 348/360 [00:11<00:00, 98.21it/s]

Chain 7:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:15, 19.60it/s]

Chain 5:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:08<00:06, 28.33it/s]

Chain 6:  31%|███████████████████████████████▏                                                                      | 110/360 [00:05<00:11, 21.81it/s]

Chain 7:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:15, 19.55it/s]

Chain 5:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:08<00:06, 27.97it/s]

Chain 7:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:15, 19.16it/s]

Chain 5:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:08<00:06, 27.40it/s]

Chain 6:  31%|████████████████████████████████                                                                      | 113/360 [00:05<00:11, 21.07it/s]

Chain 7:  16%|████████████████                                                                                       | 56/360 [00:02<00:16, 18.48it/s]

Chain 5:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:08<00:05, 27.41it/s]

Chain 6:  32%|████████████████████████████████▊                                                                     | 116/360 [00:05<00:11, 21.41it/s]

Chain 7:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:16, 18.63it/s]

Chain 5:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:08<00:05, 29.44it/s]

Chain 6:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:05<00:11, 21.49it/s]

Chain 7:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:16, 18.36it/s]

Chain 5:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:08<00:04, 31.25it/s]

Chain 7:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:15, 18.64it/s]

Chain 6:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:05<00:10, 21.99it/s]

Chain 5:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:09<00:04, 32.23it/s]

Chain 7:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 18.72it/s]

Chain 6:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:06<00:10, 22.29it/s]

Chain 5:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:09<00:04, 32.36it/s]

Chain 7:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:15, 18.98it/s]

Chain 6:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:06<00:10, 22.71it/s]

Chain 5:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:09<00:04, 33.31it/s]

Chain 7:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:15, 18.93it/s]

Chain 5:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:09<00:04, 33.75it/s]

Chain 6:  36%|█████████████████████████████████████                                                                 | 131/360 [00:06<00:10, 22.87it/s]

Chain 7:  19%|████████████████████                                                                                   | 70/360 [00:03<00:15, 18.90it/s]

Chain 5:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:09<00:03, 34.19it/s]

Chain 6:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:06<00:09, 23.18it/s]

Chain 8:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 7:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:15, 18.86it/s]

Chain 5:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:09<00:03, 35.69it/s]

Chain 8:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 96.55it/s]

Chain 6:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:06<00:09, 23.96it/s]

Chain 7:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:14, 19.51it/s]

Chain 5:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:09<00:03, 37.45it/s]

Chain 6:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:06<00:09, 24.36it/s]

Chain 7:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:14, 20.06it/s]

Chain 5:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:09<00:03, 39.24it/s]

Chain 6:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:06<00:08, 25.05it/s]

Chain 5:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:10<00:02, 40.77it/s]

Chain 7:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:13, 20.30it/s]

Chain 6:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:06<00:08, 25.42it/s]

Chain 5:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:10<00:02, 41.89it/s]

Chain 6:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:06<00:08, 25.80it/s]

Chain 7:  23%|████████████████████████                                                                               | 84/360 [00:03<00:13, 20.35it/s]

Chain 8:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 29.86it/s]

Chain 5:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:10<00:02, 43.76it/s]

Chain 6:  42%|███████████████████████████████████████████                                                           | 152/360 [00:07<00:08, 25.91it/s]

Chain 7:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:13, 20.21it/s]

Chain 5:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:10<00:02, 44.72it/s]

Chain 6:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:07<00:07, 26.17it/s]

Chain 5:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:10<00:02, 47.11it/s]

Chain 7:  25%|█████████████████████████▊                                                                             | 90/360 [00:04<00:13, 20.20it/s]

Chain 6:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:07<00:07, 26.70it/s]

Chain 8:   7%|███████▍                                                                                               | 26/360 [00:00<00:12, 25.70it/s]

Chain 5:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:10<00:01, 49.45it/s]

Chain 6:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:07<00:07, 27.38it/s]

Chain 7:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:13, 20.15it/s]

Chain 5:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:10<00:01, 51.47it/s]

Chain 8:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 24.13it/s]

Chain 6:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:07<00:07, 27.68it/s]

Chain 7:  27%|███████████████████████████▍                                                                           | 96/360 [00:04<00:12, 20.41it/s]

Chain 5:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:10<00:01, 52.88it/s]

Chain 6:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:07<00:06, 27.60it/s]

Chain 5:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:10<00:01, 56.06it/s]

Chain 8:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 22.38it/s]

Chain 7:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:12, 20.61it/s]

Chain 6:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:07<00:06, 28.41it/s]

Chain 5:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:10<00:01, 59.28it/s]

Chain 6:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:07<00:06, 27.89it/s]

Chain 7:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:12, 20.68it/s]

Chain 8:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 21.29it/s]

Chain 5:  84%|█████████████████████████████████████████████████████████████████████████████████████▊                | 303/360 [00:11<00:00, 59.40it/s]

Chain 6:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:07<00:06, 27.74it/s]

Chain 5:  86%|████████████████████████████████████████████████████████████████████████████████████████              | 311/360 [00:11<00:00, 65.32it/s]

Chain 7:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:12, 20.01it/s]

Chain 8:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.75it/s]

Chain 6:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:08<00:06, 27.98it/s]

Chain 5:  89%|██████████████████████████████████████████████████████████████████████████████████████████▋           | 320/360 [00:11<00:00, 71.03it/s]

Chain 7:  30%|██████████████████████████████▌                                                                       | 108/360 [00:05<00:12, 20.51it/s]

Chain 6:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:08<00:06, 27.58it/s]

Chain 8:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 20.29it/s]

Chain 5:  92%|█████████████████████████████████████████████████████████████████████████████████████████████▊        | 331/360 [00:11<00:00, 80.42it/s]

Chain 6:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:08<00:06, 28.09it/s]

Chain 7:  31%|███████████████████████████████▍                                                                      | 111/360 [00:05<00:11, 21.05it/s]

Chain 5:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████▍    | 344/360 [00:11<00:00, 94.53it/s]

Chain 8:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:15, 20.11it/s]

Chain 6:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:08<00:05, 28.80it/s]

Chain 7:  32%|████████████████████████████████▎                                                                     | 114/360 [00:05<00:11, 21.71it/s]

Chain 8:  14%|██████████████                                                                                         | 49/360 [00:02<00:15, 19.73it/s]

Chain 6:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:08<00:05, 28.36it/s]

Chain 7:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:11, 21.94it/s]

Chain 6:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:08<00:05, 27.72it/s]

Chain 8:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:15, 19.30it/s]

Chain 7:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:11, 20.24it/s]

Chain 6:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:08<00:05, 29.21it/s]

Chain 8:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:16, 18.94it/s]

Chain 7:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:11, 20.42it/s]

Chain 6:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:08<00:05, 30.77it/s]

Chain 8:  16%|████████████████                                                                                       | 56/360 [00:02<00:16, 18.86it/s]

Chain 8:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:16, 18.54it/s]

Chain 6:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:09<00:04, 31.08it/s]

Chain 7:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:05<00:11, 20.68it/s]

Chain 8:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:16, 18.31it/s]

Chain 6:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:09<00:04, 31.21it/s]

Chain 7:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:06<00:11, 20.98it/s]

Chain 8:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:16, 18.56it/s]

Chain 6:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:09<00:04, 31.07it/s]

Chain 7:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:06<00:11, 20.67it/s]

Chain 8:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:15, 19.06it/s]

Chain 6:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:09<00:04, 30.81it/s]

Chain 7:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:06<00:10, 20.67it/s]

Chain 9:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 8:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:15, 18.60it/s]

Chain 6:  62%|███████████████████████████████████████████████████████████████▍                                      | 224/360 [00:09<00:04, 31.80it/s]

Chain 7:  38%|███████████████████████████████████████                                                               | 138/360 [00:06<00:10, 21.70it/s]

Chain 9:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 95.14it/s]

Chain 6:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:09<00:03, 33.77it/s]

Chain 8:  19%|████████████████████                                                                                   | 70/360 [00:03<00:15, 19.21it/s]

Chain 7:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:06<00:09, 22.81it/s]

Chain 8:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:15, 18.97it/s]

Chain 6:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:09<00:03, 35.91it/s]

Chain 7:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:06<00:09, 22.53it/s]

Chain 8:  21%|█████████████████████▏                                                                                 | 74/360 [00:03<00:14, 19.09it/s]

Chain 6:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:09<00:03, 36.57it/s]

Chain 7:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:06<00:09, 23.29it/s]

Chain 8:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:14, 19.02it/s]

Chain 6:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:09<00:03, 38.07it/s]

Chain 8:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:14, 19.11it/s]

Chain 7:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:07<00:08, 23.75it/s]

Chain 6:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:10<00:02, 38.82it/s]

Chain 9:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 29.05it/s]

Chain 8:  22%|██████████████████████▉                                                                                | 80/360 [00:03<00:14, 19.12it/s]

Chain 7:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:07<00:08, 24.03it/s]

Chain 6:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:10<00:02, 40.76it/s]

Chain 8:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:14, 19.12it/s]

Chain 7:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:07<00:08, 24.77it/s]

Chain 6:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:10<00:02, 42.33it/s]

Chain 8:  23%|████████████████████████                                                                               | 84/360 [00:03<00:14, 19.14it/s]

Chain 7:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:07<00:07, 25.65it/s]

Chain 9:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 24.78it/s]

Chain 6:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:10<00:02, 43.64it/s]

Chain 8:  24%|████████████████████████▌                                                                              | 86/360 [00:04<00:14, 19.20it/s]

Chain 7:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:07<00:07, 26.52it/s]

Chain 6:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:10<00:01, 46.43it/s]

Chain 8:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:14, 19.05it/s]

Chain 9:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.59it/s]

Chain 7:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:07<00:07, 26.93it/s]

Chain 6:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:10<00:01, 49.02it/s]

Chain 8:  25%|█████████████████████████▊                                                                             | 90/360 [00:04<00:14, 19.12it/s]

Chain 6:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:10<00:01, 51.62it/s]

Chain 7:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 28.14it/s]

Chain 8:  26%|██████████████████████████▎                                                                            | 92/360 [00:04<00:14, 18.56it/s]

Chain 9:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 22.75it/s]

Chain 7:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:06, 28.56it/s]

Chain 6:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:10<00:01, 55.27it/s]

Chain 8:  26%|███████████████████████████▏                                                                           | 95/360 [00:04<00:13, 19.50it/s]

Chain 7:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 28.80it/s]

Chain 9:  10%|██████████▌                                                                                            | 37/360 [00:01<00:14, 22.14it/s]

Chain 6:  82%|███████████████████████████████████████████████████████████████████████████████████▎                  | 294/360 [00:10<00:01, 58.93it/s]

Chain 7:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:08<00:06, 29.11it/s]

Chain 6:  84%|█████████████████████████████████████████████████████████████████████████████████████▌                | 302/360 [00:11<00:00, 63.98it/s]

Chain 8:  27%|████████████████████████████                                                                           | 98/360 [00:04<00:12, 20.16it/s]

Chain 9:  11%|███████████▍                                                                                           | 40/360 [00:01<00:14, 21.34it/s]

Chain 7:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:08<00:06, 28.88it/s]

Chain 6:  86%|████████████████████████████████████████████████████████████████████████████████████████              | 311/360 [00:11<00:00, 69.60it/s]

Chain 8:  28%|████████████████████████████▌                                                                         | 101/360 [00:04<00:12, 21.00it/s]

Chain 9:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 21.05it/s]

Chain 6:  89%|██████████████████████████████████████████████████████████████████████████████████████████▋           | 320/360 [00:11<00:00, 73.91it/s]

Chain 7:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:08<00:05, 29.87it/s]

Chain 8:  29%|█████████████████████████████▍                                                                        | 104/360 [00:04<00:11, 21.69it/s]

Chain 6:  92%|█████████████████████████████████████████████████████████████████████████████████████████████▊        | 331/360 [00:11<00:00, 83.61it/s]

Chain 9:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:14, 21.12it/s]

Chain 7:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:08<00:05, 30.93it/s]

Chain 8:  30%|██████████████████████████████▎                                                                       | 107/360 [00:05<00:11, 21.85it/s]

Chain 6:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████▊    | 345/360 [00:11<00:00, 98.47it/s]

Chain 7:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:08<00:05, 31.69it/s]

Chain 9:  14%|██████████████                                                                                         | 49/360 [00:02<00:14, 21.04it/s]

Chain 8:  31%|███████████████████████████████▏                                                                      | 110/360 [00:05<00:11, 22.39it/s]

Chain 7:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:08<00:05, 31.26it/s]

Chain 9:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:14, 20.98it/s]

Chain 8:  31%|████████████████████████████████                                                                      | 113/360 [00:05<00:10, 22.87it/s]

Chain 7:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:08<00:04, 32.20it/s]

Chain 9:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:14, 20.96it/s]

Chain 8:  32%|████████████████████████████████▊                                                                     | 116/360 [00:05<00:10, 23.11it/s]

Chain 7:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:08<00:04, 32.60it/s]

Chain 9:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:14, 20.37it/s]

Chain 8:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:05<00:10, 22.84it/s]

Chain 7:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:08<00:04, 33.04it/s]

Chain 8:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:05<00:10, 23.05it/s]

Chain 7:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:09<00:04, 33.57it/s]

Chain 9:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:14, 19.94it/s]

Chain 7:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:09<00:04, 34.18it/s]

Chain 8:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:05<00:10, 23.05it/s]

Chain 9:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 19.45it/s]

Chain 7:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:09<00:03, 35.19it/s]

Chain 8:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:05<00:09, 23.43it/s]

Chain 9:  18%|██████████████████▉                                                                                    | 66/360 [00:02<00:15, 19.33it/s]

Chain 7:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:09<00:03, 35.82it/s]

Chain 8:  36%|█████████████████████████████████████                                                                 | 131/360 [00:06<00:09, 23.93it/s]

Chain 9:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:15, 19.08it/s]

Chain 7:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:09<00:03, 36.71it/s]

Chain 8:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:06<00:09, 24.56it/s]

Chain 9:  19%|████████████████████                                                                                   | 70/360 [00:03<00:15, 19.24it/s]

Chain 7:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:09<00:03, 37.59it/s]

Chain 8:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:06<00:09, 24.70it/s]

Chain 7:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:09<00:03, 40.20it/s]

Chain 9:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 19.66it/s]

Chain 8:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:06<00:08, 25.16it/s]

Chain 7:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:09<00:02, 42.47it/s]

Chain 9:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:14, 19.57it/s]

Chain 8:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:06<00:08, 25.96it/s]

Chain 7:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:09<00:02, 45.01it/s]

Chain 9:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:14, 20.04it/s]

Chain 8:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:06<00:08, 26.15it/s]

Chain 7:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:10<00:02, 45.97it/s]

Chain 9:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:13, 20.24it/s]

Chain 8:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:06<00:07, 26.63it/s]

Chain 7:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:10<00:02, 47.70it/s]

Chain 8:  42%|███████████████████████████████████████████                                                           | 152/360 [00:06<00:07, 26.77it/s]

Chain 9:  23%|████████████████████████                                                                               | 84/360 [00:03<00:13, 20.52it/s]

Chain 7:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:10<00:01, 49.98it/s]

Chain 8:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:06<00:07, 27.32it/s]

Chain 7:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:10<00:01, 52.64it/s]

Chain 9:  24%|████████████████████████▉                                                                              | 87/360 [00:03<00:13, 20.32it/s]

Chain 8:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:07<00:07, 27.98it/s]

Chain 7:  78%|███████████████████████████████████████████████████████████████████████████████                       | 279/360 [00:10<00:01, 55.83it/s]

Chain 9:  25%|█████████████████████████▊                                                                             | 90/360 [00:04<00:13, 20.47it/s]

Chain 8:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:07<00:06, 28.90it/s]

Chain 7:  79%|█████████████████████████████████████████████████████████████████████████████████                     | 286/360 [00:10<00:01, 57.55it/s]

Chain 8:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:07<00:06, 28.01it/s]

Chain 7:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:10<00:01, 59.17it/s]

Chain 9:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:13, 19.19it/s]

Chain 7:  84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 301/360 [00:10<00:00, 64.03it/s]

Chain 8:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 28.92it/s]

Chain 9:  27%|███████████████████████████▍                                                                           | 96/360 [00:04<00:13, 20.16it/s]

Chain 7:  86%|███████████████████████████████████████████████████████████████████████████████████████▊              | 310/360 [00:10<00:00, 70.09it/s]

Chain 8:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:07<00:06, 29.83it/s]

Chain 9:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:12, 21.02it/s]

Chain 7:  89%|██████████████████████████████████████████████████████████████████████████████████████████▋           | 320/360 [00:11<00:00, 78.03it/s]

Chain 8:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:07<00:06, 29.84it/s]

Chain 7:  92%|██████████████████████████████████████████████████████████████████████████████████████████████        | 332/360 [00:11<00:00, 89.95it/s]

Chain 9:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:11, 21.79it/s]

Chain 8:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:05, 30.37it/s]

Chain 7:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████▉   | 349/360 [00:11<00:00, 113.10it/s]

Chain 9:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:11, 22.22it/s]

Chain 8:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:05, 30.51it/s]

Chain 9:  30%|██████████████████████████████▌                                                                       | 108/360 [00:04<00:11, 22.61it/s]

Chain 8:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:08<00:05, 31.47it/s]

Chain 9:  31%|███████████████████████████████▍                                                                      | 111/360 [00:05<00:10, 23.09it/s]

Chain 8:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:08<00:05, 32.46it/s]

Chain 9:  32%|████████████████████████████████▎                                                                     | 114/360 [00:05<00:10, 23.56it/s]

Chain 8:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:08<00:04, 33.34it/s]

Chain 9:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:10, 23.89it/s]

Chain 8:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:08<00:04, 34.09it/s]

Chain 8:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:08<00:04, 35.19it/s]

Chain 9:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:10, 23.57it/s]

Chain 8:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:08<00:04, 35.61it/s]

Chain 9:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:10, 23.37it/s]

Chain 8:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:08<00:04, 35.47it/s]

Chain 9:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:05<00:09, 23.91it/s]

Chain 8:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:08<00:03, 36.64it/s]

Chain 9:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:05<00:09, 24.11it/s]

Chain 8:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:08<00:03, 38.00it/s]

Chain 9:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:05<00:09, 24.54it/s]

Chain 8:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:09<00:03, 37.40it/s]

Chain 9:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:06<00:09, 24.74it/s]

Chain 8:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:09<00:03, 39.25it/s]

Chain 9:  38%|███████████████████████████████████████                                                               | 138/360 [00:06<00:08, 25.71it/s]

Chain 8:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:09<00:03, 41.18it/s]

Chain 9:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:06<00:08, 26.21it/s]

Chain 8:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:09<00:02, 43.02it/s]

Chain 9:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:06<00:08, 26.91it/s]

Chain 8:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:09<00:02, 44.86it/s]

Chain 9:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:06<00:07, 27.27it/s]

Chain 8:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:09<00:02, 46.88it/s]

Chain 9:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:06<00:07, 27.30it/s]

Chain 8:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:09<00:02, 48.81it/s]

Chain 9:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:06<00:07, 27.09it/s]

Chain 8:  73%|██████████████████████████████████████████████████████████████████████████▌                           | 263/360 [00:09<00:01, 50.47it/s]

Chain 9:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:06<00:07, 27.81it/s]

Chain 8:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:09<00:01, 53.55it/s]

Chain 9:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:06, 29.11it/s]

Chain 8:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:10<00:01, 55.00it/s]

Chain 9:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:07<00:06, 29.81it/s]

Chain 8:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:10<00:01, 58.04it/s]

Chain 9:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:07<00:06, 30.66it/s]

Chain 8:  81%|██████████████████████████████████████████████████████████████████████████████████▍                   | 291/360 [00:10<00:01, 62.12it/s]

Chain 9:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:06, 31.28it/s]

Chain 8:  83%|████████████████████████████████████████████████████████████████████████████████████▋                 | 299/360 [00:10<00:00, 65.25it/s]

Chain 8:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:10<00:00, 73.49it/s]

Chain 9:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:07<00:05, 31.89it/s]

Chain 8:  89%|██████████████████████████████████████████████████████████████████████████████████████████▍           | 319/360 [00:10<00:00, 79.73it/s]

Chain 9:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:05, 31.62it/s]

Chain 8:  92%|██████████████████████████████████████████████████████████████████████████████████████████████        | 332/360 [00:10<00:00, 93.11it/s]

Chain 9:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:05, 32.19it/s]

Chain 8:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████▍  | 351/360 [00:10<00:00, 119.82it/s]

Chain 9:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:07<00:05, 32.76it/s]

Chain 9:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:07<00:04, 33.76it/s]

Chain 9:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:07<00:04, 34.46it/s]

Chain 9:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:08<00:04, 35.42it/s]

Chain 9:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:08<00:04, 36.57it/s]

Chain 9:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:08<00:04, 36.59it/s]

Chain 9:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:08<00:03, 37.00it/s]

Chain 9:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:08<00:03, 38.58it/s]

Chain 9:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:08<00:03, 38.88it/s]

Chain 9:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:08<00:03, 39.95it/s]

Chain 9:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:08<00:03, 41.58it/s]

Chain 9:  66%|██████████████████████████████████████████████████████████████████▊                                   | 236/360 [00:08<00:02, 43.25it/s]

Chain 9:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:09<00:02, 45.08it/s]

Chain 9:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:09<00:02, 47.28it/s]

Chain 9:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:09<00:02, 47.81it/s]

Chain 9:  72%|█████████████████████████████████████████████████████████████████████████                             | 258/360 [00:09<00:02, 49.79it/s]

Chain 9:  73%|██████████████████████████████████████████████████████████████████████████▊                           | 264/360 [00:09<00:01, 52.17it/s]

Chain 9:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:09<00:01, 55.72it/s]

Chain 9:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:09<00:01, 58.31it/s]

Chain 9:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:09<00:01, 61.59it/s]

Chain 9:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:09<00:01, 66.00it/s]

Chain 9:  84%|█████████████████████████████████████████████████████████████████████████████████████▌                | 302/360 [00:10<00:00, 71.90it/s]

Chain 9:  87%|████████████████████████████████████████████████████████████████████████████████████████▋             | 313/360 [00:10<00:00, 81.14it/s]

Chain 9:  91%|████████████████████████████████████████████████████████████████████████████████████████████▎         | 326/360 [00:10<00:00, 94.96it/s]

Chain 9:  96%|████████████████████████████████████████████████████████████████████████████████████████████████▊    | 345/360 [00:10<00:00, 122.13it/s]

2026-05-28 21:02:31.247 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 21:02:31.858 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 21:02:38.203 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 21:02:38.925 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 21:02:38.926 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 21:02:38.932 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 21:02:40.144 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 21:02:40.189 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 21:02:40.847 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 21:02:41.915 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 21:02:43.048 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 21:02:43.268 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 21:02:43.268 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,81.6,138.1,234.1,374.4,531.6
GIIP (mscf),Total Volumes,1.0,33.2,57.0,102.0,170.9,261.8
Condensate (stb),Total Volumes,1.0,1.0,1.8,3.6,6.6,11.1
Solution Gas (mscf),Total Volumes,1.0,141.5,239.3,433.0,733.0,1128.4

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50   P10     P1
Total Oil EUR         1.0  18.1  31.1  53.7  87.8  129.1

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.93  0.5  1.8  5.6  14.9  32.1
Zone 2           0.57  0.7  2.5  7.0  18.1  38.3
Zone 3           0.95  0.7  1.8  4.7  11.0  22.3
Zone 4           0.43  1.0  2.8  7.4  18.1  37.0
Zone 5           0.53  1.1  3.0  8.8  21.9  48.2
Zone 6           0.69  1.0  3.1  9.3  25.3  60.8
Zone 7           0.53  0.6  1.7  5.3  13.0  25.6
Zone 8           0.50  0.5  1.7  5.4  14.5  33.5
Zone 9           0.53  0.7  2.1  5.9  15.3  33.4
Zone 10          0.93  0.8  2.5  7.8  21.8  47.0

In [14]:
reporter.tabler.npv_table()

     P(Commercial)    P99    P90    P50     P10      P1
NPV           0.94 -324.0  155.0  838.0  1642.0  2311.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)    P99    P90    P50     P10      P1
EMV           0.94 -309.0  140.0  782.0  1538.0  2166.0

In [16]:
from resgo.plotting.tables import npv_USD
import numpy as np
import pandas as pd

npv = npv_USD(
    simpack,
    nominal=True,
    discounted=True,
    success_only=False,
)
npv_usd = npv.to_numpy().ravel()
npv_df = pd.DataFrame({"npv_usd_mm": npv_usd / 1e6})

histogram = (
    alt.Chart(npv_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Nominal discounted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Project NPV Distribution",
    )
)

break_even = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(histogram, break_even)
fig.show()

alt.LayerChart(...)

In [17]:
BANKRUPTCY_THRESHOLD_USD = 300e6
LOSS_FLOOR_USD = -5e9

def loss_adjusted_npv_USD(
    npv_usd,
    bankruptcy_threshold_usd=BANKRUPTCY_THRESHOLD_USD,
    floor_usd=LOSS_FLOOR_USD,
):
    npv_usd = np.asarray(npv_usd)
    threshold = bankruptcy_threshold_usd

    with np.errstate(divide="ignore", invalid="ignore"):
        adjusted = np.where(
            npv_usd >= 0,
            npv_usd,
            (threshold * npv_usd) / (threshold + npv_usd),
        )

    adjusted = np.where(npv_usd <= -threshold, floor_usd, adjusted)
    return np.maximum(adjusted, floor_usd)

x_usd = np.linspace(-0.9999 * BANKRUPTCY_THRESHOLD_USD, 1.5e9, 1_000)
loss_function_df = pd.DataFrame(
    {
        "npv_usd_mm": x_usd / 1e6,
        "loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(x_usd) / 1e6,
    }
)

loss_function = (
    alt.Chart(loss_function_df)
    .mark_line(color="#FACC15", strokeWidth=3)
    .encode(
        x=alt.X("npv_usd_mm:Q", title="Nominal discounted NPV ($USD MM)"),
        y=alt.Y(
            "loss_adjusted_npv_usd_mm:Q",
            title="Loss-adjusted NPV ($USD MM)",
        ),
        tooltip=[
            alt.Tooltip("npv_usd_mm:Q", title="NPV ($MM)", format=",.0f"),
            alt.Tooltip(
                "loss_adjusted_npv_usd_mm:Q",
                title="Loss-adjusted NPV ($MM)",
                format=",.0f",
            ),
        ],
    )
    .properties(
        width=650,
        height=250,
        title="Company Loss Function",
    )
)

bankruptcy_threshold = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [-BANKRUPTCY_THRESHOLD_USD / 1e6]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(loss_function, bankruptcy_threshold)
fig.show()

alt.LayerChart(...)

In [18]:
loss_df = pd.DataFrame(
    {"loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(npv_usd) / 1e6}
)

loss_histogram = (
    alt.Chart(loss_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "loss_adjusted_npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Loss-adjusted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated Loss-Adjusted NPV Distribution",
    )
)

break_even_loss = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_histogram, break_even_loss)
fig.show()

alt.LayerChart(...)