In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

/tmp/ipykernel_75122/1985460196.py:25: DeprecationWarning:

`set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 42

CHAINS = 4
DRAWS = 500
N_RESERVOIRS = 6
N_PRODUCERS = 20

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=45e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=60e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2_000_000,
    producer_abandonment_cost_USD=500_000,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 17:13:50.807 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 17:13:50.811 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 17:13:50.815 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 17:13:50.819 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 17:13:50.823 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 17:13:50.826 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 17:13:50.830 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 17:13:50.830 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 17:13:51.014 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 17:13:51.014 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 17:13:51.014 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 17:13:51.014 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 17:13:51.015 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 17:13:51.015 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 17:13:51.015 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 17:13:51.015 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 17:13:51.015 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 17:13:51.015 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 17:13:51.015 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 17:13:51.016 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 17:13:51.016 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 17:13:51.016 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 17:13:51.016 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 17:13:51.016 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 17:13:51.016 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 17:13:51.016 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 17:13:51.016 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 17:13:51.017 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 17:13:51.017 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 17:13:51.030 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 17:13:51.036 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 17:13:51.298 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 17:13:51.298 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 17:13:51.299 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (20 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 123.60it/s]

Chain 0:   7%|███████▍                                                                                               | 26/360 [00:00<00:05, 66.33it/s]

Chain 0:  10%|██████████                                                                                             | 35/360 [00:00<00:05, 57.01it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:00<00:05, 53.46it/s]

Chain 0:  13%|█████████████▋                                                                                         | 48/360 [00:00<00:06, 50.17it/s]

Chain 0:  15%|███████████████▍                                                                                       | 54/360 [00:00<00:06, 48.86it/s]

Chain 0:  16%|████████████████▉                                                                                      | 59/360 [00:01<00:06, 47.99it/s]

Chain 0:  25%|█████████████████████████▍                                                                             | 89/360 [00:01<00:05, 45.70it/s]

Chain 0:  18%|██████████████████▎                                                                                    | 64/360 [00:01<00:06, 46.64it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  19%|███████████████████▋                                                                                   | 69/360 [00:01<00:06, 46.10it/s]

Chain 1:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 113.07it/s]

Chain 0:  21%|█████████████████████▏                                                                                 | 74/360 [00:01<00:06, 46.23it/s]

Chain 0:  22%|██████████████████████▌                                                                                | 79/360 [00:01<00:06, 46.40it/s]

Chain 0:  23%|████████████████████████                                                                               | 84/360 [00:01<00:06, 45.67it/s]

Chain 1:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 58.74it/s]

Chain 0:  26%|██████████████████████████▉                                                                            | 94/360 [00:01<00:05, 46.33it/s]

Chain 1:   9%|█████████▍                                                                                             | 33/360 [00:00<00:06, 52.60it/s]

Chain 0:  28%|████████████████████████████▎                                                                          | 99/360 [00:01<00:05, 46.56it/s]

Chain 1:  11%|███████████▏                                                                                           | 39/360 [00:00<00:06, 50.09it/s]

Chain 0:  29%|█████████████████████████████▍                                                                        | 104/360 [00:02<00:05, 46.61it/s]

Chain 1:  12%|████████████▉                                                                                          | 45/360 [00:00<00:06, 47.02it/s]

Chain 0:  30%|██████████████████████████████▉                                                                       | 109/360 [00:02<00:05, 46.71it/s]

Chain 1:  14%|██████████████▎                                                                                        | 50/360 [00:00<00:06, 45.80it/s]

Chain 0:  32%|████████████████████████████████▎                                                                     | 114/360 [00:02<00:05, 47.39it/s]

Chain 0:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:02<00:05, 47.90it/s]

Chain 1:  15%|███████████████▋                                                                                       | 55/360 [00:01<00:06, 45.19it/s]

Chain 0:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:02<00:04, 48.13it/s]

Chain 1:  17%|█████████████████▏                                                                                     | 60/360 [00:01<00:06, 44.46it/s]

Chain 0:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:02<00:04, 49.17it/s]

Chain 1:  18%|██████████████████▌                                                                                    | 65/360 [00:01<00:06, 43.41it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:02<00:04, 49.68it/s]

Chain 1:  19%|████████████████████                                                                                   | 70/360 [00:01<00:06, 43.17it/s]

Chain 2:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 109.95it/s]

Chain 0:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:02<00:04, 50.20it/s]

Chain 1:  21%|█████████████████████▍                                                                                 | 75/360 [00:01<00:06, 42.95it/s]

Chain 0:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:02<00:04, 51.42it/s]

Chain 1:  22%|██████████████████████▉                                                                                | 80/360 [00:01<00:06, 42.90it/s]

Chain 2:   7%|██████▊                                                                                                | 24/360 [00:00<00:05, 59.60it/s]

Chain 0:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:03<00:03, 52.56it/s]

Chain 1:  24%|████████████████████████▎                                                                              | 85/360 [00:01<00:06, 42.84it/s]

Chain 0:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:03<00:03, 53.43it/s]

Chain 1:  25%|█████████████████████████▊                                                                             | 90/360 [00:01<00:06, 43.30it/s]

Chain 2:   9%|█████████▏                                                                                             | 32/360 [00:00<00:06, 51.07it/s]

Chain 0:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:03<00:03, 55.98it/s]

Chain 1:  26%|███████████████████████████▏                                                                           | 95/360 [00:02<00:06, 44.17it/s]

Chain 2:  11%|██████████▊                                                                                            | 38/360 [00:00<00:06, 47.48it/s]

Chain 0:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:03<00:03, 58.39it/s]

Chain 1:  28%|████████████████████████████▎                                                                         | 100/360 [00:02<00:05, 44.60it/s]

Chain 0:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:03<00:02, 60.27it/s]

Chain 2:  12%|████████████▌                                                                                          | 44/360 [00:00<00:06, 45.41it/s]

Chain 1:  29%|█████████████████████████████▊                                                                        | 105/360 [00:02<00:05, 44.86it/s]

Chain 0:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:03<00:02, 62.24it/s]

Chain 2:  14%|██████████████                                                                                         | 49/360 [00:00<00:07, 43.56it/s]

Chain 1:  31%|███████████████████████████████▏                                                                      | 110/360 [00:02<00:05, 45.29it/s]

Chain 0:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:03<00:02, 64.12it/s]

Chain 1:  32%|████████████████████████████████▌                                                                     | 115/360 [00:02<00:05, 45.86it/s]

Chain 2:  15%|███████████████▍                                                                                       | 54/360 [00:01<00:07, 43.35it/s]

Chain 0:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:03<00:02, 67.81it/s]

Chain 1:  33%|██████████████████████████████████                                                                    | 120/360 [00:02<00:05, 45.79it/s]

Chain 2:  16%|████████████████▉                                                                                      | 59/360 [00:01<00:07, 42.79it/s]

Chain 0:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:03<00:02, 71.23it/s]

Chain 1:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:02<00:05, 46.06it/s]

Chain 2:  18%|██████████████████▎                                                                                    | 64/360 [00:01<00:07, 42.19it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:04<00:01, 74.25it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:02<00:04, 46.47it/s]

Chain 0:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:04<00:01, 76.50it/s]

Chain 2:  19%|███████████████████▋                                                                                   | 69/360 [00:01<00:07, 41.54it/s]

Chain 1:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:02<00:04, 47.38it/s]

Chain 3:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 108.87it/s]

Chain 0:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:04<00:01, 80.17it/s]

Chain 2:  21%|█████████████████████▏                                                                                 | 74/360 [00:01<00:06, 42.05it/s]

Chain 1:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:02<00:04, 47.65it/s]

Chain 0:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:04<00:01, 86.82it/s]

Chain 2:  22%|██████████████████████▌                                                                                | 79/360 [00:01<00:06, 42.74it/s]

Chain 1:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:03<00:04, 48.83it/s]

Chain 3:   7%|██████▊                                                                                                | 24/360 [00:00<00:05, 61.55it/s]

Chain 0:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:04<00:01, 93.11it/s]

Chain 2:  23%|████████████████████████                                                                               | 84/360 [00:01<00:06, 42.78it/s]

Chain 1:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:03<00:04, 49.09it/s]

Chain 0:  76%|████████████████████████████████████████████████████████████████████████████▎                        | 272/360 [00:04<00:00, 100.87it/s]

Chain 2:  25%|█████████████████████████▍                                                                             | 89/360 [00:01<00:06, 43.44it/s]

Chain 1:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:03<00:04, 50.19it/s]

Chain 3:   9%|█████████▏                                                                                             | 32/360 [00:00<00:06, 51.07it/s]

Chain 0:  79%|████████████████████████████████████████████████████████████████████████████████▏                    | 286/360 [00:04<00:00, 109.93it/s]

Chain 2:  26%|██████████████████████████▉                                                                            | 94/360 [00:02<00:06, 43.46it/s]

Chain 1:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:03<00:03, 51.09it/s]

Chain 0:  84%|████████████████████████████████████████████████████████████████████████████████████▋                | 302/360 [00:04<00:00, 124.03it/s]

Chain 3:  11%|██████████▊                                                                                            | 38/360 [00:00<00:06, 48.00it/s]

Chain 2:  28%|████████████████████████████▎                                                                          | 99/360 [00:02<00:06, 43.41it/s]

Chain 1:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:03<00:03, 54.14it/s]

Chain 0:  89%|██████████████████████████████████████████████████████████████████████████████████████████▎          | 322/360 [00:04<00:00, 146.26it/s]

Chain 2:  29%|█████████████████████████████▍                                                                        | 104/360 [00:02<00:05, 43.82it/s]

Chain 3:  12%|████████████▌                                                                                          | 44/360 [00:00<00:06, 45.60it/s]

Chain 1:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:03<00:03, 55.68it/s]

Chain 0:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████▍| 358/360 [00:04<00:00, 208.43it/s]

Chain 2:  30%|██████████████████████████████▉                                                                       | 109/360 [00:02<00:05, 44.49it/s]

Chain 1:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:03<00:03, 58.74it/s]

Chain 3:  14%|██████████████                                                                                         | 49/360 [00:00<00:07, 43.82it/s]

Chain 2:  32%|████████████████████████████████▎                                                                     | 114/360 [00:02<00:05, 44.40it/s]

Chain 1:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:03<00:02, 61.17it/s]

Chain 3:  15%|███████████████▍                                                                                       | 54/360 [00:01<00:07, 42.12it/s]

Chain 2:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:02<00:05, 44.33it/s]

Chain 1:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:03<00:02, 61.97it/s]

Chain 3:  16%|████████████████▉                                                                                      | 59/360 [00:01<00:07, 41.81it/s]

Chain 2:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:02<00:05, 44.82it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:04<00:02, 64.98it/s]

Chain 3:  18%|██████████████████▎                                                                                    | 64/360 [00:01<00:07, 41.07it/s]

Chain 2:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:02<00:05, 46.12it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:04<00:02, 68.33it/s]

Chain 3:  19%|███████████████████▋                                                                                   | 69/360 [00:01<00:07, 41.41it/s]

Chain 2:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:02<00:04, 46.71it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:04<00:01, 70.35it/s]

Chain 3:  21%|█████████████████████▏                                                                                 | 74/360 [00:01<00:06, 41.39it/s]

Chain 2:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:03<00:04, 46.77it/s]

Chain 1:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:04<00:01, 74.04it/s]

Chain 2:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:03<00:04, 47.64it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:04<00:01, 78.21it/s]

Chain 3:  22%|██████████████████████▌                                                                                | 79/360 [00:01<00:06, 40.70it/s]

Chain 2:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:03<00:04, 49.41it/s]

Chain 1:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:04<00:01, 84.72it/s]

Chain 3:  23%|████████████████████████                                                                               | 84/360 [00:01<00:06, 40.85it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:04<00:01, 91.39it/s]

Chain 2:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:03<00:04, 50.16it/s]

Chain 3:  25%|█████████████████████████▍                                                                             | 89/360 [00:01<00:06, 41.32it/s]

Chain 1:  76%|████████████████████████████████████████████████████████████████████████████▊                        | 274/360 [00:04<00:00, 100.92it/s]

Chain 2:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:03<00:03, 51.54it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:02<00:06, 41.24it/s]

Chain 1:  80%|████████████████████████████████████████████████████████████████████████████████▌                    | 287/360 [00:04<00:00, 107.73it/s]

Chain 2:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:03<00:03, 53.30it/s]

Chain 3:  28%|████████████████████████████▎                                                                          | 99/360 [00:02<00:06, 41.99it/s]

Chain 1:  84%|█████████████████████████████████████████████████████████████████████████████████████                | 303/360 [00:05<00:00, 122.59it/s]

Chain 2:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:03<00:03, 55.25it/s]

Chain 3:  29%|█████████████████████████████▍                                                                        | 104/360 [00:02<00:05, 42.76it/s]

Chain 1:  90%|██████████████████████████████████████████████████████████████████████████████████████████▉          | 324/360 [00:05<00:00, 147.40it/s]

Chain 2:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:03<00:03, 58.14it/s]

Chain 3:  30%|██████████████████████████████▉                                                                       | 109/360 [00:02<00:05, 43.83it/s]

Chain 2:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:03<00:02, 61.46it/s]

Chain 3:  32%|████████████████████████████████▎                                                                     | 114/360 [00:02<00:05, 44.97it/s]

Chain 2:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:04<00:02, 64.73it/s]

Chain 3:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:02<00:05, 45.70it/s]

Chain 2:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:04<00:02, 65.90it/s]

Chain 3:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:02<00:05, 44.17it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:04<00:02, 68.90it/s]

Chain 3:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:02<00:05, 45.75it/s]

Chain 2:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:04<00:01, 73.52it/s]

Chain 3:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:02<00:04, 47.72it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:04<00:01, 78.95it/s]

Chain 3:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:03<00:04, 49.34it/s]

Chain 2:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:04<00:01, 84.40it/s]

Chain 3:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:03<00:04, 51.19it/s]

Chain 2:  70%|███████████████████████████████████████████████████████████████████████▋                              | 253/360 [00:04<00:01, 93.49it/s]

Chain 3:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:03<00:03, 52.99it/s]

Chain 2:  74%|██████████████████████████████████████████████████████████████████████████▋                          | 266/360 [00:04<00:00, 102.13it/s]

Chain 3:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:03<00:03, 53.64it/s]

Chain 2:  78%|██████████████████████████████████████████████████████████████████████████████▎                      | 279/360 [00:04<00:00, 109.93it/s]

Chain 3:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:03<00:03, 56.69it/s]

Chain 2:  82%|██████████████████████████████████████████████████████████████████████████████████▍                  | 294/360 [00:04<00:00, 120.72it/s]

Chain 3:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:03<00:03, 58.26it/s]

Chain 2:  87%|███████████████████████████████████████████████████████████████████████████████████████▊             | 313/360 [00:05<00:00, 139.68it/s]

Chain 2:  95%|███████████████████████████████████████████████████████████████████████████████████████████████▋     | 341/360 [00:05<00:00, 180.60it/s]

Chain 3:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:03<00:03, 59.89it/s]

Chain 3:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:03<00:02, 63.78it/s]

Chain 3:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:03<00:02, 66.34it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:04<00:02, 71.55it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:04<00:01, 76.18it/s]

Chain 3:  62%|███████████████████████████████████████████████████████████████▍                                      | 224/360 [00:04<00:01, 82.06it/s]

Chain 3:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:04<00:01, 89.03it/s]

Chain 3:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:04<00:01, 97.66it/s]

Chain 3:  72%|█████████████████████████████████████████████████████████████████████████▏                           | 261/360 [00:04<00:00, 108.00it/s]

Chain 3:  76%|████████████████████████████████████████████████████████████████████████████▊                        | 274/360 [00:04<00:00, 112.88it/s]

Chain 3:  80%|█████████████████████████████████████████████████████████████████████████████████                    | 289/360 [00:04<00:00, 122.84it/s]

Chain 3:  86%|██████████████████████████████████████████████████████████████████████████████████████▍              | 308/360 [00:04<00:00, 141.15it/s]

Chain 3:  94%|██████████████████████████████████████████████████████████████████████████████████████████████▌      | 337/360 [00:05<00:00, 183.48it/s]

2026-05-28 17:14:03.564 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 17:14:03.696 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 17:14:05.785 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 17:14:06.146 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 17:14:06.147 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 17:14:06.151 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 17:14:06.426 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 17:14:06.439 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 17:14:06.591 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 17:14:06.803 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 17:14:07.039 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 17:14:07.119 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 17:14:07.119 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
print(prospect.model_dump())

{'name': 'Demo Prospect', 'volumetric_model': {'reservoirs': [{'area_km2': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 1 - Area (km^2)', 'params': {'mu': 1.7868395090870686, 'sigma': 0.5607939994191797}}, 'zone': {'name': 'Zone 1', 'net_m': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 1 - Net (m)', 'params': {'mu': 2.0835263728023388, 'sigma': 0.08000060761674234}}, 'porosity': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 1 - Porosity', 'params': {'mu': -1.1558174642569816, 'sigma': 0.08571555919219949}}, 'water_saturation': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 1 - Water Saturation', 'params': {'mu': -0.6090787196589462, 'sigma': 0.22340523400962686}}, 'corr_matrix': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]}, 'gas': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 1 - Gas GOR (scf/stb)', 'params': {'mu': 10.361632918473205, 'sigma': 0.3574927285445493}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 1 - Bg', 'params': {'mu': -5.868034508142219, 'sigma': 0.2704328094146527}}, 'corr': 0.8}, 'oil': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 1 - Oil GOR (scf/stb)', 'params': {'mu': 7.457061423316191, 'sigma': 0.4286258618868955}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 1 - Bo', 'params': {'mu': 0.2223429106307228, 'sigma': 0.031228828330259972}}, 'corr': 0.8}, 'gas_type_curve': {'type_curve_type': <TypeCurveType.GAS: 'gas'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.GAS_RATE: 'Gas Rate (mscf/day)'>, 'params': {'mu': 9.759646516310237, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.42364893019360184, 'sigma': 0.3305750167091954}}}, 'oil_type_curve': {'type_curve_type': <TypeCurveType.OIL: 'oil'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.OIL_RATE: 'Oil Rate (stb/day)'>, 'params': {'mu': 8.150208603876138, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.8958797346140275, 'sigma': 0.3826725663570623}}}, 'gas_cap_fraction': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 1 - Gas Cap Fraction', 'params': {'mu': -1.791759469228055, 'sigma': 0.316386104944486}}, 'risk_profile': {'p_reservoir': 0.8, 'p_seal': 1.0, 'p_closure': 1.0, 'p_charge': 1.0}}, {'area_km2': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 2 - Area (km^2)', 'params': {'mu': 1.6924865721425633, 'sigma': 0.7125438569095064}}, 'zone': {'name': 'Zone 2', 'net_m': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 2 - Net (m)', 'params': {'mu': 2.2346992858269723, 'sigma': 0.24681579280123273}}, 'porosity': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 2 - Porosity', 'params': {'mu': -1.1558174642569816, 'sigma': 0.08571555919219949}}, 'water_saturation': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 2 - Water Saturation', 'params': {'mu': -0.6336175005519511, 'sigma': 0.24255294648000028}}, 'corr_matrix': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]}, 'gas': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 2 - Gas GOR (scf/stb)', 'params': {'mu': 10.361632918473205, 'sigma': 0.3574927285445493}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 2 - Bg', 'params': {'mu': -5.868034508142219, 'sigma': 0.2704328094146527}}, 'corr': 0.8}, 'oil': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 2 - Oil GOR (scf/stb)', 'params': {'mu': 7.457061423316191, 'sigma': 0.4286258618868955}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 2 - Bo', 'params': {'mu': 0.2223429106307228, 'sigma': 0.031228828330259972}}, 'corr': 0.8}, 'gas_type_curve': {'type_curve_type': <TypeCurveType.GAS: 'gas'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.GAS_RATE: 'Gas Rate (mscf/day)'>, 'params': {'mu': 9.759646516310237, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.42364893019360184, 'sigma': 0.3305750167091954}}}, 'oil_type_curve': {'type_curve_type': <TypeCurveType.OIL: 'oil'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.OIL_RATE: 'Oil Rate (stb/day)'>, 'params': {'mu': 8.150208603876138, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.8958797346140275, 'sigma': 0.3826725663570623}}}, 'gas_cap_fraction': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 2 - Gas Cap Fraction', 'params': {'mu': -1.791759469228055, 'sigma': 0.316386104944486}}, 'risk_profile': {'p_reservoir': 0.96, 'p_seal': 1.0, 'p_closure': 1.0, 'p_charge': 1.0}}, {'area_km2': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 3 - Area (km^2)', 'params': {'mu': 1.7259927742471302, 'sigma': 0.5717608412623378}}, 'zone': {'name': 'Zone 3', 'net_m': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 3 - Net (m)', 'params': {'mu': 2.0984972036649054, 'sigma': 0.3555256982195237}}, 'porosity': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 3 - Porosity', 'params': {'mu': -1.1854469849631433, 'sigma': 0.10883559704535466}}, 'water_saturation': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 3 - Water Saturation', 'params': {'mu': -0.8325038817944556, 'sigma': 0.16656736968482372}}, 'corr_matrix': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]}, 'gas': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 3 - Gas GOR (scf/stb)', 'params': {'mu': 10.361632918473205, 'sigma': 0.3574927285445493}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 3 - Bg', 'params': {'mu': -5.868034508142219, 'sigma': 0.2704328094146527}}, 'corr': 0.8}, 'oil': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 3 - Oil GOR (scf/stb)', 'params': {'mu': 7.457061423316191, 'sigma': 0.4286258618868955}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 3 - Bo', 'params': {'mu': 0.2223429106307228, 'sigma': 0.031228828330259972}}, 'corr': 0.8}, 'gas_type_curve': {'type_curve_type': <TypeCurveType.GAS: 'gas'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.GAS_RATE: 'Gas Rate (mscf/day)'>, 'params': {'mu': 9.759646516310237, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.42364893019360184, 'sigma': 0.3305750167091954}}}, 'oil_type_curve': {'type_curve_type': <TypeCurveType.OIL: 'oil'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.OIL_RATE: 'Oil Rate (stb/day)'>, 'params': {'mu': 8.150208603876138, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.8958797346140275, 'sigma': 0.3826725663570623}}}, 'gas_cap_fraction': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 3 - Gas Cap Fraction', 'params': {'mu': -1.791759469228055, 'sigma': 0.316386104944486}}, 'risk_profile': {'p_reservoir': 0.41, 'p_seal': 1.0, 'p_closure': 1.0, 'p_charge': 1.0}}, {'area_km2': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 4 - Area (km^2)', 'params': {'mu': 1.509030559518527, 'sigma': 0.5141265071678357}}, 'zone': {'name': 'Zone 4', 'net_m': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 4 - Net (m)', 'params': {'mu': 2.1356131751328453, 'sigma': 0.3592422923420161}}, 'porosity': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 4 - Porosity', 'params': {'mu': -1.1558174642569816, 'sigma': 0.08571555919219949}}, 'water_saturation': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 4 - Water Saturation', 'params': {'mu': -0.5480273712584962, 'sigma': 0.2710438542898073}}, 'corr_matrix': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]}, 'gas': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 4 - Gas GOR (scf/stb)', 'params': {'mu': 10.361632918473205, 'sigma': 0.3574927285445493}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 4 - Bg', 'params': {'mu': -5.868034508142219, 'sigma': 0.2704328094146527}}, 'corr': 0.8}, 'oil': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 4 - Oil GOR (scf/stb)', 'params': {'mu': 7.457061423316191, 'sigma': 0.4286258618868955}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 4 - Bo', 'params': {'mu': 0.2223429106307228, 'sigma': 0.031228828330259972}}, 'corr': 0.8}, 'gas_type_curve': {'type_curve_type': <TypeCurveType.GAS: 'gas'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.GAS_RATE: 'Gas Rate (mscf/day)'>, 'params': {'mu': 9.759646516310237, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.42364893019360184, 'sigma': 0.3305750167091954}}}, 'oil_type_curve': {'type_curve_type': <TypeCurveType.OIL: 'oil'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.OIL_RATE: 'Oil Rate (stb/day)'>, 'params': {'mu': 8.150208603876138, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.8958797346140275, 'sigma': 0.3826725663570623}}}, 'gas_cap_fraction': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 4 - Gas Cap Fraction', 'params': {'mu': -1.791759469228055, 'sigma': 0.316386104944486}}, 'risk_profile': {'p_reservoir': 0.4, 'p_seal': 1.0, 'p_closure': 1.0, 'p_charge': 1.0}}, {'area_km2': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 5 - Area (km^2)', 'params': {'mu': 1.5243544501711186, 'sigma': 0.6142479205351986}}, 'zone': {'name': 'Zone 5', 'net_m': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 5 - Net (m)', 'params': {'mu': 1.9916841538893193, 'sigma': 0.1638443790793046}}, 'porosity': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 5 - Porosity', 'params': {'mu': -1.1821393309996928, 'sigma': 0.06517649744049736}}, 'water_saturation': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 5 - Water Saturation', 'params': {'mu': -0.7466403866131762, 'sigma': 0.23356701097104174}}, 'corr_matrix': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]}, 'gas': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 5 - Gas GOR (scf/stb)', 'params': {'mu': 10.361632918473205, 'sigma': 0.3574927285445493}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 5 - Bg', 'params': {'mu': -5.868034508142219, 'sigma': 0.2704328094146527}}, 'corr': 0.8}, 'oil': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 5 - Oil GOR (scf/stb)', 'params': {'mu': 7.457061423316191, 'sigma': 0.4286258618868955}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 5 - Bo', 'params': {'mu': 0.2223429106307228, 'sigma': 0.031228828330259972}}, 'corr': 0.8}, 'gas_type_curve': {'type_curve_type': <TypeCurveType.GAS: 'gas'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.GAS_RATE: 'Gas Rate (mscf/day)'>, 'params': {'mu': 9.759646516310237, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.42364893019360184, 'sigma': 0.3305750167091954}}}, 'oil_type_curve': {'type_curve_type': <TypeCurveType.OIL: 'oil'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.OIL_RATE: 'Oil Rate (stb/day)'>, 'params': {'mu': 8.150208603876138, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.8958797346140275, 'sigma': 0.3826725663570623}}}, 'gas_cap_fraction': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 5 - Gas Cap Fraction', 'params': {'mu': -1.791759469228055, 'sigma': 0.316386104944486}}, 'risk_profile': {'p_reservoir': 0.85, 'p_seal': 1.0, 'p_closure': 1.0, 'p_charge': 1.0}}, {'area_km2': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 6 - Area (km^2)', 'params': {'mu': 1.6829819544452445, 'sigma': 0.6399211872131758}}, 'zone': {'name': 'Zone 6', 'net_m': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 6 - Net (m)', 'params': {'mu': 2.2085291487666487, 'sigma': 0.32131530958144944}}, 'porosity': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 6 - Porosity', 'params': {'mu': -1.0993240325605367, 'sigma': 0.041633500213606574}}, 'water_saturation': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 6 - Water Saturation', 'params': {'mu': -0.6843709737228694, 'sigma': 0.28215609202284103}}, 'corr_matrix': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]}, 'gas': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 6 - Gas GOR (scf/stb)', 'params': {'mu': 10.361632918473205, 'sigma': 0.3574927285445493}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 6 - Bg', 'params': {'mu': -5.868034508142219, 'sigma': 0.2704328094146527}}, 'corr': 0.8}, 'oil': {'gor_scf_stb': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 6 - Oil GOR (scf/stb)', 'params': {'mu': 7.457061423316191, 'sigma': 0.4286258618868955}}, 'formation_volume_factor': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': 'Zone 6 - Bo', 'params': {'mu': 0.2223429106307228, 'sigma': 0.031228828330259972}}, 'corr': 0.8}, 'gas_type_curve': {'type_curve_type': <TypeCurveType.GAS: 'gas'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.GAS_RATE: 'Gas Rate (mscf/day)'>, 'params': {'mu': 9.759646516310237, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.42364893019360184, 'sigma': 0.3305750167091954}}}, 'oil_type_curve': {'type_curve_type': <TypeCurveType.OIL: 'oil'>, 'initial_rate': {'dist_type': <UvContinuousType.LOGNORMAL: 'lognormal'>, 'name': <PSV.OIL_RATE: 'Oil Rate (stb/day)'>, 'params': {'mu': 8.150208603876138, 'sigma': 0.4286258618868955}}, 'oil_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.OIL_RF: 'Oil Recovery Factor'>, 'params': {'mu': -1.1167961107535471, 'sigma': 0.21029060212010986}}, 'gas_recovery_factor': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': <PSV.GAS_RF: 'Gas Recovery Factor'>, 'params': {'mu': -0.8958797346140275, 'sigma': 0.3826725663570623}}}, 'gas_cap_fraction': {'dist_type': <UvContinuousType.LOGITNORMAL: 'logitnormal'>, 'name': 'Zone 6 - Gas Cap Fraction', 'params': {'mu': -1.791759469228055, 'sigma': 0.316386104944486}}, 'risk_profile': {'p_reservoir': 0.87, 'p_seal': 1.0, 'p_closure': 1.0, 'p_charge': 1.0}}], 'dependency': 0.4}, 'field_development_model': {'producers': [{'name': 'Oil 1', 'producer_type': <ProducerType.OIL: 'oil'>, 'reservoir_names': None, 'capex_USD': 45000000.0, 'drill_date': datetime.datetime(2027, 1, 1, 0, 0), 'online_date': datetime.datetime(2027, 9, 28, 0, 0)}, {'name': 'Oil 2', 'producer_type': <ProducerType.OIL: 'oil'>, 'reservoir_names': None, 'capex_USD': 45000000.0, 'drill_date': datetime.datetime(2027, 12, 27, 0, 0), 'online_date': datetime.datetime(2028, 9, 22, 0, 0)}, {'name': 'Oil 3', 'producer_type': <ProducerType.OIL: 'oil'>, 'reservoir_names': None, 'capex_USD': 45000000.0, 'drill_date': datetime.datetime(2028, 12, 21, 0, 0), 'online_date': datetime.datetime(2029, 9, 17, 0, 0)}, {'name': 'Oil 4', 'producer_type': <ProducerType.OIL: 'oil'>, 'reservoir_names': None, 'capex_USD': 45000000.0, 'drill_date': datetime.datetime(2029, 12, 16, 0, 0), 'online_date': datetime.datetime(2030, 9, 12, 0, 0)}, {'name': 'Oil 5', 'producer_type': <ProducerType.OIL: 'oil'>, 'reservoir_names': None, 'capex_USD': 45000000.0, 'drill_date': datetime.datetime(2030, 12, 11, 0, 0), 'online_date': datetime.datetime(2031, 9, 7, 0, 0)}, {'name': 'Oil 6', 'producer_type': <ProducerType.OIL: 'oil'>, 'reservoir_names': None, 

In [8]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [10]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [12]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,39.2,82.5,155.0,261.0,392.3
GIIP (mscf),Total Volumes,1.0,15.3,34.0,66.0,121.5,192.4
Condensate (stb),Total Volumes,1.0,0.4,1.1,2.3,4.6,8.8
Solution Gas (mscf),Total Volumes,1.0,63.8,141.0,279.8,508.0,798.8

In [13]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)  P99   P90   P50   P10    P1
Total Oil EUR         1.0  8.7  18.5  36.0  63.3  97.3

In [14]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.79  1.4  3.1  7.2  16.3  29.6
Zone 2           0.96  0.9  2.5  8.2  24.0  53.1
Zone 3           0.41  1.2  2.6  7.3  18.4  34.3
Zone 4           0.42  0.7  1.9  5.4  12.9  28.4
Zone 5           0.84  0.7  1.8  5.0  12.8  29.0
Zone 6           0.88  0.8  2.6  7.8  20.9  51.6

In [15]:
reporter.tabler.npv_table()

     P(Commercial)    P99   P90    P50     P10      P1
NPV           0.89 -423.0 -20.0  577.0  1312.0  2001.0

In [16]:
reporter.tabler.emv_table()

     P(Commercial)    P99   P90    P50     P10      P1
EMV           0.89 -381.0 -23.0  508.0  1162.0  1775.0