In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_4093804/1985460196.py:25: DeprecationWarning:

`set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 2

CHAINS = 4
DRAWS = 500
N_RESERVOIRS = 6
N_PRODUCERS = 20

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=45e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=60e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2_000_000,
    producer_abandonment_cost_USD=500_000,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 15:29:35.365 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 15:29:35.369 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 15:29:35.373 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 15:29:35.376 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 15:29:35.380 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 15:29:35.384 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 15:29:35.388 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 15:29:35.388 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 15:29:35.571 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 15:29:35.572 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 15:29:35.572 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 15:29:35.573 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 15:29:35.573 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 15:29:35.573 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 15:29:35.573 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 15:29:35.573 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 15:29:35.574 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 15:29:35.574 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 15:29:35.574 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 15:29:35.574 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 15:29:35.574 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 15:29:35.574 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 15:29:35.574 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 15:29:35.574 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 15:29:35.575 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 15:29:35.575 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 15:29:35.575 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 15:29:35.575 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 15:29:35.575 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 15:29:35.587 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 15:29:35.594 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 15:29:35.879 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 15:29:35.880 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 15:29:35.880 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (20 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 122.41it/s]

Chain 0:   7%|███████▍                                                                                               | 26/360 [00:00<00:04, 67.07it/s]

Chain 0:  10%|██████████                                                                                             | 35/360 [00:00<00:05, 59.05it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:00<00:05, 54.69it/s]

Chain 0:  13%|█████████████▋                                                                                         | 48/360 [00:00<00:05, 52.55it/s]

Chain 0:  15%|███████████████▍                                                                                       | 54/360 [00:00<00:06, 50.61it/s]

Chain 0:  17%|█████████████████▏                                                                                     | 60/360 [00:01<00:06, 49.07it/s]

Chain 0:  18%|██████████████████▌                                                                                    | 65/360 [00:01<00:06, 48.72it/s]

Chain 0:  19%|████████████████████                                                                                   | 70/360 [00:01<00:06, 47.30it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  21%|█████████████████████▍                                                                                 | 75/360 [00:01<00:06, 46.82it/s]

Chain 1:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 117.97it/s]

Chain 0:  22%|██████████████████████▉                                                                                | 80/360 [00:01<00:05, 46.80it/s]

Chain 0:  24%|████████████████████████▎                                                                              | 85/360 [00:01<00:05, 46.74it/s]

Chain 1:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 64.99it/s]

Chain 0:  25%|█████████████████████████▊                                                                             | 90/360 [00:01<00:05, 47.03it/s]

Chain 0:  26%|███████████████████████████▏                                                                           | 95/360 [00:01<00:05, 46.97it/s]

Chain 1:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 58.40it/s]

Chain 0:  28%|████████████████████████████▎                                                                         | 100/360 [00:01<00:05, 47.18it/s]

Chain 1:  11%|███████████▍                                                                                           | 40/360 [00:00<00:05, 54.10it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:02<00:05, 47.92it/s]

Chain 1:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 51.68it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:02<00:05, 49.00it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:02<00:04, 49.76it/s]

Chain 1:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:06, 49.89it/s]

Chain 0:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:02<00:04, 49.82it/s]

Chain 1:  16%|████████████████▌                                                                                      | 58/360 [00:01<00:06, 48.63it/s]

Chain 0:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:02<00:04, 49.86it/s]

Chain 1:  18%|██████████████████                                                                                     | 63/360 [00:01<00:06, 47.70it/s]

Chain 0:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:02<00:04, 50.55it/s]

Chain 1:  19%|███████████████████▍                                                                                   | 68/360 [00:01<00:06, 47.16it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:02<00:04, 51.60it/s]

Chain 1:  20%|████████████████████▉                                                                                  | 73/360 [00:01<00:06, 46.28it/s]

Chain 2:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 113.86it/s]

Chain 0:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:02<00:04, 51.82it/s]

Chain 1:  22%|██████████████████████▎                                                                                | 78/360 [00:01<00:06, 45.55it/s]

Chain 0:  42%|███████████████████████████████████████████                                                           | 152/360 [00:02<00:03, 52.85it/s]

Chain 1:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:06, 45.21it/s]

Chain 0:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:03<00:03, 53.77it/s]

Chain 2:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 62.03it/s]

Chain 1:  24%|█████████████████████████▏                                                                             | 88/360 [00:01<00:06, 44.75it/s]

Chain 0:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:03<00:03, 53.97it/s]

Chain 1:  26%|██████████████████████████▌                                                                            | 93/360 [00:01<00:06, 44.20it/s]

Chain 2:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 55.83it/s]

Chain 0:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:03<00:03, 55.43it/s]

Chain 1:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 44.32it/s]

Chain 0:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:03<00:03, 56.55it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:00<00:06, 52.36it/s]

Chain 1:  29%|█████████████████████████████▏                                                                        | 103/360 [00:02<00:05, 44.64it/s]

Chain 0:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:03<00:03, 57.35it/s]

Chain 2:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 50.64it/s]

Chain 1:  30%|██████████████████████████████▌                                                                       | 108/360 [00:02<00:05, 44.81it/s]

Chain 0:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:03<00:02, 59.46it/s]

Chain 1:  31%|████████████████████████████████                                                                      | 113/360 [00:02<00:05, 45.28it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:06, 48.92it/s]

Chain 0:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:03<00:02, 61.11it/s]

Chain 1:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:02<00:05, 45.53it/s]

Chain 2:  16%|████████████████▎                                                                                      | 57/360 [00:01<00:06, 47.99it/s]

Chain 0:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:03<00:02, 63.98it/s]

Chain 1:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:02<00:05, 45.61it/s]

Chain 2:  17%|█████████████████▋                                                                                     | 62/360 [00:01<00:06, 46.47it/s]

Chain 0:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:03<00:02, 66.21it/s]

Chain 1:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:02<00:05, 46.28it/s]

Chain 2:  19%|███████████████████▏                                                                                   | 67/360 [00:01<00:06, 45.73it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:04<00:02, 68.99it/s]

Chain 1:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:02<00:04, 47.17it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:  20%|████████████████████▌                                                                                  | 72/360 [00:01<00:06, 44.60it/s]

Chain 0:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:04<00:01, 73.05it/s]

Chain 1:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:02<00:04, 48.78it/s]

Chain 0:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:04<00:01, 77.27it/s]

Chain 3:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 110.99it/s]

Chain 2:  21%|██████████████████████                                                                                 | 77/360 [00:01<00:06, 44.00it/s]

Chain 1:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:02<00:04, 48.80it/s]

Chain 0:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:04<00:01, 80.80it/s]

Chain 2:  23%|███████████████████████▍                                                                               | 82/360 [00:01<00:06, 43.78it/s]

Chain 1:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:03<00:04, 49.61it/s]

Chain 0:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:04<00:01, 85.72it/s]

Chain 2:  24%|████████████████████████▉                                                                              | 87/360 [00:01<00:06, 43.51it/s]

Chain 3:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 61.70it/s]

Chain 1:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:03<00:04, 50.52it/s]

Chain 0:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:04<00:00, 92.69it/s]

Chain 2:  26%|██████████████████████████▎                                                                            | 92/360 [00:01<00:06, 43.35it/s]

Chain 1:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:03<00:03, 52.25it/s]

Chain 0:  78%|██████████████████████████████████████████████████████████████████████████████▊                      | 281/360 [00:04<00:00, 101.48it/s]

Chain 3:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 55.02it/s]

Chain 2:  27%|███████████████████████████▊                                                                           | 97/360 [00:01<00:05, 43.99it/s]

Chain 1:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:03<00:03, 53.49it/s]

Chain 0:  82%|███████████████████████████████████████████████████████████████████████████████████                  | 296/360 [00:04<00:00, 113.57it/s]

Chain 2:  28%|████████████████████████████▉                                                                         | 102/360 [00:02<00:05, 44.94it/s]

Chain 3:  11%|███████████▍                                                                                           | 40/360 [00:00<00:06, 51.87it/s]

Chain 1:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:03<00:03, 54.85it/s]

Chain 0:  87%|████████████████████████████████████████████████████████████████████████████████████████             | 314/360 [00:04<00:00, 130.72it/s]

Chain 2:  30%|██████████████████████████████▎                                                                       | 107/360 [00:02<00:05, 44.49it/s]

Chain 1:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:03<00:03, 55.50it/s]

Chain 0:  94%|██████████████████████████████████████████████████████████████████████████████████████████████▊      | 338/360 [00:04<00:00, 161.22it/s]

Chain 3:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 49.59it/s]

Chain 2:  31%|███████████████████████████████▋                                                                      | 112/360 [00:02<00:05, 45.74it/s]

Chain 1:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:03<00:03, 57.60it/s]

Chain 3:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:06, 48.01it/s]

Chain 2:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:02<00:05, 46.78it/s]

Chain 1:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:03<00:02, 59.77it/s]

Chain 3:  16%|████████████████▎                                                                                      | 57/360 [00:01<00:06, 46.28it/s]

Chain 2:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:02<00:05, 46.61it/s]

Chain 1:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:03<00:02, 59.75it/s]

Chain 2:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:02<00:05, 46.29it/s]

Chain 3:  17%|█████████████████▋                                                                                     | 62/360 [00:01<00:06, 44.35it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:04<00:02, 60.28it/s]

Chain 2:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:02<00:04, 46.34it/s]

Chain 3:  19%|███████████████████▏                                                                                   | 67/360 [00:01<00:06, 44.17it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:04<00:02, 62.64it/s]

Chain 2:  38%|███████████████████████████████████████                                                               | 138/360 [00:02<00:04, 48.25it/s]

Chain 3:  20%|████████████████████▌                                                                                  | 72/360 [00:01<00:06, 43.95it/s]

Chain 1:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:04<00:02, 66.17it/s]

Chain 2:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:02<00:04, 48.65it/s]

Chain 3:  21%|██████████████████████                                                                                 | 77/360 [00:01<00:06, 44.56it/s]

Chain 1:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:04<00:01, 69.45it/s]

Chain 2:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:03<00:04, 47.78it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:04<00:01, 72.04it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:01<00:06, 43.61it/s]

Chain 2:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:03<00:04, 50.13it/s]

Chain 1:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:04<00:01, 78.31it/s]

Chain 3:  24%|████████████████████████▉                                                                              | 87/360 [00:01<00:06, 44.19it/s]

Chain 2:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:03<00:03, 51.80it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████                             | 258/360 [00:04<00:01, 83.53it/s]

Chain 3:  26%|██████████████████████████▎                                                                            | 92/360 [00:01<00:06, 44.04it/s]

Chain 2:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:03<00:03, 52.49it/s]

Chain 1:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:04<00:01, 90.99it/s]

Chain 3:  27%|███████████████████████████▊                                                                           | 97/360 [00:02<00:05, 43.85it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████                      | 282/360 [00:04<00:00, 101.65it/s]

Chain 2:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:03<00:03, 53.25it/s]

Chain 3:  28%|████████████████████████████▉                                                                         | 102/360 [00:02<00:05, 44.38it/s]

Chain 1:  82%|███████████████████████████████████████████████████████████████████████████████████                  | 296/360 [00:04<00:00, 112.38it/s]

Chain 2:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:03<00:03, 54.13it/s]

Chain 3:  30%|██████████████████████████████▎                                                                       | 107/360 [00:02<00:05, 44.93it/s]

Chain 1:  87%|████████████████████████████████████████████████████████████████████████████████████████             | 314/360 [00:05<00:00, 130.69it/s]

Chain 2:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:03<00:03, 55.31it/s]

Chain 3:  31%|███████████████████████████████▋                                                                      | 112/360 [00:02<00:05, 45.31it/s]

Chain 1:  95%|███████████████████████████████████████████████████████████████████████████████████████████████▋     | 341/360 [00:05<00:00, 170.97it/s]

Chain 2:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:03<00:02, 57.94it/s]

Chain 3:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:02<00:05, 45.96it/s]

Chain 2:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:03<00:02, 60.31it/s]

Chain 3:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:02<00:05, 46.72it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:04<00:02, 62.83it/s]

Chain 3:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:02<00:04, 48.23it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:04<00:02, 65.55it/s]

Chain 3:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:02<00:04, 49.70it/s]

Chain 2:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:04<00:02, 68.71it/s]

Chain 3:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:02<00:04, 50.50it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:04<00:01, 72.73it/s]

Chain 3:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:03<00:04, 50.92it/s]

Chain 2:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:04<00:01, 78.22it/s]

Chain 3:  42%|███████████████████████████████████████████                                                           | 152/360 [00:03<00:03, 52.58it/s]

Chain 2:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:04<00:01, 84.36it/s]

Chain 3:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:03<00:03, 54.17it/s]

Chain 2:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:04<00:01, 90.81it/s]

Chain 3:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:03<00:03, 54.53it/s]

Chain 2:  76%|████████████████████████████████████████████████████████████████████████████▊                        | 274/360 [00:04<00:00, 100.60it/s]

Chain 3:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:03<00:03, 55.99it/s]

Chain 2:  80%|█████████████████████████████████████████████████████████████████████████████████                    | 289/360 [00:04<00:00, 113.76it/s]

Chain 3:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:03<00:03, 57.71it/s]

Chain 2:  85%|█████████████████████████████████████████████████████████████████████████████████████▊               | 306/360 [00:04<00:00, 129.59it/s]

Chain 3:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:03<00:02, 59.01it/s]

Chain 2:  92%|████████████████████████████████████████████████████████████████████████████████████████████▌        | 330/360 [00:05<00:00, 160.74it/s]

Chain 3:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:03<00:02, 61.76it/s]

Chain 3:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:03<00:02, 63.54it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:03<00:02, 66.42it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:04<00:02, 67.37it/s]

Chain 3:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:04<00:01, 70.00it/s]

Chain 3:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:04<00:01, 74.74it/s]

Chain 3:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:04<00:01, 78.90it/s]

Chain 3:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:04<00:01, 84.70it/s]

Chain 3:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:04<00:01, 91.34it/s]

Chain 3:  76%|████████████████████████████████████████████████████████████████████████████▊                        | 274/360 [00:04<00:00, 104.25it/s]

Chain 3:  81%|█████████████████████████████████████████████████████████████████████████████████▎                   | 290/360 [00:04<00:00, 119.31it/s]

Chain 3:  86%|██████████████████████████████████████████████████████████████████████████████████████▋              | 309/360 [00:04<00:00, 138.44it/s]

Chain 3:  94%|██████████████████████████████████████████████████████████████████████████████████████████████▌      | 337/360 [00:05<00:00, 178.63it/s]

2026-05-28 15:29:48.266 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 15:29:48.396 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 15:29:50.615 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 15:29:50.987 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 15:29:50.988 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 15:29:50.992 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 15:29:51.278 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 15:29:51.291 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 15:29:51.451 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 15:29:51.681 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 15:29:51.941 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 15:29:52.025 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 15:29:52.026 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,67.0,118.0,192.7,318.6,470.7
GIIP (mscf),Total Volumes,1.0,26.9,47.9,84.0,145.8,232.2
Condensate (stb),Total Volumes,1.0,0.8,1.5,2.9,5.7,10.0
Solution Gas (mscf),Total Volumes,1.0,117.2,202.1,359.0,621.5,1027.3

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50   P10     P1
Total Oil EUR         1.0  14.8  27.2  45.6  77.1  116.5

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.84  0.6  2.4  8.2  24.1  52.1
Zone 2           0.84  0.7  2.5  7.4  20.5  52.1
Zone 3           0.74  0.7  2.7  7.9  21.7  48.3
Zone 4           0.93  0.7  2.0  6.2  16.7  36.6
Zone 5           0.87  1.5  3.0  6.9  14.7  24.0
Zone 6           0.96  1.2  3.1  7.4  17.1  33.9

In [14]:
reporter.tabler.npv_table()

     P(Commercial)    P99    P90    P50     P10      P1
NPV           0.97 -158.0  274.0  861.0  1623.0  2281.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)    P99    P90    P50     P10      P1
EMV           0.97 -155.0  265.0  835.0  1574.0  2213.0