In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_3648280/1985460196.py:25: DeprecationWarning:

`set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"

CHAINS = 4
DRAWS = 500
N_RESERVOIRS = 9
N_PRODUCERS = 25

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=45e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=60e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2_000_000,
    producer_abandonment_cost_USD=500_000,
)

simpack = prospect.simulate(risked=True, levered=True, chains=CHAINS, draws=DRAWS)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 11:21:12.648 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 11:21:12.652 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 11:21:12.655 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 11:21:12.659 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 11:21:12.662 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 11:21:12.665 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 11:21:12.669 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 7 reservoir volumetric simulation complete.

2026-05-28 11:21:12.672 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 8 reservoir volumetric simulation complete.

2026-05-28 11:21:12.676 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 9 reservoir volumetric simulation complete.

2026-05-28 11:21:12.679 | INFO     | resgo.engine.volumetric_simulator:simulate:72 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 11:21:12.680 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:77 - Demo Prospect volumetric simulation complete!

2026-05-28 11:21:13.038 | INFO     | resgo.engine.production_simulator:prepare_simpack:142 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 11:21:13.038 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 1 start_idx = 8

2026-05-28 11:21:13.039 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 2 start_idx = 20

2026-05-28 11:21:13.039 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 3 start_idx = 32

2026-05-28 11:21:13.039 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 4 start_idx = 44

2026-05-28 11:21:13.039 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 5 start_idx = 56

2026-05-28 11:21:13.039 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 6 start_idx = 68

2026-05-28 11:21:13.039 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 7 start_idx = 79

2026-05-28 11:21:13.040 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 8 start_idx = 91

2026-05-28 11:21:13.040 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 9 start_idx = 103

2026-05-28 11:21:13.040 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 10 start_idx = 115

2026-05-28 11:21:13.040 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 11 start_idx = 127

2026-05-28 11:21:13.040 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 12 start_idx = 139

2026-05-28 11:21:13.040 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 13 start_idx = 150

2026-05-28 11:21:13.040 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 14 start_idx = 162

2026-05-28 11:21:13.040 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 15 start_idx = 174

2026-05-28 11:21:13.041 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 16 start_idx = 186

2026-05-28 11:21:13.041 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 17 start_idx = 198

2026-05-28 11:21:13.041 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 18 start_idx = 209

2026-05-28 11:21:13.041 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 19 start_idx = 221

2026-05-28 11:21:13.041 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 20 start_idx = 233

2026-05-28 11:21:13.041 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 21 start_idx = 245

2026-05-28 11:21:13.041 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 22 start_idx = 257

2026-05-28 11:21:13.041 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 23 start_idx = 269

2026-05-28 11:21:13.042 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 24 start_idx = 280

2026-05-28 11:21:13.042 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 25 start_idx = 292

2026-05-28 11:21:13.064 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:232 - Flowing array initialized.

2026-05-28 11:21:13.073 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:419 - Recovery factors simulated.

2026-05-28 11:21:13.516 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:303 - Oil well rates initialized.

2026-05-28 11:21:13.517 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:319 - No gas producers, skipping gas rate initialization...

2026-05-28 11:21:13.517 | INFO     | resgo.engine.production_simulator:simulate:84 - Commencing field production simulation (25 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 85.47it/s]

Chain 0:   6%|█████▋                                                                                                 | 20/360 [00:00<00:09, 34.15it/s]

Chain 0:   7%|███████▏                                                                                               | 25/360 [00:00<00:11, 29.68it/s]

Chain 0:   8%|████████▎                                                                                              | 29/360 [00:00<00:12, 26.86it/s]

Chain 0:   9%|█████████▍                                                                                             | 33/360 [00:01<00:12, 25.74it/s]

Chain 0:  10%|██████████▎                                                                                            | 36/360 [00:01<00:12, 25.28it/s]

Chain 0:  11%|███████████▏                                                                                           | 39/360 [00:01<00:13, 24.60it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:01<00:13, 24.23it/s]

Chain 0:  12%|████████████▉                                                                                          | 45/360 [00:01<00:13, 23.63it/s]

Chain 0:  13%|█████████████▋                                                                                         | 48/360 [00:01<00:13, 23.42it/s]

Chain 0:  14%|██████████████▌                                                                                        | 51/360 [00:01<00:13, 23.07it/s]

Chain 0:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:13, 22.73it/s]

Chain 0:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:13, 22.37it/s]

Chain 0:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:13, 22.07it/s]

Chain 0:  18%|██████████████████                                                                                     | 63/360 [00:02<00:13, 21.79it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  18%|██████████████████▉                                                                                    | 66/360 [00:02<00:13, 22.39it/s]

Chain 1:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 80.30it/s]

Chain 0:  19%|███████████████████▋                                                                                   | 69/360 [00:02<00:12, 22.63it/s]

Chain 0:  20%|████████████████████▌                                                                                  | 72/360 [00:02<00:12, 22.96it/s]

Chain 0:  21%|█████████████████████▍                                                                                 | 75/360 [00:02<00:12, 23.46it/s]

Chain 1:   6%|█████▋                                                                                                 | 20/360 [00:00<00:10, 33.73it/s]

Chain 0:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:11, 23.72it/s]

Chain 0:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:11, 23.97it/s]

Chain 1:   7%|███████▏                                                                                               | 25/360 [00:00<00:11, 29.26it/s]

Chain 0:  23%|████████████████████████                                                                               | 84/360 [00:03<00:11, 24.05it/s]

Chain 1:   8%|████████▎                                                                                              | 29/360 [00:00<00:12, 26.62it/s]

Chain 0:  24%|████████████████████████▉                                                                              | 87/360 [00:03<00:11, 24.22it/s]

Chain 1:   9%|█████████▏                                                                                             | 32/360 [00:01<00:12, 25.80it/s]

Chain 0:  25%|█████████████████████████▊                                                                             | 90/360 [00:03<00:10, 24.57it/s]

Chain 0:  26%|██████████████████████████▌                                                                            | 93/360 [00:03<00:10, 24.91it/s]

Chain 1:  10%|██████████                                                                                             | 35/360 [00:01<00:13, 24.89it/s]

Chain 0:  27%|███████████████████████████▍                                                                           | 96/360 [00:03<00:10, 24.97it/s]

Chain 1:  11%|██████████▊                                                                                            | 38/360 [00:01<00:13, 24.54it/s]

Chain 0:  28%|████████████████████████████▎                                                                          | 99/360 [00:03<00:10, 24.70it/s]

Chain 1:  11%|███████████▋                                                                                           | 41/360 [00:01<00:13, 23.64it/s]

Chain 0:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:10, 24.80it/s]

Chain 1:  12%|████████████▌                                                                                          | 44/360 [00:01<00:13, 23.05it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:10, 25.06it/s]

Chain 1:  13%|█████████████▍                                                                                         | 47/360 [00:01<00:14, 22.27it/s]

Chain 0:  30%|██████████████████████████████▌                                                                       | 108/360 [00:04<00:10, 25.14it/s]

Chain 1:  14%|██████████████▎                                                                                        | 50/360 [00:01<00:13, 22.19it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:04<00:09, 25.46it/s]

Chain 1:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:13, 22.34it/s]

Chain 0:  32%|████████████████████████████████▎                                                                     | 114/360 [00:04<00:09, 25.43it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:04<00:09, 25.19it/s]

Chain 1:  16%|████████████████                                                                                       | 56/360 [00:02<00:13, 22.03it/s]

Chain 0:  33%|██████████████████████████████████                                                                    | 120/360 [00:04<00:09, 24.79it/s]

Chain 1:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:14, 21.44it/s]

Chain 0:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:04<00:09, 25.53it/s]

Chain 1:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:14, 21.08it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:04<00:09, 25.59it/s]

Chain 1:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:13, 21.97it/s]

Chain 0:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:05<00:09, 25.39it/s]

Chain 2:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 76.42it/s]

Chain 1:  19%|███████████████████▍                                                                                   | 68/360 [00:02<00:12, 22.57it/s]

Chain 0:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:05<00:08, 25.43it/s]

Chain 1:  20%|████████████████████▎                                                                                  | 71/360 [00:02<00:12, 22.44it/s]

Chain 0:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:05<00:08, 25.53it/s]

Chain 0:  38%|███████████████████████████████████████                                                               | 138/360 [00:05<00:08, 25.42it/s]

Chain 1:  21%|█████████████████████▏                                                                                 | 74/360 [00:02<00:12, 22.33it/s]

Chain 2:   5%|█████▍                                                                                                 | 19/360 [00:00<00:11, 30.59it/s]

Chain 0:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:05<00:08, 25.11it/s]

Chain 1:  21%|██████████████████████                                                                                 | 77/360 [00:03<00:12, 22.73it/s]

Chain 0:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:05<00:08, 25.55it/s]

Chain 1:  22%|██████████████████████▉                                                                                | 80/360 [00:03<00:12, 22.70it/s]

Chain 2:   7%|██████▊                                                                                                | 24/360 [00:00<00:12, 26.42it/s]

Chain 0:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:05<00:08, 25.72it/s]

Chain 1:  23%|███████████████████████▋                                                                               | 83/360 [00:03<00:12, 22.38it/s]

Chain 0:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:05<00:07, 27.04it/s]

Chain 2:   8%|████████                                                                                               | 28/360 [00:00<00:13, 24.77it/s]

Chain 1:  24%|████████████████████████▌                                                                              | 86/360 [00:03<00:12, 22.19it/s]

Chain 0:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 27.52it/s]

Chain 2:   9%|████████▊                                                                                              | 31/360 [00:01<00:13, 24.18it/s]

Chain 1:  25%|█████████████████████████▍                                                                             | 89/360 [00:03<00:11, 22.61it/s]

Chain 0:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:06<00:07, 28.30it/s]

Chain 2:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 23.53it/s]

Chain 1:  26%|██████████████████████████▎                                                                            | 92/360 [00:03<00:11, 22.89it/s]

Chain 0:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:06<00:06, 28.48it/s]

Chain 1:  26%|███████████████████████████▏                                                                           | 95/360 [00:03<00:11, 22.70it/s]

Chain 2:  10%|██████████▌                                                                                            | 37/360 [00:01<00:14, 22.59it/s]

Chain 0:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:06<00:07, 27.79it/s]

Chain 1:  27%|████████████████████████████                                                                           | 98/360 [00:04<00:11, 23.07it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:01<00:14, 22.42it/s]

Chain 0:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:06<00:06, 28.63it/s]

Chain 1:  28%|████████████████████████████▌                                                                         | 101/360 [00:04<00:11, 23.33it/s]

Chain 0:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:06<00:06, 29.62it/s]

Chain 2:  12%|████████████▎                                                                                          | 43/360 [00:01<00:14, 21.77it/s]

Chain 1:  29%|█████████████████████████████▍                                                                        | 104/360 [00:04<00:10, 23.49it/s]

Chain 0:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:06<00:06, 30.07it/s]

Chain 2:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:14, 21.67it/s]

Chain 1:  30%|██████████████████████████████▎                                                                       | 107/360 [00:04<00:10, 23.90it/s]

Chain 0:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:06<00:05, 30.60it/s]

Chain 2:  14%|██████████████                                                                                         | 49/360 [00:01<00:14, 21.01it/s]

Chain 1:  31%|███████████████████████████████▏                                                                      | 110/360 [00:04<00:10, 24.24it/s]

Chain 0:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:05, 31.25it/s]

Chain 1:  31%|████████████████████████████████                                                                      | 113/360 [00:04<00:10, 24.46it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:15, 20.09it/s]

Chain 0:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:07<00:05, 31.24it/s]

Chain 1:  32%|████████████████████████████████▊                                                                     | 116/360 [00:04<00:10, 23.93it/s]

Chain 0:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:07<00:05, 31.84it/s]

Chain 2:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:15, 19.98it/s]

Chain 1:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:04<00:09, 24.60it/s]

Chain 0:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:07<00:05, 32.66it/s]

Chain 2:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:15, 19.34it/s]

Chain 1:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:05<00:09, 24.97it/s]

Chain 0:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:07<00:04, 33.51it/s]

Chain 2:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:15, 19.45it/s]

Chain 1:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:05<00:09, 25.53it/s]

Chain 0:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:07<00:04, 34.20it/s]

Chain 2:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:15, 18.93it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:05<00:09, 25.31it/s]

Chain 0:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:07<00:04, 35.02it/s]

Chain 2:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:14, 19.81it/s]

Chain 3:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 89.95it/s]

Chain 1:  36%|█████████████████████████████████████                                                                 | 131/360 [00:05<00:09, 25.22it/s]

Chain 0:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:07<00:04, 35.69it/s]

Chain 2:  19%|███████████████████▍                                                                                   | 68/360 [00:02<00:14, 20.78it/s]

Chain 0:  60%|█████████████████████████████████████████████████████████████▏                                        | 216/360 [00:07<00:03, 36.59it/s]

Chain 1:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:05<00:08, 25.85it/s]

Chain 1:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:05<00:08, 26.24it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:08<00:03, 38.00it/s]

Chain 2:  20%|████████████████████▎                                                                                  | 71/360 [00:03<00:13, 21.01it/s]

Chain 1:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:05<00:08, 25.99it/s]

Chain 0:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:08<00:03, 39.19it/s]

Chain 2:  21%|█████████████████████▏                                                                                 | 74/360 [00:03<00:13, 21.23it/s]

Chain 3:   5%|█████▍                                                                                                 | 19/360 [00:00<00:11, 30.95it/s]

Chain 1:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:05<00:08, 26.09it/s]

Chain 0:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:08<00:03, 40.81it/s]

Chain 2:  21%|██████████████████████                                                                                 | 77/360 [00:03<00:13, 21.58it/s]

Chain 1:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:05<00:08, 26.27it/s]

Chain 0:  66%|██████████████████████████████████████████████████████████████████▊                                   | 236/360 [00:08<00:02, 42.05it/s]

Chain 3:   7%|██████▊                                                                                                | 24/360 [00:00<00:12, 26.86it/s]

Chain 2:  22%|██████████████████████▉                                                                                | 80/360 [00:03<00:13, 20.85it/s]

Chain 1:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:06<00:08, 25.51it/s]

Chain 0:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:08<00:02, 40.44it/s]

Chain 1:  42%|███████████████████████████████████████████                                                           | 152/360 [00:06<00:08, 25.77it/s]

Chain 2:  23%|███████████████████████▋                                                                               | 83/360 [00:03<00:13, 20.83it/s]

Chain 0:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:08<00:02, 41.23it/s]

Chain 3:   8%|████████                                                                                               | 28/360 [00:01<00:13, 23.88it/s]

Chain 1:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:06<00:07, 25.97it/s]

Chain 0:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:08<00:02, 42.55it/s]

Chain 2:  24%|████████████████████████▌                                                                              | 86/360 [00:03<00:13, 20.55it/s]

Chain 3:   9%|████████▊                                                                                              | 31/360 [00:01<00:14, 23.06it/s]

Chain 1:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:06<00:07, 26.52it/s]

Chain 0:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:08<00:02, 44.55it/s]

Chain 2:  25%|█████████████████████████▍                                                                             | 89/360 [00:03<00:12, 21.12it/s]

Chain 0:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:08<00:02, 47.74it/s]

Chain 3:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 22.86it/s]

Chain 1:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:06<00:07, 27.68it/s]

Chain 2:  26%|██████████████████████████▎                                                                            | 92/360 [00:04<00:12, 21.60it/s]

Chain 0:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:09<00:01, 51.80it/s]

Chain 1:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:06<00:06, 28.89it/s]

Chain 3:  10%|██████████▌                                                                                            | 37/360 [00:01<00:14, 22.51it/s]

Chain 2:  26%|███████████████████████████▏                                                                           | 95/360 [00:04<00:11, 22.17it/s]

Chain 0:  76%|█████████████████████████████████████████████████████████████████████████████▉                        | 275/360 [00:09<00:01, 53.48it/s]

Chain 1:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:06<00:06, 29.68it/s]

Chain 3:  11%|███████████▍                                                                                           | 40/360 [00:01<00:14, 21.85it/s]

Chain 0:  78%|███████████████████████████████████████████████████████████████████████████████▌                      | 281/360 [00:09<00:01, 54.69it/s]

Chain 2:  27%|████████████████████████████                                                                           | 98/360 [00:04<00:11, 22.72it/s]

Chain 1:  48%|█████████████████████████████████████████████████▎                                                    | 174/360 [00:06<00:06, 30.61it/s]

Chain 0:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:09<00:01, 59.95it/s]

Chain 3:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 21.05it/s]

Chain 2:  28%|████████████████████████████▌                                                                         | 101/360 [00:04<00:11, 22.93it/s]

Chain 1:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:05, 30.46it/s]

Chain 0:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:09<00:00, 66.03it/s]

Chain 2:  29%|█████████████████████████████▍                                                                        | 104/360 [00:04<00:11, 23.25it/s]

Chain 3:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:14, 21.02it/s]

Chain 0:  85%|██████████████████████████████████████████████████████████████████████████████████████▉               | 307/360 [00:09<00:00, 72.47it/s]

Chain 1:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:07<00:05, 30.52it/s]

Chain 2:  30%|██████████████████████████████▎                                                                       | 107/360 [00:04<00:10, 23.27it/s]

Chain 3:  14%|██████████████                                                                                         | 49/360 [00:02<00:14, 21.01it/s]

Chain 0:  88%|█████████████████████████████████████████████████████████████████████████████████████████▊            | 317/360 [00:09<00:00, 78.73it/s]

Chain 1:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:07<00:05, 30.11it/s]

Chain 0:  91%|████████████████████████████████████████████████████████████████████████████████████████████▋         | 327/360 [00:09<00:00, 84.45it/s]

Chain 2:  31%|███████████████████████████████▏                                                                      | 110/360 [00:04<00:11, 22.50it/s]

Chain 3:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:15, 20.12it/s]

Chain 1:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:07<00:05, 30.46it/s]

Chain 0:  95%|███████████████████████████████████████████████████████████████████████████████████████████████▋     | 341/360 [00:09<00:00, 100.14it/s]

Chain 2:  31%|████████████████████████████████                                                                      | 113/360 [00:04<00:10, 23.19it/s]

Chain 1:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:07<00:05, 31.50it/s]

Chain 3:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:14, 20.57it/s]

Chain 2:  32%|████████████████████████████████▊                                                                     | 116/360 [00:05<00:10, 23.52it/s]

Chain 1:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:07<00:05, 32.09it/s]

Chain 3:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:14, 20.42it/s]

Chain 2:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:05<00:10, 23.83it/s]

Chain 1:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:07<00:04, 33.17it/s]

Chain 3:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:14, 20.45it/s]

Chain 2:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:05<00:09, 24.05it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:07<00:04, 34.22it/s]

Chain 2:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:05<00:09, 24.69it/s]

Chain 3:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:14, 20.88it/s]

Chain 1:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:07<00:04, 35.04it/s]

Chain 2:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:05<00:09, 25.25it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:08<00:04, 36.29it/s]

Chain 3:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:13, 21.69it/s]

Chain 2:  36%|█████████████████████████████████████                                                                 | 131/360 [00:05<00:09, 25.21it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:08<00:03, 38.09it/s]

Chain 3:  19%|████████████████████                                                                                   | 70/360 [00:03<00:13, 22.26it/s]

Chain 1:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:08<00:03, 38.55it/s]

Chain 2:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:05<00:08, 25.64it/s]

Chain 3:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:12, 22.12it/s]

Chain 2:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:05<00:08, 26.12it/s]

Chain 1:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:08<00:03, 39.44it/s]

Chain 3:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:12, 22.91it/s]

Chain 2:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:06<00:08, 26.69it/s]

Chain 1:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:08<00:03, 40.62it/s]

Chain 3:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:11, 23.74it/s]

Chain 2:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:06<00:08, 27.08it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:08<00:02, 41.82it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:11, 23.99it/s]

Chain 2:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:06<00:07, 27.46it/s]

Chain 1:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:08<00:02, 43.11it/s]

Chain 2:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:06<00:07, 27.96it/s]

Chain 3:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:11, 24.29it/s]

Chain 1:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:08<00:02, 44.68it/s]

Chain 2:  42%|███████████████████████████████████████████                                                           | 152/360 [00:06<00:07, 28.54it/s]

Chain 3:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:11, 24.50it/s]

Chain 1:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:08<00:02, 47.76it/s]

Chain 2:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:06<00:06, 29.31it/s]

Chain 3:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:10, 24.68it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:09<00:02, 48.95it/s]

Chain 2:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:06, 30.05it/s]

Chain 1:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:09<00:01, 51.35it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:03<00:10, 24.20it/s]

Chain 2:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:06<00:06, 29.90it/s]

Chain 1:  76%|█████████████████████████████████████████████████████████████████████████████▎                        | 273/360 [00:09<00:01, 54.41it/s]

Chain 3:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:10, 24.28it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:09<00:01, 57.66it/s]

Chain 2:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:06<00:06, 30.50it/s]

Chain 3:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:10, 24.58it/s]

Chain 1:  80%|█████████████████████████████████████████████████████████████████████████████████▌                    | 288/360 [00:09<00:01, 61.87it/s]

Chain 2:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:07<00:06, 30.94it/s]

Chain 3:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:10, 24.34it/s]

Chain 1:  82%|███████████████████████████████████████████████████████████████████████████████████▊                  | 296/360 [00:09<00:00, 66.22it/s]

Chain 2:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:05, 31.15it/s]

Chain 3:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:10, 24.40it/s]

Chain 1:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:09<00:00, 71.57it/s]

Chain 2:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:07<00:05, 31.45it/s]

Chain 3:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:10, 24.46it/s]

Chain 1:  88%|█████████████████████████████████████████████████████████████████████████████████████████▎            | 315/360 [00:09<00:00, 79.23it/s]

Chain 2:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:07<00:05, 32.11it/s]

Chain 3:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:10, 24.72it/s]

Chain 1:  91%|████████████████████████████████████████████████████████████████████████████████████████████▋         | 327/360 [00:09<00:00, 90.45it/s]

Chain 2:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:07<00:05, 33.00it/s]

Chain 1:  96%|████████████████████████████████████████████████████████████████████████████████████████████████▌    | 344/360 [00:10<00:00, 113.00it/s]

Chain 3:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:09, 25.15it/s]

Chain 2:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:07<00:04, 33.84it/s]

Chain 3:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:04<00:09, 25.13it/s]

Chain 2:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:07<00:04, 34.70it/s]

Chain 3:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:09, 25.64it/s]

Chain 2:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:07<00:04, 35.52it/s]

Chain 3:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:08, 26.23it/s]

Chain 2:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:07<00:04, 36.48it/s]

Chain 3:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:08, 26.53it/s]

Chain 2:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:08<00:04, 37.92it/s]

Chain 3:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:08, 26.62it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:08<00:03, 39.46it/s]

Chain 3:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:08, 26.96it/s]

Chain 2:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:08<00:03, 40.81it/s]

Chain 3:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:08, 27.49it/s]

Chain 2:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:08<00:03, 41.57it/s]

Chain 3:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:05<00:07, 27.91it/s]

Chain 2:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:08<00:03, 43.24it/s]

Chain 3:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:05<00:07, 28.34it/s]

Chain 2:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:08<00:02, 44.30it/s]

Chain 3:  40%|█████████████████████████████████████████                                                             | 145/360 [00:05<00:07, 28.38it/s]

Chain 2:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:08<00:02, 45.70it/s]

Chain 3:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:07, 28.27it/s]

Chain 2:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:08<00:02, 46.08it/s]

Chain 3:  42%|███████████████████████████████████████████                                                           | 152/360 [00:06<00:07, 28.93it/s]

Chain 2:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:08<00:02, 47.84it/s]

Chain 3:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:06<00:06, 29.84it/s]

Chain 2:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:09<00:02, 50.03it/s]

Chain 3:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:06, 30.68it/s]

Chain 2:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:09<00:01, 52.15it/s]

Chain 3:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:06<00:06, 30.89it/s]

Chain 2:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:09<00:01, 55.24it/s]

Chain 3:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:06<00:06, 30.95it/s]

Chain 2:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:09<00:01, 55.58it/s]

Chain 2:  78%|███████████████████████████████████████████████████████████████████████████████▌                      | 281/360 [00:09<00:01, 58.31it/s]

Chain 3:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:06<00:05, 31.73it/s]

Chain 2:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:09<00:01, 63.37it/s]

Chain 3:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:06<00:05, 32.34it/s]

Chain 2:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:09<00:00, 69.02it/s]

Chain 3:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:05, 32.85it/s]

Chain 2:  85%|██████████████████████████████████████████████████████████████████████████████████████▉               | 307/360 [00:09<00:00, 74.61it/s]

Chain 3:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:05, 32.99it/s]

Chain 2:  88%|██████████████████████████████████████████████████████████████████████████████████████████            | 318/360 [00:09<00:00, 83.00it/s]

Chain 3:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:07<00:05, 34.07it/s]

Chain 2:  92%|██████████████████████████████████████████████████████████████████████████████████████████████        | 332/360 [00:10<00:00, 99.21it/s]

Chain 3:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:07<00:04, 34.28it/s]

Chain 2:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████▌ | 355/360 [00:10<00:00, 136.46it/s]

Chain 3:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:07<00:04, 34.73it/s]

Chain 3:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:07<00:04, 36.53it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:07<00:04, 37.24it/s]

Chain 3:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:07<00:03, 38.70it/s]

Chain 3:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:07<00:03, 40.11it/s]

Chain 3:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:08<00:03, 40.59it/s]

Chain 3:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:08<00:03, 41.36it/s]

Chain 3:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:08<00:03, 42.71it/s]

Chain 3:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:08<00:02, 43.95it/s]

Chain 3:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:08<00:02, 45.86it/s]

Chain 3:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:08<00:02, 46.87it/s]

Chain 3:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:08<00:02, 48.67it/s]

Chain 3:  72%|█████████████████████████████████████████████████████████████████████████                             | 258/360 [00:08<00:02, 50.67it/s]

Chain 3:  73%|██████████████████████████████████████████████████████████████████████████▊                           | 264/360 [00:08<00:01, 53.19it/s]

Chain 3:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:09<00:01, 56.11it/s]

Chain 3:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:09<00:01, 58.08it/s]

Chain 3:  79%|█████████████████████████████████████████████████████████████████████████████████                     | 286/360 [00:09<00:01, 62.36it/s]

Chain 3:  82%|███████████████████████████████████████████████████████████████████████████████████▎                  | 294/360 [00:09<00:00, 66.91it/s]

Chain 3:  84%|█████████████████████████████████████████████████████████████████████████████████████▊                | 303/360 [00:09<00:00, 72.79it/s]

Chain 3:  87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 314/360 [00:09<00:00, 81.43it/s]

Chain 3:  91%|████████████████████████████████████████████████████████████████████████████████████████████▋         | 327/360 [00:09<00:00, 93.75it/s]

Chain 3:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████    | 346/360 [00:09<00:00, 121.25it/s]

2026-05-28 11:21:36.824 | SUCCESS  | resgo.engine.production_simulator:simulate:101 - Demo Prospect Field production simulation complete!

2026-05-28 11:21:37.044 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:315 - Discount and inflation curves initialized

2026-05-28 11:21:39.709 | INFO     | resgo.engine.economic_simulator:simulate_capex:375 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 11:21:40.084 | INFO     | resgo.engine.economic_simulator:simulate_leverage:389 - Debt repayments simulated.

2026-05-28 11:21:40.085 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:402 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 11:21:40.087 | INFO     | resgo.engine.economic_simulator:simulate_prices:417 - Oil and Gas prices simulated using a flat price model.

2026-05-28 11:21:40.575 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:443 - Gross sales simulated.

2026-05-28 11:21:40.596 | INFO     | resgo.engine.economic_simulator:simulate_expenses:462 - OPEX and ABEX simulated.

2026-05-28 11:21:40.853 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:487 - Royalties simulated using a flat royalty model.

2026-05-28 11:21:41.259 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:513 - Infrastructure depreciation model simulated.

2026-05-28 11:21:41.721 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:527 - Producer depreciation model simulated.

2026-05-28 11:21:41.818 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:538 - Taxes simulated using a progressive tax model.

2026-05-28 11:21:41.818 | SUCCESS  | resgo.engine.economic_simulator:simulate:299 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

                                     P99    P90    P50    P10     P1
stream
STOIIP (stb)        Total Volumes   63.1  117.7  200.5  309.7  448.7
GIIP (mscf)         Total Volumes   24.7   47.8   87.6  142.9  213.8
Condensate (stb)    Total Volumes    0.7    1.5    3.1    5.6    9.3
Solution Gas (mscf) Total Volumes  107.1  200.3  364.7  619.0  974.1

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

                P99   P90   P50   P10     P1
Total Oil EUR  13.1  26.3  46.5  73.6  111.3

In [13]:
reporter.tabler.oil_eur_table(group_by="producer")

          P99  P90  P50   P10    P1
producer
Oil 1     4.1  5.9  8.1  10.7  14.1
Oil 2     2.8  4.3  6.0   8.1  10.6
Oil 3     2.4  3.6  5.2   7.0   9.0
Oil 4     2.0  3.0  4.6   6.4   8.1
Oil 5     0.0  2.5  4.1   5.7   7.5
Oil 6     0.0  2.1  3.6   5.2   7.0
Oil 7     0.0  1.8  3.1   4.9   6.6
Oil 8     0.0  1.4  2.7   4.5   6.3
Oil 9     0.0  0.0  2.4   4.0   5.6
Oil 10    0.0  0.0  1.9   3.6   5.2
Oil 11    0.0  0.0  1.6   3.1   4.8
Oil 12    0.0  0.0  1.1   2.6   4.5
Oil 13    0.0  0.0  0.8   2.4   4.2
Oil 14    0.0  0.0  0.4   2.0   3.7
Oil 15    0.0  0.0  0.1   1.7   3.3
Oil 16    0.0  0.0  0.0   1.3   3.0
Oil 17    0.0  0.0  0.0   1.0   2.5
Oil 18    0.0  0.0  0.0   0.8   2.2
Oil 19    0.0  0.0  0.0   0.6   1.8
Oil 20    0.0  0.0  0.0   0.5   1.6
Oil 21    0.0  0.0  0.0   0.3   1.4
Oil 22    0.0  0.0  0.0   0.1   1.1
Oil 23    0.0  0.0  0.0   0.1   0.9
Oil 24    0.0  0.0  0.0   0.0   0.9
Oil 25    0.0  0.0  0.0   0.0   1.4

In [14]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P99  P90  P50   P10    P1
reservoir
Zone 1     0.0  0.0  4.0  12.9  28.1
Zone 2     0.0  0.0  4.1  13.5  25.4
Zone 3     0.0  0.0  5.2  15.2  30.9
Zone 4     0.0  0.0  5.9  19.1  44.9
Zone 5     0.0  0.0  2.5  10.8  23.4
Zone 6     0.0  0.0  4.3  15.0  32.5
Zone 7     0.0  0.0  5.2  13.8  26.2
Zone 8     0.0  0.0  0.0   9.8  24.3
Zone 9     0.0  0.0  0.0   8.7  25.6

In [15]:
reporter.tabler.gas_eur_table(group_by=None)
reporter.tabler.gas_eur_table(group_by=None)

                P99   P90    P50    P10     P1
Total Gas EUR  35.5  70.1  137.4  241.5  367.0

In [16]:
reporter.tabler.gas_eur_table(group_by="producer")

          P99   P90   P50   P10    P1
producer
Oil 1     9.1  13.9  21.6  33.4  48.1
Oil 2     6.8  10.2  16.6  26.3  38.4
Oil 3     5.6   8.7  14.2  22.7  31.9
Oil 4     4.7   7.3  12.4  19.9  29.7
Oil 5     0.0   6.3  10.8  17.9  26.7
Oil 6     0.0   5.7   9.6  16.0  24.3
Oil 7     0.0   5.1   8.7  14.6  22.2
Oil 8     0.0   4.1   7.9  13.0  19.5
Oil 9     0.0   0.0   7.0  11.7  18.1
Oil 10    0.0   0.0   6.0  10.6  16.2
Oil 11    0.0   0.0   5.3   9.7  15.9
Oil 12    0.0   0.0   4.4   8.5  13.6
Oil 13    0.0   0.0   3.8   7.8  12.5
Oil 14    0.0   0.0   2.9   6.9  11.4
Oil 15    0.0   0.0   2.0   5.9  10.0
Oil 16    0.0   0.0   1.0   5.2   9.1
Oil 17    0.0   0.0   0.4   4.4   7.9
Oil 18    0.0   0.0   0.0   3.8   6.9
Oil 19    0.0   0.0   0.0   3.1   6.3
Oil 20    0.0   0.0   0.0   2.5   5.4
Oil 21    0.0   0.0   0.0   2.0   4.8
Oil 22    0.0   0.0   0.0   1.6   4.1
Oil 23    0.0   0.0   0.0   1.2   3.3
Oil 24    0.0   0.0   0.0   1.0   3.5
Oil 25    0.0   0.0   0.0   2.0   5.0

In [17]:
reporter.tabler.gas_eur_table(group_by="reservoir")

           P99  P90   P50   P10     P1
reservoir
Zone 1     0.0  0.0  10.1  40.5   86.4
Zone 2     0.0  0.0  10.2  43.4  105.5
Zone 3     0.0  0.0  13.3  48.0  110.5
Zone 4     0.0  0.0  16.0  59.5  147.5
Zone 5     0.0  0.0   5.6  34.0   84.8
Zone 6     0.0  0.0  10.7  48.8  143.0
Zone 7     0.0  0.0  13.4  44.0   94.7
Zone 8     0.0  0.0   0.0  33.3   86.0
Zone 9     0.0  0.0   0.0  27.5   97.0

In [18]:
reporter.tabler.npv_table(success_only=False)

      P99  P90  P50   P10    P1
NPV  -262  230  855  1527  2198