In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_180192/1985460196.py:25: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats(fig_format)

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 42

CHAINS = 4
DRAWS = 500
N_RESERVOIRS = 6
N_PRODUCERS = 20

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=45e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=60e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2_000_000,
    producer_abandonment_cost_USD=500_000,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 18:11:38.394 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 18:11:38.399 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 18:11:38.402 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 18:11:38.406 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 18:11:38.409 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 18:11:38.412 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 18:11:38.416 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 18:11:38.416 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 18:11:38.590 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 18:11:38.590 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 18:11:38.591 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 18:11:38.591 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 18:11:38.591 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 18:11:38.592 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 18:11:38.593 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 18:11:38.593 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 18:11:38.593 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 18:11:38.593 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 18:11:38.593 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 18:11:38.593 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 18:11:38.593 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 18:11:38.605 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 18:11:38.611 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 18:11:38.851 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 18:11:38.852 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 18:11:38.852 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (20 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 123.68it/s]

Chain 0:   7%|███████▍                                                                                               | 26/360 [00:00<00:05, 66.80it/s]

Chain 0:  10%|██████████                                                                                             | 35/360 [00:00<00:05, 60.39it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:00<00:05, 57.11it/s]

Chain 0:  14%|██████████████                                                                                         | 49/360 [00:00<00:05, 55.04it/s]

Chain 0:  15%|███████████████▋                                                                                       | 55/360 [00:00<00:05, 53.05it/s]

Chain 0:  17%|█████████████████▍                                                                                     | 61/360 [00:01<00:05, 51.48it/s]

Chain 0:  19%|███████████████████▏                                                                                   | 67/360 [00:01<00:05, 49.60it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  20%|████████████████████▌                                                                                  | 72/360 [00:01<00:05, 48.83it/s]

Chain 1:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 116.74it/s]

Chain 0:  21%|██████████████████████                                                                                 | 77/360 [00:01<00:05, 48.87it/s]

Chain 0:  23%|███████████████████████▍                                                                               | 82/360 [00:01<00:05, 48.49it/s]

Chain 1:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 64.00it/s]

Chain 0:  24%|████████████████████████▉                                                                              | 87/360 [00:01<00:05, 48.23it/s]

Chain 0:  26%|██████████████████████████▎                                                                            | 92/360 [00:01<00:05, 48.36it/s]

Chain 1:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 57.42it/s]

Chain 0:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 48.48it/s]

Chain 1:  11%|███████████▍                                                                                           | 40/360 [00:00<00:05, 54.61it/s]

Chain 0:  29%|█████████████████████████████▏                                                                        | 103/360 [00:01<00:05, 48.87it/s]

Chain 1:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:05, 52.70it/s]

Chain 0:  30%|██████████████████████████████▉                                                                       | 109/360 [00:02<00:05, 49.59it/s]

Chain 1:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:05, 51.49it/s]

Chain 0:  32%|████████████████████████████████▌                                                                     | 115/360 [00:02<00:04, 50.47it/s]

Chain 0:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:02<00:04, 50.61it/s]

Chain 1:  16%|████████████████▌                                                                                      | 58/360 [00:01<00:06, 49.18it/s]

Chain 0:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:02<00:04, 50.45it/s]

Chain 1:  18%|██████████████████                                                                                     | 63/360 [00:01<00:06, 47.41it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:02<00:04, 50.02it/s]

Chain 1:  19%|███████████████████▍                                                                                   | 68/360 [00:01<00:06, 46.03it/s]

Chain 2:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 122.13it/s]

Chain 0:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:02<00:04, 51.36it/s]

Chain 1:  20%|████████████████████▉                                                                                  | 73/360 [00:01<00:06, 45.69it/s]

Chain 0:  40%|█████████████████████████████████████████                                                             | 145/360 [00:02<00:04, 52.47it/s]

Chain 1:  22%|██████████████████████▎                                                                                | 78/360 [00:01<00:06, 45.62it/s]

Chain 0:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:02<00:03, 54.12it/s]

Chain 1:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:06, 46.01it/s]

Chain 2:   7%|███████▍                                                                                               | 26/360 [00:00<00:05, 65.82it/s]

Chain 0:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:02<00:03, 55.31it/s]

Chain 1:  24%|█████████████████████████▏                                                                             | 88/360 [00:01<00:05, 46.09it/s]

Chain 2:   9%|█████████▋                                                                                             | 34/360 [00:00<00:05, 60.16it/s]

Chain 0:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:03<00:03, 56.43it/s]

Chain 1:  26%|██████████████████████████▌                                                                            | 93/360 [00:01<00:05, 46.67it/s]

Chain 0:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:03<00:03, 58.96it/s]

Chain 2:  11%|███████████▋                                                                                           | 41/360 [00:00<00:05, 57.01it/s]

Chain 1:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 47.03it/s]

Chain 0:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:03<00:02, 61.44it/s]

Chain 1:  29%|█████████████████████████████▍                                                                        | 104/360 [00:02<00:05, 48.10it/s]

Chain 2:  13%|█████████████▋                                                                                         | 48/360 [00:00<00:05, 53.55it/s]

Chain 0:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:03<00:02, 63.63it/s]

Chain 1:  30%|██████████████████████████████▉                                                                       | 109/360 [00:02<00:05, 48.51it/s]

Chain 2:  15%|███████████████▍                                                                                       | 54/360 [00:00<00:05, 51.35it/s]

Chain 0:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:03<00:02, 66.05it/s]

Chain 1:  32%|████████████████████████████████▎                                                                     | 114/360 [00:02<00:05, 48.62it/s]

Chain 0:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:03<00:02, 69.09it/s]

Chain 2:  17%|█████████████████▏                                                                                     | 60/360 [00:01<00:06, 49.48it/s]

Chain 1:  33%|██████████████████████████████████                                                                    | 120/360 [00:02<00:04, 49.21it/s]

Chain 0:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:03<00:02, 71.82it/s]

Chain 1:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:02<00:04, 49.43it/s]

Chain 2:  18%|██████████████████▉                                                                                    | 66/360 [00:01<00:06, 48.23it/s]

Chain 0:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:03<00:01, 75.30it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:  20%|████████████████████▎                                                                                  | 71/360 [00:01<00:06, 47.60it/s]

Chain 1:  36%|█████████████████████████████████████                                                                 | 131/360 [00:02<00:04, 49.60it/s]

Chain 0:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:03<00:01, 76.48it/s]

Chain 3:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 111.30it/s]

Chain 2:  21%|█████████████████████▋                                                                                 | 76/360 [00:01<00:06, 46.41it/s]

Chain 1:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:02<00:04, 50.61it/s]

Chain 0:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:04<00:01, 79.40it/s]

Chain 2:  22%|███████████████████████▏                                                                               | 81/360 [00:01<00:06, 44.83it/s]

Chain 1:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:02<00:04, 50.53it/s]

Chain 0:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:04<00:01, 84.74it/s]

Chain 2:  24%|████████████████████████▌                                                                              | 86/360 [00:01<00:06, 44.22it/s]

Chain 1:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:02<00:04, 51.60it/s]

Chain 3:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 62.49it/s]

Chain 0:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:04<00:01, 92.94it/s]

Chain 2:  25%|██████████████████████████                                                                             | 91/360 [00:01<00:05, 45.40it/s]

Chain 1:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:03<00:03, 52.31it/s]

Chain 0:  75%|███████████████████████████████████████████████████████████████████████████▍                         | 269/360 [00:04<00:00, 101.75it/s]

Chain 3:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 56.87it/s]

Chain 2:  27%|███████████████████████████▍                                                                           | 96/360 [00:01<00:05, 45.98it/s]

Chain 1:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:03<00:03, 54.00it/s]

Chain 0:  79%|███████████████████████████████████████████████████████████████████████████████▍                     | 283/360 [00:04<00:00, 112.22it/s]

Chain 2:  28%|████████████████████████████▌                                                                         | 101/360 [00:01<00:05, 46.61it/s]

Chain 3:  11%|███████████▍                                                                                           | 40/360 [00:00<00:05, 53.93it/s]

Chain 1:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:03<00:03, 56.33it/s]

Chain 0:  83%|████████████████████████████████████████████████████████████████████████████████████▏                | 300/360 [00:04<00:00, 128.19it/s]

Chain 2:  29%|██████████████████████████████                                                                        | 106/360 [00:02<00:05, 47.12it/s]

Chain 1:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:03<00:03, 58.95it/s]

Chain 0:  89%|██████████████████████████████████████████████████████████████████████████████████████████▎          | 322/360 [00:04<00:00, 154.09it/s]

Chain 3:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 52.26it/s]

Chain 2:  31%|███████████████████████████████▍                                                                      | 111/360 [00:02<00:05, 47.89it/s]

Chain 1:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:03<00:02, 61.20it/s]

Chain 3:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:06, 50.59it/s]

Chain 2:  32%|████████████████████████████████▊                                                                     | 116/360 [00:02<00:05, 47.81it/s]

Chain 1:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:03<00:02, 63.55it/s]

Chain 3:  16%|████████████████▌                                                                                      | 58/360 [00:01<00:06, 47.96it/s]

Chain 2:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:02<00:04, 48.14it/s]

Chain 1:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:03<00:02, 66.49it/s]

Chain 2:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:02<00:04, 48.11it/s]

Chain 3:  18%|██████████████████                                                                                     | 63/360 [00:01<00:06, 46.74it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:03<00:02, 69.33it/s]

Chain 3:  19%|███████████████████▍                                                                                   | 68/360 [00:01<00:06, 46.08it/s]

Chain 2:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:02<00:04, 49.06it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:03<00:02, 71.68it/s]

Chain 3:  20%|████████████████████▉                                                                                  | 73/360 [00:01<00:06, 45.54it/s]

Chain 2:  38%|███████████████████████████████████████                                                               | 138/360 [00:02<00:04, 50.09it/s]

Chain 1:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:04<00:01, 76.19it/s]

Chain 3:  22%|██████████████████████▎                                                                                | 78/360 [00:01<00:06, 45.70it/s]

Chain 1:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:04<00:01, 81.97it/s]

Chain 2:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:02<00:04, 51.57it/s]

Chain 1:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:04<00:01, 86.93it/s]

Chain 3:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:06, 45.86it/s]

Chain 2:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:02<00:04, 52.23it/s]

Chain 1:  70%|███████████████████████████████████████████████████████████████████████▋                              | 253/360 [00:04<00:01, 93.09it/s]

Chain 3:  24%|█████████████████████████▏                                                                             | 88/360 [00:01<00:05, 46.08it/s]

Chain 2:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:03<00:03, 54.24it/s]

Chain 1:  74%|██████████████████████████████████████████████████████████████████████████▋                          | 266/360 [00:04<00:00, 102.05it/s]

Chain 3:  26%|██████████████████████████▌                                                                            | 93/360 [00:01<00:05, 46.91it/s]

Chain 2:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:03<00:03, 55.33it/s]

Chain 1:  78%|██████████████████████████████████████████████████████████████████████████████▌                      | 280/360 [00:04<00:00, 112.66it/s]

Chain 3:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 47.38it/s]

Chain 2:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:03<00:03, 57.72it/s]

Chain 1:  82%|███████████████████████████████████████████████████████████████████████████████████                  | 296/360 [00:04<00:00, 126.42it/s]

Chain 3:  29%|█████████████████████████████▏                                                                        | 103/360 [00:02<00:05, 47.93it/s]

Chain 2:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:03<00:03, 59.74it/s]

Chain 1:  88%|████████████████████████████████████████████████████████████████████████████████████████▍            | 315/360 [00:04<00:00, 143.88it/s]

Chain 3:  30%|██████████████████████████████▌                                                                       | 108/360 [00:02<00:05, 47.53it/s]

Chain 2:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:03<00:02, 61.93it/s]

Chain 1:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████▋   | 348/360 [00:04<00:00, 197.81it/s]

Chain 3:  31%|████████████████████████████████                                                                      | 113/360 [00:02<00:05, 47.79it/s]

Chain 2:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:03<00:02, 65.88it/s]

Chain 3:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:02<00:04, 48.88it/s]

Chain 2:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:03<00:02, 69.33it/s]

Chain 2:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:03<00:02, 73.44it/s]

Chain 3:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:02<00:04, 49.61it/s]

Chain 2:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:03<00:01, 77.83it/s]

Chain 3:  36%|█████████████████████████████████████                                                                 | 131/360 [00:02<00:04, 50.73it/s]

Chain 2:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:04<00:01, 83.02it/s]

Chain 3:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:02<00:04, 52.08it/s]

Chain 2:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:04<00:01, 86.70it/s]

Chain 3:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:02<00:04, 53.37it/s]

Chain 2:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:04<00:01, 94.43it/s]

Chain 3:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:02<00:03, 54.14it/s]

Chain 2:  73%|█████████████████████████████████████████████████████████████████████████▊                           | 263/360 [00:04<00:00, 105.82it/s]

Chain 3:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:03<00:03, 55.53it/s]

Chain 2:  77%|█████████████████████████████████████████████████████████████████████████████▉                       | 278/360 [00:04<00:00, 116.34it/s]

Chain 3:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:03<00:03, 56.98it/s]

Chain 2:  82%|███████████████████████████████████████████████████████████████████████████████████                  | 296/360 [00:04<00:00, 132.85it/s]

Chain 3:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:03<00:03, 58.79it/s]

Chain 2:  88%|█████████████████████████████████████████████████████████████████████████████████████████▏           | 318/360 [00:04<00:00, 156.91it/s]

Chain 3:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:03<00:03, 60.45it/s]

Chain 2:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████▏| 357/360 [00:04<00:00, 223.91it/s]

Chain 3:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:03<00:02, 62.55it/s]

Chain 3:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:03<00:02, 65.85it/s]

Chain 3:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:03<00:02, 70.35it/s]

Chain 3:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:03<00:02, 73.90it/s]

Chain 3:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:03<00:01, 77.84it/s]

Chain 3:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:04<00:01, 83.73it/s]

Chain 3:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:04<00:01, 89.87it/s]

Chain 3:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:04<00:01, 97.93it/s]

Chain 3:  73%|██████████████████████████████████████████████████████████████████████████                           | 264/360 [00:04<00:00, 106.27it/s]

Chain 3:  78%|██████████████████████████████████████████████████████████████████████████████▎                      | 279/360 [00:04<00:00, 118.91it/s]

Chain 3:  82%|███████████████████████████████████████████████████████████████████████████████████                  | 296/360 [00:04<00:00, 133.83it/s]

Chain 3:  89%|██████████████████████████████████████████████████████████████████████████████████████████           | 321/360 [00:04<00:00, 167.08it/s]

2026-05-28 18:11:50.380 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 18:11:50.503 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 18:11:52.560 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 18:11:52.920 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 18:11:52.921 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 18:11:52.925 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 18:11:53.191 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 18:11:53.205 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 18:11:53.352 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 18:11:53.562 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 18:11:53.799 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 18:11:53.874 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 18:11:53.874 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,55.8,90.7,161.6,271.9,404.8
GIIP (mscf),Total Volumes,1.0,22.0,37.3,69.4,123.3,195.3
Condensate (stb),Total Volumes,1.0,0.6,1.1,2.4,4.7,8.1
Solution Gas (mscf),Total Volumes,1.0,87.4,153.3,294.6,529.0,855.7

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50   P10     P1
Total Oil EUR         1.0  11.9  20.2  37.8  65.2  101.3

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.80  0.9  2.5  7.0  18.3  38.3
Zone 2           0.65  0.8  2.0  5.5  13.3  26.0
Zone 3           0.99  0.9  2.5  6.9  17.3  31.8
Zone 4           0.75  1.0  2.8  8.6  24.3  62.9
Zone 5           0.84  1.1  2.4  5.6  12.2  24.4
Zone 6           0.71  0.5  2.0  5.9  15.9  36.5

In [14]:
reporter.tabler.npv_table()

     P(Commercial)    P99   P90    P50     P10      P1
NPV           0.92 -281.0  39.0  632.0  1359.0  2060.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)    P99   P90    P50     P10      P1
EMV           0.92 -261.0  32.0  576.0  1241.0  1884.0

In [16]:
from resgo.plotting.tables import npv_USD
import numpy as np
import pandas as pd

npv = npv_USD(
    simpack,
    nominal=True,
    discounted=True,
    success_only=False,
)
npv_usd = npv.to_numpy().ravel()
npv_df = pd.DataFrame({"npv_usd_mm": npv_usd / 1e6})

histogram = (
    alt.Chart(npv_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "npv_usd_mm:Q",
            bin=alt.Bin(maxbins=60),
            title="Nominal discounted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", title="Simulation count"),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated NPV Distribution",
    )
)

break_even = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(histogram, break_even)
fig.show()

alt.LayerChart(...)

In [17]:
def loss_adjusted_npv_USD(
    npv_usd,
    bankruptcy_threshold_usd=500e6,
    floor_usd=-5e9,
):
    npv_usd = np.asarray(npv_usd)
    threshold = bankruptcy_threshold_usd

    with np.errstate(divide="ignore", invalid="ignore"):
        adjusted = np.where(
            npv_usd >= 0,
            npv_usd,
            (threshold * npv_usd) / (threshold + npv_usd),
        )

    adjusted = np.where(npv_usd <= -threshold, floor_usd, adjusted)
    return np.maximum(adjusted, floor_usd)

x_usd = np.linspace(-499.9e6, 1.5e9, 1_000)
loss_function_df = pd.DataFrame(
    {
        "npv_usd_mm": x_usd / 1e6,
        "loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(x_usd) / 1e6,
    }
)

loss_function = (
    alt.Chart(loss_function_df)
    .mark_line(color="#FACC15", strokeWidth=3)
    .encode(
        x=alt.X("npv_usd_mm:Q", title="Nominal discounted NPV ($USD MM)"),
        y=alt.Y(
            "loss_adjusted_npv_usd_mm:Q",
            title="Loss-adjusted NPV ($USD MM)",
        ),
        tooltip=[
            alt.Tooltip("npv_usd_mm:Q", title="NPV ($MM)", format=",.0f"),
            alt.Tooltip(
                "loss_adjusted_npv_usd_mm:Q",
                title="Loss-adjusted NPV ($MM)",
                format=",.0f",
            ),
        ],
    )
    .properties(
        width=650,
        height=250,
        title="Company Loss Function",
    )
)

bankruptcy_threshold = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [-500]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

loss_floor = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [-5_000]}))
    .mark_rule(color="red", strokeDash=[2, 4], strokeWidth=1)
    .encode(y="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_function, bankruptcy_threshold, loss_floor)
fig.show()

alt.LayerChart(...)

In [18]:
loss_df = pd.DataFrame(
    {"loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(npv_usd) / 1e6}
)

loss_histogram = (
    alt.Chart(loss_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "loss_adjusted_npv_usd_mm:Q",
            bin=alt.Bin(maxbins=60),
            title="Loss-adjusted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", title="Simulation count"),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated Loss-Adjusted NPV Distribution",
    )
)

break_even_loss = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_histogram, break_even_loss)
fig.show()

alt.LayerChart(...)