In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_389850/1985460196.py:25: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats(fig_format)

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 42

CHAINS = 6
DRAWS = 500
N_RESERVOIRS = 12
N_PRODUCERS = 25

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=50e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=100e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2e6,
    producer_abandonment_cost_USD=500_000,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 20:08:49.669 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 20:08:49.673 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 20:08:49.677 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 20:08:49.681 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 20:08:49.684 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 20:08:49.688 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 20:08:49.692 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 7 reservoir volumetric simulation complete.

2026-05-28 20:08:49.696 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 8 reservoir volumetric simulation complete.

2026-05-28 20:08:49.700 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 9 reservoir volumetric simulation complete.

2026-05-28 20:08:49.703 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 10 reservoir volumetric simulation complete.

2026-05-28 20:08:49.707 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 11 reservoir volumetric simulation complete.

2026-05-28 20:08:49.711 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 12 reservoir volumetric simulation complete.

2026-05-28 20:08:49.716 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 20:08:49.716 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 20:08:50.313 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 20:08:50.314 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 20:08:50.314 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 20:08:50.314 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 20:08:50.314 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 20:08:50.315 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 20:08:50.315 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 20:08:50.315 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 20:08:50.315 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 20:08:50.315 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 20:08:50.315 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 20:08:50.315 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 20:08:50.315 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 20:08:50.316 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 21 start_idx = 245

2026-05-28 20:08:50.317 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 22 start_idx = 257

2026-05-28 20:08:50.317 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 23 start_idx = 269

2026-05-28 20:08:50.317 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 24 start_idx = 280

2026-05-28 20:08:50.317 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 25 start_idx = 292

2026-05-28 20:08:50.349 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 20:08:50.363 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 20:08:50.973 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 20:08:50.974 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 20:08:50.974 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (25 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 93.31it/s]

Chain 0:   9%|█████████▏                                                                                             | 32/360 [00:01<00:15, 21.79it/s]

Chain 0:   8%|████████▎                                                                                              | 29/360 [00:01<00:14, 22.41it/s]

Chain 0:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 28.35it/s]

Chain 0:   7%|███████▏                                                                                               | 25/360 [00:00<00:13, 24.41it/s]

Chain 0:  10%|██████████                                                                                             | 35/360 [00:01<00:15, 21.14it/s]

Chain 0:  11%|██████████▊                                                                                            | 38/360 [00:01<00:15, 20.91it/s]

Chain 0:  11%|███████████▋                                                                                           | 41/360 [00:01<00:15, 20.57it/s]

Chain 0:  12%|████████████▌                                                                                          | 44/360 [00:01<00:15, 20.16it/s]

Chain 0:  13%|█████████████▍                                                                                         | 47/360 [00:02<00:15, 20.27it/s]

Chain 0:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:15, 19.83it/s]

Chain 0:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:15, 20.02it/s]

Chain 0:  16%|████████████████                                                                                       | 56/360 [00:02<00:15, 20.14it/s]

Chain 0:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:15, 19.84it/s]

Chain 0:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:14, 20.01it/s]

Chain 0:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:14, 19.87it/s]

Chain 0:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:14, 19.88it/s]

Chain 0:  19%|████████████████████                                                                                   | 70/360 [00:03<00:14, 19.94it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:14, 19.71it/s]

Chain 1:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 89.67it/s]

Chain 0:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:14, 19.94it/s]

Chain 0:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:13, 20.22it/s]

Chain 0:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:14, 19.84it/s]

Chain 0:  23%|███████████████████████▋                                                                               | 83/360 [00:03<00:14, 19.67it/s]

Chain 1:   5%|█████▍                                                                                                 | 19/360 [00:00<00:12, 27.88it/s]

Chain 0:  24%|████████████████████████▌                                                                              | 86/360 [00:04<00:13, 19.82it/s]

Chain 0:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:13, 19.44it/s]

Chain 1:   7%|██████▊                                                                                                | 24/360 [00:00<00:14, 23.69it/s]

Chain 0:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:13, 19.72it/s]

Chain 1:   8%|████████                                                                                               | 28/360 [00:01<00:15, 21.98it/s]

Chain 0:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:14, 19.00it/s]

Chain 0:  26%|███████████████████████████▏                                                                           | 95/360 [00:04<00:14, 18.47it/s]

Chain 1:   9%|████████▊                                                                                              | 31/360 [00:01<00:15, 20.94it/s]

Chain 0:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:14, 18.65it/s]

Chain 0:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:13, 18.75it/s]

Chain 1:   9%|█████████▋                                                                                             | 34/360 [00:01<00:16, 20.28it/s]

Chain 0:  28%|████████████████████████████▌                                                                         | 101/360 [00:04<00:13, 18.56it/s]

Chain 1:  10%|██████████▌                                                                                            | 37/360 [00:01<00:16, 19.92it/s]

Chain 0:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:13, 18.61it/s]

Chain 1:  11%|███████████▍                                                                                           | 40/360 [00:01<00:16, 19.74it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:05<00:13, 18.78it/s]

Chain 0:  30%|██████████████████████████████▎                                                                       | 107/360 [00:05<00:13, 19.05it/s]

Chain 1:  12%|████████████▎                                                                                          | 43/360 [00:01<00:16, 19.45it/s]

Chain 0:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:13, 18.93it/s]

Chain 1:  12%|████████████▉                                                                                          | 45/360 [00:02<00:16, 19.48it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:05<00:13, 19.05it/s]

Chain 1:  13%|█████████████▍                                                                                         | 47/360 [00:02<00:16, 19.34it/s]

Chain 0:  31%|████████████████████████████████                                                                      | 113/360 [00:05<00:12, 19.09it/s]

Chain 1:  14%|██████████████                                                                                         | 49/360 [00:02<00:16, 19.39it/s]

Chain 0:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:12, 19.29it/s]

Chain 1:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:16, 18.82it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:12, 18.86it/s]

Chain 1:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:16, 18.87it/s]

Chain 0:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:12, 19.36it/s]

Chain 1:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:16, 19.03it/s]

Chain 0:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:05<00:12, 19.30it/s]

Chain 1:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 19.26it/s]

Chain 0:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:06<00:12, 19.08it/s]

Chain 1:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:15, 18.86it/s]

Chain 0:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:06<00:12, 19.14it/s]

Chain 1:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:15, 18.77it/s]

Chain 0:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:06<00:12, 19.21it/s]

Chain 1:  18%|██████████████████                                                                                     | 63/360 [00:02<00:15, 18.62it/s]

Chain 0:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:06<00:11, 19.29it/s]

Chain 1:  18%|██████████████████▌                                                                                    | 65/360 [00:03<00:15, 18.75it/s]

Chain 1:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:15, 18.82it/s]

Chain 0:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:11, 19.60it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  19%|███████████████████▋                                                                                   | 69/360 [00:03<00:15, 18.64it/s]

Chain 0:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:11, 19.88it/s]

Chain 2:   3%|██▊                                                                                                    | 10/360 [00:00<00:04, 86.84it/s]

Chain 1:  20%|████████████████████▎                                                                                  | 71/360 [00:03<00:15, 18.33it/s]

Chain 0:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:10, 20.42it/s]

Chain 1:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:15, 18.29it/s]

Chain 1:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:15, 18.50it/s]

Chain 0:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:10, 20.83it/s]

Chain 1:  21%|██████████████████████                                                                                 | 77/360 [00:03<00:15, 18.66it/s]

Chain 0:  40%|█████████████████████████████████████████                                                             | 145/360 [00:07<00:09, 21.53it/s]

Chain 1:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:15, 18.32it/s]

Chain 0:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:07<00:09, 22.28it/s]

Chain 2:   5%|█████▍                                                                                                 | 19/360 [00:00<00:12, 26.31it/s]

Chain 1:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:15, 18.26it/s]

Chain 0:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:07<00:09, 22.83it/s]

Chain 1:  23%|███████████████████████▋                                                                               | 83/360 [00:04<00:15, 18.38it/s]

Chain 0:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:07<00:08, 23.07it/s]

Chain 1:  24%|████████████████████████▎                                                                              | 85/360 [00:04<00:15, 18.13it/s]

Chain 2:   7%|██████▊                                                                                                | 24/360 [00:00<00:14, 22.50it/s]

Chain 0:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:07<00:08, 23.73it/s]

Chain 1:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:15, 17.80it/s]

Chain 0:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:08, 24.24it/s]

Chain 1:  25%|█████████████████████████▍                                                                             | 89/360 [00:04<00:15, 18.00it/s]

Chain 2:   8%|████████                                                                                               | 28/360 [00:01<00:15, 21.16it/s]

Chain 0:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:08, 24.40it/s]

Chain 1:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:14, 18.08it/s]

Chain 2:   9%|████████▊                                                                                              | 31/360 [00:01<00:16, 19.98it/s]

Chain 0:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 24.79it/s]

Chain 1:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:14, 17.88it/s]

Chain 0:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:07, 25.22it/s]

Chain 1:  26%|███████████████████████████▏                                                                           | 95/360 [00:04<00:14, 17.72it/s]

Chain 2:   9%|█████████▋                                                                                             | 34/360 [00:01<00:17, 18.82it/s]

Chain 0:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:08<00:07, 25.07it/s]

Chain 1:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:14, 17.75it/s]

Chain 2:  10%|██████████▌                                                                                            | 37/360 [00:01<00:17, 18.44it/s]

Chain 1:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:14, 17.86it/s]

Chain 0:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:08<00:07, 25.00it/s]

Chain 2:  11%|███████████▏                                                                                           | 39/360 [00:01<00:17, 18.41it/s]

Chain 1:  28%|████████████████████████████▌                                                                         | 101/360 [00:05<00:14, 18.09it/s]

Chain 0:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:08<00:07, 25.76it/s]

Chain 2:  11%|███████████▋                                                                                           | 41/360 [00:01<00:17, 18.39it/s]

Chain 0:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:08<00:06, 26.36it/s]

Chain 1:  29%|█████████████████████████████▏                                                                        | 103/360 [00:05<00:14, 17.75it/s]

Chain 0:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:08<00:06, 27.06it/s]

Chain 2:  12%|████████████▎                                                                                          | 43/360 [00:02<00:17, 18.15it/s]

Chain 1:  29%|█████████████████████████████▊                                                                        | 105/360 [00:05<00:14, 17.43it/s]

Chain 0:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:08<00:06, 27.32it/s]

Chain 2:  12%|████████████▉                                                                                          | 45/360 [00:02<00:17, 18.17it/s]

Chain 1:  30%|██████████████████████████████▎                                                                       | 107/360 [00:05<00:14, 17.53it/s]

Chain 0:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:08<00:06, 27.64it/s]

Chain 2:  13%|█████████████▍                                                                                         | 47/360 [00:02<00:17, 18.11it/s]

Chain 1:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:14, 17.66it/s]

Chain 0:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:08<00:05, 27.83it/s]

Chain 2:  14%|██████████████                                                                                         | 49/360 [00:02<00:17, 17.97it/s]

Chain 1:  31%|███████████████████████████████▍                                                                      | 111/360 [00:05<00:14, 17.71it/s]

Chain 0:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:09<00:05, 28.69it/s]

Chain 2:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:17, 17.70it/s]

Chain 1:  31%|████████████████████████████████                                                                      | 113/360 [00:05<00:13, 18.11it/s]

Chain 0:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:09<00:05, 28.75it/s]

Chain 2:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:17, 17.88it/s]

Chain 1:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:13, 18.19it/s]

Chain 2:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:17, 17.94it/s]

Chain 1:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:13, 18.09it/s]

Chain 0:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:09<00:05, 29.33it/s]

Chain 0:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:09<00:05, 29.49it/s]

Chain 1:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:06<00:13, 18.33it/s]

Chain 2:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:16, 17.85it/s]

Chain 0:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:09<00:05, 28.64it/s]

Chain 1:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:06<00:13, 17.47it/s]

Chain 2:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:17, 16.89it/s]

Chain 1:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:06<00:13, 17.71it/s]

Chain 0:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:09<00:04, 29.61it/s]

Chain 2:  17%|█████████████████▍                                                                                     | 61/360 [00:03<00:17, 17.03it/s]

Chain 1:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:06<00:13, 17.49it/s]

Chain 0:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:09<00:04, 30.50it/s]

Chain 2:  18%|██████████████████                                                                                     | 63/360 [00:03<00:17, 17.04it/s]

Chain 1:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:06<00:13, 17.78it/s]

Chain 2:  18%|██████████████████▌                                                                                    | 65/360 [00:03<00:17, 17.16it/s]

Chain 0:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:09<00:04, 30.79it/s]

Chain 1:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:06<00:13, 17.46it/s]

Chain 2:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:17, 17.06it/s]

Chain 0:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:09<00:04, 31.39it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  36%|█████████████████████████████████████                                                                 | 131/360 [00:06<00:13, 17.56it/s]

Chain 2:  19%|███████████████████▋                                                                                   | 69/360 [00:03<00:17, 16.85it/s]

Chain 0:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:10<00:04, 32.08it/s]

Chain 1:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:12, 17.89it/s]

Chain 3:   3%|██▊                                                                                                    | 10/360 [00:00<00:04, 81.92it/s]

Chain 0:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:10<00:03, 33.10it/s]

Chain 2:  20%|████████████████████▎                                                                                  | 71/360 [00:03<00:17, 16.60it/s]

Chain 1:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:06<00:12, 17.92it/s]

Chain 0:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:10<00:03, 33.85it/s]

Chain 2:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:17, 16.67it/s]

Chain 1:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:07<00:12, 18.18it/s]

Chain 0:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:10<00:03, 35.11it/s]

Chain 2:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:16, 16.87it/s]

Chain 1:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:07<00:11, 19.44it/s]

Chain 0:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:10<00:03, 35.95it/s]

Chain 2:  21%|██████████████████████                                                                                 | 77/360 [00:04<00:16, 16.97it/s]

Chain 0:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:10<00:02, 36.82it/s]

Chain 1:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:07<00:10, 20.10it/s]

Chain 2:  22%|██████████████████████▌                                                                                | 79/360 [00:04<00:17, 16.44it/s]

Chain 3:   5%|█████▍                                                                                                 | 19/360 [00:00<00:13, 24.82it/s]

Chain 0:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:10<00:02, 38.62it/s]

Chain 1:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:07<00:10, 20.65it/s]

Chain 2:  22%|███████████████████████▏                                                                               | 81/360 [00:04<00:16, 16.43it/s]

Chain 0:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:10<00:02, 39.61it/s]

Chain 1:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:07<00:10, 20.95it/s]

Chain 2:  23%|███████████████████████▋                                                                               | 83/360 [00:04<00:17, 16.25it/s]

Chain 0:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:10<00:02, 40.47it/s]

Chain 3:   7%|██████▊                                                                                                | 24/360 [00:00<00:15, 21.13it/s]

Chain 2:  24%|████████████████████████▎                                                                              | 85/360 [00:04<00:16, 16.31it/s]

Chain 1:  42%|███████████████████████████████████████████                                                           | 152/360 [00:07<00:09, 21.42it/s]

Chain 0:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:11<00:02, 42.26it/s]

Chain 2:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:16, 16.15it/s]

Chain 1:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:07<00:09, 21.92it/s]

Chain 0:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:11<00:01, 45.00it/s]

Chain 3:   8%|████████                                                                                               | 28/360 [00:01<00:16, 19.88it/s]

Chain 0:  78%|███████████████████████████████████████████████████████████████████████████████▌                      | 281/360 [00:11<00:01, 46.37it/s]

Chain 2:  25%|█████████████████████████▍                                                                             | 89/360 [00:04<00:16, 16.28it/s]

Chain 1:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:08<00:09, 22.28it/s]

Chain 0:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:11<00:01, 48.60it/s]

Chain 2:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:16, 16.52it/s]

Chain 1:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:08<00:08, 22.94it/s]

Chain 3:   9%|████████▊                                                                                              | 31/360 [00:01<00:17, 18.84it/s]

Chain 0:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:11<00:01, 50.68it/s]

Chain 2:  26%|██████████████████████████▌                                                                            | 93/360 [00:05<00:16, 15.83it/s]

Chain 1:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:08<00:08, 22.54it/s]

Chain 0:  83%|█████████████████████████████████████████████████████████████████████████████████████                 | 300/360 [00:11<00:01, 53.87it/s]

Chain 3:   9%|█████████▋                                                                                             | 34/360 [00:01<00:18, 18.04it/s]

Chain 2:  26%|███████████████████████████▏                                                                           | 95/360 [00:05<00:16, 15.79it/s]

Chain 1:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:08<00:08, 22.95it/s]

Chain 0:  85%|██████████████████████████████████████████████████████████████████████████████████████▉               | 307/360 [00:11<00:00, 58.04it/s]

Chain 3:  10%|██████████▎                                                                                            | 36/360 [00:01<00:18, 17.89it/s]

Chain 2:  27%|███████████████████████████▊                                                                           | 97/360 [00:05<00:16, 16.06it/s]

Chain 1:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:08<00:08, 23.64it/s]

Chain 0:  88%|█████████████████████████████████████████████████████████████████████████████████████████▎            | 315/360 [00:11<00:00, 63.40it/s]

Chain 3:  11%|██████████▊                                                                                            | 38/360 [00:01<00:18, 17.71it/s]

Chain 2:  28%|████████████████████████████▎                                                                          | 99/360 [00:05<00:15, 16.40it/s]

Chain 0:  90%|███████████████████████████████████████████████████████████████████████████████████████████▊          | 324/360 [00:11<00:00, 70.13it/s]

Chain 1:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:08<00:07, 23.90it/s]

Chain 3:  11%|███████████▍                                                                                           | 40/360 [00:01<00:18, 17.60it/s]

Chain 2:  28%|████████████████████████████▌                                                                         | 101/360 [00:05<00:15, 16.61it/s]

Chain 0:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▉       | 335/360 [00:12<00:00, 79.55it/s]

Chain 1:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:08<00:07, 24.27it/s]

Chain 3:  12%|████████████                                                                                           | 42/360 [00:02<00:18, 17.34it/s]

Chain 2:  29%|█████████████████████████████▏                                                                        | 103/360 [00:05<00:15, 16.84it/s]

Chain 0:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████▌   | 348/360 [00:12<00:00, 93.37it/s]

Chain 1:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:08<00:07, 24.21it/s]

Chain 3:  12%|████████████▌                                                                                          | 44/360 [00:02<00:18, 17.29it/s]

Chain 2:  29%|█████████████████████████████▊                                                                        | 105/360 [00:05<00:15, 16.88it/s]

Chain 1:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:09<00:07, 24.72it/s]

Chain 3:  13%|█████████████▏                                                                                         | 46/360 [00:02<00:18, 17.34it/s]

Chain 2:  30%|██████████████████████████████▎                                                                       | 107/360 [00:05<00:15, 16.64it/s]

Chain 1:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:09<00:06, 25.16it/s]

Chain 3:  13%|█████████████▋                                                                                         | 48/360 [00:02<00:18, 17.15it/s]

Chain 2:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:15, 16.23it/s]

Chain 1:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:09<00:06, 24.90it/s]

Chain 3:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:18, 16.58it/s]

Chain 2:  31%|███████████████████████████████▍                                                                      | 111/360 [00:06<00:15, 16.51it/s]

Chain 1:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:09<00:06, 25.40it/s]

Chain 3:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:18, 16.77it/s]

Chain 2:  31%|████████████████████████████████                                                                      | 113/360 [00:06<00:14, 16.77it/s]

Chain 1:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:09<00:06, 25.90it/s]

Chain 3:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:18, 16.95it/s]

Chain 2:  32%|████████████████████████████████▌                                                                     | 115/360 [00:06<00:14, 16.78it/s]

Chain 1:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:09<00:06, 26.37it/s]

Chain 3:  16%|████████████████                                                                                       | 56/360 [00:02<00:18, 16.29it/s]

Chain 1:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:09<00:06, 26.27it/s]

Chain 2:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:06<00:15, 16.12it/s]

Chain 3:  16%|████████████████▌                                                                                      | 58/360 [00:03<00:18, 16.16it/s]

Chain 1:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:09<00:05, 26.75it/s]

Chain 2:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:06<00:14, 16.45it/s]

Chain 3:  17%|█████████████████▏                                                                                     | 60/360 [00:03<00:18, 16.31it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:09<00:06, 23.96it/s]

Chain 2:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:06<00:16, 14.69it/s]

Chain 3:  17%|█████████████████▋                                                                                     | 62/360 [00:03<00:18, 16.26it/s]

Chain 1:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:10<00:06, 24.63it/s]

Chain 2:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:06<00:15, 15.25it/s]

Chain 3:  18%|██████████████████▎                                                                                    | 64/360 [00:03<00:18, 16.19it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:10<00:05, 25.64it/s]

Chain 2:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:06<00:15, 15.53it/s]

Chain 1:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:10<00:05, 26.64it/s]

Chain 3:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:18, 16.32it/s]

Chain 2:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:07<00:14, 16.04it/s]

Chain 3:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:18, 16.21it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:10<00:05, 27.98it/s]

Chain 4:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:07<00:14, 16.49it/s]

Chain 3:  19%|████████████████████                                                                                   | 70/360 [00:03<00:17, 16.67it/s]

Chain 4:   3%|██▊                                                                                                    | 10/360 [00:00<00:04, 81.90it/s]

Chain 1:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:10<00:04, 29.20it/s]

Chain 2:  36%|█████████████████████████████████████                                                                 | 131/360 [00:07<00:13, 17.07it/s]

Chain 3:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:17, 16.48it/s]

Chain 1:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:10<00:04, 29.61it/s]

Chain 2:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:07<00:12, 17.47it/s]

Chain 3:  21%|█████████████████████▏                                                                                 | 74/360 [00:04<00:16, 16.88it/s]

Chain 1:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:10<00:04, 31.17it/s]

Chain 2:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:07<00:12, 17.96it/s]

Chain 3:  21%|█████████████████████▋                                                                                 | 76/360 [00:04<00:16, 16.91it/s]

Chain 2:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:07<00:12, 18.09it/s]

Chain 1:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:10<00:03, 31.48it/s]

Chain 3:  22%|██████████████████████▎                                                                                | 78/360 [00:04<00:17, 16.55it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:11<00:03, 31.71it/s]

Chain 2:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:07<00:11, 19.16it/s]

Chain 4:   5%|█████▍                                                                                                 | 19/360 [00:00<00:13, 24.79it/s]

Chain 3:  22%|██████████████████████▉                                                                                | 80/360 [00:04<00:16, 16.57it/s]

Chain 1:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:11<00:03, 33.29it/s]

Chain 2:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:07<00:10, 20.12it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:04<00:18, 15.28it/s]

Chain 1:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:11<00:03, 31.65it/s]

Chain 2:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:08<00:10, 20.78it/s]

Chain 1:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:11<00:03, 33.44it/s]

Chain 3:  23%|████████████████████████                                                                               | 84/360 [00:04<00:17, 15.78it/s]

Chain 4:   7%|██████▊                                                                                                | 24/360 [00:01<00:15, 21.02it/s]

Chain 2:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:08<00:09, 21.27it/s]

Chain 1:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:11<00:02, 35.72it/s]

Chain 3:  24%|████████████████████████▌                                                                              | 86/360 [00:04<00:16, 16.34it/s]

Chain 2:  42%|███████████████████████████████████████████                                                           | 152/360 [00:08<00:09, 21.76it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:11<00:02, 38.03it/s]

Chain 3:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:16, 16.43it/s]

Chain 4:   8%|████████                                                                                               | 28/360 [00:01<00:17, 19.50it/s]

Chain 2:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:08<00:09, 22.07it/s]

Chain 1:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:11<00:02, 39.45it/s]

Chain 3:  25%|█████████████████████████▊                                                                             | 90/360 [00:05<00:16, 16.66it/s]

Chain 2:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:08<00:09, 22.26it/s]

Chain 1:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:11<00:02, 41.38it/s]

Chain 4:   9%|████████▊                                                                                              | 31/360 [00:01<00:17, 18.32it/s]

Chain 3:  26%|██████████████████████████▎                                                                            | 92/360 [00:05<00:16, 16.67it/s]

Chain 1:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:11<00:01, 42.72it/s]

Chain 2:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:08<00:09, 21.87it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:05<00:16, 15.94it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████▌                      | 281/360 [00:12<00:01, 43.95it/s]

Chain 4:   9%|█████████▋                                                                                             | 34/360 [00:01<00:18, 17.35it/s]

Chain 2:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:08<00:08, 22.15it/s]

Chain 3:  27%|███████████████████████████▍                                                                           | 96/360 [00:05<00:16, 15.84it/s]

Chain 1:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:12<00:01, 45.98it/s]

Chain 4:  10%|██████████▎                                                                                            | 36/360 [00:01<00:18, 17.20it/s]

Chain 2:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:08<00:08, 22.68it/s]

Chain 3:  27%|████████████████████████████                                                                           | 98/360 [00:05<00:16, 15.86it/s]

Chain 1:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:12<00:01, 47.63it/s]

Chain 4:  11%|██████████▊                                                                                            | 38/360 [00:01<00:19, 16.75it/s]

Chain 2:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:09<00:08, 23.08it/s]

Chain 3:  28%|████████████████████████████▎                                                                         | 100/360 [00:05<00:16, 15.93it/s]

Chain 1:  83%|████████████████████████████████████████████████████████████████████████████████████▋                 | 299/360 [00:12<00:01, 50.47it/s]

Chain 4:  11%|███████████▍                                                                                           | 40/360 [00:02<00:19, 16.32it/s]

Chain 2:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:09<00:07, 23.51it/s]

Chain 3:  28%|████████████████████████████▉                                                                         | 102/360 [00:05<00:15, 16.15it/s]

Chain 1:  85%|██████████████████████████████████████████████████████████████████████████████████████▋               | 306/360 [00:12<00:00, 54.46it/s]

Chain 4:  12%|████████████                                                                                           | 42/360 [00:02<00:19, 16.07it/s]

Chain 1:  87%|████████████████████████████████████████████████████████████████████████████████████████▋             | 313/360 [00:12<00:00, 58.41it/s]

Chain 2:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:09<00:07, 23.74it/s]

Chain 3:  29%|█████████████████████████████▍                                                                        | 104/360 [00:05<00:15, 16.01it/s]

Chain 4:  12%|████████████▌                                                                                          | 44/360 [00:02<00:19, 16.17it/s]

Chain 1:  89%|██████████████████████████████████████████████████████████████████████████████████████████▋           | 320/360 [00:12<00:00, 61.65it/s]

Chain 2:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:09<00:07, 23.38it/s]

Chain 3:  29%|██████████████████████████████                                                                        | 106/360 [00:06<00:15, 16.04it/s]

Chain 1:  91%|████████████████████████████████████████████████████████████████████████████████████████████▉         | 328/360 [00:12<00:00, 64.97it/s]

Chain 4:  13%|█████████████▏                                                                                         | 46/360 [00:02<00:19, 16.25it/s]

Chain 2:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:09<00:07, 23.84it/s]

Chain 3:  30%|██████████████████████████████▌                                                                       | 108/360 [00:06<00:15, 16.06it/s]

Chain 1:  94%|████████████████████████████████████████████████████████████████████████████████████████████████      | 339/360 [00:12<00:00, 76.34it/s]

Chain 4:  13%|█████████████▋                                                                                         | 48/360 [00:02<00:19, 16.37it/s]

Chain 2:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:09<00:07, 23.65it/s]

Chain 3:  31%|███████████████████████████████▏                                                                      | 110/360 [00:06<00:15, 15.85it/s]

Chain 1:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████  | 353/360 [00:13<00:00, 93.10it/s]

Chain 4:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:19, 15.99it/s]

Chain 2:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:09<00:07, 24.08it/s]

Chain 3:  31%|███████████████████████████████▋                                                                      | 112/360 [00:06<00:15, 16.11it/s]

Chain 4:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:19, 15.49it/s]

Chain 2:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:09<00:07, 24.13it/s]

Chain 3:  32%|████████████████████████████████▎                                                                     | 114/360 [00:06<00:14, 16.46it/s]

Chain 4:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:19, 15.43it/s]

Chain 2:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:10<00:06, 24.41it/s]

Chain 3:  32%|████████████████████████████████▊                                                                     | 116/360 [00:06<00:15, 16.23it/s]

Chain 2:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:10<00:06, 25.01it/s]

Chain 4:  16%|████████████████                                                                                       | 56/360 [00:03<00:19, 15.23it/s]

Chain 3:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:06<00:14, 16.17it/s]

Chain 2:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:10<00:06, 24.54it/s]

Chain 3:  33%|██████████████████████████████████                                                                    | 120/360 [00:06<00:15, 15.99it/s]

Chain 4:  16%|████████████████▌                                                                                      | 58/360 [00:03<00:20, 14.40it/s]

Chain 2:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:10<00:06, 24.32it/s]

Chain 3:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:07<00:15, 15.70it/s]

Chain 4:  17%|█████████████████▏                                                                                     | 60/360 [00:03<00:20, 14.49it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:10<00:06, 25.07it/s]

Chain 3:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:07<00:15, 15.66it/s]

Chain 4:  17%|█████████████████▋                                                                                     | 62/360 [00:03<00:20, 14.81it/s]

Chain 2:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:10<00:05, 25.94it/s]

Chain 3:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:07<00:15, 15.60it/s]

Chain 4:  18%|██████████████████▎                                                                                    | 64/360 [00:03<00:20, 14.25it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:10<00:05, 25.85it/s]

Chain 5:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 3:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:07<00:14, 15.60it/s]

Chain 2:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:10<00:05, 26.07it/s]

Chain 4:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:20, 14.06it/s]

Chain 3:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:07<00:14, 15.67it/s]

Chain 5:   3%|██▊                                                                                                    | 10/360 [00:00<00:05, 67.90it/s]

Chain 2:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:11<00:05, 26.40it/s]

Chain 4:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:20, 14.24it/s]

Chain 3:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:07<00:14, 16.15it/s]

Chain 2:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:11<00:04, 27.88it/s]

Chain 4:  19%|████████████████████                                                                                   | 70/360 [00:04<00:19, 14.62it/s]

Chain 3:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:07<00:13, 16.49it/s]

Chain 2:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:11<00:04, 29.12it/s]

Chain 4:  20%|████████████████████▌                                                                                  | 72/360 [00:04<00:19, 14.75it/s]

Chain 3:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:07<00:13, 17.09it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:11<00:04, 30.55it/s]

Chain 5:   5%|████▊                                                                                                  | 17/360 [00:00<00:13, 25.99it/s]

Chain 3:  38%|███████████████████████████████████████                                                               | 138/360 [00:07<00:12, 17.51it/s]

Chain 4:  21%|█████████████████████▏                                                                                 | 74/360 [00:04<00:18, 15.15it/s]

Chain 2:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:11<00:03, 31.91it/s]

Chain 3:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:08<00:12, 17.55it/s]

Chain 4:  21%|█████████████████████▋                                                                                 | 76/360 [00:04<00:19, 14.90it/s]

Chain 2:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:11<00:03, 31.61it/s]

Chain 3:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:08<00:12, 17.80it/s]

Chain 5:   6%|██████                                                                                                 | 21/360 [00:00<00:16, 21.08it/s]

Chain 4:  22%|██████████████████████▎                                                                                | 78/360 [00:04<00:18, 15.24it/s]

Chain 2:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:11<00:03, 32.74it/s]

Chain 3:  40%|█████████████████████████████████████████                                                             | 145/360 [00:08<00:11, 19.07it/s]

Chain 2:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:11<00:03, 34.11it/s]

Chain 4:  22%|██████████████████████▉                                                                                | 80/360 [00:04<00:18, 15.14it/s]

Chain 5:   7%|██████▊                                                                                                | 24/360 [00:01<00:16, 19.95it/s]

Chain 3:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:08<00:10, 20.05it/s]

Chain 2:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:11<00:03, 35.38it/s]

Chain 4:  23%|███████████████████████▍                                                                               | 82/360 [00:04<00:18, 15.00it/s]

Chain 2:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:12<00:02, 37.21it/s]

Chain 5:   8%|███████▋                                                                                               | 27/360 [00:01<00:17, 18.79it/s]

Chain 3:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:08<00:10, 20.36it/s]

Chain 4:  23%|████████████████████████                                                                               | 84/360 [00:04<00:17, 15.40it/s]

Chain 2:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:12<00:02, 38.66it/s]

Chain 3:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:08<00:09, 21.04it/s]

Chain 4:  24%|████████████████████████▌                                                                              | 86/360 [00:05<00:17, 15.79it/s]

Chain 5:   8%|████████▌                                                                                              | 30/360 [00:01<00:18, 18.13it/s]

Chain 2:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:12<00:02, 40.39it/s]

Chain 3:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:08<00:09, 21.36it/s]

Chain 4:  24%|█████████████████████████▏                                                                             | 88/360 [00:05<00:17, 15.82it/s]

Chain 5:   9%|█████████▏                                                                                             | 32/360 [00:01<00:18, 17.96it/s]

Chain 2:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:12<00:02, 41.34it/s]

Chain 4:  25%|█████████████████████████▊                                                                             | 90/360 [00:05<00:16, 15.97it/s]

Chain 3:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:09<00:09, 21.67it/s]

Chain 5:   9%|█████████▋                                                                                             | 34/360 [00:01<00:18, 17.63it/s]

Chain 2:  76%|█████████████████████████████████████████████████████████████████████████████▉                        | 275/360 [00:12<00:01, 43.35it/s]

Chain 4:  26%|██████████████████████████▎                                                                            | 92/360 [00:05<00:16, 16.13it/s]

Chain 5:  10%|██████████▎                                                                                            | 36/360 [00:01<00:18, 17.61it/s]

Chain 3:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:09<00:08, 22.25it/s]

Chain 2:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:12<00:01, 44.17it/s]

Chain 4:  26%|██████████████████████████▉                                                                            | 94/360 [00:05<00:16, 16.16it/s]

Chain 5:  11%|██████████▊                                                                                            | 38/360 [00:01<00:18, 17.47it/s]

Chain 2:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:12<00:01, 45.21it/s]

Chain 3:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:09<00:08, 22.68it/s]

Chain 2:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:12<00:01, 46.18it/s]

Chain 5:  11%|███████████▍                                                                                           | 40/360 [00:01<00:18, 17.44it/s]

Chain 4:  27%|███████████████████████████▍                                                                           | 96/360 [00:05<00:16, 15.79it/s]

Chain 3:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:09<00:08, 22.91it/s]

Chain 2:  82%|███████████████████████████████████████████████████████████████████████████████████▊                  | 296/360 [00:12<00:01, 49.92it/s]

Chain 5:  12%|████████████                                                                                           | 42/360 [00:02<00:18, 17.14it/s]

Chain 4:  27%|████████████████████████████                                                                           | 98/360 [00:05<00:16, 15.60it/s]

Chain 3:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:09<00:08, 22.50it/s]

Chain 2:  84%|█████████████████████████████████████████████████████████████████████████████████████▌                | 302/360 [00:13<00:01, 51.05it/s]

Chain 5:  12%|████████████▌                                                                                          | 44/360 [00:02<00:19, 16.09it/s]

Chain 4:  28%|████████████████████████████▎                                                                         | 100/360 [00:05<00:17, 15.29it/s]

Chain 3:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:09<00:08, 22.89it/s]

Chain 2:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:13<00:00, 54.55it/s]

Chain 5:  13%|█████████████▏                                                                                         | 46/360 [00:02<00:19, 16.24it/s]

Chain 4:  28%|████████████████████████████▉                                                                         | 102/360 [00:06<00:16, 15.56it/s]

Chain 3:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:09<00:07, 23.18it/s]

Chain 2:  88%|█████████████████████████████████████████████████████████████████████████████████████████▌            | 316/360 [00:13<00:00, 58.48it/s]

Chain 5:  13%|█████████████▋                                                                                         | 48/360 [00:02<00:19, 16.33it/s]

Chain 4:  29%|█████████████████████████████▍                                                                        | 104/360 [00:06<00:16, 15.79it/s]

Chain 2:  90%|███████████████████████████████████████████████████████████████████████████████████████████▊          | 324/360 [00:13<00:00, 63.61it/s]

Chain 3:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:09<00:07, 23.62it/s]

Chain 5:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:19, 16.11it/s]

Chain 2:  92%|██████████████████████████████████████████████████████████████████████████████████████████████▎       | 333/360 [00:13<00:00, 70.82it/s]

Chain 4:  29%|██████████████████████████████                                                                        | 106/360 [00:06<00:15, 16.11it/s]

Chain 3:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:10<00:07, 23.30it/s]

Chain 2:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████▊    | 345/360 [00:13<00:00, 83.45it/s]

Chain 5:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:18, 16.23it/s]

Chain 4:  30%|██████████████████████████████▌                                                                       | 108/360 [00:06<00:15, 15.94it/s]

Chain 3:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:10<00:07, 23.97it/s]

Chain 5:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:18, 16.70it/s]

Chain 4:  31%|███████████████████████████████▏                                                                      | 110/360 [00:06<00:15, 16.34it/s]

Chain 3:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:10<00:06, 24.90it/s]

Chain 5:  16%|████████████████                                                                                       | 56/360 [00:02<00:17, 17.11it/s]

Chain 4:  31%|███████████████████████████████▋                                                                      | 112/360 [00:06<00:14, 16.84it/s]

Chain 3:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:10<00:06, 25.88it/s]

Chain 5:  16%|████████████████▌                                                                                      | 58/360 [00:03<00:17, 17.13it/s]

Chain 3:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:10<00:06, 26.81it/s]

Chain 4:  32%|████████████████████████████████▎                                                                     | 114/360 [00:06<00:14, 17.19it/s]

Chain 5:  17%|█████████████████▏                                                                                     | 60/360 [00:03<00:17, 17.54it/s]

Chain 3:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:10<00:05, 27.30it/s]

Chain 4:  32%|████████████████████████████████▊                                                                     | 116/360 [00:06<00:14, 17.20it/s]

Chain 5:  17%|█████████████████▋                                                                                     | 62/360 [00:03<00:16, 17.88it/s]

Chain 4:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:07<00:13, 17.47it/s]

Chain 3:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:10<00:05, 28.38it/s]

Chain 5:  18%|██████████████████▎                                                                                    | 64/360 [00:03<00:16, 17.95it/s]

Chain 4:  33%|██████████████████████████████████                                                                    | 120/360 [00:07<00:13, 17.73it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:10<00:05, 29.35it/s]

Chain 5:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:16, 18.19it/s]

Chain 4:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:07<00:13, 17.73it/s]

Chain 3:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:10<00:05, 29.36it/s]

Chain 5:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:15, 18.37it/s]

Chain 4:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:07<00:13, 17.66it/s]

Chain 3:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:11<00:04, 30.40it/s]

Chain 5:  19%|████████████████████                                                                                   | 70/360 [00:03<00:15, 18.49it/s]

Chain 4:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:07<00:12, 18.01it/s]

Chain 5:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:15, 18.43it/s]

Chain 3:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:11<00:04, 31.18it/s]

Chain 4:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:07<00:12, 18.26it/s]

Chain 5:  21%|█████████████████████▏                                                                                 | 74/360 [00:03<00:15, 18.20it/s]

Chain 3:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:11<00:04, 32.03it/s]

Chain 4:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:07<00:12, 18.38it/s]

Chain 5:  21%|█████████████████████▋                                                                                 | 76/360 [00:04<00:15, 18.44it/s]

Chain 3:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:11<00:04, 33.03it/s]

Chain 4:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:07<00:11, 19.18it/s]

Chain 3:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:11<00:03, 34.12it/s]

Chain 5:  22%|██████████████████████▌                                                                                | 79/360 [00:04<00:14, 18.86it/s]

Chain 4:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:07<00:11, 19.67it/s]

Chain 3:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:11<00:03, 34.97it/s]

Chain 5:  22%|███████████████████████▏                                                                               | 81/360 [00:04<00:14, 18.97it/s]

Chain 3:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:11<00:03, 36.15it/s]

Chain 4:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:08<00:10, 20.32it/s]

Chain 5:  23%|███████████████████████▋                                                                               | 83/360 [00:04<00:14, 19.09it/s]

Chain 3:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:11<00:03, 37.05it/s]

Chain 5:  24%|████████████████████████▎                                                                              | 85/360 [00:04<00:14, 19.18it/s]

Chain 4:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:08<00:10, 20.93it/s]

Chain 3:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:11<00:03, 37.60it/s]

Chain 5:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:14, 18.22it/s]

Chain 4:  40%|█████████████████████████████████████████                                                             | 145/360 [00:08<00:09, 21.54it/s]

Chain 3:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:12<00:02, 39.34it/s]

Chain 5:  25%|█████████████████████████▊                                                                             | 90/360 [00:04<00:14, 18.91it/s]

Chain 4:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:08<00:09, 22.20it/s]

Chain 3:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:12<00:02, 41.01it/s]

Chain 5:  26%|██████████████████████████▎                                                                            | 92/360 [00:04<00:14, 18.88it/s]

Chain 3:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:12<00:02, 42.36it/s]

Chain 4:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:08<00:09, 22.32it/s]

Chain 5:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:13, 19.00it/s]

Chain 3:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:12<00:02, 44.13it/s]

Chain 4:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:08<00:09, 22.80it/s]

Chain 5:  27%|███████████████████████████▍                                                                           | 96/360 [00:05<00:14, 18.62it/s]

Chain 3:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:12<00:01, 45.47it/s]

Chain 4:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:08<00:08, 22.97it/s]

Chain 5:  27%|████████████████████████████                                                                           | 98/360 [00:05<00:13, 18.89it/s]

Chain 3:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:12<00:01, 46.76it/s]

Chain 4:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:09<00:08, 23.53it/s]

Chain 5:  28%|████████████████████████████▎                                                                         | 100/360 [00:05<00:13, 18.88it/s]

Chain 3:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:12<00:01, 49.59it/s]

Chain 5:  28%|████████████████████████████▉                                                                         | 102/360 [00:05<00:13, 18.95it/s]

Chain 4:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:09<00:08, 23.93it/s]

Chain 3:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:12<00:01, 52.49it/s]

Chain 5:  29%|█████████████████████████████▍                                                                        | 104/360 [00:05<00:13, 19.03it/s]

Chain 3:  82%|███████████████████████████████████████████████████████████████████████████████████▊                  | 296/360 [00:12<00:01, 55.96it/s]

Chain 4:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:09<00:08, 24.00it/s]

Chain 5:  29%|██████████████████████████████                                                                        | 106/360 [00:05<00:13, 18.31it/s]

Chain 3:  84%|█████████████████████████████████████████████████████████████████████████████████████▊                | 303/360 [00:13<00:00, 58.43it/s]

Chain 4:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:09<00:07, 24.40it/s]

Chain 5:  30%|██████████████████████████████▌                                                                       | 108/360 [00:05<00:13, 18.03it/s]

Chain 3:  86%|████████████████████████████████████████████████████████████████████████████████████████              | 311/360 [00:13<00:00, 62.77it/s]

Chain 4:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:09<00:07, 24.71it/s]

Chain 5:  31%|███████████████████████████████▏                                                                      | 110/360 [00:05<00:13, 18.07it/s]

Chain 3:  89%|██████████████████████████████████████████████████████████████████████████████████████████▋           | 320/360 [00:13<00:00, 68.79it/s]

Chain 4:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:09<00:07, 24.77it/s]

Chain 5:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:13, 18.32it/s]

Chain 3:  92%|█████████████████████████████████████████████████████████████████████████████████████████████▌        | 330/360 [00:13<00:00, 77.00it/s]

Chain 4:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:09<00:07, 25.07it/s]

Chain 3:  95%|████████████████████████████████████████████████████████████████████████████████████████████████▉     | 342/360 [00:13<00:00, 89.28it/s]

Chain 5:  32%|████████████████████████████████▎                                                                     | 114/360 [00:06<00:13, 18.44it/s]

Chain 4:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:09<00:07, 25.51it/s]

Chain 5:  32%|████████████████████████████████▊                                                                     | 116/360 [00:06<00:13, 18.28it/s]

Chain 4:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:09<00:06, 26.11it/s]

Chain 5:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:06<00:13, 18.60it/s]

Chain 4:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:10<00:06, 26.51it/s]

Chain 5:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:06<00:12, 19.12it/s]

Chain 4:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:10<00:06, 27.26it/s]

Chain 5:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:06<00:12, 19.33it/s]

Chain 4:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:10<00:05, 28.01it/s]

Chain 5:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:06<00:12, 19.14it/s]

Chain 4:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:10<00:05, 28.35it/s]

Chain 4:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:10<00:05, 29.37it/s]

Chain 5:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:06<00:11, 19.70it/s]

Chain 4:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:10<00:05, 29.50it/s]

Chain 5:  36%|█████████████████████████████████████                                                                 | 131/360 [00:06<00:11, 20.10it/s]

Chain 4:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:10<00:05, 30.38it/s]

Chain 5:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:07<00:10, 20.57it/s]

Chain 4:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:10<00:04, 31.19it/s]

Chain 5:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:07<00:10, 20.55it/s]

Chain 4:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:10<00:04, 31.46it/s]

Chain 5:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:07<00:10, 21.51it/s]

Chain 4:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:11<00:04, 32.59it/s]

Chain 5:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:07<00:09, 22.20it/s]

Chain 4:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:11<00:04, 32.71it/s]

Chain 5:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:07<00:09, 22.95it/s]

Chain 4:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:11<00:03, 33.63it/s]

Chain 4:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:11<00:03, 34.81it/s]

Chain 5:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:07<00:09, 23.22it/s]

Chain 4:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:11<00:03, 35.68it/s]

Chain 5:  42%|███████████████████████████████████████████                                                           | 152/360 [00:07<00:08, 23.65it/s]

Chain 4:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:11<00:03, 37.35it/s]

Chain 5:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:07<00:08, 24.21it/s]

Chain 4:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:11<00:02, 39.01it/s]

Chain 5:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:08<00:08, 24.53it/s]

Chain 4:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:11<00:02, 40.27it/s]

Chain 5:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:08<00:08, 24.64it/s]

Chain 4:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:11<00:02, 41.08it/s]

Chain 5:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:08<00:07, 24.94it/s]

Chain 4:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:12<00:02, 42.60it/s]

Chain 5:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:08<00:07, 24.26it/s]

Chain 4:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:12<00:02, 44.33it/s]

Chain 5:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:08<00:07, 24.39it/s]

Chain 4:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:12<00:01, 46.13it/s]

Chain 5:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:08<00:07, 25.06it/s]

Chain 4:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:12<00:01, 48.80it/s]

Chain 5:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:08<00:07, 25.61it/s]

Chain 4:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:12<00:01, 50.55it/s]

Chain 5:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:08<00:06, 25.98it/s]

Chain 4:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:12<00:01, 52.81it/s]

Chain 5:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:09<00:06, 26.55it/s]

Chain 4:  82%|███████████████████████████████████████████████████████████████████████████████████▊                  | 296/360 [00:12<00:01, 56.80it/s]

Chain 5:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:09<00:06, 27.25it/s]

Chain 4:  84%|█████████████████████████████████████████████████████████████████████████████████████▊                | 303/360 [00:12<00:00, 60.48it/s]

Chain 5:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:09<00:06, 27.64it/s]

Chain 4:  86%|████████████████████████████████████████████████████████████████████████████████████████              | 311/360 [00:12<00:00, 65.51it/s]

Chain 5:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:09<00:06, 28.17it/s]

Chain 4:  89%|██████████████████████████████████████████████████████████████████████████████████████████▉           | 321/360 [00:13<00:00, 74.27it/s]

Chain 5:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:09<00:05, 29.13it/s]

Chain 4:  92%|██████████████████████████████████████████████████████████████████████████████████████████████▎       | 333/360 [00:13<00:00, 85.58it/s]

Chain 4:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████▉   | 349/360 [00:13<00:00, 106.64it/s]

Chain 5:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:09<00:05, 29.94it/s]

Chain 5:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:09<00:05, 30.10it/s]

Chain 5:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:09<00:04, 31.08it/s]

Chain 5:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:09<00:04, 31.80it/s]

Chain 5:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:10<00:04, 32.30it/s]

Chain 5:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:10<00:04, 33.27it/s]

Chain 5:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:10<00:04, 34.22it/s]

Chain 5:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:10<00:03, 35.26it/s]

Chain 5:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:10<00:03, 35.57it/s]

Chain 5:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:10<00:03, 36.01it/s]

Chain 5:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:10<00:03, 35.86it/s]

Chain 5:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:10<00:03, 37.89it/s]

Chain 5:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:10<00:02, 39.33it/s]

Chain 5:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:11<00:02, 40.68it/s]

Chain 5:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:11<00:02, 42.69it/s]

Chain 5:  73%|██████████████████████████████████████████████████████████████████████████▊                           | 264/360 [00:11<00:02, 44.53it/s]

Chain 5:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:11<00:01, 46.96it/s]

Chain 5:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:11<00:01, 49.31it/s]

Chain 5:  78%|███████████████████████████████████████████████████████████████████████████████▉                      | 282/360 [00:11<00:01, 52.01it/s]

Chain 5:  80%|█████████████████████████████████████████████████████████████████████████████████▌                    | 288/360 [00:11<00:01, 54.28it/s]

Chain 5:  82%|███████████████████████████████████████████████████████████████████████████████████▌                  | 295/360 [00:11<00:01, 58.31it/s]

Chain 5:  84%|█████████████████████████████████████████████████████████████████████████████████████▊                | 303/360 [00:11<00:00, 63.43it/s]

Chain 5:  87%|████████████████████████████████████████████████████████████████████████████████████████▍             | 312/360 [00:12<00:00, 69.45it/s]

Chain 5:  89%|███████████████████████████████████████████████████████████████████████████████████████████▏          | 322/360 [00:12<00:00, 77.47it/s]

Chain 5:  92%|██████████████████████████████████████████████████████████████████████████████████████████████▎       | 333/360 [00:12<00:00, 86.67it/s]

Chain 5:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████▋   | 348/360 [00:12<00:00, 104.57it/s]

2026-05-28 20:09:28.575 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 20:09:29.019 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 20:09:32.790 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 20:09:33.158 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 20:09:33.158 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 20:09:33.162 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 20:09:34.020 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 20:09:34.054 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 20:09:34.513 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 20:09:35.259 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 20:09:36.054 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 20:09:36.187 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 20:09:36.188 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,97.2,166.8,281.2,447.4,620.4
GIIP (mscf),Total Volumes,1.0,38.4,69.2,123.4,203.1,305.9
Condensate (stb),Total Volumes,1.0,1.1,2.2,4.3,7.9,13.7
Solution Gas (mscf),Total Volumes,1.0,157.9,286.5,520.3,854.7,1237.7

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50    P10     P1
Total Oil EUR         1.0  21.5  37.3  64.5  102.7  148.6

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.38  1.0  3.1  9.3  24.9  57.3
Zone 2           0.59  1.0  2.8  8.4  21.1  41.6
Zone 3           0.53  0.4  1.9  6.4  18.0  42.2
Zone 4           0.50  0.9  2.6  7.1  18.7  38.7
Zone 5           0.79  0.7  2.2  7.5  22.5  52.9
Zone 6           0.76  0.9  2.8  7.6  19.7  39.7
Zone 7           0.53  1.1  2.5  6.0  13.2  24.2
Zone 8           0.72  1.0  2.6  7.0  16.4  34.5
Zone 9           0.79  0.9  2.7  7.9  23.3  50.8
Zone 10          0.59  0.5  1.9  6.1  15.9  36.9
Zone 11          0.47  0.6  2.2  6.8  17.8  37.9
Zone 12          0.68  0.7  2.0  5.1  11.0  19.2

In [14]:
reporter.tabler.npv_table()

     P(Commercial)   P99    P90     P50     P10      P1
NPV           0.98 -70.0  455.0  1195.0  1959.0  2608.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)   P99    P90     P50     P10      P1
EMV           0.98 -69.0  447.0  1174.0  1925.0  2564.0

In [16]:
from resgo.plotting.tables import npv_USD
import numpy as np
import pandas as pd

npv = npv_USD(
    simpack,
    nominal=True,
    discounted=True,
    success_only=False,
)
npv_usd = npv.to_numpy().ravel()
npv_df = pd.DataFrame({"npv_usd_mm": npv_usd / 1e6})

histogram = (
    alt.Chart(npv_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Nominal discounted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Project NPV Distribution",
    )
)

break_even = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(histogram, break_even)
fig.show()

alt.LayerChart(...)

In [17]:
BANKRUPTCY_THRESHOLD_USD = 300e6
LOSS_FLOOR_USD = -5e9

def loss_adjusted_npv_USD(
    npv_usd,
    bankruptcy_threshold_usd=BANKRUPTCY_THRESHOLD_USD,
    floor_usd=LOSS_FLOOR_USD,
):
    npv_usd = np.asarray(npv_usd)
    threshold = bankruptcy_threshold_usd

    with np.errstate(divide="ignore", invalid="ignore"):
        adjusted = np.where(
            npv_usd >= 0,
            npv_usd,
            (threshold * npv_usd) / (threshold + npv_usd),
        )

    adjusted = np.where(npv_usd <= -threshold, floor_usd, adjusted)
    return np.maximum(adjusted, floor_usd)

x_usd = np.linspace(-0.9999 * BANKRUPTCY_THRESHOLD_USD, 1.5e9, 1_000)
loss_function_df = pd.DataFrame(
    {
        "npv_usd_mm": x_usd / 1e6,
        "loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(x_usd) / 1e6,
    }
)

loss_function = (
    alt.Chart(loss_function_df)
    .mark_line(color="#FACC15", strokeWidth=3)
    .encode(
        x=alt.X("npv_usd_mm:Q", title="Nominal discounted NPV ($USD MM)"),
        y=alt.Y(
            "loss_adjusted_npv_usd_mm:Q",
            title="Loss-adjusted NPV ($USD MM)",
        ),
        tooltip=[
            alt.Tooltip("npv_usd_mm:Q", title="NPV ($MM)", format=",.0f"),
            alt.Tooltip(
                "loss_adjusted_npv_usd_mm:Q",
                title="Loss-adjusted NPV ($MM)",
                format=",.0f",
            ),
        ],
    )
    .properties(
        width=650,
        height=250,
        title="Company Loss Function",
    )
)

bankruptcy_threshold = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [-BANKRUPTCY_THRESHOLD_USD / 1e6]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

loss_floor = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [LOSS_FLOOR_USD / 1e6]}))
    .mark_rule(color="red", strokeDash=[2, 4], strokeWidth=1)
    .encode(y="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_function, bankruptcy_threshold, loss_floor)
fig.show()

alt.LayerChart(...)

In [18]:
loss_df = pd.DataFrame(
    {"loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(npv_usd) / 1e6}
)

loss_histogram = (
    alt.Chart(loss_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "loss_adjusted_npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Loss-adjusted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated Loss-Adjusted NPV Distribution",
    )
)

break_even_loss = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_histogram, break_even_loss)
fig.show()

alt.LayerChart(...)