In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_646523/1985460196.py:25: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats(fig_format)

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 41

CHAINS = 10
DRAWS = 500
N_RESERVOIRS = 10
N_PRODUCERS = 25

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=60_000,
    gas_development=False,
    producer_capex_USD=80e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=350e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2e6,
    producer_abandonment_cost_USD=0.5e6,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 22:09:56.811 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 22:09:56.815 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 22:09:56.819 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 22:09:56.824 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 22:09:56.828 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 22:09:56.832 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 22:09:56.837 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 7 reservoir volumetric simulation complete.

2026-05-28 22:09:56.841 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 8 reservoir volumetric simulation complete.

2026-05-28 22:09:56.845 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 9 reservoir volumetric simulation complete.

2026-05-28 22:09:56.851 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 10 reservoir volumetric simulation complete.

2026-05-28 22:09:56.856 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 22:09:56.856 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 22:09:57.681 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 22:09:57.682 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 22:09:57.682 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 22:09:57.682 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 22:09:57.682 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 22:09:57.682 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 22:09:57.682 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 22:09:57.683 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 21 start_idx = 245

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 22 start_idx = 257

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 23 start_idx = 269

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 24 start_idx = 280

2026-05-28 22:09:57.684 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 25 start_idx = 292

2026-05-28 22:09:57.724 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 22:09:57.739 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 22:09:58.431 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 22:09:58.432 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 22:09:58.432 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (25 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 83.23it/s]

Chain 0:   8%|████████▎                                                                                              | 29/360 [00:00<00:11, 27.62it/s]

Chain 0:   7%|███████▏                                                                                               | 25/360 [00:00<00:11, 29.74it/s]

Chain 0:   6%|█████▋                                                                                                 | 20/360 [00:00<00:10, 33.75it/s]

Chain 0:   9%|█████████▍                                                                                             | 33/360 [00:01<00:12, 25.86it/s]

Chain 0:  10%|██████████▎                                                                                            | 36/360 [00:01<00:13, 24.39it/s]

Chain 0:  11%|███████████▏                                                                                           | 39/360 [00:01<00:13, 23.96it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:01<00:13, 23.98it/s]

Chain 0:  12%|████████████▉                                                                                          | 45/360 [00:01<00:13, 24.09it/s]

Chain 0:  13%|█████████████▋                                                                                         | 48/360 [00:01<00:13, 23.66it/s]

Chain 0:  14%|██████████████▌                                                                                        | 51/360 [00:01<00:13, 23.71it/s]

Chain 0:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:12, 23.90it/s]

Chain 0:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:12, 24.01it/s]

Chain 0:  18%|██████████████████                                                                                     | 63/360 [00:02<00:12, 23.53it/s]

Chain 0:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:12, 23.39it/s]

Chain 0:  18%|██████████████████▉                                                                                    | 66/360 [00:02<00:12, 23.46it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  19%|███████████████████▋                                                                                   | 69/360 [00:02<00:12, 23.37it/s]

Chain 1:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 79.25it/s]

Chain 0:  20%|████████████████████▌                                                                                  | 72/360 [00:02<00:12, 23.55it/s]

Chain 0:  21%|█████████████████████▍                                                                                 | 75/360 [00:02<00:11, 23.92it/s]

Chain 0:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:11, 24.09it/s]

Chain 1:   5%|█████▍                                                                                                 | 19/360 [00:00<00:10, 33.77it/s]

Chain 0:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:11, 24.27it/s]

Chain 0:  23%|████████████████████████                                                                               | 84/360 [00:03<00:11, 24.25it/s]

Chain 1:   7%|██████▊                                                                                                | 24/360 [00:00<00:11, 28.85it/s]

Chain 0:  24%|████████████████████████▉                                                                              | 87/360 [00:03<00:11, 23.77it/s]

Chain 0:  25%|█████████████████████████▊                                                                             | 90/360 [00:03<00:11, 23.69it/s]

Chain 1:   8%|████████                                                                                               | 28/360 [00:00<00:12, 26.88it/s]

Chain 0:  26%|██████████████████████████▌                                                                            | 93/360 [00:03<00:11, 23.97it/s]

Chain 1:   9%|████████▊                                                                                              | 31/360 [00:01<00:12, 25.34it/s]

Chain 0:  27%|███████████████████████████▍                                                                           | 96/360 [00:03<00:10, 24.32it/s]

Chain 1:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 24.31it/s]

Chain 0:  28%|████████████████████████████▎                                                                          | 99/360 [00:03<00:10, 25.16it/s]

Chain 1:  10%|██████████▌                                                                                            | 37/360 [00:01<00:13, 23.49it/s]

Chain 0:  28%|████████████████████████████▉                                                                         | 102/360 [00:03<00:09, 25.95it/s]

Chain 1:  11%|███████████▍                                                                                           | 40/360 [00:01<00:13, 23.27it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:09, 26.42it/s]

Chain 0:  30%|██████████████████████████████▌                                                                       | 108/360 [00:04<00:09, 26.82it/s]

Chain 1:  12%|████████████▎                                                                                          | 43/360 [00:01<00:13, 23.05it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:04<00:09, 26.89it/s]

Chain 1:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:13, 22.86it/s]

Chain 0:  32%|████████████████████████████████▎                                                                     | 114/360 [00:04<00:08, 27.40it/s]

Chain 1:  14%|██████████████                                                                                         | 49/360 [00:01<00:13, 22.87it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:04<00:08, 27.52it/s]

Chain 1:  14%|██████████████▉                                                                                        | 52/360 [00:01<00:13, 22.90it/s]

Chain 0:  33%|██████████████████████████████████                                                                    | 120/360 [00:04<00:08, 27.41it/s]

Chain 0:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:04<00:08, 27.66it/s]

Chain 1:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 22.93it/s]

Chain 0:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:04<00:08, 27.72it/s]

Chain 1:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:13, 22.81it/s]

Chain 0:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:04<00:08, 27.67it/s]

Chain 1:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:13, 22.64it/s]

Chain 0:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:05<00:08, 27.49it/s]

Chain 1:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:13, 22.37it/s]

Chain 0:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:05<00:08, 27.83it/s]

Chain 0:  38%|███████████████████████████████████████                                                               | 138/360 [00:05<00:07, 27.79it/s]

Chain 1:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:13, 22.20it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:05<00:07, 28.01it/s]

Chain 1:  19%|████████████████████                                                                                   | 70/360 [00:02<00:13, 22.27it/s]

Chain 2:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 75.98it/s]

Chain 0:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:05<00:07, 27.88it/s]

Chain 1:  20%|████████████████████▉                                                                                  | 73/360 [00:02<00:13, 21.80it/s]

Chain 0:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:05<00:07, 27.34it/s]

Chain 1:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:12, 22.17it/s]

Chain 0:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:05<00:07, 27.96it/s]

Chain 0:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:05<00:07, 28.16it/s]

Chain 1:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:12, 22.42it/s]

Chain 2:   5%|█████▍                                                                                                 | 19/360 [00:00<00:10, 31.77it/s]

Chain 0:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:05<00:07, 28.54it/s]

Chain 1:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:12, 22.52it/s]

Chain 0:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:06<00:06, 28.89it/s]

Chain 2:   7%|██████▊                                                                                                | 24/360 [00:00<00:12, 27.44it/s]

Chain 1:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:12, 22.40it/s]

Chain 0:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:06<00:06, 29.52it/s]

Chain 1:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:12, 22.40it/s]

Chain 2:   8%|████████                                                                                               | 28/360 [00:00<00:12, 25.63it/s]

Chain 0:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:06<00:06, 30.23it/s]

Chain 0:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:06<00:06, 30.93it/s]

Chain 1:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:12, 22.34it/s]

Chain 2:   9%|████████▊                                                                                              | 31/360 [00:01<00:13, 24.14it/s]

Chain 1:  26%|██████████████████████████▉                                                                            | 94/360 [00:03<00:12, 21.02it/s]

Chain 0:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:06<00:06, 30.50it/s]

Chain 2:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 23.43it/s]

Chain 1:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:11, 22.37it/s]

Chain 0:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:06<00:05, 30.69it/s]

Chain 2:  10%|██████████▌                                                                                            | 37/360 [00:01<00:14, 22.88it/s]

Chain 1:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 23.31it/s]

Chain 0:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:06<00:05, 31.40it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:01<00:14, 22.64it/s]

Chain 1:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:10, 23.83it/s]

Chain 0:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:06<00:05, 32.10it/s]

Chain 2:  12%|████████████▎                                                                                          | 43/360 [00:01<00:14, 22.54it/s]

Chain 1:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:10, 24.08it/s]

Chain 0:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:07<00:05, 32.73it/s]

Chain 2:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:13, 22.57it/s]

Chain 1:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:10, 24.49it/s]

Chain 0:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:07<00:04, 33.65it/s]

Chain 2:  14%|██████████████                                                                                         | 49/360 [00:01<00:13, 22.54it/s]

Chain 0:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:07<00:04, 34.52it/s]

Chain 1:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:10, 24.12it/s]

Chain 0:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:07<00:04, 34.94it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:13, 22.24it/s]

Chain 1:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:10, 24.21it/s]

Chain 0:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:07<00:04, 35.96it/s]

Chain 1:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:04<00:09, 24.58it/s]

Chain 2:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 22.19it/s]

Chain 0:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:07<00:04, 36.41it/s]

Chain 1:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:04<00:09, 24.93it/s]

Chain 2:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:13, 21.90it/s]

Chain 0:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:07<00:03, 37.04it/s]

Chain 1:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:09, 25.05it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:07<00:03, 37.32it/s]

Chain 2:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:13, 21.67it/s]

Chain 1:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:09, 25.57it/s]

Chain 0:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:07<00:03, 37.71it/s]

Chain 2:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:13, 21.43it/s]

Chain 1:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 25.46it/s]

Chain 0:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:07<00:03, 38.99it/s]

Chain 1:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:08, 25.62it/s]

Chain 2:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:13, 21.00it/s]

Chain 0:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:08<00:03, 39.20it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:08, 25.51it/s]

Chain 0:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:08<00:03, 40.30it/s]

Chain 3:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 95.92it/s]

Chain 2:  19%|████████████████████                                                                                   | 70/360 [00:02<00:14, 20.68it/s]

Chain 1:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:05<00:08, 25.44it/s]

Chain 0:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:08<00:02, 41.14it/s]

Chain 2:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:13, 20.73it/s]

Chain 1:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:05<00:08, 25.82it/s]

Chain 0:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:08<00:02, 42.16it/s]

Chain 2:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:13, 21.09it/s]

Chain 1:  40%|█████████████████████████████████████████                                                             | 145/360 [00:05<00:08, 26.32it/s]

Chain 0:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:08<00:02, 43.67it/s]

Chain 1:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 26.42it/s]

Chain 0:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:08<00:02, 45.26it/s]

Chain 2:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 21.20it/s]

Chain 3:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 28.96it/s]

Chain 1:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:07, 26.59it/s]

Chain 0:  73%|██████████████████████████████████████████████████████████████████████████▌                           | 263/360 [00:08<00:02, 47.30it/s]

Chain 2:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:12, 21.55it/s]

Chain 1:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 26.48it/s]

Chain 0:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:08<00:01, 48.98it/s]

Chain 2:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:12, 21.41it/s]

Chain 1:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 26.62it/s]

Chain 0:  76%|█████████████████████████████████████████████████████████████████████████████▉                        | 275/360 [00:08<00:01, 51.63it/s]

Chain 3:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 25.34it/s]

Chain 2:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:12, 21.38it/s]

Chain 1:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:07, 27.24it/s]

Chain 0:  78%|███████████████████████████████████████████████████████████████████████████████▉                      | 282/360 [00:09<00:01, 54.79it/s]

Chain 1:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:06<00:07, 27.49it/s]

Chain 0:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:09<00:01, 57.46it/s]

Chain 2:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:12, 21.16it/s]

Chain 3:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.83it/s]

Chain 1:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:06<00:06, 27.99it/s]

Chain 0:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:09<00:01, 62.63it/s]

Chain 2:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:12, 21.21it/s]

Chain 1:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:06<00:06, 28.54it/s]

Chain 0:  85%|██████████████████████████████████████████████████████████████████████████████████████▋               | 306/360 [00:09<00:00, 68.20it/s]

Chain 3:   9%|█████████▋                                                                                             | 34/360 [00:01<00:15, 21.28it/s]

Chain 2:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 21.73it/s]

Chain 1:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:06<00:06, 29.49it/s]

Chain 0:  88%|█████████████████████████████████████████████████████████████████████████████████████████▎            | 315/360 [00:09<00:00, 73.93it/s]

Chain 2:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 22.20it/s]

Chain 0:  91%|████████████████████████████████████████████████████████████████████████████████████████████▎         | 326/360 [00:09<00:00, 83.51it/s]

Chain 3:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 20.94it/s]

Chain 1:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:07<00:06, 29.81it/s]

Chain 0:  94%|████████████████████████████████████████████████████████████████████████████████████████████████▎     | 340/360 [00:09<00:00, 97.85it/s]

Chain 2:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:11, 22.29it/s]

Chain 1:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:05, 30.47it/s]

Chain 3:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.88it/s]

Chain 0: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:09<00:00, 127.10it/s]

Chain 2:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 22.97it/s]

Chain 1:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:07<00:05, 30.52it/s]

Chain 3:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 20.93it/s]

Chain 2:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:10, 23.41it/s]

Chain 1:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:07<00:05, 30.64it/s]

Chain 3:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:15, 20.80it/s]

Chain 2:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:10, 23.62it/s]

Chain 1:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:07<00:05, 30.71it/s]

Chain 3:  14%|██████████████                                                                                         | 49/360 [00:02<00:15, 20.58it/s]

Chain 2:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:10, 24.09it/s]

Chain 1:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:07<00:05, 31.52it/s]

Chain 2:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:09, 24.32it/s]

Chain 3:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:15, 20.29it/s]

Chain 1:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:07<00:04, 32.03it/s]

Chain 2:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:09, 24.47it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:07<00:04, 32.86it/s]

Chain 3:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:15, 20.04it/s]

Chain 2:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 23.19it/s]

Chain 1:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:08<00:04, 32.60it/s]

Chain 3:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:15, 19.17it/s]

Chain 2:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:09, 23.71it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:08<00:04, 33.02it/s]

Chain 3:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:15, 18.87it/s]

Chain 2:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 23.91it/s]

Chain 1:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:08<00:04, 33.97it/s]

Chain 3:  18%|██████████████████                                                                                     | 63/360 [00:02<00:15, 19.51it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:08<00:03, 35.56it/s]

Chain 2:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:09, 24.17it/s]

Chain 3:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:15, 19.50it/s]

Chain 1:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:08<00:03, 35.95it/s]

Chain 2:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:09, 24.54it/s]

Chain 4:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:08<00:03, 36.89it/s]

Chain 3:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:14, 19.67it/s]

Chain 2:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:05<00:08, 24.98it/s]

Chain 4:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 92.82it/s]

Chain 1:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:08<00:03, 36.75it/s]

Chain 3:  19%|████████████████████                                                                                   | 70/360 [00:03<00:15, 19.25it/s]

Chain 2:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 24.62it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:08<00:03, 36.68it/s]

Chain 2:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 25.23it/s]

Chain 3:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 19.64it/s]

Chain 1:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:08<00:03, 38.90it/s]

Chain 2:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 25.88it/s]

Chain 3:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:14, 20.16it/s]

Chain 1:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:09<00:02, 40.95it/s]

Chain 2:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:08, 25.99it/s]

Chain 1:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:09<00:02, 43.13it/s]

Chain 3:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.60it/s]

Chain 4:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 28.83it/s]

Chain 2:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 26.51it/s]

Chain 1:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:09<00:02, 44.84it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 20.89it/s]

Chain 2:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 27.02it/s]

Chain 1:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:09<00:02, 45.54it/s]

Chain 4:   7%|███████▏                                                                                               | 25/360 [00:00<00:13, 25.53it/s]

Chain 2:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:07, 27.33it/s]

Chain 3:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.82it/s]

Chain 1:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:09<00:01, 48.46it/s]

Chain 2:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:06<00:07, 27.70it/s]

Chain 1:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:09<00:01, 49.75it/s]

Chain 3:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:12, 21.02it/s]

Chain 4:   8%|████████▎                                                                                              | 29/360 [00:01<00:13, 23.95it/s]

Chain 2:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:06<00:07, 27.55it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:09<00:01, 51.33it/s]

Chain 3:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:12, 20.96it/s]

Chain 4:   9%|█████████▏                                                                                             | 32/360 [00:01<00:14, 22.88it/s]

Chain 2:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:07<00:06, 28.58it/s]

Chain 1:  79%|█████████████████████████████████████████████████████████████████████████████████                     | 286/360 [00:09<00:01, 46.60it/s]

Chain 2:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:07<00:06, 28.15it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:12, 20.82it/s]

Chain 4:  10%|██████████                                                                                             | 35/360 [00:01<00:14, 21.71it/s]

Chain 1:  81%|██████████████████████████████████████████████████████████████████████████████████▋                   | 292/360 [00:09<00:01, 49.55it/s]

Chain 2:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:07<00:06, 27.77it/s]

Chain 3:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 21.54it/s]

Chain 1:  83%|█████████████████████████████████████████████████████████████████████████████████████                 | 300/360 [00:10<00:01, 55.94it/s]

Chain 4:  11%|██████████▊                                                                                            | 38/360 [00:01<00:15, 21.09it/s]

Chain 2:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:07<00:06, 27.80it/s]

Chain 3:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 22.38it/s]

Chain 1:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:10<00:00, 63.52it/s]

Chain 2:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:07<00:06, 29.10it/s]

Chain 4:  11%|███████████▋                                                                                           | 41/360 [00:01<00:15, 20.61it/s]

Chain 3:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:11, 22.39it/s]

Chain 1:  89%|██████████████████████████████████████████████████████████████████████████████████████████▍           | 319/360 [00:10<00:00, 71.82it/s]

Chain 2:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:07<00:05, 29.13it/s]

Chain 1:  92%|█████████████████████████████████████████████████████████████████████████████████████████████▌        | 330/360 [00:10<00:00, 81.83it/s]

Chain 4:  12%|████████████▌                                                                                          | 44/360 [00:01<00:15, 20.18it/s]

Chain 3:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 22.00it/s]

Chain 2:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:07<00:05, 29.83it/s]

Chain 1:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████▍    | 344/360 [00:10<00:00, 96.85it/s]

Chain 3:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:11, 21.79it/s]

Chain 4:  13%|█████████████▍                                                                                         | 47/360 [00:02<00:15, 19.68it/s]

Chain 2:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:07<00:05, 30.51it/s]

Chain 4:  14%|██████████████                                                                                         | 49/360 [00:02<00:15, 19.58it/s]

Chain 3:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:11, 21.82it/s]

Chain 2:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:07<00:05, 31.34it/s]

Chain 4:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:15, 19.51it/s]

Chain 3:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:11, 21.82it/s]

Chain 2:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:08<00:05, 31.36it/s]

Chain 4:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:15, 19.36it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:08<00:04, 32.33it/s]

Chain 3:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:10, 22.17it/s]

Chain 4:  16%|████████████████                                                                                       | 56/360 [00:02<00:15, 19.71it/s]

Chain 2:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:08<00:04, 32.62it/s]

Chain 3:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 22.69it/s]

Chain 4:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:15, 19.44it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:08<00:04, 33.30it/s]

Chain 3:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 22.91it/s]

Chain 4:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:15, 19.52it/s]

Chain 2:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:08<00:04, 34.39it/s]

Chain 3:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:10, 23.06it/s]

Chain 4:  17%|█████████████████▋                                                                                     | 62/360 [00:02<00:15, 19.13it/s]

Chain 2:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:08<00:03, 34.77it/s]

Chain 4:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 18.61it/s]

Chain 3:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 23.28it/s]

Chain 2:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:08<00:03, 34.88it/s]

Chain 4:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:16, 17.85it/s]

Chain 5:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 3:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:09, 23.03it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:08<00:03, 35.58it/s]

Chain 4:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:15, 18.37it/s]

Chain 5:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 88.94it/s]

Chain 3:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:09, 23.63it/s]

Chain 2:  65%|██████████████████████████████████████████████████████████████████▎                                   | 234/360 [00:08<00:03, 36.70it/s]

Chain 4:  20%|████████████████████▎                                                                                  | 71/360 [00:03<00:14, 19.46it/s]

Chain 3:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:09, 24.50it/s]

Chain 2:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:09<00:03, 38.45it/s]

Chain 3:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 24.84it/s]

Chain 2:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:09<00:02, 40.79it/s]

Chain 4:  21%|█████████████████████▏                                                                                 | 74/360 [00:03<00:14, 20.23it/s]

Chain 2:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:09<00:02, 42.38it/s]

Chain 3:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 24.86it/s]

Chain 4:  21%|██████████████████████                                                                                 | 77/360 [00:03<00:13, 20.70it/s]

Chain 5:   5%|█████▍                                                                                                 | 19/360 [00:00<00:11, 29.98it/s]

Chain 2:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:09<00:02, 44.35it/s]

Chain 3:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 25.55it/s]

Chain 4:  22%|██████████████████████▉                                                                                | 80/360 [00:03<00:13, 21.24it/s]

Chain 2:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:09<00:02, 46.44it/s]

Chain 3:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:08, 25.77it/s]

Chain 4:  23%|███████████████████████▋                                                                               | 83/360 [00:03<00:13, 21.30it/s]

Chain 2:  74%|███████████████████████████████████████████████████████████████████████████▎                          | 266/360 [00:09<00:01, 48.12it/s]

Chain 3:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 26.12it/s]

Chain 5:   7%|██████▊                                                                                                | 24/360 [00:00<00:13, 25.77it/s]

Chain 2:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:09<00:01, 50.44it/s]

Chain 4:  24%|████████████████████████▌                                                                              | 86/360 [00:03<00:12, 21.54it/s]

Chain 3:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 26.78it/s]

Chain 5:   8%|████████                                                                                               | 28/360 [00:01<00:13, 23.99it/s]

Chain 2:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:09<00:01, 52.63it/s]

Chain 3:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:07, 27.24it/s]

Chain 4:  25%|█████████████████████████▍                                                                             | 89/360 [00:04<00:12, 21.03it/s]

Chain 2:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:09<00:01, 55.57it/s]

Chain 3:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:07, 26.72it/s]

Chain 5:   9%|████████▊                                                                                              | 31/360 [00:01<00:14, 22.67it/s]

Chain 4:  26%|██████████████████████████▎                                                                            | 92/360 [00:04<00:12, 20.78it/s]

Chain 2:  81%|██████████████████████████████████████████████████████████████████████████████████▍                   | 291/360 [00:10<00:01, 55.97it/s]

Chain 3:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 26.50it/s]

Chain 5:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 21.81it/s]

Chain 2:  83%|████████████████████████████████████████████████████████████████████████████████████▍                 | 298/360 [00:10<00:01, 59.89it/s]

Chain 4:  26%|███████████████████████████▏                                                                           | 95/360 [00:04<00:12, 21.18it/s]

Chain 3:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:07, 27.20it/s]

Chain 2:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:10<00:00, 61.79it/s]

Chain 3:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:07, 26.83it/s]

Chain 4:  27%|████████████████████████████                                                                           | 98/360 [00:04<00:12, 21.45it/s]

Chain 5:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 20.39it/s]

Chain 2:  87%|████████████████████████████████████████████████████████████████████████████████████████▍             | 312/360 [00:10<00:00, 61.19it/s]

Chain 3:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:07, 25.97it/s]

Chain 4:  28%|████████████████████████████▌                                                                         | 101/360 [00:04<00:12, 21.45it/s]

Chain 2:  89%|██████████████████████████████████████████████████████████████████████████████████████████▉           | 321/360 [00:10<00:00, 68.97it/s]

Chain 5:  11%|███████████▍                                                                                           | 40/360 [00:01<00:16, 19.78it/s]

Chain 3:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:06, 26.41it/s]

Chain 4:  29%|█████████████████████████████▍                                                                        | 104/360 [00:04<00:11, 22.07it/s]

Chain 2:  92%|█████████████████████████████████████████████████████████████████████████████████████████████▊        | 331/360 [00:10<00:00, 76.76it/s]

Chain 3:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:06, 26.41it/s]

Chain 5:  12%|████████████▎                                                                                          | 43/360 [00:01<00:16, 19.52it/s]

Chain 2:  95%|████████████████████████████████████████████████████████████████████████████████████████████████▉     | 342/360 [00:10<00:00, 86.13it/s]

Chain 4:  30%|██████████████████████████████▎                                                                       | 107/360 [00:04<00:11, 22.12it/s]

Chain 3:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:06, 27.04it/s]

Chain 5:  12%|████████████▉                                                                                          | 45/360 [00:01<00:16, 19.01it/s]

Chain 2: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████▋| 359/360 [00:10<00:00, 109.99it/s]

Chain 4:  31%|███████████████████████████████▏                                                                      | 110/360 [00:05<00:10, 22.87it/s]

Chain 5:  13%|█████████████▍                                                                                         | 47/360 [00:02<00:16, 19.19it/s]

Chain 3:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:08<00:06, 28.08it/s]

Chain 4:  31%|████████████████████████████████                                                                      | 113/360 [00:05<00:10, 23.28it/s]

Chain 5:  14%|██████████████                                                                                         | 49/360 [00:02<00:16, 19.11it/s]

Chain 3:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:08<00:05, 28.21it/s]

Chain 4:  32%|████████████████████████████████▊                                                                     | 116/360 [00:05<00:10, 23.87it/s]

Chain 5:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:16, 18.90it/s]

Chain 3:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:08<00:06, 27.29it/s]

Chain 5:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:16, 18.98it/s]

Chain 4:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:05<00:09, 24.24it/s]

Chain 3:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:08<00:05, 29.02it/s]

Chain 5:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:15, 19.19it/s]

Chain 4:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:05<00:09, 24.35it/s]

Chain 3:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:08<00:05, 30.28it/s]

Chain 5:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 19.27it/s]

Chain 4:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:05<00:09, 24.30it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████▎                                           | 206/360 [00:08<00:04, 31.46it/s]

Chain 5:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:15, 19.14it/s]

Chain 4:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:05<00:09, 24.46it/s]

Chain 3:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:08<00:04, 32.34it/s]

Chain 5:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:15, 19.20it/s]

Chain 4:  36%|█████████████████████████████████████                                                                 | 131/360 [00:05<00:09, 23.88it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:08<00:04, 32.92it/s]

Chain 5:  18%|██████████████████                                                                                     | 63/360 [00:02<00:15, 19.04it/s]

Chain 5:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:15, 19.21it/s]

Chain 3:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:09<00:04, 33.97it/s]

Chain 4:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:06<00:09, 24.00it/s]

Chain 5:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:15, 18.95it/s]

Chain 6:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 3:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:09<00:04, 34.29it/s]

Chain 4:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:06<00:09, 24.26it/s]

Chain 3:  63%|████████████████████████████████████████████████████████████████                                      | 226/360 [00:09<00:03, 35.66it/s]

Chain 6:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 94.76it/s]

Chain 4:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:06<00:08, 24.67it/s]

Chain 5:  19%|████████████████████                                                                                   | 70/360 [00:03<00:14, 19.52it/s]

Chain 3:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:09<00:03, 37.71it/s]

Chain 4:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:06<00:08, 25.33it/s]

Chain 5:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 20.01it/s]

Chain 3:  66%|██████████████████████████████████████████████████████████████████▊                                   | 236/360 [00:09<00:03, 39.10it/s]

Chain 4:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:06<00:08, 25.77it/s]

Chain 5:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:14, 20.10it/s]

Chain 3:  67%|████████████████████████████████████████████████████████████████████▎                                 | 241/360 [00:09<00:02, 40.29it/s]

Chain 4:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:06<00:08, 26.13it/s]

Chain 3:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:09<00:02, 41.95it/s]

Chain 5:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.52it/s]

Chain 4:  42%|███████████████████████████████████████████                                                           | 152/360 [00:06<00:07, 26.44it/s]

Chain 6:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 29.37it/s]

Chain 3:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:09<00:02, 43.48it/s]

Chain 4:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:06<00:07, 26.74it/s]

Chain 5:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 20.37it/s]

Chain 3:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:09<00:02, 44.61it/s]

Chain 4:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:06<00:07, 26.89it/s]

Chain 5:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.58it/s]

Chain 3:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:10<00:02, 46.47it/s]

Chain 4:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:07<00:07, 27.42it/s]

Chain 6:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 25.33it/s]

Chain 4:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:07<00:07, 27.50it/s]

Chain 3:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:10<00:01, 48.19it/s]

Chain 5:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:13, 20.42it/s]

Chain 4:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:07<00:06, 28.09it/s]

Chain 6:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.69it/s]

Chain 3:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:10<00:01, 50.36it/s]

Chain 5:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:13, 20.06it/s]

Chain 3:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:10<00:01, 52.86it/s]

Chain 4:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:07<00:06, 27.65it/s]

Chain 6:   9%|█████████▍                                                                                             | 33/360 [00:01<00:14, 22.37it/s]

Chain 5:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:12, 20.84it/s]

Chain 3:  79%|█████████████████████████████████████████████████████████████████████████████████                     | 286/360 [00:10<00:01, 54.60it/s]

Chain 4:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:07<00:06, 27.69it/s]

Chain 3:  81%|██████████████████████████████████████████████████████████████████████████████████▋                   | 292/360 [00:10<00:01, 55.83it/s]

Chain 5:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 21.79it/s]

Chain 6:  10%|██████████▎                                                                                            | 36/360 [00:01<00:14, 21.67it/s]

Chain 4:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:07<00:06, 27.31it/s]

Chain 3:  83%|█████████████████████████████████████████████████████████████████████████████████████                 | 300/360 [00:10<00:00, 60.88it/s]

Chain 4:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:07<00:06, 27.76it/s]

Chain 5:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 22.02it/s]

Chain 6:  11%|███████████▏                                                                                           | 39/360 [00:01<00:15, 21.09it/s]

Chain 3:  86%|███████████████████████████████████████████████████████████████████████████████████████▎              | 308/360 [00:10<00:00, 65.40it/s]

Chain 4:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:07<00:06, 27.81it/s]

Chain 5:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:11, 21.66it/s]

Chain 6:  12%|████████████                                                                                           | 42/360 [00:01<00:15, 21.00it/s]

Chain 3:  88%|█████████████████████████████████████████████████████████████████████████████████████████▌            | 316/360 [00:10<00:00, 67.44it/s]

Chain 4:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:07<00:06, 28.25it/s]

Chain 5:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 22.21it/s]

Chain 3:  91%|████████████████████████████████████████████████████████████████████████████████████████████▎         | 326/360 [00:10<00:00, 74.88it/s]

Chain 4:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:07<00:06, 28.35it/s]

Chain 6:  12%|████████████▉                                                                                          | 45/360 [00:01<00:15, 20.34it/s]

Chain 5:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:11, 22.63it/s]

Chain 3:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▊      | 338/360 [00:11<00:00, 87.24it/s]

Chain 4:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:08<00:05, 28.69it/s]

Chain 6:  13%|█████████████▋                                                                                         | 48/360 [00:02<00:15, 19.90it/s]

Chain 3:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████▉ | 356/360 [00:11<00:00, 113.40it/s]

Chain 5:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:10, 22.73it/s]

Chain 4:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:08<00:05, 30.03it/s]

Chain 6:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:15, 19.68it/s]

Chain 4:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:08<00:05, 30.44it/s]

Chain 5:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:10, 22.65it/s]

Chain 6:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:15, 19.48it/s]

Chain 4:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:08<00:05, 31.23it/s]

Chain 5:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:10, 22.55it/s]

Chain 6:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:15, 19.38it/s]

Chain 4:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:08<00:04, 31.55it/s]

Chain 5:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 22.72it/s]

Chain 6:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 19.11it/s]

Chain 4:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:08<00:04, 31.51it/s]

Chain 5:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 22.74it/s]

Chain 6:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:15, 19.04it/s]

Chain 4:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:08<00:04, 33.14it/s]

Chain 5:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:10, 23.17it/s]

Chain 6:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:15, 18.98it/s]

Chain 4:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:08<00:04, 34.09it/s]

Chain 5:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 23.34it/s]

Chain 6:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 19.08it/s]

Chain 4:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:09<00:04, 33.26it/s]

Chain 7:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 5:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:09, 23.06it/s]

Chain 6:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:15, 18.83it/s]

Chain 4:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:09<00:03, 34.53it/s]

Chain 7:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 90.56it/s]

Chain 6:  19%|███████████████████▍                                                                                   | 68/360 [00:03<00:15, 18.89it/s]

Chain 5:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:09, 22.98it/s]

Chain 4:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:09<00:03, 34.82it/s]

Chain 6:  19%|████████████████████                                                                                   | 70/360 [00:03<00:15, 18.66it/s]

Chain 4:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:09<00:03, 35.80it/s]

Chain 5:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:09, 22.97it/s]

Chain 4:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:09<00:03, 38.01it/s]

Chain 6:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 19.33it/s]

Chain 5:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:09, 23.51it/s]

Chain 4:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:09<00:02, 39.37it/s]

Chain 5:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:09, 23.06it/s]

Chain 6:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:14, 19.48it/s]

Chain 4:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:09<00:02, 41.60it/s]

Chain 7:   6%|█████▋                                                                                                 | 20/360 [00:00<00:12, 28.11it/s]

Chain 5:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 23.98it/s]

Chain 6:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:13, 20.09it/s]

Chain 4:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:09<00:02, 43.26it/s]

Chain 5:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:08, 24.62it/s]

Chain 6:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:13, 20.51it/s]

Chain 4:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:09<00:02, 45.78it/s]

Chain 5:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:08, 25.62it/s]

Chain 7:   7%|███████▏                                                                                               | 25/360 [00:00<00:13, 25.05it/s]

Chain 4:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:10<00:01, 47.58it/s]

Chain 6:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:13, 20.67it/s]

Chain 5:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:07<00:08, 25.21it/s]

Chain 4:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:10<00:01, 46.79it/s]

Chain 7:   8%|████████▎                                                                                              | 29/360 [00:01<00:14, 22.80it/s]

Chain 5:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:07, 25.23it/s]

Chain 6:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:13, 20.13it/s]

Chain 4:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:10<00:01, 49.48it/s]

Chain 5:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:07, 25.92it/s]

Chain 7:   9%|█████████▏                                                                                             | 32/360 [00:01<00:14, 22.05it/s]

Chain 6:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:13, 20.49it/s]

Chain 4:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:10<00:01, 53.22it/s]

Chain 5:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 26.65it/s]

Chain 6:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:12, 21.41it/s]

Chain 4:  81%|██████████████████████████████████████████████████████████████████████████████████▋                   | 292/360 [00:10<00:01, 56.93it/s]

Chain 7:  10%|██████████                                                                                             | 35/360 [00:01<00:15, 21.20it/s]

Chain 5:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 27.43it/s]

Chain 4:  83%|█████████████████████████████████████████████████████████████████████████████████████                 | 300/360 [00:10<00:00, 62.38it/s]

Chain 6:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:11, 22.52it/s]

Chain 5:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:07<00:06, 28.26it/s]

Chain 7:  11%|██████████▊                                                                                            | 38/360 [00:01<00:15, 20.85it/s]

Chain 4:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:10<00:00, 68.00it/s]

Chain 6:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 22.80it/s]

Chain 5:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:07<00:06, 28.52it/s]

Chain 4:  89%|██████████████████████████████████████████████████████████████████████████████████████████▍           | 319/360 [00:10<00:00, 76.05it/s]

Chain 7:  11%|███████████▋                                                                                           | 41/360 [00:01<00:15, 20.51it/s]

Chain 5:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:07<00:07, 25.85it/s]

Chain 4:  91%|█████████████████████████████████████████████████████████████████████████████████████████████▏        | 329/360 [00:10<00:00, 81.63it/s]

Chain 6:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:12, 20.05it/s]

Chain 7:  12%|████████████▌                                                                                          | 44/360 [00:01<00:15, 20.24it/s]

Chain 5:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:08<00:06, 26.15it/s]

Chain 4:  95%|████████████████████████████████████████████████████████████████████████████████████████████████▌     | 341/360 [00:11<00:00, 91.11it/s]

Chain 6:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:12, 20.91it/s]

Chain 5:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:08<00:06, 27.07it/s]

Chain 4: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████▋| 359/360 [00:11<00:00, 115.79it/s]

Chain 7:  13%|█████████████▍                                                                                         | 47/360 [00:02<00:15, 19.76it/s]

Chain 6:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:11, 20.97it/s]

Chain 5:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:08<00:06, 27.71it/s]

Chain 7:  14%|██████████████▎                                                                                        | 50/360 [00:02<00:15, 19.61it/s]

Chain 6:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:11, 21.25it/s]

Chain 5:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:08<00:05, 28.97it/s]

Chain 7:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:16, 19.23it/s]

Chain 6:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:11, 21.62it/s]

Chain 5:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:08<00:05, 29.64it/s]

Chain 7:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:16, 19.07it/s]

Chain 6:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:11, 21.83it/s]

Chain 5:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:08<00:05, 29.83it/s]

Chain 7:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 19.36it/s]

Chain 5:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:08<00:05, 29.57it/s]

Chain 6:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 21.82it/s]

Chain 7:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:15, 19.33it/s]

Chain 5:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:08<00:05, 30.07it/s]

Chain 6:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 22.36it/s]

Chain 7:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:15, 19.32it/s]

Chain 5:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:08<00:04, 31.26it/s]

Chain 7:  18%|██████████████████                                                                                     | 63/360 [00:02<00:15, 19.36it/s]

Chain 6:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:10, 22.46it/s]

Chain 5:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:09<00:04, 32.68it/s]

Chain 7:  18%|██████████████████▌                                                                                    | 65/360 [00:02<00:15, 19.32it/s]

Chain 6:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:06<00:10, 22.73it/s]

Chain 5:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:09<00:04, 34.20it/s]

Chain 7:  19%|███████████████████▏                                                                                   | 67/360 [00:03<00:15, 18.96it/s]

Chain 6:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:09, 23.58it/s]

Chain 5:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:09<00:03, 35.34it/s]

Chain 7:  19%|████████████████████                                                                                   | 70/360 [00:03<00:14, 19.58it/s]

Chain 6:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:09, 24.29it/s]

Chain 5:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:09<00:03, 37.14it/s]

Chain 7:  20%|████████████████████▉                                                                                  | 73/360 [00:03<00:14, 20.00it/s]

Chain 6:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:09, 24.50it/s]

Chain 5:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:09<00:03, 37.01it/s]

Chain 8:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 7:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:14, 19.99it/s]

Chain 6:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 24.61it/s]

Chain 5:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:09<00:03, 38.32it/s]

Chain 8:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 97.32it/s]

Chain 7:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:13, 20.51it/s]

Chain 6:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 25.04it/s]

Chain 5:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:09<00:02, 40.04it/s]

Chain 6:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:08, 25.21it/s]

Chain 7:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:13, 20.58it/s]

Chain 5:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:09<00:02, 41.61it/s]

Chain 6:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:08, 25.68it/s]

Chain 5:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:09<00:02, 43.40it/s]

Chain 7:  23%|████████████████████████                                                                               | 84/360 [00:03<00:13, 20.43it/s]

Chain 6:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 25.81it/s]

Chain 5:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:10<00:02, 44.37it/s]

Chain 7:  24%|████████████████████████▉                                                                              | 87/360 [00:04<00:13, 20.39it/s]

Chain 8:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 29.36it/s]

Chain 6:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:07<00:07, 26.05it/s]

Chain 5:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:10<00:02, 45.77it/s]

Chain 6:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:07, 26.56it/s]

Chain 5:  74%|███████████████████████████████████████████████████████████████████████████▉                          | 268/360 [00:10<00:01, 48.31it/s]

Chain 7:  25%|█████████████████████████▊                                                                             | 90/360 [00:04<00:13, 20.35it/s]

Chain 6:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:07, 26.63it/s]

Chain 5:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:10<00:01, 50.63it/s]

Chain 7:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:12, 20.78it/s]

Chain 8:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 25.23it/s]

Chain 6:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:07, 27.35it/s]

Chain 5:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:10<00:01, 52.66it/s]

Chain 7:  27%|███████████████████████████▍                                                                           | 96/360 [00:04<00:12, 21.67it/s]

Chain 6:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 27.41it/s]

Chain 5:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:10<00:01, 55.89it/s]

Chain 8:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 23.66it/s]

Chain 7:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:11, 22.27it/s]

Chain 6:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:06, 27.96it/s]

Chain 5:  82%|███████████████████████████████████████████████████████████████████████████████████▎                  | 294/360 [00:10<00:01, 59.01it/s]

Chain 5:  84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 301/360 [00:10<00:00, 61.78it/s]

Chain 7:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:11, 22.55it/s]

Chain 6:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 27.16it/s]

Chain 8:   9%|█████████▋                                                                                             | 34/360 [00:01<00:14, 22.51it/s]

Chain 5:  86%|███████████████████████████████████████████████████████████████████████████████████████▎              | 308/360 [00:10<00:00, 63.64it/s]

Chain 6:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:07<00:06, 27.42it/s]

Chain 7:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:11, 22.24it/s]

Chain 5:  88%|█████████████████████████████████████████████████████████████████████████████████████████▌            | 316/360 [00:11<00:00, 67.55it/s]

Chain 6:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:07<00:06, 27.37it/s]

Chain 8:  10%|██████████▌                                                                                            | 37/360 [00:01<00:15, 21.49it/s]

Chain 7:  30%|██████████████████████████████▌                                                                       | 108/360 [00:05<00:11, 21.90it/s]

Chain 5:  90%|████████████████████████████████████████████████████████████████████████████████████████████          | 325/360 [00:11<00:00, 73.40it/s]

Chain 6:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:08<00:06, 27.33it/s]

Chain 8:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 20.72it/s]

Chain 5:  93%|███████████████████████████████████████████████████████████████████████████████████████████████▏      | 336/360 [00:11<00:00, 83.45it/s]

Chain 7:  31%|███████████████████████████████▍                                                                      | 111/360 [00:05<00:11, 22.10it/s]

Chain 6:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:08<00:06, 27.82it/s]

Chain 5:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████▏  | 350/360 [00:11<00:00, 99.73it/s]

Chain 7:  32%|████████████████████████████████▎                                                                     | 114/360 [00:05<00:11, 22.32it/s]

Chain 8:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 19.87it/s]

Chain 6:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:08<00:05, 28.92it/s]

Chain 7:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:10, 22.40it/s]

Chain 6:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:08<00:05, 29.85it/s]

Chain 8:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:15, 19.83it/s]

Chain 6:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:08<00:05, 30.83it/s]

Chain 7:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:10, 22.54it/s]

Chain 8:  14%|██████████████                                                                                         | 49/360 [00:02<00:16, 19.19it/s]

Chain 6:  56%|█████████████████████████████████████████████████████████▌                                            | 203/360 [00:08<00:05, 30.47it/s]

Chain 7:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:10, 21.57it/s]

Chain 8:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:16, 18.95it/s]

Chain 6:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:08<00:04, 31.52it/s]

Chain 8:  15%|███████████████▏                                                                                       | 53/360 [00:02<00:16, 19.09it/s]

Chain 7:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:05<00:10, 22.04it/s]

Chain 6:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:08<00:04, 31.53it/s]

Chain 8:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:16, 18.87it/s]

Chain 7:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:05<00:10, 22.63it/s]

Chain 8:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:16, 18.81it/s]

Chain 6:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:09<00:04, 31.53it/s]

Chain 7:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:06<00:10, 22.16it/s]

Chain 8:  16%|████████████████▉                                                                                      | 59/360 [00:02<00:16, 18.41it/s]

Chain 6:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:09<00:04, 32.06it/s]

Chain 7:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:06<00:09, 22.52it/s]

Chain 8:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:16, 18.60it/s]

Chain 6:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:09<00:04, 33.49it/s]

Chain 7:  38%|███████████████████████████████████████                                                               | 138/360 [00:06<00:09, 23.21it/s]

Chain 6:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:09<00:03, 35.54it/s]

Chain 8:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:15, 19.22it/s]

Chain 7:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:06<00:09, 23.59it/s]

Chain 9:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 6:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:09<00:03, 36.35it/s]

Chain 8:  18%|██████████████████▉                                                                                    | 66/360 [00:03<00:15, 19.10it/s]

Chain 7:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:06<00:08, 24.34it/s]

Chain 9:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 95.76it/s]

Chain 6:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:09<00:03, 38.00it/s]

Chain 8:  19%|███████████████████▋                                                                                   | 69/360 [00:03<00:14, 19.75it/s]

Chain 7:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:06<00:08, 25.06it/s]

Chain 6:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:09<00:02, 40.19it/s]

Chain 8:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:14, 20.12it/s]

Chain 7:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:06<00:08, 25.80it/s]

Chain 6:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:09<00:02, 41.58it/s]

Chain 7:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:06<00:07, 26.30it/s]

Chain 6:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:09<00:02, 43.60it/s]

Chain 8:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:14, 19.89it/s]

Chain 7:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:07<00:07, 26.76it/s]

Chain 6:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:10<00:02, 44.00it/s]

Chain 8:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:14, 19.94it/s]

Chain 7:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:07<00:07, 26.93it/s]

Chain 9:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 28.60it/s]

Chain 6:  73%|██████████████████████████████████████████████████████████████████████████▌                           | 263/360 [00:10<00:02, 46.19it/s]

Chain 7:  45%|█████████████████████████████████████████████▉                                                        | 162/360 [00:07<00:07, 26.98it/s]

Chain 8:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:13, 20.09it/s]

Chain 6:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:10<00:01, 48.59it/s]

Chain 7:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:07<00:07, 27.37it/s]

Chain 6:  76%|█████████████████████████████████████████████████████████████████████████████▉                        | 275/360 [00:10<00:01, 50.10it/s]

Chain 8:  23%|████████████████████████                                                                               | 84/360 [00:03<00:14, 19.64it/s]

Chain 9:   7%|███████▍                                                                                               | 26/360 [00:00<00:13, 24.65it/s]

Chain 7:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:07<00:06, 27.67it/s]

Chain 8:  24%|████████████████████████▌                                                                              | 86/360 [00:04<00:14, 19.54it/s]

Chain 6:  78%|███████████████████████████████████████████████████████████████████████████████▉                      | 282/360 [00:10<00:01, 53.34it/s]

Chain 7:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:07<00:06, 28.31it/s]

Chain 8:  24%|█████████████████████████▏                                                                             | 88/360 [00:04<00:14, 19.39it/s]

Chain 6:  80%|█████████████████████████████████████████████████████████████████████████████████▉                    | 289/360 [00:10<00:01, 57.25it/s]

Chain 9:   8%|████████▌                                                                                              | 30/360 [00:01<00:14, 23.36it/s]

Chain 7:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:07<00:06, 29.21it/s]

Chain 6:  82%|████████████████████████████████████████████████████████████████████████████████████▏                 | 297/360 [00:10<00:01, 61.64it/s]

Chain 8:  25%|██████████████████████████                                                                             | 91/360 [00:04<00:13, 19.58it/s]

Chain 9:   9%|█████████▍                                                                                             | 33/360 [00:01<00:14, 22.38it/s]

Chain 7:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:07<00:06, 29.97it/s]

Chain 6:  85%|██████████████████████████████████████████████████████████████████████████████████████▍               | 305/360 [00:10<00:00, 65.85it/s]

Chain 8:  26%|██████████████████████████▉                                                                            | 94/360 [00:04<00:13, 20.26it/s]

Chain 7:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:07<00:05, 29.69it/s]

Chain 6:  87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 314/360 [00:10<00:00, 72.43it/s]

Chain 9:  10%|██████████▎                                                                                            | 36/360 [00:01<00:14, 21.74it/s]

Chain 8:  27%|███████████████████████████▊                                                                           | 97/360 [00:04<00:12, 21.39it/s]

Chain 7:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:08<00:05, 30.02it/s]

Chain 6:  90%|████████████████████████████████████████████████████████████████████████████████████████████          | 325/360 [00:11<00:00, 80.89it/s]

Chain 9:  11%|███████████▏                                                                                           | 39/360 [00:01<00:15, 21.34it/s]

Chain 7:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:08<00:05, 29.75it/s]

Chain 8:  28%|████████████████████████████▎                                                                         | 100/360 [00:04<00:11, 22.29it/s]

Chain 6:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▊      | 338/360 [00:11<00:00, 93.10it/s]

Chain 9:  12%|████████████                                                                                           | 42/360 [00:01<00:14, 21.23it/s]

Chain 6:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████▍| 358/360 [00:11<00:00, 122.47it/s]

Chain 7:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:08<00:05, 31.07it/s]

Chain 8:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:11, 22.80it/s]

Chain 7:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:08<00:05, 32.02it/s]

Chain 9:  12%|████████████▉                                                                                          | 45/360 [00:01<00:14, 21.24it/s]

Chain 8:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:11, 22.85it/s]

Chain 7:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:08<00:04, 32.54it/s]

Chain 8:  30%|██████████████████████████████▉                                                                       | 109/360 [00:05<00:10, 23.06it/s]

Chain 9:  13%|█████████████▋                                                                                         | 48/360 [00:02<00:15, 20.65it/s]

Chain 7:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:08<00:04, 33.30it/s]

Chain 8:  31%|███████████████████████████████▋                                                                      | 112/360 [00:05<00:10, 23.19it/s]

Chain 9:  14%|██████████████▌                                                                                        | 51/360 [00:02<00:15, 20.59it/s]

Chain 7:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:08<00:04, 33.37it/s]

Chain 8:  32%|████████████████████████████████▌                                                                     | 115/360 [00:05<00:10, 23.33it/s]

Chain 9:  15%|███████████████▍                                                                                       | 54/360 [00:02<00:14, 20.58it/s]

Chain 7:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:08<00:04, 34.14it/s]

Chain 8:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:05<00:10, 23.24it/s]

Chain 7:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:08<00:04, 35.21it/s]

Chain 9:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:15, 20.17it/s]

Chain 8:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:05<00:10, 23.48it/s]

Chain 7:  61%|██████████████████████████████████████████████████████████████▌                                       | 221/360 [00:09<00:03, 34.87it/s]

Chain 9:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:15, 19.91it/s]

Chain 7:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:09<00:03, 35.44it/s]

Chain 8:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:05<00:10, 23.55it/s]

Chain 8:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:05<00:09, 24.13it/s]

Chain 9:  18%|██████████████████                                                                                     | 63/360 [00:02<00:14, 19.99it/s]

Chain 7:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:09<00:03, 37.13it/s]

Chain 8:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:09, 24.71it/s]

Chain 7:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:09<00:03, 39.28it/s]

Chain 9:  18%|██████████████████▉                                                                                    | 66/360 [00:02<00:14, 20.38it/s]

Chain 7:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:09<00:02, 41.41it/s]

Chain 8:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:06<00:08, 25.29it/s]

Chain 9:  19%|███████████████████▋                                                                                   | 69/360 [00:03<00:13, 20.89it/s]

Chain 7:  68%|█████████████████████████████████████████████████████████████████████▍                                | 245/360 [00:09<00:02, 43.09it/s]

Chain 8:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:06<00:08, 25.82it/s]

Chain 9:  20%|████████████████████▌                                                                                  | 72/360 [00:03<00:13, 21.28it/s]

Chain 7:  70%|███████████████████████████████████████████████████████████████████████                               | 251/360 [00:09<00:02, 45.44it/s]

Chain 8:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:06<00:08, 26.19it/s]

Chain 9:  21%|█████████████████████▍                                                                                 | 75/360 [00:03<00:13, 21.64it/s]

Chain 7:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:09<00:02, 47.45it/s]

Chain 8:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:06<00:08, 26.17it/s]

Chain 8:  40%|█████████████████████████████████████████                                                             | 145/360 [00:06<00:08, 26.80it/s]

Chain 7:  73%|██████████████████████████████████████████████████████████████████████████▌                           | 263/360 [00:09<00:01, 49.78it/s]

Chain 9:  22%|██████████████████████▎                                                                                | 78/360 [00:03<00:12, 21.99it/s]

Chain 7:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:10<00:01, 51.85it/s]

Chain 8:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:06<00:07, 26.69it/s]

Chain 9:  22%|███████████████████████▏                                                                               | 81/360 [00:03<00:12, 22.17it/s]

Chain 8:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:06<00:07, 27.34it/s]

Chain 7:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:10<00:01, 54.85it/s]

Chain 9:  23%|████████████████████████                                                                               | 84/360 [00:03<00:12, 22.25it/s]

Chain 8:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:06<00:07, 27.70it/s]

Chain 7:  79%|████████████████████████████████████████████████████████████████████████████████▏                     | 283/360 [00:10<00:01, 58.16it/s]

Chain 9:  24%|████████████████████████▉                                                                              | 87/360 [00:03<00:12, 22.11it/s]

Chain 8:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:07, 27.50it/s]

Chain 7:  81%|██████████████████████████████████████████████████████████████████████████████████▍                   | 291/360 [00:10<00:01, 62.47it/s]

Chain 7:  83%|████████████████████████████████████████████████████████████████████████████████████▋                 | 299/360 [00:10<00:00, 66.69it/s]

Chain 8:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:07<00:07, 27.53it/s]

Chain 9:  25%|█████████████████████████▊                                                                             | 90/360 [00:03<00:12, 22.18it/s]

Chain 8:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:07<00:06, 28.19it/s]

Chain 7:  86%|███████████████████████████████████████████████████████████████████████████████████████▎              | 308/360 [00:10<00:00, 73.11it/s]

Chain 9:  26%|██████████████████████████▌                                                                            | 93/360 [00:04<00:12, 22.21it/s]

Chain 7:  88%|█████████████████████████████████████████████████████████████████████████████████████████▊            | 317/360 [00:10<00:00, 77.09it/s]

Chain 8:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:07<00:06, 27.84it/s]

Chain 9:  27%|███████████████████████████▍                                                                           | 96/360 [00:04<00:11, 22.39it/s]

Chain 7:  91%|████████████████████████████████████████████████████████████████████████████████████████████▉         | 328/360 [00:10<00:00, 85.77it/s]

Chain 8:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:07<00:06, 27.51it/s]

Chain 9:  28%|████████████████████████████▎                                                                          | 99/360 [00:04<00:11, 23.16it/s]

Chain 7:  95%|████████████████████████████████████████████████████████████████████████████████████████████████▏    | 343/360 [00:10<00:00, 103.70it/s]

Chain 8:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:07<00:06, 28.68it/s]

Chain 9:  28%|████████████████████████████▉                                                                         | 102/360 [00:04<00:11, 22.39it/s]

Chain 8:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:07<00:06, 28.36it/s]

Chain 9:  29%|█████████████████████████████▊                                                                        | 105/360 [00:04<00:11, 22.84it/s]

Chain 8:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:06, 29.01it/s]

Chain 9:  30%|██████████████████████████████▌                                                                       | 108/360 [00:04<00:10, 23.65it/s]

Chain 8:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:05, 30.48it/s]

Chain 9:  31%|███████████████████████████████▍                                                                      | 111/360 [00:04<00:10, 23.68it/s]

Chain 8:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:07<00:05, 31.55it/s]

Chain 9:  32%|████████████████████████████████▎                                                                     | 114/360 [00:05<00:10, 24.28it/s]

Chain 8:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:08<00:05, 32.38it/s]

Chain 9:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:05<00:09, 24.58it/s]

Chain 8:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:08<00:05, 32.50it/s]

Chain 9:  33%|██████████████████████████████████                                                                    | 120/360 [00:05<00:09, 24.94it/s]

Chain 8:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:08<00:04, 33.25it/s]

Chain 9:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:05<00:09, 25.32it/s]

Chain 8:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:08<00:04, 34.39it/s]

Chain 9:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:05<00:09, 25.76it/s]

Chain 8:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:08<00:04, 35.07it/s]

Chain 9:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:05<00:08, 25.69it/s]

Chain 8:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:08<00:04, 36.38it/s]

Chain 9:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:05<00:08, 25.95it/s]

Chain 8:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:08<00:03, 38.29it/s]

Chain 9:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:05<00:08, 26.41it/s]

Chain 8:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:08<00:03, 39.61it/s]

Chain 9:  38%|███████████████████████████████████████                                                               | 138/360 [00:05<00:08, 26.35it/s]

Chain 8:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:08<00:03, 40.19it/s]

Chain 9:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:06<00:08, 26.73it/s]

Chain 8:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:09<00:03, 41.64it/s]

Chain 9:  40%|████████████████████████████████████████▊                                                             | 144/360 [00:06<00:07, 27.08it/s]

Chain 8:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:09<00:02, 42.89it/s]

Chain 9:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:06<00:07, 27.56it/s]

Chain 8:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:09<00:02, 44.44it/s]

Chain 9:  42%|██████████████████████████████████████████▌                                                           | 150/360 [00:06<00:07, 28.11it/s]

Chain 8:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:09<00:02, 46.47it/s]

Chain 9:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:06<00:07, 28.26it/s]

Chain 8:  70%|███████████████████████████████████████████████████████████████████████▋                              | 253/360 [00:09<00:02, 47.06it/s]

Chain 9:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:06<00:06, 29.07it/s]

Chain 8:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:09<00:02, 48.70it/s]

Chain 9:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:06, 29.20it/s]

Chain 8:  74%|███████████████████████████████████████████████████████████████████████████                           | 265/360 [00:09<00:01, 51.55it/s]

Chain 8:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:09<00:01, 53.76it/s]

Chain 9:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:06<00:06, 29.99it/s]

Chain 8:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:09<00:01, 55.62it/s]

Chain 9:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:06<00:06, 30.53it/s]

Chain 8:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:10<00:01, 58.46it/s]

Chain 9:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:07<00:06, 31.01it/s]

Chain 8:  81%|██████████████████████████████████████████████████████████████████████████████████▋                   | 292/360 [00:10<00:01, 61.50it/s]

Chain 9:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:07<00:05, 31.10it/s]

Chain 8:  84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 301/360 [00:10<00:00, 67.89it/s]

Chain 9:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:07<00:05, 31.98it/s]

Chain 8:  86%|████████████████████████████████████████████████████████████████████████████████████████              | 311/360 [00:10<00:00, 75.46it/s]

Chain 9:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:07<00:05, 32.71it/s]

Chain 8:  89%|██████████████████████████████████████████████████████████████████████████████████████████▉           | 321/360 [00:10<00:00, 82.19it/s]

Chain 9:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:07<00:05, 33.31it/s]

Chain 8:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▉       | 335/360 [00:10<00:00, 98.38it/s]

Chain 9:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:07<00:04, 34.17it/s]

Chain 8:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████▌ | 355/360 [00:10<00:00, 127.78it/s]

Chain 9:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:07<00:04, 34.85it/s]

Chain 9:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:07<00:04, 35.75it/s]

Chain 9:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:07<00:04, 36.38it/s]

Chain 9:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:08<00:04, 37.53it/s]

Chain 9:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:08<00:03, 38.67it/s]

Chain 9:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:08<00:03, 38.87it/s]

Chain 9:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:08<00:03, 40.56it/s]

Chain 9:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:08<00:03, 41.82it/s]

Chain 9:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:08<00:02, 43.35it/s]

Chain 9:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:08<00:02, 44.50it/s]

Chain 9:  68%|████████████████████████████████████████████████████████████████████▊                                 | 243/360 [00:08<00:02, 45.81it/s]

Chain 9:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:08<00:02, 47.97it/s]

Chain 9:  71%|████████████████████████████████████████████████████████████████████████▎                             | 255/360 [00:09<00:02, 50.14it/s]

Chain 9:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:09<00:01, 52.71it/s]

Chain 9:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:09<00:01, 53.68it/s]

Chain 9:  76%|█████████████████████████████████████████████████████████████████████████████▋                        | 274/360 [00:09<00:01, 56.54it/s]

Chain 9:  78%|███████████████████████████████████████████████████████████████████████████████▉                      | 282/360 [00:09<00:01, 61.06it/s]

Chain 9:  81%|██████████████████████████████████████████████████████████████████████████████████▏                   | 290/360 [00:09<00:01, 65.83it/s]

Chain 9:  83%|████████████████████████████████████████████████████████████████████████████████████▋                 | 299/360 [00:09<00:00, 71.34it/s]

Chain 9:  86%|███████████████████████████████████████████████████████████████████████████████████████▌              | 309/360 [00:09<00:00, 78.68it/s]

Chain 9:  89%|██████████████████████████████████████████████████████████████████████████████████████████▉           | 321/360 [00:09<00:00, 88.63it/s]

Chain 9:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▎      | 336/360 [00:10<00:00, 105.71it/s]

2026-05-28 22:10:42.449 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 22:10:43.047 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 22:10:49.330 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 22:10:50.056 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 22:10:50.057 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 22:10:50.064 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 22:10:51.276 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 22:10:51.322 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 22:10:51.980 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 22:10:53.064 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 22:10:54.194 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 22:10:54.412 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 22:10:54.413 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,114.3,175.0,286.7,430.7,609.3
GIIP (mscf),Total Volumes,1.0,45.3,72.9,125.2,198.0,301.8
Condensate (stb),Total Volumes,1.0,1.4,2.4,4.4,7.7,12.6
Solution Gas (mscf),Total Volumes,1.0,186.6,309.8,531.1,847.1,1290.7

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50    P10     P1
Total Oil EUR         1.0  25.3  39.8  65.3  101.0  146.1

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90   P50   P10    P1
reservoir
Zone 1           0.65  0.9  2.4   5.9  13.0  23.8
Zone 2           0.74  0.4  1.6   5.4  14.7  31.9
Zone 3           0.87  1.2  2.6   5.7  12.0  22.8
Zone 4           0.88  0.8  2.6   8.0  23.1  54.1
Zone 5           0.70  0.8  2.4   6.4  15.3  32.1
Zone 6           0.85  0.5  1.8   5.8  16.0  35.4
Zone 7           0.74  1.5  4.2  11.3  29.0  57.6
Zone 8           0.90  1.0  2.6   7.0  17.3  33.3
Zone 9           0.47  1.2  3.2   7.9  18.5  35.2
Zone 10          0.56  1.0  3.2   9.6  25.8  58.8

In [14]:
reporter.tabler.npv_table()

     P(Commercial)    P99    P90     P50     P10      P1
NPV           0.98 -134.0  366.0  1066.0  1832.0  2498.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)    P99    P90     P50     P10      P1
EMV           0.98 -133.0  356.0  1040.0  1789.0  2439.0

In [16]:
from resgo.plotting.tables import npv_USD
import numpy as np
import pandas as pd

npv = npv_USD(
    simpack,
    nominal=True,
    discounted=True,
    success_only=False,
)
npv_usd = npv.to_numpy().ravel()
npv_df = pd.DataFrame({"npv_usd_mm": npv_usd / 1e6})

histogram = (
    alt.Chart(npv_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Nominal discounted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Project NPV Distribution",
    )
)

break_even = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(histogram, break_even)
fig.show()

alt.LayerChart(...)

In [17]:
BANKRUPTCY_THRESHOLD_USD = 300e6
LOSS_FLOOR_USD = -5e9

def loss_adjusted_npv_USD(
    npv_usd,
    bankruptcy_threshold_usd=BANKRUPTCY_THRESHOLD_USD,
    floor_usd=LOSS_FLOOR_USD,
):
    npv_usd = np.asarray(npv_usd)
    threshold = bankruptcy_threshold_usd

    with np.errstate(divide="ignore", invalid="ignore"):
        adjusted = np.where(
            npv_usd >= 0,
            npv_usd,
            (threshold * npv_usd) / (threshold + npv_usd),
        )

    adjusted = np.where(npv_usd <= -threshold, floor_usd, adjusted)
    return np.maximum(adjusted, floor_usd)

x_usd = np.linspace(-0.9999 * BANKRUPTCY_THRESHOLD_USD, 1.5e9, 1_000)
loss_function_df = pd.DataFrame(
    {
        "npv_usd_mm": x_usd / 1e6,
        "loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(x_usd) / 1e6,
    }
)
loss_function_plot_df = loss_function_df[
    loss_function_df["loss_adjusted_npv_usd_mm"] > LOSS_FLOOR_USD / 1e6
]

loss_function = (
    alt.Chart(loss_function_plot_df)
    .mark_line(color="#FACC15", strokeWidth=3)
    .encode(
        x=alt.X("npv_usd_mm:Q", title="Nominal discounted NPV ($USD MM)"),
        y=alt.Y(
            "loss_adjusted_npv_usd_mm:Q",
            title="Loss-adjusted NPV ($USD MM)",
        ),
        tooltip=[
            alt.Tooltip("npv_usd_mm:Q", title="NPV ($MM)", format=",.0f"),
            alt.Tooltip(
                "loss_adjusted_npv_usd_mm:Q",
                title="Loss-adjusted NPV ($MM)",
                format=",.0f",
            ),
        ],
    )
    .properties(
        width=650,
        height=250,
        title="Company Loss Function",
    )
)

bankruptcy_threshold = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [-BANKRUPTCY_THRESHOLD_USD / 1e6]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(loss_function, bankruptcy_threshold)
fig.show()

alt.LayerChart(...)

In [18]:
loss_df = pd.DataFrame(
    {"loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(npv_usd) / 1e6}
)

loss_histogram = (
    alt.Chart(loss_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "loss_adjusted_npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Loss-adjusted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated Loss-Adjusted NPV Distribution",
    )
)

break_even_loss = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_histogram, break_even_loss)
fig.show()

alt.LayerChart(...)