In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_3904686/1985460196.py:25: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats(fig_format)

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"

CHAINS = 4
DRAWS = 500
N_RESERVOIRS = 9
N_PRODUCERS = 25

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=90_000,
    gas_development=False,
    producer_capex_USD=45e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=60e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2_000_000,
    producer_abandonment_cost_USD=500_000,
)

simpack = prospect.simulate(risked=True, levered=True, chains=CHAINS, draws=DRAWS)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 13:37:19.801 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 13:37:19.805 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 13:37:19.808 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 13:37:19.812 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 13:37:19.815 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 13:37:19.819 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 13:37:19.822 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 7 reservoir volumetric simulation complete.

2026-05-28 13:37:19.826 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 8 reservoir volumetric simulation complete.

2026-05-28 13:37:19.829 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:128 - Zone 9 reservoir volumetric simulation complete.

2026-05-28 13:37:19.834 | INFO     | resgo.engine.volumetric_simulator:simulate:72 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 13:37:19.834 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:77 - Demo Prospect volumetric simulation complete!

2026-05-28 13:37:20.176 | INFO     | resgo.engine.production_simulator:prepare_simpack:142 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 13:37:20.177 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 1 start_idx = 8

2026-05-28 13:37:20.177 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 2 start_idx = 20

2026-05-28 13:37:20.177 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 3 start_idx = 32

2026-05-28 13:37:20.177 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 4 start_idx = 44

2026-05-28 13:37:20.177 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 5 start_idx = 56

2026-05-28 13:37:20.178 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 6 start_idx = 68

2026-05-28 13:37:20.178 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 7 start_idx = 79

2026-05-28 13:37:20.178 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 8 start_idx = 91

2026-05-28 13:37:20.178 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 9 start_idx = 103

2026-05-28 13:37:20.178 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 10 start_idx = 115

2026-05-28 13:37:20.178 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 11 start_idx = 127

2026-05-28 13:37:20.178 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 12 start_idx = 139

2026-05-28 13:37:20.179 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 13 start_idx = 150

2026-05-28 13:37:20.179 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 14 start_idx = 162

2026-05-28 13:37:20.179 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 15 start_idx = 174

2026-05-28 13:37:20.179 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 16 start_idx = 186

2026-05-28 13:37:20.179 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 17 start_idx = 198

2026-05-28 13:37:20.179 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 18 start_idx = 209

2026-05-28 13:37:20.179 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 19 start_idx = 221

2026-05-28 13:37:20.180 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 20 start_idx = 233

2026-05-28 13:37:20.180 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 21 start_idx = 245

2026-05-28 13:37:20.180 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 22 start_idx = 257

2026-05-28 13:37:20.180 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 23 start_idx = 269

2026-05-28 13:37:20.181 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 24 start_idx = 280

2026-05-28 13:37:20.181 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:206 - Oil 25 start_idx = 292

2026-05-28 13:37:20.200 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:232 - Flowing array initialized.

2026-05-28 13:37:20.209 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:419 - Recovery factors simulated.

2026-05-28 13:37:20.655 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:303 - Oil well rates initialized.

2026-05-28 13:37:20.656 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:319 - No gas producers, skipping gas rate initialization...

2026-05-28 13:37:20.656 | INFO     | resgo.engine.production_simulator:simulate:84 - Commencing field production simulation (25 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 85.16it/s]

Chain 0:   6%|█████▋                                                                                                 | 20/360 [00:00<00:09, 35.25it/s]

Chain 0:   7%|███████▏                                                                                               | 25/360 [00:00<00:10, 31.21it/s]

Chain 0:   8%|████████▎                                                                                              | 29/360 [00:00<00:11, 28.56it/s]

Chain 0:   9%|█████████▍                                                                                             | 33/360 [00:01<00:11, 27.39it/s]

Chain 0:  10%|██████████▎                                                                                            | 36/360 [00:01<00:12, 26.75it/s]

Chain 0:  11%|███████████▏                                                                                           | 39/360 [00:01<00:12, 26.19it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:01<00:12, 25.73it/s]

Chain 0:  12%|████████████▉                                                                                          | 45/360 [00:01<00:12, 25.15it/s]

Chain 0:  13%|█████████████▋                                                                                         | 48/360 [00:01<00:12, 25.33it/s]

Chain 0:  14%|██████████████▌                                                                                        | 51/360 [00:01<00:12, 25.37it/s]

Chain 0:  15%|███████████████▍                                                                                       | 54/360 [00:01<00:12, 24.98it/s]

Chain 0:  16%|████████████████▎                                                                                      | 57/360 [00:02<00:12, 24.47it/s]

Chain 0:  17%|█████████████████▏                                                                                     | 60/360 [00:02<00:12, 24.10it/s]

Chain 0:  18%|██████████████████                                                                                     | 63/360 [00:02<00:12, 24.47it/s]

Chain 0:  18%|██████████████████▉                                                                                    | 66/360 [00:02<00:11, 25.63it/s]

Chain 0:  19%|███████████████████▋                                                                                   | 69/360 [00:02<00:11, 26.28it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  20%|████████████████████▌                                                                                  | 72/360 [00:02<00:10, 26.94it/s]

Chain 1:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 79.25it/s]

Chain 0:  21%|█████████████████████▍                                                                                 | 75/360 [00:02<00:10, 27.37it/s]

Chain 0:  22%|██████████████████████▎                                                                                | 78/360 [00:02<00:10, 27.49it/s]

Chain 0:  22%|███████████████████████▏                                                                               | 81/360 [00:02<00:10, 27.14it/s]

Chain 1:   5%|█████▍                                                                                                 | 19/360 [00:00<00:10, 33.27it/s]

Chain 0:  23%|████████████████████████                                                                               | 84/360 [00:03<00:10, 26.89it/s]

Chain 0:  24%|████████████████████████▉                                                                              | 87/360 [00:03<00:10, 27.18it/s]

Chain 1:   7%|██████▊                                                                                                | 24/360 [00:00<00:11, 29.05it/s]

Chain 0:  25%|█████████████████████████▊                                                                             | 90/360 [00:03<00:09, 27.75it/s]

Chain 0:  26%|██████████████████████████▌                                                                            | 93/360 [00:03<00:09, 27.02it/s]

Chain 1:   8%|████████                                                                                               | 28/360 [00:00<00:12, 26.66it/s]

Chain 0:  27%|███████████████████████████▍                                                                           | 96/360 [00:03<00:09, 27.36it/s]

Chain 0:  28%|████████████████████████████▎                                                                          | 99/360 [00:03<00:09, 27.96it/s]

Chain 1:   9%|████████▊                                                                                              | 31/360 [00:01<00:13, 23.85it/s]

Chain 0:  28%|████████████████████████████▉                                                                         | 102/360 [00:03<00:09, 27.98it/s]

Chain 1:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 23.65it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:03<00:08, 28.42it/s]

Chain 1:  10%|██████████▌                                                                                            | 37/360 [00:01<00:13, 23.63it/s]

Chain 0:  30%|██████████████████████████████▌                                                                       | 108/360 [00:03<00:08, 28.68it/s]

Chain 1:  11%|███████████▍                                                                                           | 40/360 [00:01<00:13, 23.33it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:03<00:08, 28.76it/s]

Chain 0:  32%|████████████████████████████████▎                                                                     | 114/360 [00:04<00:08, 28.99it/s]

Chain 1:  12%|████████████▎                                                                                          | 43/360 [00:01<00:13, 22.96it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:04<00:08, 28.90it/s]

Chain 1:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:13, 23.06it/s]

Chain 0:  33%|██████████████████████████████████                                                                    | 120/360 [00:04<00:08, 28.94it/s]

Chain 1:  14%|██████████████                                                                                         | 49/360 [00:01<00:13, 23.39it/s]

Chain 0:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:04<00:08, 28.33it/s]

Chain 1:  14%|██████████████▉                                                                                        | 52/360 [00:01<00:13, 23.46it/s]

Chain 0:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:04<00:08, 28.95it/s]

Chain 1:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 23.26it/s]

Chain 0:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:04<00:07, 28.98it/s]

Chain 0:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:04<00:07, 28.93it/s]

Chain 1:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:13, 22.10it/s]

Chain 0:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:04<00:07, 28.92it/s]

Chain 1:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:13, 22.58it/s]

Chain 0:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:04<00:07, 28.08it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:12, 23.01it/s]

Chain 0:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:05<00:07, 28.05it/s]

Chain 1:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:12, 24.15it/s]

Chain 2:   3%|███▏                                                                                                   | 11/360 [00:00<00:04, 79.04it/s]

Chain 0:  40%|█████████████████████████████████████████                                                             | 145/360 [00:05<00:07, 28.37it/s]

Chain 1:  19%|████████████████████                                                                                   | 70/360 [00:02<00:11, 24.93it/s]

Chain 0:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:05<00:07, 28.78it/s]

Chain 1:  20%|████████████████████▉                                                                                  | 73/360 [00:02<00:11, 25.63it/s]

Chain 0:  42%|███████████████████████████████████████████                                                           | 152/360 [00:05<00:07, 29.44it/s]

Chain 1:  21%|█████████████████████▋                                                                                 | 76/360 [00:02<00:10, 26.20it/s]

Chain 2:   5%|█████▍                                                                                                 | 19/360 [00:00<00:10, 33.34it/s]

Chain 0:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:05<00:06, 30.00it/s]

Chain 1:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:10, 26.80it/s]

Chain 0:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:05<00:06, 30.75it/s]

Chain 1:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:10, 26.58it/s]

Chain 2:   7%|██████▊                                                                                                | 24/360 [00:00<00:11, 28.86it/s]

Chain 0:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:05<00:06, 31.06it/s]

Chain 1:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:10, 26.67it/s]

Chain 1:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:10, 26.96it/s]

Chain 0:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:05<00:06, 31.47it/s]

Chain 2:   8%|████████                                                                                               | 28/360 [00:00<00:12, 26.53it/s]

Chain 1:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:10, 26.57it/s]

Chain 0:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:06<00:05, 31.67it/s]

Chain 2:   9%|████████▊                                                                                              | 31/360 [00:01<00:12, 25.60it/s]

Chain 1:  26%|██████████████████████████▉                                                                            | 94/360 [00:03<00:10, 24.54it/s]

Chain 0:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:06<00:06, 30.10it/s]

Chain 2:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 24.90it/s]

Chain 1:  27%|███████████████████████████▊                                                                           | 97/360 [00:03<00:10, 24.91it/s]

Chain 0:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:06<00:05, 30.62it/s]

Chain 2:  10%|██████████▌                                                                                            | 37/360 [00:01<00:13, 24.39it/s]

Chain 1:  28%|████████████████████████████▎                                                                         | 100/360 [00:03<00:10, 25.51it/s]

Chain 0:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:06<00:05, 31.85it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:01<00:13, 23.88it/s]

Chain 1:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:09, 26.03it/s]

Chain 0:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:06<00:05, 32.11it/s]

Chain 2:  12%|████████████▎                                                                                          | 43/360 [00:01<00:13, 23.24it/s]

Chain 1:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:09, 26.36it/s]

Chain 0:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:06<00:04, 33.78it/s]

Chain 1:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:09, 27.10it/s]

Chain 2:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:13, 23.37it/s]

Chain 0:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:06<00:04, 35.10it/s]

Chain 1:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:09, 26.46it/s]

Chain 2:  14%|██████████████                                                                                         | 49/360 [00:01<00:13, 23.51it/s]

Chain 0:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:06<00:04, 36.33it/s]

Chain 1:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:09, 27.15it/s]

Chain 0:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:06<00:04, 37.03it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:01<00:13, 23.23it/s]

Chain 1:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:04<00:08, 27.20it/s]

Chain 0:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:07<00:04, 36.93it/s]

Chain 2:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 23.03it/s]

Chain 1:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:04<00:08, 27.71it/s]

Chain 0:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:07<00:03, 37.96it/s]

Chain 1:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:04<00:08, 28.24it/s]

Chain 2:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:13, 22.34it/s]

Chain 0:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:07<00:03, 38.35it/s]

Chain 1:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:04<00:08, 28.24it/s]

Chain 2:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:13, 22.57it/s]

Chain 0:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:07<00:03, 39.57it/s]

Chain 1:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:04<00:08, 27.79it/s]

Chain 2:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:13, 22.71it/s]

Chain 0:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:07<00:03, 40.87it/s]

Chain 1:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:07, 28.39it/s]

Chain 0:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:07<00:02, 42.73it/s]

Chain 2:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:12, 23.67it/s]

Chain 1:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:07, 28.05it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:07<00:02, 42.92it/s]

Chain 2:  19%|████████████████████                                                                                   | 70/360 [00:02<00:12, 23.99it/s]

Chain 3:   3%|██▊                                                                                                    | 10/360 [00:00<00:03, 98.92it/s]

Chain 1:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:05<00:07, 27.78it/s]

Chain 0:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:07<00:02, 43.78it/s]

Chain 2:  20%|████████████████████▉                                                                                  | 73/360 [00:02<00:11, 24.39it/s]

Chain 1:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:05<00:07, 27.90it/s]

Chain 0:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:07<00:02, 45.50it/s]

Chain 2:  21%|█████████████████████▋                                                                                 | 76/360 [00:02<00:11, 25.05it/s]

Chain 1:  40%|█████████████████████████████████████████                                                             | 145/360 [00:05<00:07, 27.89it/s]

Chain 0:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:08<00:02, 46.43it/s]

Chain 2:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:10, 25.63it/s]

Chain 1:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:05<00:07, 28.41it/s]

Chain 0:  72%|█████████████████████████████████████████████████████████████████████████                             | 258/360 [00:08<00:02, 49.62it/s]

Chain 1:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:05<00:07, 28.61it/s]

Chain 2:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:10, 25.42it/s]

Chain 0:  73%|██████████████████████████████████████████████████████████████████████████▊                           | 264/360 [00:08<00:01, 52.09it/s]

Chain 3:   6%|█████▋                                                                                                 | 20/360 [00:00<00:11, 30.41it/s]

Chain 1:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:05<00:07, 28.85it/s]

Chain 2:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:10, 25.98it/s]

Chain 0:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:08<00:01, 54.35it/s]

Chain 1:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:05<00:06, 29.01it/s]

Chain 2:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:10, 26.61it/s]

Chain 0:  77%|██████████████████████████████████████████████████████████████████████████████▍                       | 277/360 [00:08<00:01, 57.75it/s]

Chain 1:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:06<00:06, 30.09it/s]

Chain 2:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:10, 26.24it/s]

Chain 3:   7%|███████▍                                                                                               | 26/360 [00:00<00:12, 26.56it/s]

Chain 0:  79%|████████████████████████████████████████████████████████████████████████████████▍                     | 284/360 [00:08<00:01, 60.07it/s]

Chain 2:  26%|██████████████████████████▉                                                                            | 94/360 [00:03<00:10, 26.25it/s]

Chain 1:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:06<00:06, 30.43it/s]

Chain 0:  81%|██████████████████████████████████████████████████████████████████████████████████▋                   | 292/360 [00:08<00:01, 63.99it/s]

Chain 3:   8%|████████▌                                                                                              | 30/360 [00:01<00:13, 25.04it/s]

Chain 2:  27%|███████████████████████████▊                                                                           | 97/360 [00:03<00:10, 26.23it/s]

Chain 0:  84%|█████████████████████████████████████████████████████████████████████████████████████▎                | 301/360 [00:08<00:00, 69.76it/s]

Chain 1:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:06<00:06, 30.26it/s]

Chain 2:  28%|████████████████████████████▎                                                                         | 100/360 [00:03<00:09, 26.64it/s]

Chain 0:  86%|████████████████████████████████████████████████████████████████████████████████████████              | 311/360 [00:08<00:00, 76.66it/s]

Chain 1:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:06<00:06, 31.02it/s]

Chain 3:   9%|█████████▋                                                                                             | 34/360 [00:01<00:13, 23.94it/s]

Chain 2:  29%|█████████████████████████████▏                                                                        | 103/360 [00:03<00:09, 26.72it/s]

Chain 0:  89%|███████████████████████████████████████████████████████████████████████████████████████████▏          | 322/360 [00:09<00:00, 85.25it/s]

Chain 1:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:06<00:05, 31.12it/s]

Chain 3:  10%|██████████▌                                                                                            | 37/360 [00:01<00:14, 23.07it/s]

Chain 0:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▋       | 334/360 [00:09<00:00, 94.51it/s]

Chain 2:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:09, 26.34it/s]

Chain 1:  50%|███████████████████████████████████████████████████▎                                                  | 181/360 [00:06<00:05, 30.42it/s]

Chain 0:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████▏  | 350/360 [00:09<00:00, 112.67it/s]

Chain 2:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:10, 24.59it/s]

Chain 3:  11%|███████████▍                                                                                           | 40/360 [00:01<00:15, 21.15it/s]

Chain 1:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:06<00:05, 31.95it/s]

Chain 2:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:09, 25.05it/s]

Chain 3:  12%|████████████▎                                                                                          | 43/360 [00:01<00:15, 21.04it/s]

Chain 1:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:06<00:05, 32.60it/s]

Chain 2:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:09, 26.04it/s]

Chain 1:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:07<00:04, 33.62it/s]

Chain 3:  13%|█████████████▏                                                                                         | 46/360 [00:01<00:14, 21.32it/s]

Chain 2:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:04<00:09, 26.56it/s]

Chain 1:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:07<00:04, 33.96it/s]

Chain 3:  14%|██████████████                                                                                         | 49/360 [00:01<00:14, 21.61it/s]

Chain 2:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:04<00:08, 27.11it/s]

Chain 1:  56%|████████████████████████████████████████████████████████▉                                             | 201/360 [00:07<00:04, 34.42it/s]

Chain 2:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:04<00:08, 27.46it/s]

Chain 3:  14%|██████████████▉                                                                                        | 52/360 [00:02<00:14, 21.80it/s]

Chain 1:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:07<00:04, 35.12it/s]

Chain 2:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:04<00:08, 28.24it/s]

Chain 3:  15%|███████████████▋                                                                                       | 55/360 [00:02<00:13, 21.97it/s]

Chain 1:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:07<00:04, 36.20it/s]

Chain 2:  36%|█████████████████████████████████████                                                                 | 131/360 [00:05<00:08, 28.28it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:07<00:04, 36.18it/s]

Chain 3:  16%|████████████████▌                                                                                      | 58/360 [00:02<00:14, 21.53it/s]

Chain 2:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:05<00:08, 27.85it/s]

Chain 1:  60%|█████████████████████████████████████████████████████████████▍                                        | 217/360 [00:07<00:03, 37.18it/s]

Chain 3:  17%|█████████████████▍                                                                                     | 61/360 [00:02<00:13, 21.80it/s]

Chain 2:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:05<00:07, 27.99it/s]

Chain 1:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:07<00:03, 38.75it/s]

Chain 3:  18%|██████████████████▎                                                                                    | 64/360 [00:02<00:12, 22.82it/s]

Chain 2:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:05<00:07, 28.19it/s]

Chain 1:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:07<00:03, 40.26it/s]

Chain 3:  19%|███████████████████▏                                                                                   | 67/360 [00:02<00:12, 24.05it/s]

Chain 2:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:05<00:07, 27.88it/s]

Chain 1:  64%|█████████████████████████████████████████████████████████████████▋                                    | 232/360 [00:08<00:03, 42.12it/s]

Chain 3:  19%|████████████████████                                                                                   | 70/360 [00:02<00:11, 24.90it/s]

Chain 2:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:05<00:07, 28.00it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:08<00:02, 43.61it/s]

Chain 3:  20%|████████████████████▉                                                                                  | 73/360 [00:02<00:11, 25.83it/s]

Chain 2:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:05<00:07, 27.94it/s]

Chain 1:  67%|████████████████████████████████████████████████████████████████████▌                                 | 242/360 [00:08<00:02, 45.00it/s]

Chain 3:  21%|█████████████████████▋                                                                                 | 76/360 [00:03<00:10, 26.50it/s]

Chain 2:  42%|███████████████████████████████████████████                                                           | 152/360 [00:05<00:07, 28.17it/s]

Chain 1:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:08<00:02, 46.92it/s]

Chain 3:  22%|██████████████████████▌                                                                                | 79/360 [00:03<00:10, 26.68it/s]

Chain 2:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:05<00:07, 28.78it/s]

Chain 1:  71%|███████████████████████████████████████████████████████████████████████▉                              | 254/360 [00:08<00:02, 49.16it/s]

Chain 3:  23%|███████████████████████▍                                                                               | 82/360 [00:03<00:10, 26.34it/s]

Chain 2:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:06<00:06, 29.38it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:08<00:01, 50.08it/s]

Chain 3:  24%|████████████████████████▎                                                                              | 85/360 [00:03<00:10, 26.31it/s]

Chain 2:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:06<00:06, 30.00it/s]

Chain 1:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:08<00:01, 53.40it/s]

Chain 3:  24%|█████████████████████████▏                                                                             | 88/360 [00:03<00:10, 26.39it/s]

Chain 1:  76%|█████████████████████████████████████████████████████████████████████████████▎                        | 273/360 [00:08<00:01, 54.98it/s]

Chain 2:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:06<00:06, 30.59it/s]

Chain 3:  25%|██████████████████████████                                                                             | 91/360 [00:03<00:09, 26.93it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:08<00:01, 58.00it/s]

Chain 2:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:06<00:05, 31.55it/s]

Chain 3:  26%|██████████████████████████▉                                                                            | 94/360 [00:03<00:09, 26.93it/s]

Chain 1:  80%|█████████████████████████████████████████████████████████████████████████████████▎                    | 287/360 [00:09<00:01, 61.03it/s]

Chain 2:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:06<00:05, 31.74it/s]

Chain 3:  27%|███████████████████████████▊                                                                           | 97/360 [00:03<00:09, 27.12it/s]

Chain 1:  82%|███████████████████████████████████████████████████████████████████████████████████▌                  | 295/360 [00:09<00:01, 64.60it/s]

Chain 3:  28%|████████████████████████████▎                                                                         | 100/360 [00:03<00:09, 26.97it/s]

Chain 2:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:06<00:05, 31.94it/s]

Chain 1:  84%|██████████████████████████████████████████████████████████████████████████████████████▏               | 304/360 [00:09<00:00, 70.18it/s]

Chain 3:  29%|█████████████████████████████▏                                                                        | 103/360 [00:04<00:09, 27.37it/s]

Chain 2:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:06<00:05, 32.49it/s]

Chain 1:  87%|████████████████████████████████████████████████████████████████████████████████████████▉             | 314/360 [00:09<00:00, 76.79it/s]

Chain 3:  29%|██████████████████████████████                                                                        | 106/360 [00:04<00:09, 27.63it/s]

Chain 2:  52%|█████████████████████████████████████████████████████▎                                                | 188/360 [00:06<00:05, 33.19it/s]

Chain 1:  90%|████████████████████████████████████████████████████████████████████████████████████████████          | 325/360 [00:09<00:00, 85.88it/s]

Chain 3:  30%|██████████████████████████████▉                                                                       | 109/360 [00:04<00:08, 28.15it/s]

Chain 2:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:06<00:04, 34.61it/s]

Chain 1:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▍     | 340/360 [00:09<00:00, 104.12it/s]

Chain 3:  31%|███████████████████████████████▋                                                                      | 112/360 [00:04<00:08, 28.54it/s]

Chain 2:  54%|███████████████████████████████████████████████████████▌                                              | 196/360 [00:07<00:04, 35.63it/s]

Chain 3:  32%|████████████████████████████████▌                                                                     | 115/360 [00:04<00:08, 28.74it/s]

Chain 2:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:07<00:04, 36.30it/s]

Chain 3:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:04<00:08, 28.83it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:07<00:04, 37.87it/s]

Chain 3:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:04<00:08, 28.87it/s]

Chain 2:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:07<00:03, 38.90it/s]

Chain 3:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:04<00:08, 28.97it/s]

Chain 2:  60%|████████████████████████████████████████████████████████████▉                                         | 215/360 [00:07<00:03, 39.93it/s]

Chain 3:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:04<00:08, 28.91it/s]

Chain 2:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:07<00:03, 41.03it/s]

Chain 3:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:05<00:07, 29.01it/s]

Chain 2:  62%|███████████████████████████████████████████████████████████████▊                                      | 225/360 [00:07<00:03, 42.18it/s]

Chain 3:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:05<00:07, 29.15it/s]

Chain 3:  38%|██████████████████████████████████████▌                                                               | 136/360 [00:05<00:07, 28.41it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:07<00:03, 42.55it/s]

Chain 2:  65%|██████████████████████████████████████████████████████████████████▌                                   | 235/360 [00:08<00:02, 44.10it/s]

Chain 3:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:05<00:07, 29.20it/s]

Chain 2:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:08<00:02, 45.17it/s]

Chain 3:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:05<00:07, 29.32it/s]

Chain 2:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:08<00:02, 47.32it/s]

Chain 3:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:05<00:07, 30.15it/s]

Chain 2:  70%|███████████████████████████████████████████████████████████████████████▍                              | 252/360 [00:08<00:02, 48.94it/s]

Chain 3:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:05<00:06, 30.56it/s]

Chain 2:  72%|█████████████████████████████████████████████████████████████████████████                             | 258/360 [00:08<00:01, 51.13it/s]

Chain 3:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:05<00:06, 30.79it/s]

Chain 2:  73%|██████████████████████████████████████████████████████████████████████████▊                           | 264/360 [00:08<00:01, 52.02it/s]

Chain 3:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:05<00:06, 31.24it/s]

Chain 2:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:08<00:01, 55.09it/s]

Chain 3:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:06<00:06, 31.75it/s]

Chain 2:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:08<00:01, 59.15it/s]

Chain 2:  79%|████████████████████████████████████████████████████████████████████████████████▊                     | 285/360 [00:08<00:01, 62.09it/s]

Chain 3:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:06<00:06, 31.62it/s]

Chain 2:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:08<00:01, 65.93it/s]

Chain 3:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:06<00:05, 32.29it/s]

Chain 2:  84%|█████████████████████████████████████████████████████████████████████████████████████▌                | 302/360 [00:09<00:00, 72.20it/s]

Chain 3:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:06<00:05, 32.68it/s]

Chain 2:  87%|████████████████████████████████████████████████████████████████████████████████████████▍             | 312/360 [00:09<00:00, 79.71it/s]

Chain 3:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:06<00:05, 33.00it/s]

Chain 2:  90%|███████████████████████████████████████████████████████████████████████████████████████████▊          | 324/360 [00:09<00:00, 90.91it/s]

Chain 3:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:06<00:05, 33.40it/s]

Chain 2:  94%|███████████████████████████████████████████████████████████████████████████████████████████████▍     | 340/360 [00:09<00:00, 110.67it/s]

Chain 3:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:06<00:05, 34.47it/s]

Chain 3:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:06<00:04, 35.07it/s]

Chain 3:  54%|███████████████████████████████████████████████████████▏                                              | 195/360 [00:07<00:04, 36.28it/s]

Chain 3:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:07<00:04, 36.82it/s]

Chain 3:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:07<00:04, 38.43it/s]

Chain 3:  58%|██████████████████████████████████████████████████████████▉                                           | 208/360 [00:07<00:03, 38.52it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:07<00:03, 40.06it/s]

Chain 3:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:07<00:03, 41.37it/s]

Chain 3:  62%|███████████████████████████████████████████████████████████████▏                                      | 223/360 [00:07<00:03, 42.53it/s]

Chain 3:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:07<00:02, 44.02it/s]

Chain 3:  65%|██████████████████████████████████████████████████████████████████                                    | 233/360 [00:07<00:02, 45.69it/s]

Chain 3:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:07<00:02, 45.79it/s]

Chain 3:  68%|█████████████████████████████████████████████████████████████████████▏                                | 244/360 [00:08<00:02, 47.53it/s]

Chain 3:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:08<00:02, 50.00it/s]

Chain 3:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:08<00:01, 52.39it/s]

Chain 3:  73%|██████████████████████████████████████████████████████████████████████████▏                           | 262/360 [00:08<00:01, 54.42it/s]

Chain 3:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:08<00:01, 57.54it/s]

Chain 3:  77%|██████████████████████████████████████████████████████████████████████████████▏                       | 276/360 [00:08<00:01, 60.70it/s]

Chain 3:  79%|████████████████████████████████████████████████████████████████████████████████▍                     | 284/360 [00:08<00:01, 64.38it/s]

Chain 3:  81%|███████████████████████████████████████████████████████████████████████████████████                   | 293/360 [00:08<00:00, 69.94it/s]

Chain 3:  84%|█████████████████████████████████████████████████████████████████████████████████████▌                | 302/360 [00:08<00:00, 75.52it/s]

Chain 3:  87%|████████████████████████████████████████████████████████████████████████████████████████▍             | 312/360 [00:09<00:00, 81.70it/s]

Chain 3:  90%|████████████████████████████████████████████████████████████████████████████████████████████          | 325/360 [00:09<00:00, 94.44it/s]

Chain 3:  95%|███████████████████████████████████████████████████████████████████████████████████████████████▉     | 342/360 [00:09<00:00, 115.89it/s]

2026-05-28 13:37:43.578 | SUCCESS  | resgo.engine.production_simulator:simulate:101 - Demo Prospect Field production simulation complete!

2026-05-28 13:37:43.819 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:315 - Discount and inflation curves initialized

2026-05-28 13:37:46.506 | INFO     | resgo.engine.economic_simulator:simulate_capex:375 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 13:37:46.884 | INFO     | resgo.engine.economic_simulator:simulate_leverage:389 - Debt repayments simulated.

2026-05-28 13:37:46.884 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:402 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 13:37:46.892 | INFO     | resgo.engine.economic_simulator:simulate_prices:417 - Oil and Gas prices simulated using a flat price model.

2026-05-28 13:37:47.372 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:443 - Gross sales simulated.

2026-05-28 13:37:47.392 | INFO     | resgo.engine.economic_simulator:simulate_expenses:462 - OPEX and ABEX simulated.

2026-05-28 13:37:47.648 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:487 - Royalties simulated using a flat royalty model.

2026-05-28 13:37:48.053 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:513 - Infrastructure depreciation model simulated.

2026-05-28 13:37:48.492 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:527 - Producer depreciation model simulated.

2026-05-28 13:37:48.594 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:538 - Taxes simulated using a progressive tax model.

2026-05-28 13:37:48.594 | SUCCESS  | resgo.engine.economic_simulator:simulate:299 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,128.2,190.5,284.1,401.6,535.6
GIIP (mscf),Total Volumes,1.0,55.8,80.9,122.8,185.7,266.4
Condensate (stb),Total Volumes,1.0,1.6,2.6,4.4,7.1,11.6
Solution Gas (mscf),Total Volumes,1.0,217.5,332.7,523.6,805.1,1233.8

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50   P10     P1
Total Oil EUR         1.0  28.2  41.5  64.5  93.9  130.3

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.60  0.8  2.3  7.6  20.5  44.9
Zone 2           0.97  0.7  2.2  5.4  12.6  23.1
Zone 3           0.89  0.9  2.2  5.1  10.6  19.8
Zone 4           0.99  0.7  2.3  7.3  23.2  50.8
Zone 5           0.87  1.4  3.2  8.6  20.3  37.4
Zone 6           0.86  1.4  3.6  9.5  22.4  43.0
Zone 7           0.61  1.0  2.4  6.4  15.9  31.1
Zone 8           0.91  1.4  2.6  5.2  10.4  16.8
Zone 9           0.90  1.0  2.9  7.5  18.0  38.4

In [14]:
reporter.tabler.npv_table()

     P(Commercial)    P99    P90     P50     P10      P1
NPV            1.0  310.0  722.0  1321.0  1943.0  2498.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)    P99    P90     P50     P10      P1
EMV            1.0  309.0  721.0  1319.0  1941.0  2496.0