In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L2hvbWUvbmljay9yZXBvcy9ibG9nL3Bvc3RzL3Jlc2dv'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

/tmp/ipykernel_512213/1985460196.py:25: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats(fig_format)

{"/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_bootstrap_external.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/zipimport.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/codecs.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/aliases.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/io.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/stat.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_collections_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/genericpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/posixpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/os.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_sitebuiltins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/encodings/utf_8_sig.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_virtualenv.py": 1775868049.4503257, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/_distutils_hack/__init__.py": 1774855538.540388, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/site.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/machinery.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/types.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/importlib/util.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/runpy.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/keyword.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/operator.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/reprlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/collections/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/functools.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/enum.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_parser.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_casefix.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/_compiler.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copyreg.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/re/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/fnmatch.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/glob.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_abc.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ntpath.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/warnings.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/_local.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pathlib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/typing.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/ipykernel/_version.py": 1772927223.279541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/__future__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/scanner.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/decoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/encoder.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/json/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/locale.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/signal.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_weakrefset.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/threading.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/selectors.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/subprocess.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/_version.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/platform.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/select.py": 1775868050.4303699, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/weakref.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/constants.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/error.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/_zmq.cpython-313-x86_64-linux-gnu.so": 1775868050.5733762, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/cython/__init__.py": 1775868050.452371, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/backend/__init__.py": 1775868050.4293697, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_typing.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/__init__.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/interop.py": 1775868050.6653805, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/attrsettr.py": 1775868050.6283786, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/struct.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_compat_pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pickle.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/bisect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/random.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/utils/jsonapi.py": 1775868050.6663804, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/poll.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/context.py": 1775868050.6453795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/frame.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/tracker.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/version.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/stopwatch.py": 1775868050.6463795, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/sugar/__init__.py": 1775868050.6283786, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/__init__.py": 1775868050.4033687, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/linecache.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/textwrap.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_colorize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/traceback.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/string.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/_base.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/concurrent/futures/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/heapq.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socket.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/base64.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ssl.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/constants.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ast.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/_opcode_metadata.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/opcode.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dis.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/token.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/tokenize.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/inspect.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/coroutines.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/contextvars.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/format_helpers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/exceptions.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/futures.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/protocols.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/transports.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/log.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/sslproto.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/mixins.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/locks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/queues.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/timeouts.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/tasks.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/staggered.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/trsock.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/runners.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/streams.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/taskgroups.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/threads.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/base_subprocess.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/selector_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/unix_events.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/asyncio/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/_future.py": 1775868050.4173691, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/asyncio.py": 1775868050.4183693, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/__init__.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/bunch.py": 1772927223.55355, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/descriptions.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/getargspec.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/importstring.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/sentinel.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/warnings.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/traitlets.py": 1772927223.3545434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/_version.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/copy.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/decorators.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/__init__.py": 1772927223.282541, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/queue.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/version.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/__init__.py": 1772927223.2125387, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_core/utils/__init__.py": 1772927223.220539, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/channelsabc.py": 1772927223.2965415, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hashlib.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/hmac.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/dataclasses.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/pprint.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/datetime.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/__init__.py": 1772927223.6845543, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/numbers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/handlers.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/entities.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/html/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/__init__.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/ipaddress.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/urllib/parse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/speedups.abi3.so": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/util.py": 1772927223.6835544, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/escape.py": 1772927224.1265693, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/curses/__init__.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/log.py": 1772927223.820559, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/concurrent.py": 1772927223.731556, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/tornado/ioloop.py": 1772927224.2205722, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/socketserver.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/logging/config.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/text.py": 1772927223.5545502, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/gettext.py": 1704067200.0, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/argparse.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/loader.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/configurable.py": 1772927223.490548, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/utils/nested_update.py": 1772927223.5545502, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/application.py": 1772927223.4185455, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/config/__init__.py": 1772927223.3555434, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/traitlets/log.py": 1772927223.282541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/__init__.py": 1775868050.6143782, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/zmq/eventloop/zmqstream.py": 1775868050.6153781, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/jupyter_client/adapter.py": 1772927223.2965415, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_version.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/__init__.py": 1772927223.2785408, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/calendar.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/six.py": 1772231759.0427225, "/home/nick/.local/share/mise/installs/python/3.13.12/lib/python3.13/decimal.py": 1704067200.0, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/_common.py": 1772927223.2785408, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/relativedelta.py": 1772927223.279541, "/home/nick/repos/blog/.venv/lib/python3.13/site-packages/dateutil/tz/_common.py": 1772927223.4185455, "/home/nick/repos/blog/.ven

In [2]:
PLOTTING_BACKEND = "altair"
SEED = 42

CHAINS = 10
DRAWS = 250
N_RESERVOIRS = 10
N_PRODUCERS = 25

import altair as alt
from src.plotting import theme

alt.data_transformers.disable_max_rows()
theme.apply_lex_altair_theme()

In [3]:
#| output: false
from datetime import datetime
from resgo.model import (
    Prospect, 
    VolumetricModel, 
    FieldDevelopmentModel, 
    EconomicModel,
    FlatPriceModel,
    FlatRoyaltyModel,
    ProgressiveTaxModel,
    LeverageModel
)
from resgo.plotting import ProspectReporter

prospect = Prospect.default(
    name="Demo Prospect",
    num_reservoirs=N_RESERVOIRS,
    num_producers=N_PRODUCERS,
    dependency=0.4,
    years=30,
)

prospect.volumetric_model = VolumetricModel.default(
    num_reservoirs=N_RESERVOIRS,
    dependency=0.4,
)

prospect.field_development_model = FieldDevelopmentModel.simple_development(
    num_producers=N_PRODUCERS,
    start_date=datetime(2027, 1, 1),
    month_offset=12,
    drill_to_online_months=9,
    max_oil_rate_stbpd=20_000,
    max_gas_rate_mscfpd=60_000,
    gas_development=False,
    producer_capex_USD=80e6,
    years=30,
)

prospect.economic_model = EconomicModel(
    price_model=FlatPriceModel(oil_price_USD_stb=70.0, gas_price_USD_mmbtu=3.5),
    royalty_model=FlatRoyaltyModel(royalty_rate=0.12),
    tax_model=ProgressiveTaxModel(tax_tiers={0: 0.15, 10e6: 0.25, 15e6: 0.4}),
    leverage_model=LeverageModel(debt_to_equity_ratio=1.0, interest_rate=0.06, loan_term_years=15),
    infrastructure_capex_USD=50e6,
    annual_discount_rate=0.10,
    annual_inflation_rate=0.025,
    annual_opex_USD=2e6,
    producer_abandonment_cost_USD=0.5e6,
)

simpack = prospect.simulate(
    risked=True, 
    levered=True, 
    chains=CHAINS, 
    draws=DRAWS,
    seed=SEED
)
reporter = ProspectReporter(prospect, simpack)

2026-05-28 20:59:57.426 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 1 reservoir volumetric simulation complete.

2026-05-28 20:59:57.430 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 2 reservoir volumetric simulation complete.

2026-05-28 20:59:57.433 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 3 reservoir volumetric simulation complete.

2026-05-28 20:59:57.437 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 4 reservoir volumetric simulation complete.

2026-05-28 20:59:57.440 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 5 reservoir volumetric simulation complete.

2026-05-28 20:59:57.444 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 6 reservoir volumetric simulation complete.

2026-05-28 20:59:57.448 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 7 reservoir volumetric simulation complete.

2026-05-28 20:59:57.451 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 8 reservoir volumetric simulation complete.

2026-05-28 20:59:57.455 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 9 reservoir volumetric simulation complete.

2026-05-28 20:59:57.458 | INFO     | resgo.engine.volumetric_simulator:simulate_reservoir:136 - Zone 10 reservoir volumetric simulation complete.

2026-05-28 20:59:57.462 | INFO     | resgo.engine.volumetric_simulator:simulate:80 - Volumetric results are risked so are masked with Outcome array.

2026-05-28 20:59:57.463 | SUCCESS  | resgo.engine.volumetric_simulator:simulate:85 - Demo Prospect volumetric simulation complete!

2026-05-28 20:59:57.876 | INFO     | resgo.engine.production_simulator:prepare_simpack:146 - Merged VolumetricSimulator dataset into ProductionSimulator dataset.

2026-05-28 20:59:57.876 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 1 start_idx = 8

2026-05-28 20:59:57.877 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 2 start_idx = 20

2026-05-28 20:59:57.877 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 3 start_idx = 32

2026-05-28 20:59:57.877 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 4 start_idx = 44

2026-05-28 20:59:57.877 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 5 start_idx = 56

2026-05-28 20:59:57.877 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 6 start_idx = 68

2026-05-28 20:59:57.877 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 7 start_idx = 79

2026-05-28 20:59:57.878 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 8 start_idx = 91

2026-05-28 20:59:57.878 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 9 start_idx = 103

2026-05-28 20:59:57.878 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 10 start_idx = 115

2026-05-28 20:59:57.878 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 11 start_idx = 127

2026-05-28 20:59:57.878 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 12 start_idx = 139

2026-05-28 20:59:57.878 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 13 start_idx = 150

2026-05-28 20:59:57.878 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 14 start_idx = 162

2026-05-28 20:59:57.878 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 15 start_idx = 174

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 16 start_idx = 186

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 17 start_idx = 198

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 18 start_idx = 209

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 19 start_idx = 221

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 20 start_idx = 233

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 21 start_idx = 245

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 22 start_idx = 257

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 23 start_idx = 269

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 24 start_idx = 280

2026-05-28 20:59:57.879 | DEBUG    | resgo.engine.production_simulator:get_producer_start_indices:210 - Oil 25 start_idx = 292

2026-05-28 20:59:57.904 | INFO     | resgo.engine.production_simulator:initialize_flowing_array:236 - Flowing array initialized.

2026-05-28 20:59:57.914 | INFO     | resgo.engine.production_simulator:simulate_recovery_factors:425 - Recovery factors simulated.

2026-05-28 20:59:58.382 | INFO     | resgo.engine.production_simulator:initialize_oil_well_rates:308 - Oil well rates initialized.

2026-05-28 20:59:58.383 | DEBUG    | resgo.engine.production_simulator:initialize_gas_well_rates:324 - No gas producers, skipping gas rate initialization...

2026-05-28 20:59:58.383 | INFO     | resgo.engine.production_simulator:simulate:88 - Commencing field production simulation (25 oil, 0 gas producers)...

Chain 0:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 126.24it/s]

Chain 0:   7%|███████▍                                                                                               | 26/360 [00:00<00:04, 68.08it/s]

Chain 0:  10%|██████████                                                                                             | 35/360 [00:00<00:05, 60.45it/s]

Chain 0:  12%|████████████                                                                                           | 42/360 [00:00<00:05, 58.55it/s]

Chain 0:  14%|██████████████                                                                                         | 49/360 [00:00<00:05, 55.91it/s]

Chain 0:  15%|███████████████▋                                                                                       | 55/360 [00:00<00:05, 54.08it/s]

Chain 0:  17%|█████████████████▍                                                                                     | 61/360 [00:01<00:05, 53.37it/s]

Chain 0:  19%|███████████████████▏                                                                                   | 67/360 [00:01<00:05, 52.43it/s]

Chain 0:  24%|████████████████████████▎                                                                              | 85/360 [00:01<00:05, 49.43it/s]

Chain 0:  20%|████████████████████▉                                                                                  | 73/360 [00:01<00:05, 51.19it/s]

Chain 1:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 0:  22%|██████████████████████▌                                                                                | 79/360 [00:01<00:05, 50.16it/s]

Chain 1:   4%|███▋                                                                                                  | 13/360 [00:00<00:02, 124.48it/s]

Chain 0:  25%|█████████████████████████▊                                                                             | 90/360 [00:01<00:05, 49.18it/s]

Chain 1:   7%|███████▍                                                                                               | 26/360 [00:00<00:05, 66.14it/s]

Chain 0:  26%|███████████████████████████▏                                                                           | 95/360 [00:01<00:05, 49.06it/s]

Chain 0:  28%|████████████████████████████▎                                                                         | 100/360 [00:01<00:05, 49.20it/s]

Chain 1:  10%|██████████                                                                                             | 35/360 [00:00<00:05, 58.17it/s]

Chain 0:  29%|█████████████████████████████▊                                                                        | 105/360 [00:01<00:05, 49.29it/s]

Chain 0:  31%|███████████████████████████████▍                                                                      | 111/360 [00:02<00:05, 49.67it/s]

Chain 1:  12%|████████████                                                                                           | 42/360 [00:00<00:05, 54.19it/s]

Chain 0:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:02<00:04, 50.53it/s]

Chain 1:  13%|█████████████▋                                                                                         | 48/360 [00:00<00:05, 52.65it/s]

Chain 0:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:02<00:04, 51.30it/s]

Chain 1:  15%|███████████████▍                                                                                       | 54/360 [00:00<00:05, 51.10it/s]

Chain 0:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:02<00:04, 51.65it/s]

Chain 1:  17%|█████████████████▏                                                                                     | 60/360 [00:01<00:05, 51.33it/s]

Chain 0:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:02<00:04, 51.63it/s]

Chain 1:  18%|██████████████████▉                                                                                    | 66/360 [00:01<00:05, 50.55it/s]

Chain 0:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:02<00:04, 52.97it/s]

Chain 1:  20%|████████████████████▌                                                                                  | 72/360 [00:01<00:05, 49.72it/s]

Chain 0:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:02<00:03, 54.18it/s]

Chain 2:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  22%|██████████████████████▎                                                                                | 78/360 [00:01<00:05, 48.01it/s]

Chain 0:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:02<00:03, 54.18it/s]

Chain 2:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 114.20it/s]

Chain 1:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:05, 47.12it/s]

Chain 0:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:02<00:03, 55.72it/s]

Chain 1:  24%|█████████████████████████▏                                                                             | 88/360 [00:01<00:05, 46.81it/s]

Chain 0:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:03<00:03, 57.40it/s]

Chain 2:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 63.52it/s]

Chain 1:  26%|██████████████████████████▌                                                                            | 93/360 [00:01<00:05, 46.66it/s]

Chain 0:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:03<00:03, 59.12it/s]

Chain 1:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 45.83it/s]

Chain 0:  50%|███████████████████████████████████████████████████                                                   | 180/360 [00:03<00:03, 59.81it/s]

Chain 2:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 57.58it/s]

Chain 1:  29%|█████████████████████████████▏                                                                        | 103/360 [00:02<00:05, 46.34it/s]

Chain 0:  52%|████████████████████████████████████████████████████▉                                                 | 187/360 [00:03<00:02, 62.32it/s]

Chain 2:  11%|███████████▍                                                                                           | 40/360 [00:00<00:05, 54.58it/s]

Chain 0:  54%|██████████████████████████████████████████████████████▉                                               | 194/360 [00:03<00:02, 63.32it/s]

Chain 1:  30%|██████████████████████████████▌                                                                       | 108/360 [00:02<00:05, 44.42it/s]

Chain 2:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:05, 52.88it/s]

Chain 0:  56%|█████████████████████████████████████████████████████████▏                                            | 202/360 [00:03<00:02, 66.75it/s]

Chain 1:  31%|████████████████████████████████                                                                      | 113/360 [00:02<00:05, 45.39it/s]

Chain 0:  58%|███████████████████████████████████████████████████████████▌                                          | 210/360 [00:03<00:02, 70.25it/s]

Chain 2:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:06, 50.81it/s]

Chain 1:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:02<00:05, 46.89it/s]

Chain 0:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:03<00:01, 73.42it/s]

Chain 1:  34%|███████████████████████████████████▏                                                                  | 124/360 [00:02<00:04, 47.74it/s]

Chain 2:  16%|████████████████▌                                                                                      | 58/360 [00:01<00:05, 50.92it/s]

Chain 0:  63%|████████████████████████████████████████████████████████████████▌                                     | 228/360 [00:03<00:01, 76.97it/s]

Chain 1:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:02<00:04, 48.23it/s]

Chain 2:  18%|██████████████████▎                                                                                    | 64/360 [00:01<00:05, 50.98it/s]

Chain 1:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:02<00:04, 48.55it/s]

Chain 0:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:04<00:01, 81.23it/s]

Chain 2:  19%|████████████████████                                                                                   | 70/360 [00:01<00:05, 50.31it/s]

Chain 0:  69%|█████████████████████████████████████████████████████████████████████▉                                | 247/360 [00:04<00:01, 82.35it/s]

Chain 1:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:02<00:04, 49.41it/s]

Chain 2:  21%|█████████████████████▋                                                                                 | 76/360 [00:01<00:05, 50.46it/s]

Chain 0:  71%|████████████████████████████████████████████████████████████████████████▊                             | 257/360 [00:04<00:01, 85.82it/s]

Chain 1:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:02<00:04, 50.69it/s]

Chain 3:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 2:  23%|███████████████████████▍                                                                               | 82/360 [00:01<00:05, 48.14it/s]

Chain 0:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:04<00:01, 88.89it/s]

Chain 1:  42%|███████████████████████████████████████████                                                           | 152/360 [00:03<00:04, 48.89it/s]

Chain 3:   3%|███▍                                                                                                  | 12/360 [00:00<00:03, 101.83it/s]

Chain 0:  77%|██████████████████████████████████████████████████████████████████████████████▊                       | 278/360 [00:04<00:00, 94.81it/s]

Chain 2:  24%|████████████████████████▉                                                                              | 87/360 [00:01<00:05, 45.77it/s]

Chain 1:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:03<00:03, 50.85it/s]

Chain 0:  81%|█████████████████████████████████████████████████████████████████████████████████▉                   | 292/360 [00:04<00:00, 106.47it/s]

Chain 2:  26%|██████████████████████████▎                                                                            | 92/360 [00:01<00:05, 45.42it/s]

Chain 1:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:03<00:03, 52.32it/s]

Chain 3:   6%|██████▌                                                                                                | 23/360 [00:00<00:05, 59.72it/s]

Chain 0:  86%|██████████████████████████████████████████████████████████████████████████████████████▍              | 308/360 [00:04<00:00, 120.27it/s]

Chain 2:  27%|███████████████████████████▊                                                                           | 97/360 [00:01<00:05, 45.28it/s]

Chain 1:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:03<00:03, 53.62it/s]

Chain 0:  91%|████████████████████████████████████████████████████████████████████████████████████████████         | 328/360 [00:04<00:00, 143.26it/s]

Chain 2:  28%|████████████████████████████▉                                                                         | 102/360 [00:01<00:05, 45.61it/s]

Chain 3:   8%|████████▌                                                                                              | 30/360 [00:00<00:06, 53.64it/s]

Chain 1:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:03<00:03, 55.87it/s]

Chain 2:  30%|██████████████████████████████▎                                                                       | 107/360 [00:02<00:05, 45.91it/s]

Chain 3:  10%|██████████▎                                                                                            | 36/360 [00:00<00:06, 51.36it/s]

Chain 1:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:03<00:03, 57.75it/s]

Chain 2:  31%|███████████████████████████████▋                                                                      | 112/360 [00:02<00:05, 45.81it/s]

Chain 1:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:03<00:03, 55.21it/s]

Chain 3:  12%|████████████                                                                                           | 42/360 [00:00<00:06, 49.84it/s]

Chain 2:  32%|█████████████████████████████████▏                                                                    | 117/360 [00:02<00:05, 46.41it/s]

Chain 1:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:03<00:02, 58.35it/s]

Chain 3:  13%|█████████████▋                                                                                         | 48/360 [00:00<00:06, 49.41it/s]

Chain 2:  34%|██████████████████████████████████▌                                                                   | 122/360 [00:02<00:05, 47.25it/s]

Chain 1:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:03<00:02, 61.46it/s]

Chain 2:  35%|███████████████████████████████████▉                                                                  | 127/360 [00:02<00:04, 47.68it/s]

Chain 3:  15%|███████████████▍                                                                                       | 54/360 [00:01<00:06, 48.14it/s]

Chain 1:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:03<00:02, 65.50it/s]

Chain 3:  16%|████████████████▉                                                                                      | 59/360 [00:01<00:06, 48.58it/s]

Chain 2:  37%|█████████████████████████████████████▍                                                                | 132/360 [00:02<00:04, 47.69it/s]

Chain 1:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:04<00:02, 69.24it/s]

Chain 2:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:02<00:04, 47.89it/s]

Chain 3:  18%|██████████████████▎                                                                                    | 64/360 [00:01<00:06, 48.25it/s]

Chain 1:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:04<00:01, 72.71it/s]

Chain 2:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:02<00:04, 49.19it/s]

Chain 3:  19%|████████████████████                                                                                   | 70/360 [00:01<00:05, 49.30it/s]

Chain 1:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:04<00:01, 77.29it/s]

Chain 3:  21%|█████████████████████▍                                                                                 | 75/360 [00:01<00:05, 49.35it/s]

Chain 2:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:02<00:04, 50.48it/s]

Chain 1:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:04<00:01, 82.71it/s]

Chain 3:  22%|██████████████████████▉                                                                                | 80/360 [00:01<00:05, 49.49it/s]

Chain 2:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:03<00:03, 51.41it/s]

Chain 4:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 1:  72%|█████████████████████████████████████████████████████████████████████████                             | 258/360 [00:04<00:01, 86.90it/s]

Chain 3:  24%|████████████████████████▎                                                                              | 85/360 [00:01<00:05, 48.90it/s]

Chain 2:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:03<00:03, 53.04it/s]

Chain 4:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 113.02it/s]

Chain 1:  75%|████████████████████████████████████████████████████████████████████████████▏                         | 269/360 [00:04<00:00, 93.10it/s]

Chain 3:  25%|█████████████████████████▊                                                                             | 90/360 [00:01<00:05, 48.07it/s]

Chain 2:  46%|███████████████████████████████████████████████▎                                                      | 167/360 [00:03<00:03, 54.38it/s]

Chain 1:  78%|███████████████████████████████████████████████████████████████████████████████                      | 282/360 [00:04<00:00, 101.48it/s]

Chain 3:  26%|███████████████████████████▏                                                                           | 95/360 [00:01<00:05, 47.89it/s]

Chain 2:  48%|█████████████████████████████████████████████████                                                     | 173/360 [00:03<00:03, 55.68it/s]

Chain 1:  82%|███████████████████████████████████████████████████████████████████████████████████                  | 296/360 [00:04<00:00, 112.45it/s]

Chain 4:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 59.98it/s]

Chain 3:  28%|████████████████████████████▎                                                                         | 100/360 [00:01<00:05, 48.08it/s]

Chain 2:  50%|██████████████████████████████████████████████████▋                                                   | 179/360 [00:03<00:03, 56.37it/s]

Chain 1:  87%|███████████████████████████████████████████████████████████████████████████████████████▊             | 313/360 [00:04<00:00, 127.59it/s]

Chain 3:  29%|█████████████████████████████▊                                                                        | 105/360 [00:02<00:05, 48.05it/s]

Chain 2:  52%|████████████████████████████████████████████████████▋                                                 | 186/360 [00:03<00:02, 58.99it/s]

Chain 1:  93%|██████████████████████████████████████████████████████████████████████████████████████████████▎      | 336/360 [00:05<00:00, 157.33it/s]

Chain 4:   9%|█████████▍                                                                                             | 33/360 [00:00<00:06, 53.78it/s]

Chain 3:  31%|███████████████████████████████▏                                                                      | 110/360 [00:02<00:05, 48.51it/s]

Chain 2:  54%|██████████████████████████████████████████████████████▋                                               | 193/360 [00:03<00:02, 60.90it/s]

Chain 3:  32%|████████████████████████████████▌                                                                     | 115/360 [00:02<00:05, 48.19it/s]

Chain 4:  11%|███████████▍                                                                                           | 40/360 [00:00<00:06, 49.88it/s]

Chain 2:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:03<00:02, 58.52it/s]

Chain 3:  33%|██████████████████████████████████                                                                    | 120/360 [00:02<00:05, 46.89it/s]

Chain 2:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:03<00:02, 60.54it/s]

Chain 4:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 47.99it/s]

Chain 3:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:02<00:05, 46.98it/s]

Chain 2:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:04<00:02, 62.81it/s]

Chain 4:  14%|██████████████▌                                                                                        | 51/360 [00:00<00:06, 46.85it/s]

Chain 3:  36%|████████████████████████████████████▊                                                                 | 130/360 [00:02<00:04, 46.89it/s]

Chain 2:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:04<00:02, 65.36it/s]

Chain 4:  16%|████████████████                                                                                       | 56/360 [00:01<00:06, 46.46it/s]

Chain 3:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:02<00:04, 47.19it/s]

Chain 2:  64%|█████████████████████████████████████████████████████████████████▏                                    | 230/360 [00:04<00:01, 68.23it/s]

Chain 4:  17%|█████████████████▍                                                                                     | 61/360 [00:01<00:06, 45.92it/s]

Chain 3:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:02<00:04, 48.59it/s]

Chain 2:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:04<00:01, 72.49it/s]

Chain 4:  18%|██████████████████▉                                                                                    | 66/360 [00:01<00:06, 45.41it/s]

Chain 3:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:02<00:04, 49.73it/s]

Chain 2:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:04<00:01, 77.92it/s]

Chain 4:  20%|████████████████████▎                                                                                  | 71/360 [00:01<00:06, 45.54it/s]

Chain 3:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:03<00:04, 50.99it/s]

Chain 2:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:04<00:01, 83.91it/s]

Chain 4:  21%|█████████████████████▋                                                                                 | 76/360 [00:01<00:06, 46.50it/s]

Chain 5:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 3:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:03<00:03, 52.13it/s]

Chain 2:  75%|████████████████████████████████████████████████████████████████████████████▌                         | 270/360 [00:04<00:00, 91.13it/s]

Chain 4:  22%|███████████████████████▏                                                                               | 81/360 [00:01<00:05, 46.71it/s]

Chain 5:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 115.64it/s]

Chain 3:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:03<00:03, 53.43it/s]

Chain 2:  79%|███████████████████████████████████████████████████████████████████████████████▍                     | 283/360 [00:04<00:00, 100.31it/s]

Chain 4:  24%|████████████████████████▌                                                                              | 86/360 [00:01<00:05, 46.86it/s]

Chain 3:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:03<00:03, 54.94it/s]

Chain 2:  82%|███████████████████████████████████████████████████████████████████████████████████▎                 | 297/360 [00:04<00:00, 110.98it/s]

Chain 4:  25%|██████████████████████████                                                                             | 91/360 [00:01<00:05, 47.21it/s]

Chain 3:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:03<00:03, 56.26it/s]

Chain 2:  87%|████████████████████████████████████████████████████████████████████████████████████████             | 314/360 [00:04<00:00, 127.01it/s]

Chain 4:  27%|███████████████████████████▍                                                                           | 96/360 [00:01<00:05, 46.95it/s]

Chain 5:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 61.68it/s]

Chain 3:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:03<00:03, 58.49it/s]

Chain 2:  94%|██████████████████████████████████████████████████████████████████████████████████████████████▊      | 338/360 [00:05<00:00, 159.26it/s]

Chain 4:  28%|████████████████████████████▌                                                                         | 101/360 [00:02<00:05, 46.57it/s]

Chain 3:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:03<00:02, 60.06it/s]

Chain 5:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 55.95it/s]

Chain 4:  29%|██████████████████████████████                                                                        | 106/360 [00:02<00:05, 46.49it/s]

Chain 3:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:03<00:02, 61.94it/s]

Chain 5:  11%|███████████▍                                                                                           | 40/360 [00:00<00:06, 53.10it/s]

Chain 4:  31%|███████████████████████████████▍                                                                      | 111/360 [00:02<00:05, 46.32it/s]

Chain 3:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:03<00:02, 63.85it/s]

Chain 4:  32%|████████████████████████████████▊                                                                     | 116/360 [00:02<00:05, 45.76it/s]

Chain 5:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 51.73it/s]

Chain 3:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:04<00:02, 66.39it/s]

Chain 4:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:02<00:05, 45.70it/s]

Chain 5:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:06, 50.00it/s]

Chain 3:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:04<00:02, 63.75it/s]

Chain 4:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:02<00:05, 46.18it/s]

Chain 5:  16%|████████████████▌                                                                                      | 58/360 [00:01<00:06, 48.69it/s]

Chain 3:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:04<00:01, 69.45it/s]

Chain 4:  36%|█████████████████████████████████████                                                                 | 131/360 [00:02<00:04, 46.38it/s]

Chain 5:  18%|██████████████████                                                                                     | 63/360 [00:01<00:06, 48.73it/s]

Chain 3:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:04<00:01, 75.19it/s]

Chain 4:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:02<00:04, 48.03it/s]

Chain 5:  19%|███████████████████▍                                                                                   | 68/360 [00:01<00:05, 48.73it/s]

Chain 3:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:04<00:01, 81.43it/s]

Chain 4:  39%|████████████████████████████████████████▏                                                             | 142/360 [00:02<00:04, 47.94it/s]

Chain 5:  20%|████████████████████▉                                                                                  | 73/360 [00:01<00:05, 48.16it/s]

Chain 3:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:04<00:01, 87.96it/s]

Chain 4:  41%|█████████████████████████████████████████▉                                                            | 148/360 [00:03<00:04, 50.08it/s]

Chain 5:  22%|██████████████████████▎                                                                                | 78/360 [00:01<00:05, 47.95it/s]

Chain 3:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:04<00:00, 94.95it/s]

Chain 4:  43%|███████████████████████████████████████████▋                                                          | 154/360 [00:03<00:03, 51.77it/s]

Chain 5:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:05, 47.53it/s]

Chain 3:  79%|███████████████████████████████████████████████████████████████████████████████▋                     | 284/360 [00:04<00:00, 103.51it/s]

Chain 4:  44%|█████████████████████████████████████████████▎                                                        | 160/360 [00:03<00:03, 53.60it/s]

Chain 5:  24%|█████████████████████████▏                                                                             | 88/360 [00:01<00:05, 47.35it/s]

Chain 3:  83%|███████████████████████████████████████████████████████████████████████████████████▉                 | 299/360 [00:04<00:00, 115.92it/s]

Chain 6:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 4:  46%|███████████████████████████████████████████████                                                       | 166/360 [00:03<00:03, 54.95it/s]

Chain 5:  26%|██████████████████████████▌                                                                            | 93/360 [00:01<00:05, 47.83it/s]

Chain 3:  88%|████████████████████████████████████████████████████████████████████████████████████████▉            | 317/360 [00:04<00:00, 133.43it/s]

Chain 6:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 113.14it/s]

Chain 4:  48%|████████████████████████████████████████████████▋                                                     | 172/360 [00:03<00:03, 55.97it/s]

Chain 3:  95%|███████████████████████████████████████████████████████████████████████████████████████████████▋     | 341/360 [00:05<00:00, 163.12it/s]

Chain 5:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 47.35it/s]

Chain 4:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:03<00:03, 56.02it/s]

Chain 5:  29%|█████████████████████████████▏                                                                        | 103/360 [00:02<00:05, 45.31it/s]

Chain 4:  51%|████████████████████████████████████████████████████▍                                                 | 185/360 [00:03<00:03, 58.15it/s]

Chain 6:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 60.81it/s]

Chain 5:  30%|██████████████████████████████▌                                                                       | 108/360 [00:02<00:05, 45.34it/s]

Chain 4:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:03<00:02, 59.84it/s]

Chain 5:  31%|████████████████████████████████                                                                      | 113/360 [00:02<00:05, 45.28it/s]

Chain 6:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 54.83it/s]

Chain 4:  55%|████████████████████████████████████████████████████████▍                                             | 199/360 [00:03<00:02, 62.50it/s]

Chain 5:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:02<00:05, 45.68it/s]

Chain 4:  57%|██████████████████████████████████████████████████████████▋                                           | 207/360 [00:04<00:02, 64.93it/s]

Chain 6:  11%|███████████▍                                                                                           | 40/360 [00:00<00:06, 50.85it/s]

Chain 5:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:02<00:05, 45.97it/s]

Chain 4:  59%|████████████████████████████████████████████████████████████▋                                         | 214/360 [00:04<00:02, 61.57it/s]

Chain 5:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:02<00:05, 46.39it/s]

Chain 6:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 49.43it/s]

Chain 4:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:04<00:02, 66.02it/s]

Chain 5:  37%|█████████████████████████████████████▋                                                                | 133/360 [00:02<00:04, 46.95it/s]

Chain 6:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:06, 48.99it/s]

Chain 4:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:04<00:01, 71.42it/s]

Chain 5:  39%|███████████████████████████████████████▍                                                              | 139/360 [00:02<00:04, 48.80it/s]

Chain 6:  16%|████████████████▌                                                                                      | 58/360 [00:01<00:06, 49.14it/s]

Chain 4:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:04<00:01, 76.28it/s]

Chain 5:  40%|█████████████████████████████████████████                                                             | 145/360 [00:02<00:04, 50.36it/s]

Chain 6:  18%|██████████████████                                                                                     | 63/360 [00:01<00:06, 49.00it/s]

Chain 4:  69%|██████████████████████████████████████████████████████████████████████▌                               | 249/360 [00:04<00:01, 79.38it/s]

Chain 5:  42%|██████████████████████████████████████████▊                                                           | 151/360 [00:03<00:04, 52.07it/s]

Chain 6:  19%|███████████████████▍                                                                                   | 68/360 [00:01<00:06, 48.23it/s]

Chain 4:  72%|█████████████████████████████████████████████████████████████████████████▋                            | 260/360 [00:04<00:01, 86.22it/s]

Chain 5:  44%|████████████████████████████████████████████▍                                                         | 157/360 [00:03<00:03, 53.29it/s]

Chain 6:  20%|████████████████████▉                                                                                  | 73/360 [00:01<00:05, 48.52it/s]

Chain 4:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:04<00:00, 94.20it/s]

Chain 5:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:03<00:03, 54.15it/s]

Chain 6:  22%|██████████████████████▎                                                                                | 78/360 [00:01<00:05, 48.72it/s]

Chain 7:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 4:  79%|███████████████████████████████████████████████████████████████████████████████▉                     | 285/360 [00:04<00:00, 102.28it/s]

Chain 5:  47%|███████████████████████████████████████████████▉                                                      | 169/360 [00:03<00:03, 55.44it/s]

Chain 6:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:05, 48.69it/s]

Chain 7:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 112.95it/s]

Chain 4:  83%|████████████████████████████████████████████████████████████████████████████████████▏                | 300/360 [00:04<00:00, 114.38it/s]

Chain 5:  49%|█████████████████████████████████████████████████▊                                                    | 176/360 [00:03<00:03, 57.41it/s]

Chain 6:  24%|█████████████████████████▏                                                                             | 88/360 [00:01<00:05, 48.43it/s]

Chain 4:  89%|█████████████████████████████████████████████████████████████████████████████████████████▍           | 319/360 [00:05<00:00, 134.88it/s]

Chain 5:  51%|███████████████████████████████████████████████████▊                                                  | 183/360 [00:03<00:02, 59.32it/s]

Chain 6:  26%|██████████████████████████▌                                                                            | 93/360 [00:01<00:05, 47.49it/s]

Chain 4:  96%|████████████████████████████████████████████████████████████████████████████████████████████████▊    | 345/360 [00:05<00:00, 170.01it/s]

Chain 7:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 62.22it/s]

Chain 5:  53%|█████████████████████████████████████████████████████▊                                                | 190/360 [00:03<00:02, 61.75it/s]

Chain 6:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 47.27it/s]

Chain 5:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:03<00:02, 63.54it/s]

Chain 6:  29%|█████████████████████████████▏                                                                        | 103/360 [00:02<00:05, 47.81it/s]

Chain 7:   9%|█████████▍                                                                                             | 33/360 [00:00<00:05, 55.44it/s]

Chain 5:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:03<00:02, 62.96it/s]

Chain 6:  30%|██████████████████████████████▌                                                                       | 108/360 [00:02<00:05, 47.53it/s]

Chain 5:  59%|███████████████████████████████████████████████████████████▊                                          | 211/360 [00:03<00:02, 64.89it/s]

Chain 7:  11%|███████████▍                                                                                           | 40/360 [00:00<00:06, 51.37it/s]

Chain 6:  31%|████████████████████████████████                                                                      | 113/360 [00:02<00:05, 45.86it/s]

Chain 5:  61%|██████████████████████████████████████████████████████████████                                        | 219/360 [00:04<00:02, 67.29it/s]

Chain 7:  13%|█████████████▏                                                                                         | 46/360 [00:00<00:06, 49.50it/s]

Chain 6:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:02<00:05, 45.18it/s]

Chain 5:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:04<00:01, 69.49it/s]

Chain 6:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:02<00:05, 45.14it/s]

Chain 7:  14%|██████████████▉                                                                                        | 52/360 [00:00<00:06, 48.13it/s]

Chain 5:  66%|██████████████████████████████████████████████████████████████████▊                                   | 236/360 [00:04<00:01, 73.29it/s]

Chain 6:  36%|████████████████████████████████████▎                                                                 | 128/360 [00:02<00:05, 45.71it/s]

Chain 7:  16%|████████████████▌                                                                                      | 58/360 [00:01<00:06, 48.89it/s]

Chain 5:  68%|█████████████████████████████████████████████████████████████████████▋                                | 246/360 [00:04<00:01, 78.69it/s]

Chain 6:  37%|█████████████████████████████████████▉                                                                | 134/360 [00:02<00:04, 47.19it/s]

Chain 7:  18%|██████████████████                                                                                     | 63/360 [00:01<00:06, 47.77it/s]

Chain 5:  71%|████████████████████████████████████████████████████████████████████████▌                             | 256/360 [00:04<00:01, 83.34it/s]

Chain 6:  39%|███████████████████████████████████████▋                                                              | 140/360 [00:02<00:04, 48.40it/s]

Chain 7:  19%|███████████████████▍                                                                                   | 68/360 [00:01<00:06, 47.12it/s]

Chain 5:  74%|███████████████████████████████████████████████████████████████████████████▋                          | 267/360 [00:04<00:01, 89.82it/s]

Chain 6:  41%|█████████████████████████████████████████▎                                                            | 146/360 [00:02<00:04, 49.94it/s]

Chain 7:  20%|████████████████████▉                                                                                  | 73/360 [00:01<00:06, 46.83it/s]

Chain 5:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 280/360 [00:04<00:00, 99.73it/s]

Chain 8:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 6:  42%|███████████████████████████████████████████                                                           | 152/360 [00:03<00:04, 51.30it/s]

Chain 7:  22%|██████████████████████▎                                                                                | 78/360 [00:01<00:06, 46.89it/s]

Chain 5:  82%|██████████████████████████████████████████████████████████████████████████████████▍                  | 294/360 [00:04<00:00, 110.04it/s]

Chain 8:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 114.55it/s]

Chain 6:  44%|████████████████████████████████████████████▊                                                         | 158/360 [00:03<00:03, 51.86it/s]

Chain 7:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:05, 46.93it/s]

Chain 5:  86%|██████████████████████████████████████████████████████████████████████████████████████▋              | 309/360 [00:04<00:00, 121.55it/s]

Chain 6:  46%|██████████████████████████████████████████████▍                                                       | 164/360 [00:03<00:03, 53.54it/s]

Chain 7:  24%|█████████████████████████▏                                                                             | 88/360 [00:01<00:05, 47.26it/s]

Chain 5:  92%|████████████████████████████████████████████████████████████████████████████████████████████▌        | 330/360 [00:05<00:00, 146.53it/s]

Chain 7:  26%|██████████████████████████▌                                                                            | 93/360 [00:01<00:05, 47.27it/s]

Chain 6:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:03<00:03, 55.61it/s]

Chain 8:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 61.19it/s]

Chain 7:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 46.87it/s]

Chain 6:  49%|██████████████████████████████████████████████████▍                                                   | 178/360 [00:03<00:03, 57.03it/s]

Chain 7:  29%|█████████████████████████████▏                                                                        | 103/360 [00:02<00:05, 45.12it/s]

Chain 8:   9%|█████████▍                                                                                             | 33/360 [00:00<00:06, 53.57it/s]

Chain 6:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:03<00:03, 55.86it/s]

Chain 7:  30%|██████████████████████████████▌                                                                       | 108/360 [00:02<00:05, 44.64it/s]

Chain 6:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:03<00:02, 57.94it/s]

Chain 8:  11%|███████████▏                                                                                           | 39/360 [00:00<00:06, 50.66it/s]

Chain 7:  31%|████████████████████████████████                                                                      | 113/360 [00:02<00:05, 45.89it/s]

Chain 6:  55%|████████████████████████████████████████████████████████                                              | 198/360 [00:03<00:02, 61.21it/s]

Chain 8:  12%|████████████▉                                                                                          | 45/360 [00:00<00:06, 50.05it/s]

Chain 7:  33%|█████████████████████████████████▍                                                                    | 118/360 [00:02<00:05, 46.75it/s]

Chain 6:  57%|██████████████████████████████████████████████████████████                                            | 205/360 [00:03<00:02, 63.21it/s]

Chain 8:  14%|██████████████▌                                                                                        | 51/360 [00:00<00:06, 48.65it/s]

Chain 7:  34%|██████████████████████████████████▊                                                                   | 123/360 [00:02<00:05, 47.35it/s]

Chain 6:  59%|████████████████████████████████████████████████████████████▎                                         | 213/360 [00:04<00:02, 66.25it/s]

Chain 8:  16%|████████████████                                                                                       | 56/360 [00:01<00:06, 47.91it/s]

Chain 7:  36%|████████████████████████████████████▌                                                                 | 129/360 [00:02<00:04, 48.44it/s]

Chain 6:  62%|██████████████████████████████████████████████████████████████▉                                       | 222/360 [00:04<00:01, 70.78it/s]

Chain 8:  17%|█████████████████▍                                                                                     | 61/360 [00:01<00:06, 46.99it/s]

Chain 6:  64%|█████████████████████████████████████████████████████████████████▍                                    | 231/360 [00:04<00:01, 75.41it/s]

Chain 7:  38%|██████████████████████████████████████▎                                                               | 135/360 [00:02<00:04, 49.61it/s]

Chain 8:  18%|██████████████████▉                                                                                    | 66/360 [00:01<00:06, 47.65it/s]

Chain 6:  67%|████████████████████████████████████████████████████████████████████                                  | 240/360 [00:04<00:01, 78.21it/s]

Chain 7:  39%|███████████████████████████████████████▉                                                              | 141/360 [00:02<00:04, 50.63it/s]

Chain 8:  20%|████████████████████▎                                                                                  | 71/360 [00:01<00:06, 47.53it/s]

Chain 6:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:04<00:01, 83.80it/s]

Chain 7:  41%|█████████████████████████████████████████▋                                                            | 147/360 [00:02<00:04, 51.72it/s]

Chain 8:  21%|█████████████████████▋                                                                                 | 76/360 [00:01<00:05, 48.10it/s]

Chain 6:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:04<00:01, 89.41it/s]

Chain 7:  42%|███████████████████████████████████████████▎                                                          | 153/360 [00:03<00:03, 52.33it/s]

Chain 8:  22%|███████████████████████▏                                                                               | 81/360 [00:01<00:05, 48.01it/s]

Chain 6:  76%|█████████████████████████████████████████████████████████████████████████████                         | 272/360 [00:04<00:00, 94.59it/s]

Chain 7:  44%|█████████████████████████████████████████████                                                         | 159/360 [00:03<00:03, 52.98it/s]

Chain 8:  24%|████████████████████████▌                                                                              | 86/360 [00:01<00:05, 47.38it/s]

Chain 6:  79%|███████████████████████████████████████████████████████████████████████████████▉                     | 285/360 [00:04<00:00, 102.83it/s]

Chain 7:  46%|██████████████████████████████████████████████▊                                                       | 165/360 [00:03<00:03, 54.06it/s]

Chain 8:  25%|██████████████████████████                                                                             | 91/360 [00:01<00:05, 46.43it/s]

Chain 9:   0%|                                                                                                                | 0/360 [00:00<?, ?it/s]

Chain 6:  83%|███████████████████████████████████████████████████████████████████████████████████▉                 | 299/360 [00:04<00:00, 112.73it/s]

Chain 7:  48%|████████████████████████████████████████████████▍                                                     | 171/360 [00:03<00:03, 54.85it/s]

Chain 8:  27%|███████████████████████████▍                                                                           | 96/360 [00:01<00:05, 46.57it/s]

Chain 9:   4%|███▋                                                                                                  | 13/360 [00:00<00:03, 113.19it/s]

Chain 6:  88%|████████████████████████████████████████████████████████████████████████████████████████▍            | 315/360 [00:04<00:00, 125.32it/s]

Chain 7:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:03<00:03, 56.27it/s]

Chain 8:  28%|████████████████████████████▌                                                                         | 101/360 [00:02<00:05, 45.93it/s]

Chain 6:  94%|███████████████████████████████████████████████████████████████████████████████████████████████      | 339/360 [00:05<00:00, 157.75it/s]

Chain 7:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:03<00:02, 58.67it/s]

Chain 8:  29%|██████████████████████████████                                                                        | 106/360 [00:02<00:05, 46.37it/s]

Chain 7:  53%|██████████████████████████████████████████████████████                                                | 191/360 [00:03<00:02, 59.98it/s]

Chain 9:   7%|███████▏                                                                                               | 25/360 [00:00<00:05, 60.77it/s]

Chain 8:  31%|███████████████████████████████▍                                                                      | 111/360 [00:02<00:05, 44.13it/s]

Chain 7:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:03<00:02, 59.00it/s]

Chain 8:  32%|████████████████████████████████▊                                                                     | 116/360 [00:02<00:05, 44.67it/s]

Chain 9:   9%|█████████▍                                                                                             | 33/360 [00:00<00:06, 53.22it/s]

Chain 7:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:03<00:02, 61.77it/s]

Chain 8:  34%|██████████████████████████████████▎                                                                   | 121/360 [00:02<00:05, 45.26it/s]

Chain 7:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:04<00:02, 64.80it/s]

Chain 9:  11%|███████████▏                                                                                           | 39/360 [00:00<00:06, 51.00it/s]

Chain 8:  35%|███████████████████████████████████▋                                                                  | 126/360 [00:02<00:05, 46.23it/s]

Chain 7:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:04<00:02, 67.50it/s]

Chain 9:  12%|████████████▉                                                                                          | 45/360 [00:00<00:06, 49.97it/s]

Chain 8:  36%|█████████████████████████████████████                                                                 | 131/360 [00:02<00:04, 46.88it/s]

Chain 7:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:04<00:01, 72.17it/s]

Chain 9:  14%|██████████████▌                                                                                        | 51/360 [00:00<00:06, 49.00it/s]

Chain 8:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:02<00:04, 47.91it/s]

Chain 7:  66%|███████████████████████████████████████████████████████████████████▍                                  | 238/360 [00:04<00:01, 77.04it/s]

Chain 9:  16%|████████████████▎                                                                                      | 57/360 [00:01<00:06, 48.79it/s]

Chain 8:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:02<00:04, 49.86it/s]

Chain 7:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:04<00:01, 82.96it/s]

Chain 9:  17%|█████████████████▋                                                                                     | 62/360 [00:01<00:06, 48.44it/s]

Chain 8:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:03<00:04, 51.68it/s]

Chain 7:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:04<00:01, 90.33it/s]

Chain 9:  19%|███████████████████▏                                                                                   | 67/360 [00:01<00:05, 48.85it/s]

Chain 8:  43%|███████████████████████████████████████████▉                                                          | 155/360 [00:03<00:03, 52.76it/s]

Chain 7:  75%|████████████████████████████████████████████████████████████████████████████▊                         | 271/360 [00:04<00:00, 97.22it/s]

Chain 9:  20%|████████████████████▌                                                                                  | 72/360 [00:01<00:05, 48.86it/s]

Chain 8:  45%|█████████████████████████████████████████████▌                                                        | 161/360 [00:03<00:03, 54.22it/s]

Chain 7:  79%|███████████████████████████████████████████████████████████████████████████████▉                     | 285/360 [00:04<00:00, 108.50it/s]

Chain 9:  22%|██████████████████████▎                                                                                | 78/360 [00:01<00:05, 49.60it/s]

Chain 8:  47%|███████████████████████████████████████████████▌                                                      | 168/360 [00:03<00:03, 56.62it/s]

Chain 7:  83%|████████████████████████████████████████████████████████████████████████████████████▏                | 300/360 [00:04<00:00, 120.29it/s]

Chain 9:  23%|███████████████████████▋                                                                               | 83/360 [00:01<00:05, 49.28it/s]

Chain 7:  89%|█████████████████████████████████████████████████████████████████████████████████████████▍           | 319/360 [00:04<00:00, 140.67it/s]

Chain 8:  49%|█████████████████████████████████████████████████▌                                                    | 175/360 [00:03<00:03, 57.90it/s]

Chain 9:  24%|█████████████████████████▏                                                                             | 88/360 [00:01<00:05, 48.59it/s]

Chain 7:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████▉   | 349/360 [00:05<00:00, 186.84it/s]

Chain 8:  51%|███████████████████████████████████████████████████▌                                                  | 182/360 [00:03<00:02, 60.15it/s]

Chain 9:  26%|██████████████████████████▌                                                                            | 93/360 [00:01<00:05, 47.24it/s]

Chain 8:  52%|█████████████████████████████████████████████████████▌                                                | 189/360 [00:03<00:02, 62.12it/s]

Chain 9:  27%|████████████████████████████                                                                           | 98/360 [00:01<00:05, 47.00it/s]

Chain 8:  55%|███████████████████████████████████████████████████████▊                                              | 197/360 [00:03<00:02, 64.74it/s]

Chain 9:  29%|█████████████████████████████▏                                                                        | 103/360 [00:02<00:05, 46.97it/s]

Chain 8:  57%|█████████████████████████████████████████████████████████▊                                            | 204/360 [00:03<00:02, 65.88it/s]

Chain 9:  30%|██████████████████████████████▌                                                                       | 108/360 [00:02<00:05, 47.28it/s]

Chain 8:  59%|████████████████████████████████████████████████████████████                                          | 212/360 [00:03<00:02, 69.60it/s]

Chain 9:  31%|████████████████████████████████                                                                      | 113/360 [00:02<00:05, 47.63it/s]

Chain 8:  61%|██████████████████████████████████████████████████████████████▎                                       | 220/360 [00:04<00:01, 71.66it/s]

Chain 9:  33%|█████████████████████████████████▋                                                                    | 119/360 [00:02<00:04, 48.64it/s]

Chain 8:  64%|████████████████████████████████████████████████████████████████▉                                     | 229/360 [00:04<00:01, 75.57it/s]

Chain 9:  35%|███████████████████████████████████▍                                                                  | 125/360 [00:02<00:04, 49.84it/s]

Chain 8:  66%|███████████████████████████████████████████████████████████████████▋                                  | 239/360 [00:04<00:01, 80.44it/s]

Chain 9:  36%|█████████████████████████████████████                                                                 | 131/360 [00:02<00:04, 50.75it/s]

Chain 8:  69%|██████████████████████████████████████████████████████████████████████▊                               | 250/360 [00:04<00:01, 86.77it/s]

Chain 8:  72%|█████████████████████████████████████████████████████████████████████████▉                            | 261/360 [00:04<00:01, 93.17it/s]

Chain 9:  38%|██████████████████████████████████████▊                                                               | 137/360 [00:02<00:04, 51.96it/s]

Chain 8:  76%|████████████████████████████████████████████████████████████████████████████▊                        | 274/360 [00:04<00:00, 102.01it/s]

Chain 9:  40%|████████████████████████████████████████▌                                                             | 143/360 [00:02<00:04, 53.64it/s]

Chain 9:  41%|██████████████████████████████████████████▏                                                           | 149/360 [00:02<00:03, 55.12it/s]

Chain 8:  80%|█████████████████████████████████████████████████████████████████████████████████                    | 289/360 [00:04<00:00, 114.38it/s]

Chain 8:  85%|██████████████████████████████████████████████████████████████████████████████████████▏              | 307/360 [00:04<00:00, 132.49it/s]

Chain 9:  43%|████████████████████████████████████████████▏                                                         | 156/360 [00:03<00:03, 56.83it/s]

Chain 8:  92%|████████████████████████████████████████████████████████████████████████████████████████████▊        | 331/360 [00:04<00:00, 163.13it/s]

Chain 9:  45%|██████████████████████████████████████████████▏                                                       | 163/360 [00:03<00:03, 58.13it/s]

Chain 9:  47%|████████████████████████████████████████████████▏                                                     | 170/360 [00:03<00:03, 58.96it/s]

Chain 9:  49%|██████████████████████████████████████████████████▏                                                   | 177/360 [00:03<00:03, 60.45it/s]

Chain 9:  51%|████████████████████████████████████████████████████▏                                                 | 184/360 [00:03<00:02, 62.91it/s]

Chain 9:  53%|██████████████████████████████████████████████████████▍                                               | 192/360 [00:03<00:02, 65.63it/s]

Chain 9:  56%|████████████████████████████████████████████████████████▋                                             | 200/360 [00:03<00:02, 67.68it/s]

Chain 9:  58%|███████████████████████████████████████████████████████████▏                                          | 209/360 [00:03<00:02, 71.89it/s]

Chain 9:  61%|█████████████████████████████████████████████████████████████▊                                        | 218/360 [00:03<00:01, 76.00it/s]

Chain 9:  63%|████████████████████████████████████████████████████████████████▎                                     | 227/360 [00:04<00:01, 79.47it/s]

Chain 9:  66%|███████████████████████████████████████████████████████████████████▏                                  | 237/360 [00:04<00:01, 83.81it/s]

Chain 9:  69%|██████████████████████████████████████████████████████████████████████▎                               | 248/360 [00:04<00:01, 89.72it/s]

Chain 9:  72%|█████████████████████████████████████████████████████████████████████████▍                            | 259/360 [00:04<00:01, 95.53it/s]

Chain 9:  76%|████████████████████████████████████████████████████████████████████████████▎                        | 272/360 [00:04<00:00, 105.50it/s]

Chain 9:  80%|████████████████████████████████████████████████████████████████████████████████▊                    | 288/360 [00:04<00:00, 121.16it/s]

Chain 9:  86%|██████████████████████████████████████████████████████████████████████████████████████▍              | 308/360 [00:04<00:00, 143.96it/s]

Chain 9:  94%|██████████████████████████████████████████████████████████████████████████████████████████████▊      | 338/360 [00:04<00:00, 189.24it/s]

2026-05-28 21:00:20.914 | SUCCESS  | resgo.engine.production_simulator:simulate:105 - Demo Prospect Field production simulation complete!

2026-05-28 21:00:21.255 | INFO     | resgo.engine.economic_simulator:initialize_factor_curves:318 - Discount and inflation curves initialized

2026-05-28 21:00:24.398 | INFO     | resgo.engine.economic_simulator:simulate_capex:378 - CAPEX payments calculated with leverage: 1.0 Debt:Equity.

2026-05-28 21:00:25.003 | INFO     | resgo.engine.economic_simulator:simulate_leverage:392 - Debt repayments simulated.

2026-05-28 21:00:25.004 | DEBUG    | resgo.engine.economic_simulator:simulate_prices:405 - An additional 7 months of prices will be simulated before development begins.

2026-05-28 21:00:25.009 | INFO     | resgo.engine.economic_simulator:simulate_prices:420 - Oil and Gas prices simulated using a flat price model.

2026-05-28 21:00:25.625 | INFO     | resgo.engine.economic_simulator:simulate_gross_sales:446 - Gross sales simulated.

2026-05-28 21:00:25.650 | INFO     | resgo.engine.economic_simulator:simulate_expenses:465 - OPEX and ABEX simulated.

2026-05-28 21:00:25.984 | INFO     | resgo.engine.economic_simulator:simulate_royalty_payments:490 - Royalties simulated using a flat royalty model.

2026-05-28 21:00:26.511 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:516 - Infrastructure depreciation model simulated.

2026-05-28 21:00:27.076 | INFO     | resgo.engine.economic_simulator:simulate_capital_depreciation:530 - Producer depreciation model simulated.

2026-05-28 21:00:27.187 | INFO     | resgo.engine.economic_simulator:simulate_tax_payments:541 - Taxes simulated using a progressive tax model.

2026-05-28 21:00:27.188 | SUCCESS  | resgo.engine.economic_simulator:simulate:302 - Economic simulation of Demo Prospect complete!

In [4]:
fig = reporter.plotter.forest_plot(
    "Net (m)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [5]:
fig = reporter.plotter.forest_plot(
    "Porosity", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [6]:
fig = reporter.plotter.forest_plot(
    "Water Saturation", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [7]:
fig = reporter.plotter.forest_plot(
    "STOIIP (stb)", 
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [8]:
fig = reporter.plotter.prospect_volumetric_ecdf_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.LayerChart(...)

In [9]:
fig = reporter.plotter.combined_production_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [10]:
fig = reporter.plotter.combined_cash_flow_plot(
    figsize=(650, 250),
    backend=PLOTTING_BACKEND
)
fig.show()

alt.VConcatChart(...)

In [11]:
reporter.tabler.volumetrics_table()

,,P(Success),P99,P90,P50,P10,P1
stream,,,,,,,
STOIIP (stb),Total Volumes,1.0,99.3,156.1,256.1,390.9,542.7
GIIP (mscf),Total Volumes,1.0,39.1,64.8,110.3,177.4,261.1
Condensate (stb),Total Volumes,1.0,1.2,2.0,3.8,6.8,11.2
Solution Gas (mscf),Total Volumes,1.0,156.4,270.4,468.6,746.0,1161.5

In [12]:
reporter.tabler.oil_eur_table(group_by=None)

               P(Success)   P99   P90   P50   P10     P1
Total Oil EUR         1.0  21.6  34.8  57.8  91.4  132.7

In [13]:
reporter.tabler.oil_eur_table(group_by="reservoir")

           P(Success)  P99  P90  P50   P10    P1
reservoir
Zone 1           0.64  0.8  2.5  8.3  23.2  51.3
Zone 2           0.62  0.5  2.2  7.2  21.9  52.2
Zone 3           0.76  0.9  2.3  5.4  12.2  23.4
Zone 4           0.78  0.4  1.9  5.9  16.8  43.6
Zone 5           0.71  1.0  2.5  7.9  20.5  44.6
Zone 6           0.95  1.4  2.9  6.8  13.9  23.9
Zone 7           0.53  0.6  2.2  7.1  20.4  42.1
Zone 8           0.68  0.6  1.9  5.6  15.1  31.4
Zone 9           0.87  0.7  2.2  5.9  14.6  31.4
Zone 10          0.60  0.6  2.2  5.8  13.4  26.5

In [14]:
reporter.tabler.npv_table()

     P(Commercial)   P99    P90     P50     P10      P1
NPV           0.99 -29.0  447.0  1113.0  1891.0  2565.0

In [15]:
reporter.tabler.emv_table()

     P(Commercial)   P99    P90     P50     P10      P1
EMV           0.99 -29.0  441.0  1098.0  1867.0  2533.0

In [16]:
from resgo.plotting.tables import npv_USD
import numpy as np
import pandas as pd

npv = npv_USD(
    simpack,
    nominal=True,
    discounted=True,
    success_only=False,
)
npv_usd = npv.to_numpy().ravel()
npv_df = pd.DataFrame({"npv_usd_mm": npv_usd / 1e6})

histogram = (
    alt.Chart(npv_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Nominal discounted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Project NPV Distribution",
    )
)

break_even = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(histogram, break_even)
fig.show()

alt.LayerChart(...)

In [17]:
BANKRUPTCY_THRESHOLD_USD = 300e6
LOSS_FLOOR_USD = -5e9

def loss_adjusted_npv_USD(
    npv_usd,
    bankruptcy_threshold_usd=BANKRUPTCY_THRESHOLD_USD,
    floor_usd=LOSS_FLOOR_USD,
):
    npv_usd = np.asarray(npv_usd)
    threshold = bankruptcy_threshold_usd

    with np.errstate(divide="ignore", invalid="ignore"):
        adjusted = np.where(
            npv_usd >= 0,
            npv_usd,
            (threshold * npv_usd) / (threshold + npv_usd),
        )

    adjusted = np.where(npv_usd <= -threshold, floor_usd, adjusted)
    return np.maximum(adjusted, floor_usd)

x_usd = np.linspace(-0.9999 * BANKRUPTCY_THRESHOLD_USD, 1.5e9, 1_000)
loss_function_df = pd.DataFrame(
    {
        "npv_usd_mm": x_usd / 1e6,
        "loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(x_usd) / 1e6,
    }
)

loss_function = (
    alt.Chart(loss_function_df)
    .mark_line(color="#FACC15", strokeWidth=3)
    .encode(
        x=alt.X("npv_usd_mm:Q", title="Nominal discounted NPV ($USD MM)"),
        y=alt.Y(
            "loss_adjusted_npv_usd_mm:Q",
            title="Loss-adjusted NPV ($USD MM)",
        ),
        tooltip=[
            alt.Tooltip("npv_usd_mm:Q", title="NPV ($MM)", format=",.0f"),
            alt.Tooltip(
                "loss_adjusted_npv_usd_mm:Q",
                title="Loss-adjusted NPV ($MM)",
                format=",.0f",
            ),
        ],
    )
    .properties(
        width=650,
        height=250,
        title="Company Loss Function",
    )
)

bankruptcy_threshold = (
    alt.Chart(pd.DataFrame({"npv_usd_mm": [-BANKRUPTCY_THRESHOLD_USD / 1e6]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="npv_usd_mm:Q")
)

fig = alt.layer(loss_function, bankruptcy_threshold)
fig.show()

alt.LayerChart(...)

In [18]:
loss_df = pd.DataFrame(
    {"loss_adjusted_npv_usd_mm": loss_adjusted_npv_USD(npv_usd) / 1e6}
)

loss_histogram = (
    alt.Chart(loss_df)
    .mark_bar(color="#FACC15", opacity=0.85)
    .encode(
        x=alt.X(
            "loss_adjusted_npv_usd_mm:Q",
            bin=alt.Bin(maxbins=100),
            title="Loss-adjusted NPV ($USD MM)",
        ),
        y=alt.Y("count():Q", axis=None),
        tooltip=[alt.Tooltip("count():Q", title="Count")],
    )
    .properties(
        width=650,
        height=250,
        title="Simulated Loss-Adjusted NPV Distribution",
    )
)

break_even_loss = (
    alt.Chart(pd.DataFrame({"loss_adjusted_npv_usd_mm": [0]}))
    .mark_rule(color="red", strokeDash=[6, 4], strokeWidth=2)
    .encode(x="loss_adjusted_npv_usd_mm:Q")
)

fig = alt.layer(loss_histogram, break_even_loss)
fig.show()

alt.LayerChart(...)